// Copyright 2026 Lusoris
// SPDX-License-Identifier: BSD-3-Clause-Plus-Patent OR MIT

// Package bpf provides the Go-side loader for the rclone FUSE bypass eBPF
// program (ADR-0779).
//
// When VMAFX_EBPF_BYPASS=1, the loader:
//  1. Compiles the BTF-enabled BPF object (pre-generated by bpf2go at build time).
//  2. Writes the mount prefix into the mount_prefix_map.
//  3. Attaches tracepoints for openat/close.
//  4. Reads ring-buffer events to populate an in-process cache of bypass-eligible FDs.
//
// The bypass logic itself is in the calling code (executor.go): for FDs in the
// cache, direct pread(2) is issued on the backing host file instead of going
// through the FUSE daemon.  No kernel memory is modified.
//
// Kernel version requirement: Linux 5.15+ (BPF CO-RE, ring buffer, bpf_d_path).
// Capability requirement: CAP_BPF (Linux 5.8+) or CAP_SYS_ADMIN.
// Container requirement: --privileged or securityContext.privileged=true + mounted
// /sys/kernel/btf/vmlinux.
//
// ADR-0779.
package bpf

import (
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"strings"
	"sync"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

const (
	// DefaultMountPrefix is the FUSE mount point watched by default.
	DefaultMountPrefix = "/rclone-mount/"

	maxPathLen = 256
)

// mountPrefixT mirrors the BPF-side struct mount_prefix_t.
// Must stay in sync with rclone_bypass.bpf.c.
type mountPrefixT struct {
	Prefix    [maxPathLen]byte
	PrefixLen uint32
	_         [4]byte // explicit padding to match C struct alignment
}

// eventT mirrors the BPF-side struct event_t.
type eventT struct {
	PidTgid uint64
	FdKey   uint64
	Inode   uint64
	Path    [maxPathLen]byte
}

// BypassEntry describes a bypass-eligible open file descriptor.
type BypassEntry struct {
	FdKey uint64 // (pid << 32) | fd
	Path  string // path that was opened
}

// Loader manages the lifecycle of the eBPF bypass program.
type Loader struct {
	mu           sync.RWMutex
	objs         rcloneBypassObjects // generated by bpf2go
	links        []link.Link
	ringReader   *ringbuf.Reader
	activeFDs    map[uint64]string // fd_key → path
	mountPrefix  string
	log          *slog.Logger
}

// New creates a Loader.  The eBPF program is NOT loaded until Start is called.
func New(mountPrefix string, log *slog.Logger) *Loader {
	if mountPrefix == "" {
		mountPrefix = DefaultMountPrefix
	}
	if !strings.HasSuffix(mountPrefix, "/") {
		mountPrefix += "/"
	}
	if log == nil {
		log = slog.Default()
	}
	return &Loader{
		mountPrefix: mountPrefix,
		activeFDs:   make(map[uint64]string),
		log:         log,
	}
}

// Start loads and attaches the eBPF program.  Returns an error if the kernel
// does not support the required features or the process lacks privileges.
func (l *Loader) Start(ctx context.Context) error {
	// Remove the default locked memory limit so BPF maps can be allocated.
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("ebpf: remove memlock: %w", err)
	}

	// Load pre-compiled BPF objects (generated by bpf2go; embedded in binary).
	if err := loadRcloneBypassObjects(&l.objs, nil); err != nil {
		return fmt.Errorf("ebpf: load objects: %w", err)
	}

	// Write mount prefix into the BPF map.
	if err := l.writeMountPrefix(); err != nil {
		l.objs.Close()
		return fmt.Errorf("ebpf: write mount prefix: %w", err)
	}

	// Attach tracepoints.
	tpOpenatEnter, err := link.Tracepoint("syscalls", "sys_enter_openat",
		l.objs.TpOpenatEnter, nil)
	if err != nil {
		l.objs.Close()
		return fmt.Errorf("ebpf: attach sys_enter_openat: %w", err)
	}
	l.links = append(l.links, tpOpenatEnter)

	tpOpenatExit, err := link.Tracepoint("syscalls", "sys_exit_openat",
		l.objs.TpOpenatExit, nil)
	if err != nil {
		l.closeLinks()
		l.objs.Close()
		return fmt.Errorf("ebpf: attach sys_exit_openat: %w", err)
	}
	l.links = append(l.links, tpOpenatExit)

	tpClose, err := link.Tracepoint("syscalls", "sys_enter_close",
		l.objs.TpCloseEnter, nil)
	if err != nil {
		l.closeLinks()
		l.objs.Close()
		return fmt.Errorf("ebpf: attach sys_enter_close: %w", err)
	}
	l.links = append(l.links, tpClose)

	// Open ring-buffer reader.
	rd, err := ringbuf.NewReader(l.objs.Events)
	if err != nil {
		l.closeLinks()
		l.objs.Close()
		return fmt.Errorf("ebpf: ring buffer: %w", err)
	}
	l.ringReader = rd

	// Drain ring buffer in background goroutine.
	go l.drainLoop(ctx)

	l.log.Info("ebpf bypass active",
		"mount_prefix", l.mountPrefix,
		"kernel_min", "5.15")
	return nil
}

// Stop detaches all eBPF probes and frees resources.
func (l *Loader) Stop() {
	if l.ringReader != nil {
		_ = l.ringReader.Close()
	}
	l.closeLinks()
	l.objs.Close()
	l.log.Info("ebpf bypass stopped")
}

// IsBypassFD returns true if the given (pid, fd) pair is bypass-eligible.
func (l *Loader) IsBypassFD(pid uint32, fd uint32) (string, bool) {
	fdKey := (uint64(pid) << 32) | uint64(fd)
	l.mu.RLock()
	path, ok := l.activeFDs[fdKey]
	l.mu.RUnlock()
	return path, ok
}

// writeMountPrefix encodes the mount prefix into the BPF array map at index 0.
func (l *Loader) writeMountPrefix() error {
	var mp mountPrefixT
	prefix := l.mountPrefix
	if len(prefix) > maxPathLen-1 {
		prefix = prefix[:maxPathLen-1]
	}
	copy(mp.Prefix[:], prefix)
	mp.PrefixLen = uint32(len(prefix)) // #nosec G115 -- len(prefix) is bounded to maxPathLen-1 (≤255) above

	key := uint32(0)
	// Serialize to bytes for map update (cilium/ebpf needs []byte for structs
	// without generated marshalers).
	buf := make([]byte, unsafe.Sizeof(mp))
	copy(buf, prefix)
	binary.NativeEndian.PutUint32(buf[maxPathLen:], mp.PrefixLen)

	return l.objs.MountPrefixMap.Update(key, buf, ebpf.UpdateAny)
}

// drainLoop reads ring-buffer events and updates the in-process FD cache.
func (l *Loader) drainLoop(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		default:
		}

		rec, err := l.ringReader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			l.log.Warn("ebpf ring buffer read error", "err", err)
			continue
		}

		var ev eventT
		if len(rec.RawSample) < int(unsafe.Sizeof(ev)) {
			continue
		}
		copy((*[unsafe.Sizeof(ev)]byte)(unsafe.Pointer(&ev))[:], rec.RawSample) // #nosec G103 -- unsafe.Pointer required for BPF ring-buffer struct deserialisation; bounds checked above

		// Null-terminate path string.
		pathEnd := 0
		for pathEnd < maxPathLen && ev.Path[pathEnd] != 0 {
			pathEnd++
		}
		path := string(ev.Path[:pathEnd])

		l.mu.Lock()
		l.activeFDs[ev.FdKey] = path
		l.mu.Unlock()

		l.log.Debug("ebpf bypass: new eligible FD",
			"fd_key", ev.FdKey, "path", path)
	}
}

func (l *Loader) closeLinks() {
	for _, lk := range l.links {
		_ = lk.Close()
	}
	l.links = nil
}

// Enabled reports whether the eBPF bypass feature flag is set.
// Returns true when VMAFX_EBPF_BYPASS=1.
func Enabled() bool {
	return os.Getenv("VMAFX_EBPF_BYPASS") == "1"
}
