// Copyright 2026 Lusoris
// SPDX-License-Identifier: BSD-3-Clause-Plus-Patent OR MIT

// rclone_bypass_stub.go — compile-time stub for the bpf2go-generated bindings.
//
// bpf2go normally generates rcloneBypass_bpfel.go + rcloneBypass_bpfel.o
// (and bpfeb variants) from rclone_bypass.bpf.c.  This stub provides the same
// exported symbols so the package compiles in CI without a BPF toolchain.
// Replace with `go generate` output before running in production.
//
// ADR-0779.
package bpf

import (
	"fmt"

	"github.com/cilium/ebpf"
)

// rcloneBypassObjects holds all BPF maps and programs from rclone_bypass.bpf.c.
// The real version is generated by bpf2go; this stub satisfies the compiler.
type rcloneBypassObjects struct {
	rcloneBypassPrograms
	rcloneBypassMaps
}

func (o *rcloneBypassObjects) Close() {
	o.rcloneBypassPrograms.Close()
	o.rcloneBypassMaps.Close()
}

type rcloneBypassPrograms struct {
	TpOpenatEnter *ebpf.Program `ebpf:"tp_openat_enter"`
	TpOpenatExit  *ebpf.Program `ebpf:"tp_openat_exit"`
	TpCloseEnter  *ebpf.Program `ebpf:"tp_close_enter"`
}

func (p *rcloneBypassPrograms) Close() {
	if p.TpOpenatEnter != nil {
		_ = p.TpOpenatEnter.Close()
	}
	if p.TpOpenatExit != nil {
		_ = p.TpOpenatExit.Close()
	}
	if p.TpCloseEnter != nil {
		_ = p.TpCloseEnter.Close()
	}
}

type rcloneBypassMaps struct {
	MountPrefixMap *ebpf.Map `ebpf:"mount_prefix_map"`
	ScratchPaths   *ebpf.Map `ebpf:"scratch_paths"`
	BypassFds      *ebpf.Map `ebpf:"bypass_fds"`
	Events         *ebpf.Map `ebpf:"events"`
}

func (m *rcloneBypassMaps) Close() {
	if m.MountPrefixMap != nil {
		_ = m.MountPrefixMap.Close()
	}
	if m.ScratchPaths != nil {
		_ = m.ScratchPaths.Close()
	}
	if m.BypassFds != nil {
		_ = m.BypassFds.Close()
	}
	if m.Events != nil {
		_ = m.Events.Close()
	}
}

// loadRcloneBypassObjects loads the BPF programs and maps.
// The real implementation embeds the compiled .o via go:embed.
// This stub always returns an error so callers fail fast in non-privileged CI.
func loadRcloneBypassObjects(objs *rcloneBypassObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("ebpf: stub loader — run `go generate ./cmd/vmafx-node/bpf/` to build real objects (requires clang + libbpf-dev + Linux 5.15+, CAP_BPF)")
}
