// Copyright 2026 Lusoris
// SPDX-License-Identifier: EUPL-1.2

// rclone_bypass_stub.go — compile-time stub for the bpf2go-generated bindings.
//
// bpf2go normally generates rcloneBypass_bpfel.go + rcloneBypass_bpfel.o
// (and bpfeb variants) from rclone_bypass.bpf.c.  This stub provides the same
// exported symbols so the package compiles in CI without a BPF toolchain.
// Replace with `go generate` output before running in production.
//
// The Close methods return an error, matching the signature bpf2go emits for
// the real bindings (cmd/bpf2go/gen/output.tpl), so swapping the generated file
// in is a drop-in replacement for callers.
//
// ADR-0779.
package bpf

import (
	"errors"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// rcloneBypassObjects holds all BPF maps and programs from rclone_bypass.bpf.c.
// The real version is generated by bpf2go; this stub satisfies the compiler.
type rcloneBypassObjects struct {
	rcloneBypassPrograms
	rcloneBypassMaps
}

func (o *rcloneBypassObjects) Close() error {
	return errors.Join(o.rcloneBypassPrograms.Close(), o.rcloneBypassMaps.Close())
}

type rcloneBypassPrograms struct {
	TpOpenatEnter *ebpf.Program `ebpf:"tp_openat_enter"`
	TpOpenatExit  *ebpf.Program `ebpf:"tp_openat_exit"`
	TpCloseEnter  *ebpf.Program `ebpf:"tp_close_enter"`
}

func (p *rcloneBypassPrograms) Close() error {
	return closeAll(p.TpOpenatEnter, p.TpOpenatExit, p.TpCloseEnter)
}

type rcloneBypassMaps struct {
	MountPrefixMap *ebpf.Map `ebpf:"mount_prefix_map"`
	ScratchPaths   *ebpf.Map `ebpf:"scratch_paths"`
	BypassFds      *ebpf.Map `ebpf:"bypass_fds"`
	Events         *ebpf.Map `ebpf:"events"`
}

func (m *rcloneBypassMaps) Close() error {
	return closeAll(m.MountPrefixMap, m.ScratchPaths, m.BypassFds, m.Events)
}

// closeAll releases every closer and reports the failures that occurred.
//
// It deliberately continues past a failing Close instead of returning early, so a single
// failure cannot leak the handles behind the closers that follow it; that is the
// close-everything behaviour the hand-written nil guards used to provide, with the errors
// now propagated to the caller instead of discarded.
//
// A nil *ebpf.Map or *ebpf.Program is safe to pass: both Close methods guard their nil
// receiver and return nil (ebpf v0.22.0 map.go:1518, prog.go:809), which is what lets the
// zero-valued stub objects close cleanly.
func closeAll(closers ...io.Closer) error {
	errs := make([]error, 0, len(closers))
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// loadRcloneBypassObjects loads the BPF programs and maps.
// The real implementation embeds the compiled .o via go:embed.
// This stub always returns an error so callers fail fast in non-privileged CI.
func loadRcloneBypassObjects(objs *rcloneBypassObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("ebpf: stub loader — run `go generate ./cmd/vmafx-node/bpf/` to build real objects (requires clang + libbpf-dev + Linux 5.15+, CAP_BPF)")
}
