/**
 *  Copyright 2016-2026 Netflix, Inc.
 *  Copyright 2026 Lusoris
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 *  Host/device contract of the CUDA CAMBI extractor (T3-15 / ADR-0360),
 *  device-resident since ADR-1379: the launch geometry integer_cambi_cuda.c
 *  and integer_cambi/cambi_score.cu must agree on, the one argument block
 *  each kernel takes by value, the per-scale radix-select state and the one
 *  block read back per frame. Included by both the C host glue and nvcc.
 *
 *  Every kernel takes exactly one parameter, its argument struct, and the
 *  host passes `void *params[] = {&args}`: the driver silently ignores a
 *  surplus argument (ADR-1215), a shared struct cannot drift. Device
 *  pointers travel as uint64_t (CUdeviceptr on the host).
 */
#ifndef FEATURE_CAMBI_CUDA_H_
#define FEATURE_CAMBI_CUDA_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PTX blob generated by nvcc from integer_cambi/cambi_score.cu. */
extern const unsigned char cambi_score_ptx[];

/* Must equal VMAF_CAMBI_NUM_SCALES (the host glue asserts it). */
#define CAMBI_CUDA_NUM_SCALES 5

/* Thread-block shapes. The kernels' __launch_bounds__ use the same values. */
#define CAMBI_CUDA_IMAGE_BLOCK_X 16u
#define CAMBI_CUDA_IMAGE_BLOCK_Y 16u
#define CAMBI_CUDA_ROWMASK_ROWS 8u
#define CAMBI_CUDA_CVALS_BLOCK 64u
#define CAMBI_CUDA_POOL_BLOCK 256u

/* Top-K radix select over the IEEE bit pattern: 11 + 11 + 10 bits. */
#define CAMBI_CUDA_RADIX_BINS 2048u
#define CAMBI_CUDA_RADIX_PASSES 3

/* Level-map value of a pixel that neither feeds nor queries a histogram:
 * masked out, or outside the [v_band_base, v_band_base + v_band_size) band
 * calculate_c_values() keeps. */
#define CAMBI_CUDA_Q_INVALID 0xFFFFu

/* Every non-zero c-value is a multiple of 2^-24 (ADR-1357). */
#define CAMBI_CUDA_FIXED_SHIFT 24

/* Status bits returned with the per-scale sums. */
#define CAMBI_CUDA_STATUS_INVALID_INPUT 1u

/* Per-scale radix-select state (device only, zeroed every frame). Scan pass
 * p reads the rank it looks for from k_next[p - 1] (pass 0: the scale's
 * top-K count argument) and writes the rank left inside the chosen bucket to
 * k_next[p], so no lane rewrites a word another lane still reads. `resolved`
 * is set when pass 0 lands in bin 0: that bin holds only exact zeros (every
 * non-zero c-value is >= 0.5), so the threshold is 0 and the later passes
 * have nothing to do. */
typedef struct CambiCudaSelect {
    uint32_t hist[CAMBI_CUDA_RADIX_BINS];
    uint32_t prefix;
    uint32_t k_next[CAMBI_CUDA_RADIX_PASSES];
    uint32_t resolved;
} CambiCudaSelect;

/* The one block collect() reads back: per-scale 128-bit top-K sums in units
 * of 2^-24 (value = hi * 2^64 + lo) and the status word. Two uint64 words,
 * not `unsigned __int128`, because the host TU is also compiled by MSVC,
 * which has no 128-bit integer type. */
typedef struct CambiCudaResults {
    uint64_t sum_lo[CAMBI_CUDA_NUM_SCALES];
    uint64_t sum_hi[CAMBI_CUDA_NUM_SCALES];
    uint32_t status;
    uint32_t reserved;
} CambiCudaResults;

/* cambi_validate_kernel / cambi_preprocess_kernel. `src` is the device
 * picture's luma plane with a pitch of `src_pitch` bytes. */
typedef struct CambiCudaPreprocArgs {
    uint64_t src;
    uint64_t dst;     /* uint16 out_width x out_height */
    uint64_t ori_x;   /* uint32 source column per output column (resize) */
    uint64_t ori_y;   /* uint32 source row per output row (resize) */
    uint64_t results; /* CambiCudaResults, status word */
    uint32_t src_pitch;
    uint32_t src_width;
    uint32_t src_height;
    uint32_t out_width;
    uint32_t out_height;
    uint32_t bpc;
    uint32_t same_size;
    uint32_t anti_dither;
} CambiCudaPreprocArgs;

/* cambi_spatial_mask_kernel. */
typedef struct CambiCudaMaskArgs {
    uint64_t image; /* uint16 width x height */
    uint64_t mask;  /* uint16 width x height, 1 = flat enough to test */
    uint32_t width;
    uint32_t height;
    uint32_t mask_index;
    uint32_t reserved;
} CambiCudaMaskArgs;

/* cambi_decimate_kernel. */
typedef struct CambiCudaDecimateArgs {
    uint64_t src; /* uint16, row stride src_stride */
    uint64_t dst; /* uint16 out_width x out_height */
    uint32_t out_width;
    uint32_t out_height;
    uint32_t src_stride;
    uint32_t reserved;
} CambiCudaDecimateArgs;

/* cambi_filter_mode_h_kernel (image -> filtered_h) and
 * cambi_filter_mode_v_levels_kernel (filtered_h -> image, level map q). */
typedef struct CambiCudaFilterArgs {
    uint64_t image;      /* uint16 width x height */
    uint64_t filtered_h; /* uint16 width x height */
    uint64_t mask;       /* uint16 width x height */
    uint64_t q;          /* uint16 width x height level map */
    uint32_t width;
    uint32_t height;
    uint32_t v_band_base;
    uint32_t v_band_size;
} CambiCudaFilterArgs;

/* cambi_row_masks_kernel and cambi_cvals_kernel (one scale). */
typedef struct CambiCudaCvalsArgs {
    uint64_t q;        /* uint16 level map */
    uint64_t runs;     /* uint32 words x height */
    uint64_t change;   /* uint32 words x height */
    uint64_t hist;     /* uint16 chunks x levels x width */
    uint64_t cvals;    /* float width x height */
    uint64_t select;   /* CambiCudaSelect of the scale */
    uint64_t partials; /* uint64, one per c-values block */
    uint64_t lut;      /* float reciprocal table */
    uint64_t tvi;      /* uint16 tvi_for_diff[num_diffs] */
    uint64_t weights;  /* int diff weights[num_diffs] */
    uint32_t width;
    uint32_t height;
    uint32_t words;
    uint32_t pad;
    uint32_t chunk_rows;
    uint32_t levels;
    uint32_t num_diffs;
    uint32_t vlt_luma;
    uint32_t v_band_base;
    uint32_t reserved;
} CambiCudaCvalsArgs;

/* The top-K pooling kernels (one scale, one radix pass). */
typedef struct CambiCudaPoolArgs {
    uint64_t cvals;    /* float n */
    uint64_t select;   /* CambiCudaSelect of the scale */
    uint64_t partials; /* uint64 per-block sums */
    uint64_t results;  /* CambiCudaResults */
    uint32_t n;
    uint32_t groups;
    uint32_t cvals_groups;
    uint32_t topk;
    int32_t pass;
    int32_t scale;
} CambiCudaPoolArgs;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* FEATURE_CAMBI_CUDA_H_ */
