// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

package obsgen

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/logs"
	"github.com/grafana/grafana-foundation-sdk/go/loki"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
)

// LogsUID is the Logs dashboard's uid.
const LogsUID = "vmafx-logs"

// lokiDatasourceVar is the Logs dashboard's Loki data source variable.
const lokiDatasourceVar = "loki_datasource"

// Loki stores an OTLP log record's service.name as the index label
// service_name and its severity text, trace id and span id as the structured
// metadata severity_text, trace_id and span_id (Loki's OTLP ingestion).
const (
	lokiService = `service_name=~"$service"`
	lokiStream  = "{" + lokiService + "}"
)

func lokiRef() common.DataSourceRef {
	return common.DataSourceRef{Type: cog.ToPtr("loki"), Uid: cog.ToPtr("${" + lokiDatasourceVar + "}")}
}

func logQuery(expr, legend string) *loki.DataqueryBuilder {
	return loki.NewDataqueryBuilder().Datasource(lokiRef()).Expr(expr).LegendFormat(legend).Range(true)
}

// logsDashboard answers: how much does each service log at each level, where
// are the errors, and what did every service log for one trace. The service
// logs arrive over OTLP through the slog bridge (bootstrap.Base).
func logsDashboard() *dashboard.DashboardBuilder {
	b := dashboard.NewDashboardBuilder("VMAFx Logs").
		Uid(LogsUID).
		Description("Logs of the VMAFx services in Loki, sent over OTLP by the slog bridge: volume per level, errors, and every line of one trace. Generated by tools/obsgen.").
		Tags([]string{tag}).
		Readonly().
		Refresh("1m").
		Time("now-1h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(dashboard.NewDatasourceVariableBuilder(lokiDatasourceVar).Label("Loki data source").Type("loki")).
		WithVariable(dashboard.NewQueryVariableBuilder("service").
			Label("Service").
			Datasource(lokiRef()).
			Query(dashboard.StringOrMap{String: cog.ToPtr("label_values(service_name)")}).
			Regex("/^vmafx-.*/").
			Refresh(dashboard.VariableRefreshOnTimeRangeChanged).
			Multi(true).
			IncludeAll(true).
			AllValue("vmafx-.+")).
		WithVariable(dashboard.NewTextBoxVariableBuilder("trace_id").Label("Trace ID").
			DefaultValue(dashboard.StringOrMap{String: cog.ToPtr("")})).
		Link(dashboard.NewDashboardLinkBuilder("VMAFx dashboards").
			Type(dashboard.DashboardLinkTypeDashboards).Tags([]string{tag}).AsDropdown(true).IncludeVars(true).KeepTime(true))
	return withRows(b, []row{
		{"Volume", []panelBuilder{
			logTimeseries("Log lines per minute by service and level", "Lines each service logged per minute, per severity. A jump in WARN or ERROR is the first place to look.",
				`sum by (service_name, severity_text) (count_over_time(`+lokiStream+` [$__auto]))`, "{{service_name}} {{severity_text}}"),
			logTimeseries("Errors per minute by service", "ERROR lines per minute and service.",
				`sum by (service_name) (count_over_time(`+lokiStream+` | severity_text="ERROR" [$__auto]))`, "{{service_name}}"),
		}},
		{"Lines", []panelBuilder{
			logsPanel("Warnings and errors", "WARN and ERROR lines of the selected services. Open a line's trace_id field to jump to its trace.",
				lokiStream+` | severity_text=~"WARN|ERROR"`),
			logsPanel("Lines of one trace", "Every line any service logged under the trace in the Trace ID box: the log side of one request or job.",
				lokiStream+` | trace_id="$trace_id"`),
			logsPanel("All lines", "Every line of the selected services.", lokiStream),
		}},
	})
}

func logTimeseries(title, description, expr, legend string) *timeseries.PanelBuilder {
	return timeseries.NewPanelBuilder().
		Title(title).Description(description).Datasource(lokiRef()).Unit(unitCount).Min(0).
		Height(8).Span(12).FillOpacity(10).
		Legend(common.NewVizLegendOptionsBuilder().DisplayMode(common.LegendDisplayModeTable).Placement(common.LegendPlacementBottom).ShowLegend(true).Calcs([]string{"sum", "max"})).
		WithTarget(logQuery(expr, legend))
}

func logsPanel(title, description, expr string) *logs.PanelBuilder {
	return logs.NewPanelBuilder().
		Title(title).Description(description).Datasource(lokiRef()).
		Height(10).Span(24).
		ShowTime(true).WrapLogMessage(true).EnableLogDetails(true).
		SortOrder(common.LogsSortOrderDescending).
		WithTarget(logQuery(expr, ""))
}
