# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Reference page (docs/api/vmafx/reference.md)."""

from __future__ import annotations

from . import ctext
from .layout import struct_layout
from .model import Api, Struct


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _functions(api: Api) -> list[str]:
    out = ["## Functions", ""]
    for header in api.headers:
        out += [
            f"### `{header.path}`",
            "",
            "| Function | Since | Description |",
            "| --- | --- | --- |",
        ]
        for fn in api.functions:
            if fn.header == header.path:
                out.append(f"| `{fn.name}` | {fn.since} | {_cell(fn.doc)} |")
        out.append("")
        out.append("```c")
        out += [
            ctext.declaration(api, fn, api.export_macro)
            for fn in api.functions
            if fn.header == header.path
        ]
        out += ["```", ""]
    return out


def _struct(item: Struct) -> list[str]:
    lay = struct_layout(item)
    out = [f"### `{item.name}`", "", f"{item.doc} Size {lay.size} bytes.", ""]
    out += ["| Field | Type | Offset | Description |", "| --- | --- | --- | --- |"]
    for field, place in zip(item.fields, lay.fields, strict=True):
        kind = ctext.field_type(field) + (f" (`{field.enum}`)" if field.enum else "")
        out.append(f"| `{field.name}` | `{kind}` | {place.offset} | {_cell(field.doc)} |")
    return [*out, ""]


def _constants(api: Api) -> list[str]:
    out = [
        "## Status codes",
        "",
        "| Code | Value | libvmaf errno | Meaning |",
        "| --- | --- | --- | --- |",
    ]
    for status in api.statuses:
        errno = "0" if status.errno == "0" else f"-{status.errno}"
        out.append(f"| `{status.name}` | {status.value} | `{errno}` | {_cell(status.doc)} |")
    out.append("")
    for enum in api.enums:
        out += [f"### `{enum.name}`", "", enum.doc, "", "| Constant | Value |", "| --- | --- |"]
        out += [f"| `{v.name}` | {v.value} |" for v in enum.values]
        out.append("")
    return out


def _compat(api: Api) -> list[str]:
    out = ["## libvmaf compatibility shims", "", "| libvmaf function | Header | Kind | Calls |"]
    out.append("| --- | --- | --- | --- |")
    out += [f"| `{c.name}` | `{c.header}` | {c.kind} | `{c.target}` |" for c in api.compats]
    return [*out, ""]


def reference_text(api: Api) -> str:
    major, minor, patch = api.abi_version
    lines = [
        "<!-- markdownlint-disable MD013 -->",
        "<!-- GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852). Do not edit. -->",
        "# VMAFx C API reference (generated)",
        "",
        f"ABI version {major}.{minor}.{patch}. This page is generated from",
        "[`core/api/vmafx.toml`](../../../core/api/vmafx.toml); the overview is",
        "[the VMAFx API page](index.md).",
        "",
    ]
    lines += _functions(api)
    lines += ["## Structs", ""]
    for item in api.structs:
        lines += _struct(item)
    lines += _constants(api)
    lines += _compat(api)
    return "\n".join(lines).rstrip("\n") + "\n"
