# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Scoring options as data for the MCP servers and the scoring server.

One JSON document, written to two places so each package ships it
(`pkg/scoreopts/options.gen.json` for the Go MCP server and `vmafx-server`,
`mcp-server/vmaf-mcp/src/vmaf_mcp/options.gen.json` for the Python MCP
server):

- `tools`: the complete input schema (JSON Schema 2020-12, the MCP default
  dialect) of every MCP tool an option group names;
- `options`: every option a server reads, with its type, bounds, default and
  the surfaces it is on;
- `argv`: how an argument becomes `vmaf` command-line flags (stage, flag,
  form), in definition order, which is the order the servers append them;
- `cli`: the flag of every command-line option a server passes on its own
  (`-q`, `-o`, `--no_cuda`, ...);
- `library_defaults`: the value of every C macro an option names as its
  default (`default_macro`), read from the public headers when the file is
  generated (the default model, for a model spec the servers complete).

Both MCP servers serve the `tools` schemas as they are and build their `vmaf`
argument vectors from `argv`, so the two servers cannot drift from each other
or from the command line.
"""

from __future__ import annotations

import json
from typing import Any

from .macros import library_defaults
from .model import Api, Option, OptionGroup
from .options import all_options

DIALECT = "https://json-schema.org/draft/2020-12/schema"
COMMENT = (
    "GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852). "
    "Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`."
)
OUTPUTS = ("pkg/scoreopts/options.gen.json", "mcp-server/vmaf-mcp/src/vmaf_mcp/options.gen.json")
JSON_TYPES = {
    "bool": "boolean",
    "int": "integer",
    "uint": "integer",
    "float": "number",
    "string": "string",
    "enum": "string",
}


def _number(option: Option) -> dict[str, Any]:
    out: dict[str, Any] = {}
    low, high = option.range or (0.0 if option.type == "uint" else None, None)
    cast = float if option.type == "float" else int
    if low is not None:
        out["minimum"] = cast(low)
    if high is not None:
        out["maximum"] = cast(high)
    return out


def value_schema(option: Option) -> dict[str, Any]:
    """The JSON Schema of one value of the option."""
    if option.type == "flags":
        items = {"type": "string", "enum": list(option.values)}
        return {"type": "array", "items": items, "uniqueItems": True}
    out: dict[str, Any] = {"type": JSON_TYPES[option.type]}
    if option.values:
        out["enum"] = list(option.values)
    if option.choices:
        out["enum"] = list(option.choices)
    elif option.type in ("int", "uint", "float"):
        out.update(_number(option))
    return out


def description(option: Option) -> str:
    text = option.doc
    if option.cli is not None and option.cli.flags:
        text += f" (CLI: {option.cli.flags[0]})"
    if option.default_macro:
        text += f" Default: the library default ({option.default_macro})."
    if option.reserved:
        text += f" Reserved: {option.reserved}; only the default is accepted."
    return text


def property_schema(option: Option, surface: str) -> dict[str, Any]:
    """The schema of an argument on a surface (`mcp`): list form when it repeats there."""
    value = value_schema(option)
    out: dict[str, Any] = (
        {"type": "array", "items": value} if surface in option.repeat else dict(value)
    )
    out["description"] = description(option)
    default = option.default_on(surface)
    if default is not None and not option.mcp_required and surface not in option.repeat:
        out["default"] = default
    return out


def tool_schemas(api: Api) -> dict[str, dict[str, Any]]:
    """Input schema of every MCP tool named by an option group."""
    tools: dict[str, dict[str, Any]] = {}
    for group, option in all_options(api.option_groups):
        if "mcp" not in option.surfaces:
            continue
        name = option.spellings["mcp"][0]
        for tool in group.mcp_tools:
            schema = tools.setdefault(
                tool, {"$schema": DIALECT, "type": "object", "required": [], "properties": {}}
            )
            schema["properties"][name] = property_schema(option, "mcp")
            if option.mcp_required:
                schema["required"].append(name)
    return tools


def option_record(group: OptionGroup, option: Option) -> dict[str, Any]:
    """What a server needs to check and pass one option."""
    record: dict[str, Any] = {
        "name": option.name,
        "group": group.name,
        "type": option.type,
        "surfaces": list(option.surfaces),
        "mcp": option.spellings.get("mcp", (None,))[0],
        "proto_field": option.proto_field or None,
        "schema": value_schema(option),
        "repeat": list(option.repeat),
        "default": option.default,
        "surface_defaults": dict(option.surface_defaults) or None,
        "default_macro": option.default_macro or None,
        "reserved": option.reserved or None,
    }
    return record


def argv_record(option: Option) -> dict[str, Any]:
    assert option.argv is not None
    values = dict(option.cli.values) if option.cli is not None else {}
    return {
        "option": option.name,
        "mcp": option.spellings.get("mcp", (None,))[0],
        "stage": option.argv.stage,
        "flag": option.argv.flag,
        "form": option.argv.form,
        "suffix": option.argv.suffix or None,
        "values": values or None,
    }


def cli_flags(api: Api) -> dict[str, str]:
    """Option name -> the flag a server passes for it (short form when one exists)."""
    out: dict[str, str] = {}
    for _, option in all_options(api.option_groups):
        if option.cli is None or not option.cli.flags:
            continue
        out[option.name] = f"-{option.cli.short}" if option.cli.short else option.cli.flags[0]
    return out


def document(api: Api) -> dict[str, Any]:
    served = [
        (g, o) for g, o in all_options(api.option_groups) if {"mcp", "proto"} & set(o.surfaces)
    ]
    return {
        "$comment": COMMENT,
        "dialect": DIALECT,
        "tools": tool_schemas(api),
        "options": [option_record(g, o) for g, o in served],
        "argv": [argv_record(o) for _, o in served if o.argv is not None],
        "cli": cli_flags(api),
        "library_defaults": library_defaults(api),
    }


def options_json(api: Api) -> str:
    return json.dumps(document(api), indent=2) + "\n"
