# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""FFmpeg AVOption table of the `vmafx` filter (design section 5.2, WP9 consumes it).

`ffmpeg-patches/src/vf_vmafx_options.h` declares:

- `VMAFX_FILTER_OPTION_FIELDS`: the context fields the options write, for the
  filter's private context struct;
- `VMAFX_FILTER_OPTIONS(CTX, FLAGS)`: the AVOption entries, aliases (upstream
  names such as `n_threads`) pointing at the same field, enumerated and flags
  options with their AV_OPT_TYPE_CONST values;
- `VMAFX_OPT_<NAME>_VALUES`: an initializer list of an enumerated or flags
  option's value names, indexed by the integer (enum) or bit (flags) stored.

The header is compiled into an FFmpeg filter, so it carries FFmpeg's licence
like the fork's other FFmpeg sources. An option whose default is the library's
(`default_macro`) stores NULL, and the filter asks the library at init.
"""

from __future__ import annotations

from .model import Api, Option
from .options import all_options

PATH = "ffmpeg-patches/src/vf_vmafx_options.h"
LICENCE = """/*
 * Copyright 2026 Lusoris
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * {spdx}
 */
"""
BANNER = """/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852),
 * option groups. Do not edit: change the definition and run
 * `python3 scripts/codegen/vmafx-api.py --write`. Consumed by the `vmafx`
 * filter (libavfilter/vf_vmafx.c), after libavutil/opt.h.
 */
"""
INT_MAX = 2_147_483_647
INT64_MAX = "INT64_MAX"
FIELD_TYPES = {
    "bool": "int",
    "int": "int",
    "uint": "int",
    "float": "double",
    "string": "char *",
    "enum": "int",
    "flags": "int",
}


def ffmpeg_options(api: Api) -> list[Option]:
    return [o for _, o in all_options(api.option_groups) if "ffmpeg" in o.surfaces]


def _wide(option: Option) -> bool:
    high = option.range[1] if option.range else None
    return option.type in ("int", "uint") and (high is None or high > INT_MAX)


def _field(option: Option) -> str:
    kind = "int64_t" if _wide(option) else FIELD_TYPES[option.type]
    space = "" if kind.endswith("*") else " "
    return f"    {kind}{space}{option.name};"


def _bounds(option: Option) -> tuple[str, str]:
    if option.type == "enum":
        return "0", str(len(option.values) - 1)
    if option.type == "flags":
        return "0", str((1 << len(option.values)) - 1)
    if option.type == "bool":
        return "0", "1"
    if option.type in ("string",):
        return "0", "0"
    low, high = option.range or (0.0 if option.type == "uint" else None, None)
    fallback = INT64_MAX if _wide(option) or option.type == "float" else "INT_MAX"
    low_text = (
        _number(low) if low is not None else ("-DBL_MAX" if option.type == "float" else "INT_MIN")
    )
    high_text = (
        _number(high) if high is not None else ("DBL_MAX" if option.type == "float" else fallback)
    )
    return low_text, high_text


def _number(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else repr(value)


def _default(option: Option) -> str:
    value = option.default_on("ffmpeg")
    if option.type == "string":
        return "{.str = NULL}" if value in (None, "") else "{.str = " + _c_string(str(value)) + "}"
    if option.type == "float":
        number = value if isinstance(value, int | float) else 0.0
        return "{.dbl = " + repr(float(number)) + "}"
    return "{.i64 = " + str(_int_default(option, value)) + "}"


def _int_default(option: Option, value: object) -> int:
    if value is None:
        return 0
    if option.type == "enum":
        return option.values.index(str(value))
    if option.type == "flags":
        assert isinstance(value, list)
        return sum(1 << option.values.index(v) for v in value)
    assert isinstance(value, int | float)
    return int(value)


def _av_type(option: Option) -> str:
    if option.type in ("enum", "flags"):
        return "AV_OPT_TYPE_FLAGS" if option.type == "flags" else "AV_OPT_TYPE_INT"
    return {
        "bool": "AV_OPT_TYPE_BOOL",
        "float": "AV_OPT_TYPE_DOUBLE",
        "string": "AV_OPT_TYPE_STRING",
    }.get(option.type, "AV_OPT_TYPE_INT64" if _wide(option) else "AV_OPT_TYPE_INT")


def _c_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _help(option: Option, alias_of: str = "") -> str:
    text = option.doc if not alias_of else f"alias of {alias_of}"
    if option.default_macro and not alias_of:
        text += f" (default: the library default, {option.default_macro})"
    return text


def _entries(option: Option) -> list[str]:
    low, high = _bounds(option)
    unit = _c_string(option.name) if option.type in ("enum", "flags") else "NULL"
    names = option.spellings["ffmpeg"]
    out = []
    for i, name in enumerate(names):
        help_text = _help(option, names[0] if i else "")
        out.append(
            f"    {{{_c_string(name)}, {_c_string(help_text)}, offsetof(CTX, {option.name}), "
            f"{_av_type(option)}, {_default(option)}, {low}, {high}, FLAGS, {unit}}},"
        )
    for index, value in enumerate(option.values):
        number = (1 << index) if option.type == "flags" else index
        out.append(
            f"    {{{_c_string(value)}, {_c_string(value)}, 0, AV_OPT_TYPE_CONST, "
            f"{{.i64 = {number}}}, 0, 0, FLAGS, {unit}}},"
        )
    return out


def _macro(name: str, lines: list[str]) -> list[str]:
    width = max(len(line) for line in lines) + 1
    body = [line.ljust(width) + "\\" for line in lines]
    return [f"#define {name} \\", *body[:-1], lines[-1]]


def _value_lists(options: list[Option]) -> list[str]:
    """`VMAFX_OPT_<NAME>_VALUES`: an initializer of the value names, index = stored integer."""
    out: list[str] = []
    for option in options:
        if option.type in ("enum", "flags"):
            values = ", ".join(_c_string(v) for v in option.values)
            out.append(f"#define VMAFX_OPT_{option.name.upper()}_VALUES {{{values}}}")
    return out


def header_text(api: Api) -> str:
    options = ffmpeg_options(api)
    fields = [_field(o) for o in options]
    entries = [line for o in options for line in _entries(o)]
    parts = [
        LICENCE.format(spdx="SPDX-" + "License-Identifier: LGPL-2.1-or-later") + BANNER,
        "#ifndef VMAFX_VF_VMAFX_OPTIONS_H",
        "#define VMAFX_VF_VMAFX_OPTIONS_H",
        "",
        "#include <float.h>",
        "#include <limits.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "// clang-format off",
        *_macro("VMAFX_FILTER_OPTION_FIELDS", fields),
        "",
        *_macro("VMAFX_FILTER_OPTIONS(CTX, FLAGS)", entries),
        "",
        *_value_lists(options),
        "// clang-format on",
        "",
        "#endif /* VMAFX_VF_VMAFX_OPTIONS_H */",
    ]
    return "\n".join(parts) + "\n"
