# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Meson install list of the generated headers (core/include/vmafx/meson.build).

Generated so a header added to or removed from `[[headers]]` is installed or
dropped in the same `--write`; no hand-kept list can fall behind.
"""

from __future__ import annotations

from .model import Api

INCLUDE_DIR = "core/include/"


def header_install(api: Api) -> str:
    names = [h.path.rsplit("/", 1)[-1] for h in api.headers]
    subdir = api.headers[0].path.rsplit("/", 1)[0]
    listed = "".join(f"    '{name}',\n" for name in names)
    return (
        "# Copyright 2026 Lusoris\n"
        "# " + "SPDX-" + "License-Identifier: EUPL-1.2\n"  # split: not this file's header
        "#\n"
        "# GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).\n"
        "# Do not edit: change [[headers]] and run `python3 scripts/codegen/vmafx-api.py --write`.\n"
        "# Every VMAFx header is generated; test_vmafx_api_generated_current fails when\n"
        "# one differs from the definition.\n"
        f"install_headers([\n{listed}], subdir : '{subdir}')\n"
    )
