# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Exported-symbol artefacts: linker version script, Windows `.def`, symbol list.

All three come from the functions of the definition and their `since`, so a
new function cannot ship unversioned: each lands in the version node of the
ABI minor that introduced it (`VMAFX_0.1`, `VMAFX_0.2`, ... each inheriting the
previous). `core/test/check_exported_symbols.py` reads the symbol list and
refuses a `vmafx_` export that is missing from it, a listed symbol the library
does not export, and an export in the wrong version node.

`[api] hide_unlisted = false` while the VMAFx functions share `libvmaf.so` with
the libvmaf API: the script then versions the `vmafx_` symbols and leaves every
other export as it was. The library split (ADR-1852 D3, WP6 / WP12) sets it to
true, which adds `local: *;` to the first node.
"""

from __future__ import annotations

from .model import Api, Function, node_name, version_text

HASH_HEADER = (
    "# Copyright 2026 Lusoris\n"
    "# " + "SPDX-" + "License-Identifier: EUPL-1.2\n"  # split: not this file's header
    "#\n"
    "# GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).\n"
    "# Do not edit: change the definition and run\n"
    "# `python3 scripts/codegen/vmafx-api.py --write`.\n"
)


def nodes(api: Api) -> list[tuple[tuple[int, int], list[Function]]]:
    """(ABI minor, its functions sorted by name), oldest first."""
    minors = sorted({fn.since for fn in api.functions})
    return [
        (m, sorted((f for f in api.functions if f.since == m), key=lambda f: f.name))
        for m in minors
    ]


def version_script(api: Api) -> str:
    out = [
        "/*",
        " * Copyright 2026 Lusoris",
        " * " + "SPDX-" + "License-Identifier: EUPL-1.2",
        " *",
        " * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).",
        " * Do not edit. One node per ABI minor, from each function's `since`.",
        " */",
    ]
    previous = ""
    for position, (minor, functions) in enumerate(nodes(api)):
        name = node_name(api, minor)
        out.append(f"{name} {{")
        out.append("    global:")
        out += [f"        {fn.name};" for fn in functions]
        if position == 0 and api.hide_unlisted:
            out += ["    local:", "        *;"]
        out.append(f"}}{' ' + previous if previous else ''};")
        previous = name
    return "\n".join(out) + "\n"


def def_file(api: Api) -> str:
    """Windows module-definition file: one EXPORTS line per function."""
    lines = [line.replace("#", ";", 1) for line in HASH_HEADER.splitlines()]
    names = sorted(fn.name for fn in api.functions)
    return "\n".join([*lines, "EXPORTS", *[f"    {name}" for name in names]]) + "\n"


def symbol_list(api: Api) -> str:
    """`<symbol> <version node>` per exported function, sorted by symbol."""
    rows = sorted((fn.name, node_name(api, fn.since)) for fn in api.functions)
    body = "".join(f"{name} {node}\n" for name, node in rows)
    note = f"# ABI {version_text(api.abi_version)}: symbol, linker version node.\n"
    return HASH_HEADER + note + body


def legacy_backends(api: Api) -> list[str]:
    """Backends whose builds keep libvmaf functions in the engine (declared exceptions)."""
    return sorted({c.engine_with for c in api.compats if c.engine_with})


def legacy_map_path(backend: str) -> str:
    return f"core/src/vmafx_legacy_{backend}.map"


def legacy_version_script(api: Api, backend: str) -> str:
    """Version node of the libvmaf functions the engine exports while `backend` is built.

    Linked next to vmafx.map only in builds with that backend; each name is a
    declared exception (`engine_with`, `until`) of the definition.
    """
    names = sorted(c.name for c in api.compats if c.engine_with == backend)
    out = [
        "/*",
        " * Copyright 2026 Lusoris",
        " * " + "SPDX-" + "License-Identifier: EUPL-1.2",
        " *",
        " * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).",
        f" * Do not edit. libvmaf functions libvmafx keeps while the {backend} backend is",
        " * built (declared exceptions of [[compat]], each with the work that ends it).",
        " */",
        f"VMAF_LEGACY_{backend.upper()} {{",
        "    global:",
        *[f"        {name};" for name in names],
        "};",
    ]
    return "\n".join(out) + "\n"


def compat_symbol_list(api: Api) -> str:
    """`<symbol> <library>[:<condition>]` per libvmaf function, sorted by symbol.

    `compat`: libvmaf.so.3 exports it in every build; `compat:!B`: unless
    backend B is built, when `engine:B` applies instead; `compat:F`: only in
    builds with feature F; `engine:B`: libvmafx.so.1 exports it in builds with
    backend B and nothing exports it otherwise.
    """
    rows = []
    for item in sorted(api.compats, key=lambda c: c.name):
        if item.kind == "engine":
            rows.append(f"{item.name} engine:{item.engine_with}")
        elif item.engine_with:
            rows.append(f"{item.name} compat:!{item.engine_with}")
        elif item.when:
            rows.append(f"{item.name} compat:{item.when}")
        else:
            rows.append(f"{item.name} compat")
    note = "# libvmaf functions: symbol, library[:condition] (emit_symbols.compat_symbol_list).\n"
    return HASH_HEADER + note + "".join(row + "\n" for row in rows)
