/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

#include <assert.h>
#include <errno.h>
#include <stddef.h>
#include <stdint.h>

#include "libvmaf/libvmaf.h"
#include "status_gen.h"
#include "vmafx/vmafx.h"
#include "vmafx/libvmaf_bridge.h"

/* NOLINTBEGIN(modernize-use-nullptr): C translation unit. The fork builds C as
 * C23, where clang-tidy also proposes the `nullptr` keyword, but MSVC's
 * documented /std:clatest C23 feature set does not include `nullptr` and the
 * required Windows builds compile this TU with cl.exe (C2065). ADR-1138. */

/* The negative errno libvmaf returned for this failure: the engine's own code
 * when the failure came from the engine, else the status's errno. Releases
 * the error. */
static int compat_errno(VmafxStatus status, VmafxError *error)
{
    const int32_t engine_errno = vmafx_error_errno(error);
    vmafx_error_free(error);
    if (engine_errno != 0) {
        return engine_errno;
    }
    return vmafx_status_to_errno(status);
}

/* libvmaf/libvmaf.h: vmaf_init() on vmafx_context_create() (glue). */
int vmaf_init(VmafContext **vmaf, VmafConfiguration cfg)
{
    if (!vmaf) {
        return -EINVAL;
    }
    *vmaf = NULL;
    VmafxContextConfig config = VMAFX_CONTEXT_CONFIG_INIT;
    config.log_level = (uint32_t)cfg.log_level;
    config.n_threads = cfg.n_threads;
    config.n_subsample = cfg.n_subsample;
    config.cpumask = cfg.cpumask;
    config.gpumask = cfg.gpumask;
    config.log_callback = NULL;
    config.log_user = NULL;
    VmafxContext *context = NULL;
    VmafxError *error = NULL;
    const VmafxStatus status = vmafx_context_create(&config, &context, &error);
    if (status != VMAFX_OK) {
        return compat_errno(status, error);
    }
    assert(context != NULL);
    *vmaf = vmafx_context_libvmaf_handle(context);
    return 0;
}

/* libvmaf/libvmaf.h: vmaf_close() on vmafx_context_destroy() (shim). */
int vmaf_close(VmafContext *vmaf)
{
    if (!vmaf) {
        return -EINVAL;
    }
    VmafxContext *context = vmafx_context_from_libvmaf(vmaf);
    if (!context) {
        return -EINVAL;
    }
    VmafxError *error = NULL;
    const VmafxStatus status = vmafx_context_destroy(context, &error);
    if (status != VMAFX_OK) {
        return compat_errno(status, error);
    }
    return 0;
}

/* libvmaf/libvmaf.h: vmaf_feature_score_at_index() on vmafx_feature_score() (shim). */
int vmaf_feature_score_at_index(VmafContext *vmaf, const char *feature_name, double *score,
                                unsigned index)
{
    if (!vmaf) {
        return -EINVAL;
    }
    if (!feature_name) {
        return -EINVAL;
    }
    if (!score) {
        return -EINVAL;
    }
    VmafxContext *context = vmafx_context_from_libvmaf(vmaf);
    if (!context) {
        return -EINVAL;
    }
    VmafxScore record = VMAFX_SCORE_INIT;
    VmafxError *error = NULL;
    const VmafxStatus status =
        vmafx_feature_score(context, feature_name, (uint64_t)index, &record, &error);
    if (status != VMAFX_OK) {
        return compat_errno(status, error);
    }
    *score = record.value;
    return 0;
}

/* libvmaf/libvmaf.h: vmaf_version() on vmafx_version_string() (shim). */
const char *vmaf_version(void)
{
    return vmafx_version_string();
}

/* NOLINTEND(modernize-use-nullptr) */
