/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

/* Internal status <-> errno maps; not exported (the library builds with
 * -fvisibility=hidden and these carry no export attribute). */

#ifndef VMAFX_STATUS_GEN_H
#define VMAFX_STATUS_GEN_H

#include "vmafx/vmafx.h"

/** Negative errno libvmaf returns for a status without an engine errno. */
int vmafx_status_to_errno(VmafxStatus status);

/** Status for a negative errno the engine returned. */
VmafxStatus vmafx_status_from_errno(int negative_errno);

#endif /* VMAFX_STATUS_GEN_H */
