#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Render each subtree ``AGENTS.md`` index from its ``AGENTS.d/`` topic pages.

A directory that carries ``AGENTS.d/`` keeps its agent invariants as one page
per topic. ``AGENTS.d/_index.md`` holds the title and the rules that apply to
every file of the directory; every other ``AGENTS.d/<slug>.md`` starts with a
front-matter block naming the paths it governs and its one-line invariant.
``AGENTS.md`` next to the directory is rendered from those files and is never
edited by hand.

Flags:
    --check   Exit 1 when an in-tree index differs from its rendering: stale
              against its pages, or edited or appended to by hand. The message
              names the page directory the text belongs in.
    --write   Rewrite every index.

Positional arguments restrict the run to the named directories (relative to
``--root``); without them every tracked or untracked-but-not-ignored
``AGENTS.d/`` is processed. Invalid sources (malformed front matter, a glob
that matches nothing, a page or index over its size budget) exit 65.

Wired into ``make docs-fragments-check`` / ``make docs-fragments-write``
(ADR-0221 pattern, ADR-1454).
"""

from __future__ import annotations

import argparse
import os
import posixpath
import re
import sys
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from scripts.lib.safe_subprocess import run as run_command  # noqa: E402

PAGES_DIR = "AGENTS.d"
HEAD_NAME = "_index.md"
INDEX_NAME = "AGENTS.md"
GUIDE = "docs/development/agents-index.md"

# Size budgets in bytes (ADR-1454). An index is read by every agent that works
# in the directory; a page only by an agent that touches its paths.
INDEX_MAX_BYTES = 16_000
PAGE_MAX_BYTES = 12_000
INVARIANT_MAX_CHARS = 120
MAX_PATHS_PER_PAGE = 24
MAX_REPORTED_LINES = 5
REPORTED_LINE_CHARS = 100

EXIT_STALE = 1
EXIT_INVALID = 65

SLUG_RE = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
GLOB_RE = re.compile(r"[A-Za-z0-9_.*?\[\]@+-]+(?:/[A-Za-z0-9_.*?\[\]@+-]+)*")
H1_RE = re.compile(r"# \S")
COMMENT_RE = re.compile(r"<!--.*-->\s*")
FENCE_RE = re.compile(r"\s*(```+|~~~+)")
# A code span (left untouched) or the target of an inline link.
LINK_RE = re.compile(r"(?s)(`+)(?:(?!\1).)+\1|\]\(([^)\s]+)\)")
EXTERNAL_RE = re.compile(r"[A-Za-z][A-Za-z0-9+.-]*:|/|#")

BANNER = (
    "<!-- GENERATED by scripts/docs/agents_index.py from AGENTS.d/: do not edit by hand.\n"
    "Edit AGENTS.d/_index.md or a page under AGENTS.d/, then run\n"
    "`make docs-fragments-write`. -->\n"
)
TABLE_HEAD = "## Topic pages\n\n| Touching | Read first | Invariant |\n| --- | --- | --- |\n"


class AgentsIndexError(ValueError):
    """A source under ``AGENTS.d/`` does not satisfy the page contract."""


@dataclass(frozen=True)
class Page:
    """One topic page: its slug, governed path globs and one-line invariant."""

    slug: str
    paths: tuple[str, ...]
    invariant: str


def map_links(text: str, rewrite: Callable[[str], str]) -> str:
    """Return ``text`` with every relative inline-link target passed to ``rewrite``.

    Fenced code blocks and code spans are left untouched, as are targets with
    a scheme, absolute targets and same-file anchors.
    """

    def substitute(match: re.Match[str]) -> str:
        target = match.group(2)
        if target is None or EXTERNAL_RE.match(target):
            return match.group(0)
        return f"]({rewrite(target)})"

    out: list[str] = []
    for fenced, block in _blocks(text):
        out.append(block if fenced else LINK_RE.sub(substitute, block))
    return "".join(out)


def _blocks(text: str) -> list[tuple[bool, str]]:
    """Split ``text`` into (is-fenced-code, text) runs; blank lines end a run."""

    runs: list[tuple[bool, str]] = []
    current: list[str] = []
    fence = ""
    for line in text.splitlines(keepends=True):
        opener = FENCE_RE.match(line)
        if fence:
            current.append(line)
            if opener and opener.group(1).startswith(fence):
                runs.append((True, "".join(current)))
                current, fence = [], ""
            continue
        if opener:
            runs.append((False, "".join(current)))
            current, fence = [line], opener.group(1)[:3]
            continue
        current.append(line)
        if not line.strip():
            runs.append((False, "".join(current)))
            current = []
    runs.append((bool(fence), "".join(current)))
    return runs


def rebase_target(target: str, from_dir: str, to_dir: str) -> str:
    """Re-express a relative link ``target`` written in ``from_dir`` for ``to_dir``."""

    path, sep, fragment = target.partition("#")
    resolved = posixpath.normpath(posixpath.join(from_dir, path))
    slash = "/" if path.endswith("/") else ""
    return posixpath.relpath(resolved, to_dir or ".") + slash + sep + fragment


def rebase_links(text: str, from_dir: str, to_dir: str) -> str:
    """Rewrite every relative link in ``text`` from ``from_dir`` to ``to_dir``."""

    return map_links(text, lambda target: rebase_target(target, from_dir, to_dir))


def split_front_matter(text: str, name: str) -> tuple[list[str], str]:
    """Return (front-matter lines, body) of a page; raise when there is none."""

    lines = text.splitlines(keepends=True)
    if not lines or lines[0].rstrip() != "---":
        raise AgentsIndexError(f"{name}: the first line must open a `---` front-matter block")
    for number, line in enumerate(lines[1:], start=1):
        if line.rstrip() == "---":
            return [entry.rstrip("\n") for entry in lines[1:number]], "".join(lines[number + 1 :])
    raise AgentsIndexError(f"{name}: the front-matter block is never closed with `---`")


def parse_front_matter(lines: Sequence[str], name: str) -> tuple[tuple[str, ...], str]:
    """Parse the two-key front matter: a ``paths:`` list and ``invariant:``."""

    paths: list[str] = []
    fields: dict[str, str] = {}
    key = ""
    for line in lines:
        if line.startswith("  - ") and key == "paths":
            paths.append(line[4:].strip())
            continue
        key, sep, value = line.partition(":")
        if not sep or key not in ("paths", "invariant") or key in fields:
            raise AgentsIndexError(f"{name}: unexpected front-matter line {line!r}")
        fields[key] = value.strip()
    if set(fields) != {"paths", "invariant"} or fields["paths"]:
        raise AgentsIndexError(
            f"{name}: front matter needs `paths:` (a list) and `invariant:`, nothing else"
        )
    return tuple(paths), fields["invariant"]


def _check_paths(paths: Sequence[str], name: str, root: Path) -> None:
    if not 1 <= len(paths) <= MAX_PATHS_PER_PAGE:
        raise AgentsIndexError(f"{name}: `paths:` needs 1 to {MAX_PATHS_PER_PAGE} entries")
    if len(set(paths)) != len(paths):
        raise AgentsIndexError(f"{name}: `paths:` lists an entry twice")
    for pattern in paths:
        if not GLOB_RE.fullmatch(pattern) or ".." in pattern.split("/"):
            raise AgentsIndexError(f"{name}: path {pattern!r} is not a repository-relative glob")
        if next(iter(root.glob(pattern)), None) is None:
            raise AgentsIndexError(f"{name}: path {pattern!r} matches nothing in the tree")


def _check_invariant(invariant: str, name: str) -> None:
    if not invariant:
        raise AgentsIndexError(f"{name}: `invariant:` is empty")
    if len(invariant) > INVARIANT_MAX_CHARS:
        raise AgentsIndexError(
            f"{name}: `invariant:` is {len(invariant)} characters, limit {INVARIANT_MAX_CHARS}"
        )


def first_heading_is_h1(body: str) -> bool:
    """True when the first line that is neither blank nor a comment is an H1."""

    for line in body.splitlines():
        if line.strip() and not COMMENT_RE.fullmatch(line):
            return H1_RE.match(line) is not None
    return False


def load_page(path: Path, root: Path) -> Page:
    """Validate one topic page and return its index entry."""

    name = path.relative_to(root).as_posix()
    if not SLUG_RE.fullmatch(path.stem):
        raise AgentsIndexError(f"{name}: the file name must be lower-case words joined by `-`")
    raw = path.read_bytes()
    if len(raw) > PAGE_MAX_BYTES:
        raise AgentsIndexError(
            f"{name}: {len(raw)} bytes, page budget {PAGE_MAX_BYTES}; split it by topic"
        )
    front, body = split_front_matter(raw.decode("utf-8"), name)
    paths, invariant = parse_front_matter(front, name)
    _check_paths(paths, name, root)
    _check_invariant(invariant, name)
    if not first_heading_is_h1(body):
        raise AgentsIndexError(f"{name}: the body must start with a `# ` title")
    return Page(path.stem, paths, invariant)


def load_pages(pages_dir: Path, root: Path) -> list[Page]:
    """Load every page of one ``AGENTS.d/`` directory, sorted by slug."""

    name = pages_dir.relative_to(root).as_posix()
    entries = sorted(pages_dir.iterdir())
    for entry in entries:
        if entry.is_dir() or entry.suffix != ".md":
            raise AgentsIndexError(f"{name}: {entry.name} is not a Markdown page")
    pages = [load_page(entry, root) for entry in entries if entry.name != HEAD_NAME]
    if not pages:
        raise AgentsIndexError(f"{name}: no topic page next to {HEAD_NAME}")
    return pages


def split_head(text: str, name: str) -> tuple[str, str]:
    """Split ``_index.md`` into (comments and title, rules for every file)."""

    lines = text.splitlines(keepends=True)
    for number, line in enumerate(lines):
        if H1_RE.match(line):
            return "".join(lines[: number + 1]), "".join(lines[number + 1 :]).strip("\n")
        if line.strip() and not COMMENT_RE.fullmatch(line.rstrip("\n")):
            break
    raise AgentsIndexError(f"{name}: must start with a `# ` title (comments may precede it)")


def display_path(pattern: str, directory: str) -> str:
    """Spell a governed glob the way the index shows it."""

    prefix = f"{directory}/" if directory else ""
    if prefix and pattern.startswith(prefix):
        return pattern[len(prefix) :]
    return pattern if not prefix else f"/{pattern}"


def _row(page: Page, directory: str) -> str:
    touching = ", ".join(f"`{display_path(pattern, directory)}`" for pattern in page.paths)
    invariant = page.invariant.replace("|", "\\|")
    return f"| {touching} | [{page.slug}]({PAGES_DIR}/{page.slug}.md) | {invariant} |\n"


def _instruction(directory: str) -> str:
    guide = posixpath.relpath(GUIDE, directory or ".")
    return (
        "Generated index. Before editing: match every path you will touch against\n"
        "`Touching` in [Topic pages](#topic-pages) and read each matching page first; no\n"
        "match, no page. Text between here and [Topic pages](#topic-pages) binds every\n"
        "file of this directory. `Touching` paths: relative to this directory, leading\n"
        f"`/` = repository root. New invariant: new page under `{PAGES_DIR}/` ([how]({guide})).\n"
    )


def render(directory: str, root: Path = ROOT) -> str:
    """Return the full text of ``<directory>/AGENTS.md``."""

    pages_dir = root / directory / PAGES_DIR
    head_path = pages_dir / HEAD_NAME
    head_name = posixpath.join(directory, PAGES_DIR, HEAD_NAME)
    if not head_path.is_file():
        raise AgentsIndexError(f"{head_name}: missing; every {PAGES_DIR}/ needs it")
    pages = load_pages(pages_dir, root)
    title, rules = split_head(head_path.read_text(encoding="utf-8"), head_name)
    rules = rebase_links(rules, posixpath.join(directory, PAGES_DIR), directory)
    parts = [BANNER, title, "\n", _instruction(directory), "\n"]
    if rules:
        parts += [rules, "\n\n"]
    parts.append(TABLE_HEAD)
    parts += [_row(page, directory) for page in pages]
    text = "".join(parts)
    size = len(text.encode("utf-8"))
    if size > INDEX_MAX_BYTES:
        raise AgentsIndexError(
            f"{posixpath.join(directory, INDEX_NAME)}: {size} bytes, index budget "
            f"{INDEX_MAX_BYTES}; shorten `invariant:` lines or merge pages"
        )
    return text


def directories_from(files: Iterable[str]) -> list[str]:
    """Return the directories that own an ``AGENTS.d/`` among ``files``."""

    owners: set[str] = set()
    for name in files:
        parts = name.split("/")
        if PAGES_DIR in parts[:-1]:
            owners.add("/".join(parts[: parts.index(PAGES_DIR)]))
    return sorted(owners)


def discover(root: Path) -> list[str]:
    """List every directory with an ``AGENTS.d/`` that Git does not ignore."""

    environment = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    result = run_command(
        ("git", "-C", str(root), "ls-files", "-z", "--cached", "--others", "--exclude-standard"),
        allowed_executables=("git",),
        env=environment,
        capture_output=True,
        text=True,
        check=True,
        max_output_bytes=64 * 1_048_576,
    )
    names = [name for name in result.stdout.split("\0") if name and (root / name).is_file()]
    return directories_from(names)


def foreign_lines(current: str, rendered: str) -> list[str]:
    """Return the non-blank lines of ``current`` that the generator did not write."""

    produced = set(rendered.splitlines())
    return [line for line in current.splitlines() if line.strip() and line not in produced]


def stale_message(directory: str, current: str | None, rendered: str) -> str:
    """Say why an in-tree index differs from its rendering and where the text belongs."""

    name = posixpath.join(directory, INDEX_NAME)
    pages = posixpath.join(directory, PAGES_DIR) + "/"
    if current is None:
        return f"{name} is missing; it is rendered from {pages}: run `make docs-fragments-write`"
    extra = foreign_lines(current, rendered)
    if not extra:
        return f"{name} is stale against {pages}; run `make docs-fragments-write`"
    shown = "".join(f"\n    {line[:REPORTED_LINE_CHARS]}" for line in extra[:MAX_REPORTED_LINES])
    more = len(extra) - MAX_REPORTED_LINES
    shown += f"\n    ... {more} more" if more > 0 else ""
    return (
        f"{name} is generated and holds {len(extra)} line(s) its sources do not produce:{shown}\n"
        f"  Never edit or append to {name}. An invariant goes into a page under {pages}\n"
        f"  ({pages}{HEAD_NAME} only when it binds every file of the directory); then run\n"
        "  `make docs-fragments-write`, which overwrites the generated file."
    )


def _process(directory: str, root: Path, write: bool) -> int:
    text = render(directory, root)
    output = root / directory / INDEX_NAME
    if write:
        output.write_text(text, encoding="utf-8")
        return 0
    current = output.read_text(encoding="utf-8") if output.is_file() else None
    if current == text:
        return 0
    print(f"agents index: {stale_message(directory, current, text)}", file=sys.stderr)
    return EXIT_STALE


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("directories", nargs="*")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    directories = [name.strip("/") for name in args.directories] or discover(root)
    status = 0
    try:
        for directory in directories:
            status = max(status, _process(directory, root, args.write))
    except AgentsIndexError as exc:
        print(f"agents index: {exc}", file=sys.stderr)
        return EXIT_INVALID
    return status


if __name__ == "__main__":
    sys.exit(main())
