#!/usr/bin/env bash
# Scan every ADR for its `Tags:` field, bucket by tag, and emit one
# `docs/adr/by-tag/<tag>.md` index per distinct tag plus a top-level
# `docs/adr/by-tag/index.md`.
#
# Tag-line forms accepted in ADR front matter:
#   - **Tags**: ci, cuda, sycl              (the modern bullet form)
#   - Tags: simd, neon, motion              (legacy bare form)
#
# Output structure:
#   docs/adr/by-tag/index.md     Markdown index of every tag with counts
#   docs/adr/by-tag/<tag>.md     One file per tag, listing every ADR carrying
#                                that tag in numeric order
#
# The script is idempotent — it rewrites the entire `by-tag/` directory each
# run. Hand-edits inside `by-tag/` will be lost. The `--check` mode compares
# against the in-tree files and exits non-zero on drift; CI uses it.
#
# Flags:
#   --check   Compare against the in-tree by-tag/ files; exit 1 on drift.
#   --write   Rewrite by-tag/.
#
# Copyright 2026 Lusoris
# SPDX-License-Identifier: BSD-3-Clause-Plus-Patent

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
ADR_DIR="$REPO_ROOT/docs/adr"
BY_TAG_DIR="$ADR_DIR/by-tag"

mode="render"
case "${1:-}" in
  --check) mode="check" ;;
  --write) mode="write" ;;
  --help | -h)
    sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  "") ;;
  *)
    printf 'unknown flag: %s\n' "$1" >&2
    exit 64
    ;;
esac

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

python3 - "$ADR_DIR" "$WORK_DIR" <<'PY'
import os
import re
import sys
from collections import defaultdict

adr_dir = sys.argv[1]
work_dir = sys.argv[2]

fname_re = re.compile(r"^(\d{4})-(.+)\.md$")
# Accept either bullet-prefixed `- **Tags**:` or bare `Tags:`.
tag_re = re.compile(
    r"^\s*(?:[-*]\s*)?\*{0,2}[Tt]ags\*{0,2}\s*:\s*(.+?)\s*$",
    re.MULTILINE,
)
# Title line: `# ADR-NNNN: <title>` (first H1 in the file).
title_re = re.compile(r"^#\s+ADR-\d{4}:\s*(.+?)\s*$", re.MULTILINE)


def normalise_tag(raw: str) -> str:
    """Strip backticks, surrounding whitespace, trailing punctuation."""
    s = raw.strip().strip("`").strip()
    # Filter out template placeholders ("<...>", angle-bracketed examples).
    if not s or s.startswith("<") or s.endswith(">"):
        return ""
    # Disallow tag values containing whitespace — those are almost always
    # the inline-example line from ADR-0000 / README rather than real tags.
    if any(ch.isspace() for ch in s):
        return ""
    return s.lower()


by_tag: dict[str, list[tuple[int, str, str]]] = defaultdict(list)

for name in sorted(os.listdir(adr_dir)):
    m = fname_re.match(name)
    if not m:
        continue
    if name == "0000-template.md":
        continue
    path = os.path.join(adr_dir, name)
    try:
        with open(path, encoding="utf-8") as fh:
            # Front matter is small; read the first 60 lines only.
            head = "".join(fh.readline() for _ in range(60))
    except OSError:
        continue

    title_m = title_re.search(head)
    title = title_m.group(1) if title_m else name
    tag_m = tag_re.search(head)
    if not tag_m:
        continue
    raw_tags = tag_m.group(1)
    for raw in raw_tags.split(","):
        t = normalise_tag(raw)
        if not t:
            continue
        by_tag[t].append((int(m.group(1)), name, title))

# Sort entries within each tag ascending by ADR number.
for tag in by_tag:
    by_tag[tag].sort()

os.makedirs(work_dir, exist_ok=True)

# Per-tag files.
for tag, entries in sorted(by_tag.items()):
    safe = tag  # Tags are already kebab-case / lowercase alnum; trust them.
    out = os.path.join(work_dir, f"{safe}.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(f"# ADRs tagged `{tag}`\n\n")
        fh.write(
            "Auto-generated by `scripts/docs/generate-adr-by-tag.sh`. "
            "Edit ADR `Tags:` lines to update.\n\n"
        )
        fh.write(f"{len(entries)} ADR(s) carry this tag.\n\n")
        fh.write("| ID | Title |\n|----|-------|\n")
        for num, fname, title in entries:
            # Relative link from by-tag/<tag>.md to ../NNNN-<slug>.md
            fh.write(f"| [ADR-{num:04d}](../{fname}) | {title} |\n")

# Index file.
with open(os.path.join(work_dir, "index.md"), "w", encoding="utf-8") as fh:
    fh.write("# ADRs by tag\n\n")
    fh.write(
        "Auto-generated by `scripts/docs/generate-adr-by-tag.sh` from each "
        "ADR's `Tags:` field. One entry per distinct tag, sorted by tag name.\n\n"
    )
    fh.write(f"{len(by_tag)} distinct tags across the corpus.\n\n")
    fh.write("| Tag | ADR count |\n|-----|----------:|\n")
    for tag in sorted(by_tag):
        fh.write(f"| [{tag}]({tag}.md) | {len(by_tag[tag])} |\n")

print(f"wrote {len(by_tag)} tag files + index.md", file=sys.stderr)
PY

# Now reconcile WORK_DIR against BY_TAG_DIR.
if [[ "$mode" == render ]]; then
  # Print summary only (the actual files live in WORK_DIR for inspection).
  printf 'rendered into %s — pass --write to commit, --check to compare\n' \
    "$WORK_DIR"
  find "$WORK_DIR" -maxdepth 1 -type f -name '*.md' -printf '%f\n' |
    LC_ALL=C sort | head -20
  exit 0
fi

if [[ "$mode" == check ]]; then
  if [[ ! -d "$BY_TAG_DIR" ]]; then
    printf '%s does not exist — run --write first.\n' "$BY_TAG_DIR" >&2
    exit 1
  fi
  # Compare both directions: file set + content.
  drift=0
  while IFS= read -r f; do
    bn="$(basename "$f")"
    if [[ ! -f "$BY_TAG_DIR/$bn" ]]; then
      printf 'missing in tree: by-tag/%s\n' "$bn" >&2
      drift=1
      continue
    fi
    if ! diff -q "$f" "$BY_TAG_DIR/$bn" >/dev/null; then
      diff -u "$BY_TAG_DIR/$bn" "$f" >&2 || true
      drift=1
    fi
  done < <(find "$WORK_DIR" -maxdepth 1 -type f -name '*.md')
  while IFS= read -r f; do
    bn="$(basename "$f")"
    if [[ ! -f "$WORK_DIR/$bn" ]]; then
      printf 'stale in tree (no source ADR carries this tag): by-tag/%s\n' \
        "$bn" >&2
      drift=1
    fi
  done < <(find "$BY_TAG_DIR" -maxdepth 1 -type f -name '*.md' 2>/dev/null)
  if [[ $drift -ne 0 ]]; then
    printf '\ndocs/adr/by-tag/ is out of sync.\n' >&2
    printf 'Run: scripts/docs/generate-adr-by-tag.sh --write\n' >&2
    exit 1
  fi
  exit 0
fi

# --write: replace the directory contents atomically.
mkdir -p "$BY_TAG_DIR"
# Remove old .md files first so deleted tags don't linger.
find "$BY_TAG_DIR" -maxdepth 1 -type f -name '*.md' -delete
cp "$WORK_DIR"/*.md "$BY_TAG_DIR/"
printf 'docs/adr/by-tag/ rewritten (%d files).\n' \
  "$(find "$BY_TAG_DIR" -maxdepth 1 -type f -name '*.md' | wc -l)" >&2
