/**
 *  Copyright 2026 Lusoris
 *  SPDX-License-Identifier: EUPL-1.2
 *
 *  Elementary functions on fp32 pairs, for device code that has to follow a
 *  host computation done in fp64 without using fp64 itself: a SYCL kernel has
 *  no fp64 type (ADR-0220), and a HIP device's fp64 math library is too slow
 *  to call per pixel (ADR-1448). One definition for every backend; a backend
 *  supplies the primitives named below and includes this header.
 *
 *  A pair (hi + lo) carries about 48 significant bits. The functions here
 *  return their result to about 2^-44 of its value. That is not fp64: a value
 *  the host rounds from fp64 to fp32 comes out the same unless it lies within
 *  about 2^-20 of an fp32 step of a rounding boundary, roughly one result in
 *  a million. A twin built on these is close to the host to that degree, not
 *  bit-identical; where bit-identity is required the reference's fp64
 *  operations have to be replayed exactly, which no math-library call allows.
 *
 *  What the including file defines first:
 *
 *    VMAF_FF_INLINE         the specifier of every function here
 *    namespace vmaf_ffm_base   (an alias is enough) with the pair type `Ff`
 *                           {hi, lo} and the exact operations two_sum(),
 *                           quick_two_sum(), two_prod(), ff_add(), ff_mul(),
 *                           ff_neg() (ff_pair.h has them for a backend with
 *                           none of its own)
 *    VMAF_FF_FABS(x)        |x|, exact
 *    VMAF_FF_RINT(x)        x rounded to an integer, ties to even, exact
 *    VMAF_FF_SQRT(x)        an fp32 square root
 *    VMAF_FF_CBRT(x)        an fp32 cube root
 *    VMAF_FF_ROOT5(x)       an fp32 fifth root
 *
 *  The three roots are estimates: sqrt() corrects its estimate with one
 *  Newton step and the others with one Halley step, whose error is the cube
 *  of the estimate's, so any estimate within 2^-16 of the root gives the
 *  2^-44 above and the backend's own function need not be correctly rounded.
 *  The fp32 `/` in div() and sqrt() need not be either.
 *
 *  Every function assumes its translation unit is compiled with contraction
 *  off. sin_cos() and atan2() read their table through the pointer they are
 *  given: on SYCL the caller copies kAtanTable / kSinCosTable to device
 *  memory first, because a constant array indexed at run time inside a kernel
 *  is scratch memory there (ADR-1395). This header must not mention the fp64
 *  type.
 *
 *  A backend that compiles the subset Metal Shading Language and host C++
 *  share (Metal's language revision is C++14-based: no inline variables, no
 *  designated initializers, every pointer and every program-scope variable in
 *  an address space; no C++ standard library) defines VMAF_FF_MSL_SUBSET and,
 *  with it,
 *
 *    VMAF_FF_PROGRAM_CONST  the specifier of a program-scope constant
 *    VMAF_FF_TABLE_SPACE    the address space of the two tables
 *
 *  and gets those spellings and positional initializers (hi, lo) where the
 *  other backends get C++17 inline variables and designated initializers
 *  (feature/metal/metal_ciede_math.h, ADR-1498). For the other backends the
 *  preprocessed header is what it was before the subset existed.
 *
 *  The constants and tables are generated by scripts/dev/gen_sycl_ff_math.py.
 */

#ifndef VMAF_FEATURE_FF_MATH_H_
#define VMAF_FEATURE_FF_MATH_H_

#if !defined(__METAL_VERSION__)
#include <cstddef>
#include <cstdint>
#endif

#if !defined(VMAF_FF_INLINE) || !defined(VMAF_FF_FABS) || !defined(VMAF_FF_RINT) ||                \
    !defined(VMAF_FF_SQRT) || !defined(VMAF_FF_CBRT) || !defined(VMAF_FF_ROOT5)
#error "ff_math.h: define the backend's primitives before including it (see the header comment)"
#endif

/* How a constant, a pair initializer and a table pointer are spelled (see the
 * header comment). */
#if defined(VMAF_FF_MSL_SUBSET)
#if !defined(VMAF_FF_PROGRAM_CONST) || !defined(VMAF_FF_TABLE_SPACE)
#error "ff_math.h: VMAF_FF_MSL_SUBSET needs VMAF_FF_PROGRAM_CONST and VMAF_FF_TABLE_SPACE"
#endif
#define VMAF_FF_CONSTANT VMAF_FF_PROGRAM_CONST
#define VMAF_FF_PAIR_INIT(high, low) {high, low}
#else
#define VMAF_FF_CONSTANT inline constexpr
/* The arguments are initializer elements: parentheses would change what the
 * SYCL and HIP twins compile. */
// NOLINTNEXTLINE(bugprone-macro-parentheses): initializer elements, ADR-1498
#define VMAF_FF_PAIR_INIT(high, low) {.hi = high, .lo = low}
#if !defined(VMAF_FF_TABLE_SPACE)
#define VMAF_FF_TABLE_SPACE
#endif
#endif

namespace vmaf_ffm
{

using vmaf_ffm_base::Ff;
using vmaf_ffm_base::ff_add;
using vmaf_ffm_base::ff_mul;
using vmaf_ffm_base::ff_neg;
using vmaf_ffm_base::quick_two_sum;
using vmaf_ffm_base::two_prod;
using vmaf_ffm_base::two_sum;

/* ------------------------------------------------------------------ */
/* Generated constants (scripts/dev/gen_sycl_ff_math.py)               */
/* ------------------------------------------------------------------ */

// BEGIN GENERATED
// clang-format off
/* NOLINTBEGIN(modernize-use-std-numbers): generated parts of pairs and
 * triples. std::numbers has no pairs, and the high word of a pair must be
 * the literal its low word was computed against (ADR-1436). */
/* pi / 16 and ln 2 in three parts. The first has 13 significant bits, so
 * its product with an integer below 2^11 is exact. */
VMAF_FF_CONSTANT float kPi16A = 0x1.921p-3f;
VMAF_FF_CONSTANT float kPi16B = 0x1.f6a888p-16f;
VMAF_FF_CONSTANT float kPi16C = 0x1.68c234p-42f;
VMAF_FF_CONSTANT float kLn2A = 0x1.62ep-1f;
VMAF_FF_CONSTANT float kLn2B = 0x1.0bfbe8p-15f;
VMAF_FF_CONSTANT float kLn2C = 0x1.cf79acp-40f;
VMAF_FF_CONSTANT float kSixteenOverPi = 0x1.45f306p+2f;
VMAF_FF_CONSTANT float kInvLn2 = 0x1.715476p+0f;
VMAF_FF_CONSTANT Ff kPi = VMAF_FF_PAIR_INIT(0x1.921fb6p+1f, -0x1.777a5cp-24f);
VMAF_FF_CONSTANT Ff kHalfPi = VMAF_FF_PAIR_INIT(0x1.921fb6p+0f, -0x1.777a5cp-25f);
VMAF_FF_CONSTANT Ff kThird = VMAF_FF_PAIR_INIT(0x1.555556p-2f, -0x1.555556p-27f);
VMAF_FF_CONSTANT Ff kFifth = VMAF_FF_PAIR_INIT(0x1.99999ap-3f, -0x1.99999ap-29f);
VMAF_FF_CONSTANT Ff kSixth = VMAF_FF_PAIR_INIT(0x1.555556p-3f, -0x1.555556p-28f);
VMAF_FF_CONSTANT Ff kOne24 = VMAF_FF_PAIR_INIT(0x1.555556p-5f, -0x1.555556p-30f);
VMAF_FF_CONSTANT Ff kOne120 = VMAF_FF_PAIR_INIT(0x1.111112p-7f, -0x1.dddddep-32f);

/* 1 / n! for exp(): pairs where the term needs them, fp32 beyond. */
VMAF_FF_CONSTANT Ff kInvF3 = VMAF_FF_PAIR_INIT(0x1.555556p-3f, -0x1.555556p-28f);
VMAF_FF_CONSTANT Ff kInvF4 = VMAF_FF_PAIR_INIT(0x1.555556p-5f, -0x1.555556p-30f);
VMAF_FF_CONSTANT Ff kInvF5 = VMAF_FF_PAIR_INIT(0x1.111112p-7f, -0x1.dddddep-32f);
VMAF_FF_CONSTANT Ff kInvF6 = VMAF_FF_PAIR_INIT(0x1.6c16c2p-10f, -0x1.27d27ep-35f);
VMAF_FF_CONSTANT Ff kInvF7 = VMAF_FF_PAIR_INIT(0x1.a01a02p-13f, -0x1.7f97fap-39f);
VMAF_FF_CONSTANT float kInvF8 = 0x1.a01a02p-16f;
VMAF_FF_CONSTANT float kInvF9 = 0x1.71de3ap-19f;
VMAF_FF_CONSTANT float kInvF10 = 0x1.27e4fcp-22f;
VMAF_FF_CONSTANT float kInvF11 = 0x1.ae6456p-26f;
VMAF_FF_CONSTANT float kInvF12 = 0x1.1eed8ep-29f;
VMAF_FF_CONSTANT float kInvF13 = 0x1.612462p-33f;
VMAF_FF_CONSTANT float kInvF14 = 0x1.93974ap-37f;

/* atan(j / 16), j = 0 .. 16, as (hi, lo). */
VMAF_FF_CONSTANT float kAtanTable[2 * 17] = {
    0.0f, 0.0f,
    0x1.ff55bcp-5f, -0x1.1a6042p-30f,
    0x1.fd5baap-4f, -0x1.54f424p-30f,
    0x1.7b97b4p-3f, 0x1.79cb6p-28f,
    0x1.f5b76p-3f, -0x1.b4dfc8p-29f,
    0x1.362774p-2f, -0x1.1f0286p-27f,
    0x1.6f6194p-2f, 0x1.e4defp-30f,
    0x1.a64eecp-2f, 0x1.e611fep-29f,
    0x1.dac67p-2f, 0x1.586ed4p-28f,
    0x1.0657eap-1f, -0x1.6499e6p-26f,
    0x1.1e00bap-1f, 0x1.7bdfd6p-26f,
    0x1.345f02p-1f, -0x1.98e422p-28f,
    0x1.4978fap-1f, 0x1.934f7p-28f,
    0x1.5d5898p-1f, 0x1.c5a6c6p-27f,
    0x1.700a7cp-1f, 0x1.5e118cp-27f,
    0x1.819d0cp-1f, -0x1.1d4eb6p-26f,
    0x1.921fb6p-1f, -0x1.777a5cp-26f,
};

/* sin(k pi / 16) and cos(k pi / 16), k = 0 .. 31, as
 * (sin hi, sin lo, cos hi, cos lo). */
VMAF_FF_CONSTANT float kSinCosTable[4 * 32] = {
    0.0f, 0.0f, 0x1p+0f, 0.0f,
    0x1.8f8b84p-3f, -0x1.cb2cfap-30f, 0x1.f6297cp-1f, 0x1.feeb96p-26f,
    0x1.87de2ap-2f, 0x1.abaa58p-28f, 0x1.d906bcp-1f, 0x1.e651a8p-26f,
    0x1.1c73b4p-1f, -0x1.9465cep-27f, 0x1.a9b662p-1f, 0x1.21d434p-26f,
    0x1.6a09e6p-1f, 0x1.9fcef4p-27f, 0x1.6a09e6p-1f, 0x1.9fcef4p-27f,
    0x1.a9b662p-1f, 0x1.21d434p-26f, 0x1.1c73b4p-1f, -0x1.9465cep-27f,
    0x1.d906bcp-1f, 0x1.e651a8p-26f, 0x1.87de2ap-2f, 0x1.abaa58p-28f,
    0x1.f6297cp-1f, 0x1.feeb96p-26f, 0x1.8f8b84p-3f, -0x1.cb2cfap-30f,
    0x1p+0f, 0.0f, 0.0f, 0.0f,
    0x1.f6297cp-1f, 0x1.feeb96p-26f, -0x1.8f8b84p-3f, 0x1.cb2cfap-30f,
    0x1.d906bcp-1f, 0x1.e651a8p-26f, -0x1.87de2ap-2f, -0x1.abaa58p-28f,
    0x1.a9b662p-1f, 0x1.21d434p-26f, -0x1.1c73b4p-1f, 0x1.9465cep-27f,
    0x1.6a09e6p-1f, 0x1.9fcef4p-27f, -0x1.6a09e6p-1f, -0x1.9fcef4p-27f,
    0x1.1c73b4p-1f, -0x1.9465cep-27f, -0x1.a9b662p-1f, -0x1.21d434p-26f,
    0x1.87de2ap-2f, 0x1.abaa58p-28f, -0x1.d906bcp-1f, -0x1.e651a8p-26f,
    0x1.8f8b84p-3f, -0x1.cb2cfap-30f, -0x1.f6297cp-1f, -0x1.feeb96p-26f,
    0.0f, 0.0f, -0x1p+0f, 0.0f,
    -0x1.8f8b84p-3f, 0x1.cb2cfap-30f, -0x1.f6297cp-1f, -0x1.feeb96p-26f,
    -0x1.87de2ap-2f, -0x1.abaa58p-28f, -0x1.d906bcp-1f, -0x1.e651a8p-26f,
    -0x1.1c73b4p-1f, 0x1.9465cep-27f, -0x1.a9b662p-1f, -0x1.21d434p-26f,
    -0x1.6a09e6p-1f, -0x1.9fcef4p-27f, -0x1.6a09e6p-1f, -0x1.9fcef4p-27f,
    -0x1.a9b662p-1f, -0x1.21d434p-26f, -0x1.1c73b4p-1f, 0x1.9465cep-27f,
    -0x1.d906bcp-1f, -0x1.e651a8p-26f, -0x1.87de2ap-2f, -0x1.abaa58p-28f,
    -0x1.f6297cp-1f, -0x1.feeb96p-26f, -0x1.8f8b84p-3f, 0x1.cb2cfap-30f,
    -0x1p+0f, 0.0f, 0.0f, 0.0f,
    -0x1.f6297cp-1f, -0x1.feeb96p-26f, 0x1.8f8b84p-3f, -0x1.cb2cfap-30f,
    -0x1.d906bcp-1f, -0x1.e651a8p-26f, 0x1.87de2ap-2f, 0x1.abaa58p-28f,
    -0x1.a9b662p-1f, -0x1.21d434p-26f, 0x1.1c73b4p-1f, -0x1.9465cep-27f,
    -0x1.6a09e6p-1f, -0x1.9fcef4p-27f, 0x1.6a09e6p-1f, 0x1.9fcef4p-27f,
    -0x1.1c73b4p-1f, 0x1.9465cep-27f, 0x1.a9b662p-1f, 0x1.21d434p-26f,
    -0x1.87de2ap-2f, -0x1.abaa58p-28f, 0x1.d906bcp-1f, 0x1.e651a8p-26f,
    -0x1.8f8b84p-3f, 0x1.cb2cfap-30f, 0x1.f6297cp-1f, 0x1.feeb96p-26f,
};
/* NOLINTEND(modernize-use-std-numbers) */
// clang-format on
// END GENERATED

VMAF_FF_CONSTANT unsigned kAtanTableFloats = 2u * 17u;
VMAF_FF_CONSTANT unsigned kSinCosTableFloats = 4u * 32u;

/* The two tables in device memory. */
struct Tables {
    const VMAF_FF_TABLE_SPACE float *atan;    /* kAtanTable */
    const VMAF_FF_TABLE_SPACE float *sin_cos; /* kSinCosTable */
};

/* ------------------------------------------------------------------ */
/* Pair arithmetic beyond the backend's exact operations               */
/* ------------------------------------------------------------------ */

VMAF_FF_INLINE Ff from_float(float x)
{
#if defined(VMAF_FF_MSL_SUBSET)
    // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
    return {x, 0.0f};
#else
    return {.hi = x, .lo = 0.0f};
#endif
}

/* The pair rounded to fp32, once. */
VMAF_FF_INLINE float to_float(Ff a)
{
    return a.hi + a.lo;
}

VMAF_FF_INLINE Ff sub(Ff a, Ff b)
{
    return ff_add(a, ff_neg(b));
}

VMAF_FF_INLINE Ff add_f(Ff a, float b)
{
    const Ff sum = two_sum(a.hi, b);
    return quick_two_sum(sum.hi, sum.lo + a.lo);
}

VMAF_FF_INLINE Ff mul_f(Ff a, float b)
{
    const Ff product = two_prod(a.hi, b);
    const float cross = a.lo * b;
    return quick_two_sum(product.hi, product.lo + cross);
}

VMAF_FF_INLINE Ff square(Ff a)
{
    const Ff product = two_prod(a.hi, a.hi);
    const float cross = a.hi * a.lo;
    return quick_two_sum(product.hi, product.lo + (cross + cross));
}

/* a * p for a power of two p: exact. */
VMAF_FF_INLINE Ff scale(Ff a, float power_of_two)
{
#if defined(VMAF_FF_MSL_SUBSET)
    // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
    return {a.hi * power_of_two, a.lo * power_of_two};
#else
    return {.hi = a.hi * power_of_two, .lo = a.lo * power_of_two};
#endif
}

VMAF_FF_INLINE bool less(Ff a, Ff b)
{
    return a.hi < b.hi || (a.hi == b.hi && a.lo < b.lo);
}

/* a / b for a non-zero b. The two partial quotients need not be correctly
 * rounded: what the first leaves, the second takes from the exact residual.
 * So this is the device's own division twice, where a pair division built on
 * correctly rounded quotients (sycl_exact_fp.h's ff_div()) pays for two of
 * those. */
VMAF_FF_INLINE Ff div(Ff a, Ff b)
{
    const float q1 = a.hi / b.hi;
    const Ff residual = sub(a, mul_f(b, q1));
    const float q2 = residual.hi / b.hi;
    return quick_two_sum(q1, q2);
}

/* The square root of a non-negative pair: the device's fp32 root and one
 * Newton correction from the exact residual. As in div(), the root need not
 * be correctly rounded. */
VMAF_FF_INLINE Ff sqrt(Ff a)
{
    if (!(a.hi > 0.0f)) {
#if defined(VMAF_FF_MSL_SUBSET)
        // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
        return {0.0f, 0.0f};
#else
        return {.hi = 0.0f, .lo = 0.0f};
#endif
    }
    const float root = VMAF_FF_SQRT(a.hi);
    const Ff residual = sub(a, two_prod(root, root));
    const float correction = residual.hi / (root + root);
    return quick_two_sum(root, correction);
}

/* ------------------------------------------------------------------ */
/* Roots and powers                                                    */
/* ------------------------------------------------------------------ */

/* x^(1/n) from an fp32 estimate y by one Halley step,
 *   y * ((n - 1) y^n + (n + 1) x) / ((n + 1) y^n + (n - 1) x),
 * whose error is the cube of the estimate's. `yn` is y^n. */
VMAF_FF_INLINE Ff halley_root(Ff x, float y, Ff yn, float n)
{
    const Ff numerator = ff_add(mul_f(yn, n - 1.0f), mul_f(x, n + 1.0f));
    const Ff denominator = ff_add(mul_f(yn, n + 1.0f), mul_f(x, n - 1.0f));
    return mul_f(div(numerator, denominator), y);
}

/* x^(1/3) for x > 0. */
VMAF_FF_INLINE Ff cbrt(Ff x)
{
    const float y = VMAF_FF_CBRT(x.hi);
    const Ff y3 = mul_f(two_prod(y, y), y);
    return halley_root(x, y, y3, 3.0f);
}

/* x^2.4 for x > 0: the square of x times its fifth root. */
VMAF_FF_INLINE Ff pow_2_4(Ff x)
{
    const float y = VMAF_FF_ROOT5(x.hi);
    const Ff y5 = mul_f(square(two_prod(y, y)), y);
    const Ff root = halley_root(x, y, y5, 5.0f);
    return square(ff_mul(x, root));
}

/* x^7. */
VMAF_FF_INLINE Ff pow_7(float x)
{
    const Ff x2 = two_prod(x, x);
    const Ff x4 = square(x2);
    return mul_f(ff_mul(x4, x2), x);
}

/* ------------------------------------------------------------------ */
/* exp                                                                 */
/* ------------------------------------------------------------------ */

/* e^x = 2^k e^r with |r| <= ln(2) / 2. The exponent k is returned apart: for
 * a large negative x the result is below the fp32 range and only its product
 * with something else is representable. */
struct Exp {
    Ff value; /* e^r, in [0.70, 1.42] */
    int k;
};

VMAF_FF_INLINE Exp exp(float x)
{
    const float k = VMAF_FF_RINT(x * kInvLn2);
    Ff r = sub(from_float(x), two_prod(k, kLn2A));
    r = sub(r, two_prod(k, kLn2B));
    r = add_f(r, -(k * kLn2C));
    /* Terms 8 to 14 are below 2^-27 of the result: fp32 is enough there. */
    float tail = kInvF14;
    tail = tail * r.hi + kInvF13;
    tail = tail * r.hi + kInvF12;
    tail = tail * r.hi + kInvF11;
    tail = tail * r.hi + kInvF10;
    tail = tail * r.hi + kInvF9;
    tail = tail * r.hi + kInvF8;
    Ff p = add_f(kInvF7, tail * r.hi);
    p = ff_add(ff_mul(p, r), kInvF6);
    p = ff_add(ff_mul(p, r), kInvF5);
    p = ff_add(ff_mul(p, r), kInvF4);
    p = ff_add(ff_mul(p, r), kInvF3);
    p = add_f(ff_mul(p, r), 0.5f);
    p = add_f(ff_mul(p, r), 1.0f);
    p = add_f(ff_mul(p, r), 1.0f);
#if defined(VMAF_FF_MSL_SUBSET)
    // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
    return {p, (int)k};
#else
    return {.value = p, .k = (int)k};
#endif
}

/* ------------------------------------------------------------------ */
/* sin and cos                                                         */
/* ------------------------------------------------------------------ */

struct SinCos {
    Ff sin;
    Ff cos;
};

/* sin(x) and cos(x) for |x| below about 400: x = k pi / 16 + r with
 * |r| <= pi / 32, the functions of k pi / 16 from the table, those of r from
 * their series. */
VMAF_FF_INLINE SinCos sin_cos(Ff x, const VMAF_FF_TABLE_SPACE float *table)
{
    const float k = VMAF_FF_RINT(x.hi * kSixteenOverPi);
    Ff r = sub(x, two_prod(k, kPi16A));
    r = sub(r, two_prod(k, kPi16B));
    r = add_f(r, -(k * kPi16C));
    const Ff z = square(r);
    /* sin(r) = r + r z (-1/6 + z (1/120 + z (-1/5040 + z / 362880))) */
    const float sin_tail = -0x1.a01a02p-13f + z.hi * 0x1.71de3ap-19f;
    Ff s = add_f(kOne120, z.hi * sin_tail);
    s = sub(ff_mul(s, z), kSixth);
    const Ff sin_r = ff_add(r, ff_mul(r, ff_mul(s, z)));
    /* cos(r) = 1 + z (-1/2 + z (1/24 + z (-1/720 + z (1/40320 - z / 3628800)))) */
    const float cos_tail = -0x1.6c16c2p-10f + z.hi * (0x1.a01a02p-16f + z.hi * -0x1.27e4fcp-22f);
    Ff c = add_f(kOne24, z.hi * cos_tail);
    c = add_f(ff_mul(c, z), -0.5f);
    const Ff cos_r = add_f(ff_mul(c, z), 1.0f);

#if defined(VMAF_FF_MSL_SUBSET)
    /* k mod 32 as the other spelling takes it, in two's complement. */
    const size_t index = (size_t)((unsigned)(int)k & 31u) * 4u;
    // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
    const Ff sin_k = {table[index + 0u], table[index + 1u]};
    // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
    const Ff cos_k = {table[index + 2u], table[index + 3u]};
    // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
    return {ff_add(ff_mul(sin_k, cos_r), ff_mul(cos_k, sin_r)),
            sub(ff_mul(cos_k, cos_r), ff_mul(sin_k, sin_r))};
#else
    const size_t index = (size_t)((int)k & 31) * 4u;
    const Ff sin_k = {.hi = table[index + 0u], .lo = table[index + 1u]};
    const Ff cos_k = {.hi = table[index + 2u], .lo = table[index + 3u]};
    return {.sin = ff_add(ff_mul(sin_k, cos_r), ff_mul(cos_k, sin_r)),
            .cos = sub(ff_mul(cos_k, cos_r), ff_mul(sin_k, sin_r))};
#endif
}

/* ------------------------------------------------------------------ */
/* atan2                                                               */
/* ------------------------------------------------------------------ */

/* The angle of the point (x, y) in (-pi, pi], for fp32 coordinates that are
 * not both zero: the smaller coordinate over the larger is t in [0, 1],
 * atan(t) = atan(j / 16) + atan((t - j / 16) / (1 + t j / 16)) with the first
 * term from the table and the second, below 1 / 32, from its series. */
VMAF_FF_INLINE Ff atan2(float y, float x, const VMAF_FF_TABLE_SPACE float *table)
{
    const float ax = VMAF_FF_FABS(x);
    const float ay = VMAF_FF_FABS(y);
    const bool steep = ay > ax;
    const float small = steep ? ax : ay;
    const float large = steep ? ay : ax;
    const Ff t = div(from_float(small), from_float(large));
    const float j = VMAF_FF_RINT(t.hi * 16.0f);
    const float c = j * 0.0625f;
    const Ff u = div(add_f(t, -c), add_f(mul_f(t, c), 1.0f));
    const Ff z = square(u);
    /* atan(u) = u + u z (-1/3 + z (1/5 + z (-1/7 + z / 9))) */
    const float tail = -0x1.24924ap-3f + z.hi * 0x1.c71c72p-4f;
    Ff p = add_f(kFifth, z.hi * tail);
    p = sub(ff_mul(p, z), kThird);
    const Ff atan_u = ff_add(u, ff_mul(u, ff_mul(p, z)));
    const size_t index = (size_t)(int)j * 2u;
#if defined(VMAF_FF_MSL_SUBSET)
    // NOLINTNEXTLINE(modernize-use-designated-initializers): MSL has none, ADR-1498
    Ff angle = ff_add(Ff{table[index], table[index + 1u]}, atan_u);
#else
    Ff angle = ff_add(Ff{.hi = table[index], .lo = table[index + 1u]}, atan_u);
#endif
    if (steep) {
        angle = sub(kHalfPi, angle);
    }
    if (x < 0.0f) {
        angle = sub(kPi, angle);
    }
    if (y < 0.0f) {
        angle = ff_neg(angle);
    }
    return angle;
}

} // namespace vmaf_ffm

#endif /* VMAF_FEATURE_FF_MATH_H_ */
