// Copyright 2026 Lusoris
// SPDX-License-Identifier: EUPL-1.2

package scoreopts

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func mustLoad(t *testing.T) *Document {
	t.Helper()
	doc, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	return doc
}

// TestEmbeddedFileEqualsThePythonServerCopy: both MCP servers read the same
// generated bytes, so neither can serve a schema the other does not.
func TestEmbeddedFileEqualsThePythonServerCopy(t *testing.T) {
	t.Parallel()
	python, err := os.ReadFile(filepath.Join("..", "..", "mcp-server", "vmaf-mcp", "src", "vmaf_mcp", "options.gen.json"))
	if err != nil {
		t.Fatalf("read the Python copy: %v", err)
	}
	if !bytes.Equal(python, Raw()) {
		t.Fatal("pkg/scoreopts/options.gen.json differs from the Python server's copy: " +
			"run python3 scripts/codegen/vmafx-api.py --write")
	}
}

// TestParseRefusesADocumentWithoutOptions is the planted defect of Parse.
func TestParseRefusesADocumentWithoutOptions(t *testing.T) {
	t.Parallel()
	for _, raw := range []string{`{}`, `{"options": [], "argv": [], "tools": {}}`, `not json`} {
		if _, err := Parse([]byte(raw)); err == nil {
			t.Errorf("Parse(%q) accepted a document without options", raw)
		}
	}
}

func TestExtraArgsFollowTheDefinitionOrder(t *testing.T) {
	t.Parallel()
	doc := mustLoad(t)
	values := Values{
		"metal_device": float64(1),
		"threads":      float64(4),
		"feature":      []string{"psnr", "cambi=full_ref=true"},
		"tiny_fp16":    true,
		"no_reference": false,
		"frame_cnt":    uint64(10),
		"width":        float64(576), // a core option: not an extra flag
	}
	got := doc.ExtraArgs(values)
	want := []string{
		"--feature", "psnr", "--feature", "cambi=full_ref=true",
		"--tiny-fp16", "--threads", "4", "--frame_cnt", "10", "--metal_device", "1",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("ExtraArgs = %q, want %q", got, want)
	}
}

func TestCheckRefusesValuesTheDefinitionRefuses(t *testing.T) {
	t.Parallel()
	doc := mustLoad(t)
	cases := []struct {
		option, surface string
		value           any
		want            string
	}{
		{"pixel_format", "mcp", "422p", "invalid pixfmt 422p: must be one of 420|422|444"},
		{"bitdepth", "proto", uint64(14), "invalid bitdepth 14: must be one of 8|10|12|16"},
		{"tiny_crf", "mcp", float64(64), "invalid tiny_crf 64: must be <= 63"},
		{"width", "proto", uint64(0), "invalid width 0: must be >= 1"},
		{"threads", "mcp", float64(1.5), "expected an integer"},
		{"feature", "mcp", []string{"psnr", ""}, "invalid feature"},
		{"target_width", "proto", uint64(1920), "lands in RC5"},
		{"backend", "proto", "vulkan", "must be one of auto|cpu|cuda|sycl|hip|metal"},
		{"view_distance", "mcp", float64(1.5), "must be >= 3"},
	}
	for _, tc := range cases {
		option, ok := doc.Option(tc.option)
		if !ok {
			t.Fatalf("no option %q", tc.option)
		}
		err := option.Check(tc.surface, tc.value)
		if err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Errorf("Check(%s, %v) = %v, want %q", tc.option, tc.value, err, tc.want)
		}
	}
	threads, _ := doc.Option("threads")
	if err := threads.Check("mcp", float64(0)); err != nil {
		t.Errorf("threads 0 (score in the calling thread) refused: %v", err)
	}
	target, _ := doc.Option("target_width")
	if err := target.Check("proto", uint64(0)); err != nil {
		t.Errorf("a reserved option at its default refused: %v", err)
	}
}

func TestModelSpecAppendsSuffixesOnce(t *testing.T) {
	t.Parallel()
	doc := mustLoad(t)
	values := Values{"disable_clip": true, "enable_transform": false, "view_distance": 4.5, "display_height": uint64(2160)}
	got := doc.ModelSpec("version=vmaf_v0.6.1:disable_clip", values)
	want := "version=vmaf_v0.6.1:disable_clip:adm.adm_norm_view_dist=4.5:adm.adm_ref_display_height=2160"
	if got != want {
		t.Fatalf("ModelSpec = %q, want %q", got, want)
	}
}

func TestLibraryDefaultAndFlags(t *testing.T) {
	t.Parallel()
	doc := mustLoad(t)
	model, err := doc.LibraryDefault("model")
	if err != nil || !strings.HasPrefix(model, "vmaf_") {
		t.Fatalf("LibraryDefault(model) = %q, %v", model, err)
	}
	if _, err := doc.LibraryDefault("threads"); err == nil {
		t.Error("an option without default_macro reported a library default")
	}
	flags := map[string]string{"reference": "-r", "width": "--width", "quiet": "-q", "no_cuda": "--no_cuda", "subsample": "--subsample"}
	for option, want := range flags {
		if got, err := doc.Flag(option); err != nil || got != want {
			t.Errorf("Flag(%s) = %q, %v; want %q", option, got, err, want)
		}
	}
	if _, err := doc.Flag("perceptual_weight"); err == nil {
		t.Error("an FFmpeg-only option reported a vmaf flag")
	}
}

func TestFromMCPChecksAndRenames(t *testing.T) {
	t.Parallel()
	doc := mustLoad(t)
	values, err := doc.FromMCP(map[string]any{"pixfmt": "420", "feature": []any{"psnr"}, "unrelated": 1})
	if err != nil {
		t.Fatalf("FromMCP: %v", err)
	}
	if values["pixel_format"] != "420" || !reflect.DeepEqual(values["feature"], []string{"psnr"}) {
		t.Fatalf("FromMCP = %v", values)
	}
	if _, err := doc.FromMCP(map[string]any{"feature": []any{"psnr", 3}}); err == nil {
		t.Error("a feature list with a number accepted")
	}
}

func TestToolSchemasAreTheGeneratedOnes(t *testing.T) {
	t.Parallel()
	doc := mustLoad(t)
	for _, tool := range []string{"vmaf_score", "vmaf_score_encoded", "describe_worst_frames"} {
		schema, err := doc.ToolSchema(tool)
		if err != nil || !bytes.Contains(schema, []byte(`"https://json-schema.org/draft/2020-12/schema"`)) {
			t.Errorf("ToolSchema(%s) = %s, %v", tool, schema, err)
		}
	}
	if _, err := doc.ToolSchema("list_models"); err == nil {
		t.Error("a tool without option groups reported a generated schema")
	}
}
