/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

/* Compiled twice (core/test/meson.build): VMAF_COMPAT_SIDE_NEW=0 with the
 * engine's names (the old libvmaf bodies), =1 with VMAF_PUBLIC_NAMES (the
 * compat library). */

#if VMAF_COMPAT_SIDE_NEW
#define VMAF_COMPAT_THUNK(n) new_##n
#define VMAF_COMPAT_CALLS vmaf_compat_calls_new
#define VMAF_COMPAT_TABLE vmaf_compat_new
#define VMAF_COMPAT_ENTRIES_DEFINE
#else
#define VMAF_COMPAT_THUNK(n) old_##n
#define VMAF_COMPAT_CALLS vmaf_compat_calls_old
#define VMAF_COMPAT_TABLE vmaf_compat_old
#endif

#include "compat_conformance_gen.h"

/* NOLINTBEGIN(modernize-use-nullptr): C translation unit. The fork builds C as
 * C23, where clang-tidy also proposes the `nullptr` keyword, but MSVC's
 * documented /std:clatest C23 feature set does not include `nullptr` and the
 * required Windows builds compile this TU with cl.exe (C2065). ADR-1138. */

unsigned VMAF_COMPAT_CALLS[VMAF_COMPAT_COUNT];

static int VMAF_COMPAT_THUNK(0)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_AVAILABLE]++;
    return vmaf_dnn_available();
}

static int VMAF_COMPAT_THUNK(1)(VmafContext *ctx, const char *onnx_path, const VmafDnnConfig *cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_USE_TINY_MODEL]++;
    return vmaf_use_tiny_model(ctx, onnx_path, cfg);
}

static int VMAF_COMPAT_THUNK(2)(VmafContext *ctx, const char *codec_name, const char *preset,
                                int crf)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SET_CODEC_CONTEXT]++;
    return vmaf_dnn_set_codec_context(ctx, codec_name, preset, crf);
}

static int VMAF_COMPAT_THUNK(3)(const VmafContext *ctx)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_IS_CODEC_AWARE]++;
    return vmaf_dnn_is_codec_aware(ctx);
}

static int VMAF_COMPAT_THUNK(4)(VmafContext *ctx, VmafDnnResizeMode mode)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SET_RESIZE_MODE]++;
    return vmaf_dnn_set_resize_mode(ctx, mode);
}

static int VMAF_COMPAT_THUNK(5)(VmafDnnSession **out, const char *onnx_path,
                                const VmafDnnConfig *cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SESSION_OPEN]++;
    return vmaf_dnn_session_open(out, onnx_path, cfg);
}

static int VMAF_COMPAT_THUNK(6)(VmafDnnSession *sess, const uint8_t *in, size_t in_stride, int w,
                                int h, uint8_t *out, size_t out_stride)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SESSION_RUN_LUMA8]++;
    return vmaf_dnn_session_run_luma8(sess, in, in_stride, w, h, out, out_stride);
}

static int VMAF_COMPAT_THUNK(7)(VmafDnnSession *sess, const uint16_t *in, size_t in_stride, int w,
                                int h, int bpc, uint16_t *out, size_t out_stride)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SESSION_RUN_PLANE16]++;
    return vmaf_dnn_session_run_plane16(sess, in, in_stride, w, h, bpc, out, out_stride);
}

static int VMAF_COMPAT_THUNK(8)(VmafDnnSession *sess, const VmafDnnInput *inputs, size_t n_inputs,
                                VmafDnnOutput *outputs, size_t n_outputs)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SESSION_RUN]++;
    return vmaf_dnn_session_run(sess, inputs, n_inputs, outputs, n_outputs);
}

static void VMAF_COMPAT_THUNK(9)(VmafDnnSession *sess)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SESSION_CLOSE]++;
    vmaf_dnn_session_close(sess);
}

static const char *VMAF_COMPAT_THUNK(10)(VmafDnnSession *sess)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_SESSION_ATTACHED_EP]++;
    return vmaf_dnn_session_attached_ep(sess);
}

static int VMAF_COMPAT_THUNK(11)(const char *onnx_path, const char *registry_path)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DNN_VERIFY_SIGNATURE]++;
    return vmaf_dnn_verify_signature(onnx_path, registry_path);
}

static int VMAF_COMPAT_THUNK(12)(VmafFeatureDictionary **dict, const char *key, const char *val)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_FEATURE_DICTIONARY_SET]++;
    return vmaf_feature_dictionary_set(dict, key, val);
}

static int VMAF_COMPAT_THUNK(13)(VmafFeatureDictionary **dict)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_FEATURE_DICTIONARY_FREE]++;
    return vmaf_feature_dictionary_free(dict);
}

static int VMAF_COMPAT_THUNK(14)(VmafContext **vmaf, VmafConfiguration cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_INIT]++;
    return vmaf_init(vmaf, cfg);
}

static int VMAF_COMPAT_THUNK(15)(VmafContext *vmaf, VmafModel *model)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_USE_FEATURES_FROM_MODEL]++;
    return vmaf_use_features_from_model(vmaf, model);
}

static int VMAF_COMPAT_THUNK(16)(VmafContext *vmaf, VmafModelCollection *model_collection)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_USE_FEATURES_FROM_MODEL_COLLECTION]++;
    return vmaf_use_features_from_model_collection(vmaf, model_collection);
}

static int VMAF_COMPAT_THUNK(17)(VmafContext *vmaf, const char *feature_name,
                                 VmafFeatureDictionary *opts_dict)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_USE_FEATURE]++;
    return vmaf_use_feature(vmaf, feature_name, opts_dict);
}

static int VMAF_COMPAT_THUNK(18)(VmafContext *vmaf, const char *feature_name, double value,
                                 unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_IMPORT_FEATURE_SCORE]++;
    return vmaf_import_feature_score(vmaf, feature_name, value, index);
}

static int VMAF_COMPAT_THUNK(19)(VmafContext *vmaf, VmafPicture *ref, VmafPicture *dist,
                                 unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_READ_PICTURES]++;
    return vmaf_read_pictures(vmaf, ref, dist, index);
}

static int VMAF_COMPAT_THUNK(20)(VmafContext *vmaf, VmafModel *model, double *score, unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_SCORE_AT_INDEX]++;
    return vmaf_score_at_index(vmaf, model, score, index);
}

static int VMAF_COMPAT_THUNK(21)(VmafContext *vmaf, VmafModelCollection *model_collection,
                                 VmafModelCollectionScore *score, unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_SCORE_AT_INDEX_MODEL_COLLECTION]++;
    return vmaf_score_at_index_model_collection(vmaf, model_collection, score, index);
}

static int VMAF_COMPAT_THUNK(22)(VmafContext *vmaf, const char *feature_name, double *score,
                                 unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_FEATURE_SCORE_AT_INDEX]++;
    return vmaf_feature_score_at_index(vmaf, feature_name, score, index);
}

static int VMAF_COMPAT_THUNK(23)(VmafContext *vmaf, VmafModel *model,
                                 enum VmafPoolingMethod pool_method, double *score,
                                 unsigned index_low, unsigned index_high)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_SCORE_POOLED]++;
    return vmaf_score_pooled(vmaf, model, pool_method, score, index_low, index_high);
}

static int VMAF_COMPAT_THUNK(24)(VmafContext *vmaf, VmafModelCollection *model_collection,
                                 enum VmafPoolingMethod pool_method,
                                 VmafModelCollectionScore *score, unsigned index_low,
                                 unsigned index_high)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_SCORE_POOLED_MODEL_COLLECTION]++;
    return vmaf_score_pooled_model_collection(vmaf, model_collection, pool_method, score, index_low,
                                              index_high);
}

static int VMAF_COMPAT_THUNK(25)(VmafContext *vmaf, const char *feature_name,
                                 enum VmafPoolingMethod pool_method, double *score,
                                 unsigned index_low, unsigned index_high)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_FEATURE_SCORE_POOLED]++;
    return vmaf_feature_score_pooled(vmaf, feature_name, pool_method, score, index_low, index_high);
}

static int VMAF_COMPAT_THUNK(26)(VmafContext *vmaf, VmafPictureConfiguration cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PREALLOCATE_PICTURES]++;
    return vmaf_preallocate_pictures(vmaf, cfg);
}

static int VMAF_COMPAT_THUNK(27)(VmafContext *vmaf, VmafPicture *pic)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_FETCH_PREALLOCATED_PICTURE]++;
    return vmaf_fetch_preallocated_picture(vmaf, pic);
}

static int VMAF_COMPAT_THUNK(28)(VmafContext *vmaf)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_CLOSE]++;
    return vmaf_close(vmaf);
}

static int VMAF_COMPAT_THUNK(29)(VmafContext *vmaf, const char *output_path,
                                 enum VmafOutputFormat fmt)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_WRITE_OUTPUT]++;
    return vmaf_write_output(vmaf, output_path, fmt);
}

static int VMAF_COMPAT_THUNK(30)(VmafContext *vmaf, const char *output_path,
                                 enum VmafOutputFormat fmt, const char *score_format)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_WRITE_OUTPUT_WITH_FORMAT]++;
    return vmaf_write_output_with_format(vmaf, output_path, fmt, score_format);
}

static int VMAF_COMPAT_THUNK(31)(VmafContext *vmaf, enum VmafBackend *out)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_CONTEXT_GET_BACKEND]++;
    return vmaf_context_get_backend(vmaf, out);
}

static int VMAF_COMPAT_THUNK(32)(VmafContext *vmaf, const char *feature_name,
                                 const VmafFeatureDictionary *opts_dict,
                                 const VmafPictureConfiguration *pic_cfg, const char **twin_name,
                                 const char **unsupported_option)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_FEATURE_BACKEND_TWIN]++;
    return vmaf_feature_backend_twin(vmaf, feature_name, opts_dict, pic_cfg, twin_name,
                                     unsupported_option);
}

static int VMAF_COMPAT_THUNK(33)(VmafContext *vmaf, unsigned index, const char **name,
                                 enum VmafBackend *backend)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_REGISTERED_FEATURE_EXTRACTOR]++;
    return vmaf_registered_feature_extractor(vmaf, index, name, backend);
}

static const char *VMAF_COMPAT_THUNK(34)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_VERSION]++;
    return vmaf_version();
}

#if !VMAFX_ENGINE_EXPORTS_HIP
static int VMAF_COMPAT_THUNK(35)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_HIP_AVAILABLE]++;
    return vmaf_hip_available();
}

#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
static int VMAF_COMPAT_THUNK(36)(VmafHipState **out, VmafHipConfiguration cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_HIP_STATE_INIT]++;
    return vmaf_hip_state_init(out, cfg);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
static int VMAF_COMPAT_THUNK(37)(VmafContext *ctx, VmafHipState *state)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_HIP_IMPORT_STATE]++;
    return vmaf_hip_import_state(ctx, state);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
static void VMAF_COMPAT_THUNK(38)(VmafHipState **state)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_HIP_STATE_FREE]++;
    vmaf_hip_state_free(state);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
static int VMAF_COMPAT_THUNK(39)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_HIP_LIST_DEVICES]++;
    return vmaf_hip_list_devices();
}

#endif
#if VMAFX_BUILD_MCP
static int VMAF_COMPAT_THUNK(40)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_AVAILABLE]++;
    return vmaf_mcp_available();
}

#endif
#if VMAFX_BUILD_MCP
static int VMAF_COMPAT_THUNK(41)(VmafMcpTransport transport)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_TRANSPORT_AVAILABLE]++;
    return vmaf_mcp_transport_available(transport);
}

#endif
#if VMAFX_BUILD_MCP
static int VMAF_COMPAT_THUNK(42)(VmafMcpServer **out, VmafContext *ctx, const VmafMcpConfig *cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_INIT]++;
    return vmaf_mcp_init(out, ctx, cfg);
}

#endif
#if VMAFX_BUILD_MCP
static int VMAF_COMPAT_THUNK(43)(VmafMcpServer *server, VmafMcpSseConfig *cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_START_SSE]++;
    return vmaf_mcp_start_sse(server, cfg);
}

#endif
#if VMAFX_BUILD_MCP
static int VMAF_COMPAT_THUNK(44)(VmafMcpServer *server, const VmafMcpUdsConfig *cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_START_UDS]++;
    return vmaf_mcp_start_uds(server, cfg);
}

#endif
#if VMAFX_BUILD_MCP
static int VMAF_COMPAT_THUNK(45)(VmafMcpServer *server, const VmafMcpStdioConfig *cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_START_STDIO]++;
    return vmaf_mcp_start_stdio(server, cfg);
}

#endif
#if VMAFX_BUILD_MCP
static int VMAF_COMPAT_THUNK(46)(VmafMcpServer *server)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_STOP]++;
    return vmaf_mcp_stop(server);
}

#endif
#if VMAFX_BUILD_MCP
static void VMAF_COMPAT_THUNK(47)(VmafMcpServer **server)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MCP_CLOSE]++;
    vmaf_mcp_close(server);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(48)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_AVAILABLE]++;
    return vmaf_metal_available();
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(49)(VmafMetalState **out, VmafMetalConfiguration cfg)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_STATE_INIT]++;
    return vmaf_metal_state_init(out, cfg);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(50)(VmafContext *ctx, VmafMetalState *state)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_IMPORT_STATE]++;
    return vmaf_metal_import_state(ctx, state);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static void VMAF_COMPAT_THUNK(51)(VmafMetalState **state)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_STATE_FREE]++;
    vmaf_metal_state_free(state);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(52)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_LIST_DEVICES]++;
    return vmaf_metal_list_devices();
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(53)(VmafMetalState **out, VmafMetalExternalHandles handles)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_STATE_INIT_EXTERNAL]++;
    return vmaf_metal_state_init_external(out, handles);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(54)(VmafMetalState *state, uintptr_t iosurface, unsigned plane,
                                 unsigned w, unsigned h, unsigned bpc, int is_ref, unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_PICTURE_IMPORT]++;
    return vmaf_metal_picture_import(state, iosurface, plane, w, h, bpc, is_ref, index);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(55)(VmafMetalState *state)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_WAIT_COMPUTE]++;
    return vmaf_metal_wait_compute(state);
}

#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
static int VMAF_COMPAT_THUNK(56)(VmafContext *ctx, unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_METAL_READ_IMPORTED_PICTURES]++;
    return vmaf_metal_read_imported_pictures(ctx, index);
}

#endif
static int VMAF_COMPAT_THUNK(57)(VmafModel **model, VmafModelConfig *cfg, const char *version)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_LOAD]++;
    return vmaf_model_load(model, cfg, version);
}

static int VMAF_COMPAT_THUNK(58)(VmafModel **model, VmafModelConfig *cfg, const char *path)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_LOAD_FROM_PATH]++;
    return vmaf_model_load_from_path(model, cfg, path);
}

static int VMAF_COMPAT_THUNK(59)(VmafModel *model, const char *feature_name,
                                 VmafFeatureDictionary *opts_dict)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_FEATURE_OVERLOAD]++;
    return vmaf_model_feature_overload(model, feature_name, opts_dict);
}

static void VMAF_COMPAT_THUNK(60)(VmafModel *model)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_DESTROY]++;
    vmaf_model_destroy(model);
}

static unsigned VMAF_COMPAT_THUNK(61)(const VmafModel *model)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_FEATURE_COUNT]++;
    return vmaf_model_feature_count(model);
}

static const char *VMAF_COMPAT_THUNK(62)(const VmafModel *model, unsigned index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_FEATURE_NAME]++;
    return vmaf_model_feature_name(model, index);
}

static int VMAF_COMPAT_THUNK(63)(VmafModel **model, VmafModelCollection **model_collection,
                                 VmafModelConfig *cfg, const char *version)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_COLLECTION_LOAD]++;
    return vmaf_model_collection_load(model, model_collection, cfg, version);
}

static int VMAF_COMPAT_THUNK(64)(VmafModel **model, VmafModelCollection **model_collection,
                                 VmafModelConfig *cfg, const char *path)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_COLLECTION_LOAD_FROM_PATH]++;
    return vmaf_model_collection_load_from_path(model, model_collection, cfg, path);
}

static int VMAF_COMPAT_THUNK(65)(VmafModel *model, VmafModelCollection **model_collection,
                                 const char *feature_name, VmafFeatureDictionary *opts_dict)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_COLLECTION_FEATURE_OVERLOAD]++;
    return vmaf_model_collection_feature_overload(model, model_collection, feature_name, opts_dict);
}

static void VMAF_COMPAT_THUNK(66)(VmafModelCollection *model_collection)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_COLLECTION_DESTROY]++;
    vmaf_model_collection_destroy(model_collection);
}

static const void *VMAF_COMPAT_THUNK(67)(const void *prev, const char **version)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_MODEL_VERSION_NEXT]++;
    return vmaf_model_version_next(prev, version);
}

static const char *VMAF_COMPAT_THUNK(68)(void)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_DEFAULT_MODEL_VERSION]++;
    return vmaf_default_model_version();
}

static int VMAF_COMPAT_THUNK(69)(VmafContext *vmaf, int enabled)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_SET_PERCEPTUAL_WEIGHT_ENABLED]++;
    return vmaf_set_perceptual_weight_enabled(vmaf, enabled);
}

static int VMAF_COMPAT_THUNK(70)(VmafContext *vmaf, double strength)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_SET_PERCEPTUAL_WEIGHT_STRENGTH]++;
    return vmaf_set_perceptual_weight_strength(vmaf, strength);
}

static int VMAF_COMPAT_THUNK(71)(VmafContext *vmaf, const uint8_t *blob, size_t len,
                                 unsigned pic_index)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_SET_PERCEPTUAL_SIDEDATA]++;
    return vmaf_set_perceptual_sidedata(vmaf, blob, len, pic_index);
}

static int VMAF_COMPAT_THUNK(72)(VmafPicture *pic, enum VmafPixelFormat pix_fmt, unsigned bpc,
                                 unsigned w, unsigned h)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE_ALLOC]++;
    return vmaf_picture_alloc(pic, pix_fmt, bpc, w, h);
}

static int VMAF_COMPAT_THUNK(73)(VmafPicture *pic)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE_UNREF]++;
    return vmaf_picture_unref(pic);
}

static int VMAF_COMPAT_THUNK(74)(VmafPictureConvertContext **ctx, const VmafPicture *src,
                                 const VmafColor *src_color, const VmafPictureConvertTarget *target)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE_CONVERT_CONTEXT_INIT_WITH_COLOR]++;
    return vmaf_picture_convert_context_init_with_color(ctx, src, src_color, target);
}

static int VMAF_COMPAT_THUNK(75)(VmafPictureConvertContext *ctx, VmafPicture *dst,
                                 const VmafPicture *src)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE_CONVERT]++;
    return vmaf_picture_convert(ctx, dst, src);
}

static int VMAF_COMPAT_THUNK(76)(VmafPictureConvertContext *ctx)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE_CONVERT_CONTEXT_CLOSE]++;
    return vmaf_picture_convert_context_close(ctx);
}

static int VMAF_COMPAT_THUNK(77)(VmafPicture2 *pic, enum VmafPixelFormat pix_fmt, unsigned bpc,
                                 unsigned w, unsigned h)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE2_ALLOC]++;
    return vmaf_picture2_alloc(pic, pix_fmt, bpc, w, h);
}

static int VMAF_COMPAT_THUNK(78)(VmafPicture2 *pic)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE2_UNREF]++;
    return vmaf_picture2_unref(pic);
}

static int VMAF_COMPAT_THUNK(79)(const VmafPicture *src, VmafPicture2 *dst)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE_V1_TO_V2]++;
    return vmaf_picture_v1_to_v2(src, dst);
}

static int VMAF_COMPAT_THUNK(80)(const VmafPicture2 *src, VmafPicture *dst)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_PICTURE_V2_TO_V1]++;
    return vmaf_picture_v2_to_v1(src, dst);
}

static const char *VMAF_COMPAT_THUNK(81)(VmafBackendHandle backend)
{
    VMAF_COMPAT_CALLS[VMAF_COMPAT_BACKEND_HANDLE_NAME]++;
    return vmaf_backend_handle_name(backend);
}

const VmafCompatApi VMAF_COMPAT_TABLE = {
    .count = VMAF_COMPAT_COUNT,
    .dnn_available = VMAF_COMPAT_THUNK(0),
    .use_tiny_model = VMAF_COMPAT_THUNK(1),
    .dnn_set_codec_context = VMAF_COMPAT_THUNK(2),
    .dnn_is_codec_aware = VMAF_COMPAT_THUNK(3),
    .dnn_set_resize_mode = VMAF_COMPAT_THUNK(4),
    .dnn_session_open = VMAF_COMPAT_THUNK(5),
    .dnn_session_run_luma8 = VMAF_COMPAT_THUNK(6),
    .dnn_session_run_plane16 = VMAF_COMPAT_THUNK(7),
    .dnn_session_run = VMAF_COMPAT_THUNK(8),
    .dnn_session_close = VMAF_COMPAT_THUNK(9),
    .dnn_session_attached_ep = VMAF_COMPAT_THUNK(10),
    .dnn_verify_signature = VMAF_COMPAT_THUNK(11),
    .feature_dictionary_set = VMAF_COMPAT_THUNK(12),
    .feature_dictionary_free = VMAF_COMPAT_THUNK(13),
    .init = VMAF_COMPAT_THUNK(14),
    .use_features_from_model = VMAF_COMPAT_THUNK(15),
    .use_features_from_model_collection = VMAF_COMPAT_THUNK(16),
    .use_feature = VMAF_COMPAT_THUNK(17),
    .import_feature_score = VMAF_COMPAT_THUNK(18),
    .read_pictures = VMAF_COMPAT_THUNK(19),
    .score_at_index = VMAF_COMPAT_THUNK(20),
    .score_at_index_model_collection = VMAF_COMPAT_THUNK(21),
    .feature_score_at_index = VMAF_COMPAT_THUNK(22),
    .score_pooled = VMAF_COMPAT_THUNK(23),
    .score_pooled_model_collection = VMAF_COMPAT_THUNK(24),
    .feature_score_pooled = VMAF_COMPAT_THUNK(25),
    .preallocate_pictures = VMAF_COMPAT_THUNK(26),
    .fetch_preallocated_picture = VMAF_COMPAT_THUNK(27),
    .close = VMAF_COMPAT_THUNK(28),
    .write_output = VMAF_COMPAT_THUNK(29),
    .write_output_with_format = VMAF_COMPAT_THUNK(30),
    .context_get_backend = VMAF_COMPAT_THUNK(31),
    .feature_backend_twin = VMAF_COMPAT_THUNK(32),
    .registered_feature_extractor = VMAF_COMPAT_THUNK(33),
    .version = VMAF_COMPAT_THUNK(34),
#if !VMAFX_ENGINE_EXPORTS_HIP
    .hip_available = VMAF_COMPAT_THUNK(35),
#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
    .hip_state_init = VMAF_COMPAT_THUNK(36),
#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
    .hip_import_state = VMAF_COMPAT_THUNK(37),
#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
    .hip_state_free = VMAF_COMPAT_THUNK(38),
#endif
#if !VMAFX_ENGINE_EXPORTS_HIP
    .hip_list_devices = VMAF_COMPAT_THUNK(39),
#endif
#if VMAFX_BUILD_MCP
    .mcp_available = VMAF_COMPAT_THUNK(40),
#endif
#if VMAFX_BUILD_MCP
    .mcp_transport_available = VMAF_COMPAT_THUNK(41),
#endif
#if VMAFX_BUILD_MCP
    .mcp_init = VMAF_COMPAT_THUNK(42),
#endif
#if VMAFX_BUILD_MCP
    .mcp_start_sse = VMAF_COMPAT_THUNK(43),
#endif
#if VMAFX_BUILD_MCP
    .mcp_start_uds = VMAF_COMPAT_THUNK(44),
#endif
#if VMAFX_BUILD_MCP
    .mcp_start_stdio = VMAF_COMPAT_THUNK(45),
#endif
#if VMAFX_BUILD_MCP
    .mcp_stop = VMAF_COMPAT_THUNK(46),
#endif
#if VMAFX_BUILD_MCP
    .mcp_close = VMAF_COMPAT_THUNK(47),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_available = VMAF_COMPAT_THUNK(48),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_state_init = VMAF_COMPAT_THUNK(49),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_import_state = VMAF_COMPAT_THUNK(50),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_state_free = VMAF_COMPAT_THUNK(51),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_list_devices = VMAF_COMPAT_THUNK(52),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_state_init_external = VMAF_COMPAT_THUNK(53),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_picture_import = VMAF_COMPAT_THUNK(54),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_wait_compute = VMAF_COMPAT_THUNK(55),
#endif
#if !VMAFX_ENGINE_EXPORTS_METAL
    .metal_read_imported_pictures = VMAF_COMPAT_THUNK(56),
#endif
    .model_load = VMAF_COMPAT_THUNK(57),
    .model_load_from_path = VMAF_COMPAT_THUNK(58),
    .model_feature_overload = VMAF_COMPAT_THUNK(59),
    .model_destroy = VMAF_COMPAT_THUNK(60),
    .model_feature_count = VMAF_COMPAT_THUNK(61),
    .model_feature_name = VMAF_COMPAT_THUNK(62),
    .model_collection_load = VMAF_COMPAT_THUNK(63),
    .model_collection_load_from_path = VMAF_COMPAT_THUNK(64),
    .model_collection_feature_overload = VMAF_COMPAT_THUNK(65),
    .model_collection_destroy = VMAF_COMPAT_THUNK(66),
    .model_version_next = VMAF_COMPAT_THUNK(67),
    .default_model_version = VMAF_COMPAT_THUNK(68),
    .set_perceptual_weight_enabled = VMAF_COMPAT_THUNK(69),
    .set_perceptual_weight_strength = VMAF_COMPAT_THUNK(70),
    .set_perceptual_sidedata = VMAF_COMPAT_THUNK(71),
    .picture_alloc = VMAF_COMPAT_THUNK(72),
    .picture_unref = VMAF_COMPAT_THUNK(73),
    .picture_convert_context_init_with_color = VMAF_COMPAT_THUNK(74),
    .picture_convert = VMAF_COMPAT_THUNK(75),
    .picture_convert_context_close = VMAF_COMPAT_THUNK(76),
    .picture2_alloc = VMAF_COMPAT_THUNK(77),
    .picture2_unref = VMAF_COMPAT_THUNK(78),
    .picture_v1_to_v2 = VMAF_COMPAT_THUNK(79),
    .picture_v2_to_v1 = VMAF_COMPAT_THUNK(80),
    .backend_handle_name = VMAF_COMPAT_THUNK(81),
};

/* NOLINTEND(modernize-use-nullptr) */
