/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "vmafx/vmafx.h"

_Static_assert(sizeof(void *) == 8, "VMAFx builds 64-bit only (ADR-1258)");
_Static_assert(sizeof(VmafxContextConfig) == 32, "VmafxContextConfig size");
_Static_assert(offsetof(VmafxContextConfig, struct_size) == 0,
               "VmafxContextConfig.struct_size offset");
_Static_assert(offsetof(VmafxContextConfig, log_level) == 4, "VmafxContextConfig.log_level offset");
_Static_assert(offsetof(VmafxContextConfig, n_threads) == 8, "VmafxContextConfig.n_threads offset");
_Static_assert(offsetof(VmafxContextConfig, n_subsample) == 12,
               "VmafxContextConfig.n_subsample offset");
_Static_assert(offsetof(VmafxContextConfig, cpumask) == 16, "VmafxContextConfig.cpumask offset");
_Static_assert(offsetof(VmafxContextConfig, gpumask) == 24, "VmafxContextConfig.gpumask offset");
_Static_assert(sizeof(VmafxProvenance) == 32, "VmafxProvenance size");
_Static_assert(offsetof(VmafxProvenance, struct_size) == 0, "VmafxProvenance.struct_size offset");
_Static_assert(offsetof(VmafxProvenance, abi_major) == 4, "VmafxProvenance.abi_major offset");
_Static_assert(offsetof(VmafxProvenance, abi_minor) == 8, "VmafxProvenance.abi_minor offset");
_Static_assert(offsetof(VmafxProvenance, abi_patch) == 12, "VmafxProvenance.abi_patch offset");
_Static_assert(offsetof(VmafxProvenance, active_backend) == 16,
               "VmafxProvenance.active_backend offset");
_Static_assert(offsetof(VmafxProvenance, n_extractors) == 20,
               "VmafxProvenance.n_extractors offset");
_Static_assert(offsetof(VmafxProvenance, version) == 24, "VmafxProvenance.version offset");
_Static_assert(sizeof(VmafxExtractorInfo) == 16, "VmafxExtractorInfo size");
_Static_assert(offsetof(VmafxExtractorInfo, struct_size) == 0,
               "VmafxExtractorInfo.struct_size offset");
_Static_assert(offsetof(VmafxExtractorInfo, backend) == 4, "VmafxExtractorInfo.backend offset");
_Static_assert(offsetof(VmafxExtractorInfo, name) == 8, "VmafxExtractorInfo.name offset");
_Static_assert(sizeof(VmafxScore) == 40, "VmafxScore size");
_Static_assert(offsetof(VmafxScore, struct_size) == 0, "VmafxScore.struct_size offset");
_Static_assert(offsetof(VmafxScore, backend) == 4, "VmafxScore.backend offset");
_Static_assert(offsetof(VmafxScore, index) == 8, "VmafxScore.index offset");
_Static_assert(offsetof(VmafxScore, value) == 16, "VmafxScore.value offset");
_Static_assert(offsetof(VmafxScore, feature) == 24, "VmafxScore.feature offset");
_Static_assert(offsetof(VmafxScore, extractor) == 32, "VmafxScore.extractor offset");
_Static_assert(VMAFX_OK == 0, "VMAFX_OK");
_Static_assert(VMAFX_PENDING == 1, "VMAFX_PENDING");
_Static_assert(VMAFX_E_INVALID == -1, "VMAFX_E_INVALID");
_Static_assert(VMAFX_E_NOMEM == -2, "VMAFX_E_NOMEM");
_Static_assert(VMAFX_E_NOTSUP == -3, "VMAFX_E_NOTSUP");
_Static_assert(VMAFX_E_NOTFOUND == -4, "VMAFX_E_NOTFOUND");
_Static_assert(VMAFX_E_BUSY == -5, "VMAFX_E_BUSY");
_Static_assert(VMAFX_E_DEVICE == -6, "VMAFX_E_DEVICE");
_Static_assert(VMAFX_E_IO == -7, "VMAFX_E_IO");
_Static_assert(VMAFX_E_RANGE == -8, "VMAFX_E_RANGE");
_Static_assert(VMAFX_E_INTERNAL == -9, "VMAFX_E_INTERNAL");
_Static_assert(VMAFX_LOG_LEVEL_NONE == 0, "VMAFX_LOG_LEVEL_NONE");
_Static_assert(VMAFX_LOG_LEVEL_ERROR == 1, "VMAFX_LOG_LEVEL_ERROR");
_Static_assert(VMAFX_LOG_LEVEL_WARNING == 2, "VMAFX_LOG_LEVEL_WARNING");
_Static_assert(VMAFX_LOG_LEVEL_INFO == 3, "VMAFX_LOG_LEVEL_INFO");
_Static_assert(VMAFX_LOG_LEVEL_DEBUG == 4, "VMAFX_LOG_LEVEL_DEBUG");
_Static_assert(VMAFX_BACKEND_CPU == 0, "VMAFX_BACKEND_CPU");
_Static_assert(VMAFX_BACKEND_CUDA == 1, "VMAFX_BACKEND_CUDA");
_Static_assert(VMAFX_BACKEND_SYCL == 2, "VMAFX_BACKEND_SYCL");
_Static_assert(VMAFX_BACKEND_METAL == 3, "VMAFX_BACKEND_METAL");
_Static_assert(VMAFX_BACKEND_HIP == 4, "VMAFX_BACKEND_HIP");

int main(void)
{
    (void)printf("vmafx ABI layout: %d structs, %d fields, %d constants match the definition\n", 4,
                 22, 21);
    return 0;
}
