/**
 *
 *  Copyright 2026 Lusoris
 *
 *     Licensed under the BSD+Patent License (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         https://opensource.org/licenses/BSDplusPatent
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

/*
 * SYCL parity round 5 — CAMBI CPU vs. SYCL parity (ADR-1001).
 *
 * CAMBI (Contrast-Aware Multiscale Banding Index) is implemented by
 * cambi.c (CPU scalar / AVX2 / AVX-512 / NEON) and by
 * integer_cambi_sycl.cpp::vmaf_fex_cambi_sycl (SYCL GPU port of the
 * multi-scale banding detector: luminance masking, topk
 * accumulation, temporal integration).  ADR-0049 § "bit-for-bit" notes
 * the SYCL kernel is designed to match the CPU integer path.
 *
 * Prior state: test_integer_cambi_sycl.c was a smoke test only (the
 * file itself says "This is NOT a numerical-correctness test").  ADR-0957
 * claimed 16/18 registered SYCL extractors had active parity tests,
 * correctly excluding the two dormant SpEED twins but incorrectly
 * treating the smoke test as equivalent to a parity gate.  This test
 * fills that gap.
 *
 * Fixture: 256×256 — the CAMBI minimum is 216×216 (both dimensions;
 * see CAMBI_MIN_WIDTH_HEIGHT in cambi.c).  A quantised gradient pattern
 * (8-step / 32-pixel bands) is used so that CAMBI sees a non-trivial
 * banding score on both backends rather than a degenerate all-zero path.
 * Using identical ref and dist salts would collapse CAMBI to zero; using
 * different salts ensures a non-zero headline score.
 *
 * Tolerance: 1e-4 (places=4) — matches the ADR-0214 default for integer
 * kernels on Arc A380.  The SYCL kernel uses 32-bit integer accumulation
 * rather than 64-bit, consistent with the CUDA twin; single-frame
 * rounding stays within the places=4 bound empirically.
 *
 * Skip behaviour: if vmaf_sycl_state_init() fails (no oneAPI runtime or
 * no device visible) the test emits "[skip: no SYCL device]" and passes,
 * mirroring test_sycl_motion3_parity.c and all subsequent round tests.
 */

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "test.h"

#include "feature/feature_extractor.h"
#include "libvmaf/libvmaf.h"
#include "libvmaf/libvmaf_sycl.h"
#include "libvmaf/picture.h"

/* CAMBI minimum: 216×216.  Use 256×256 so both dimensions clear the
 * threshold and the cost stays small for CI. */
#define FIXTURE_W 256u
#define FIXTURE_H 256u
#define FIXTURE_BPC 8u
/* places=4 — ADR-0214 default for integer kernels. */
#define PARITY_TOL 1e-4

/* Fixture B ("textured"): the quantised-gradient fixture above is flat in the
 * vertical direction and flat along every image border, which makes three
 * host-side CAMBI stages unobservable — the spatial-mask box sum at the image
 * edge, `filter_mode`'s untouched first/last output rows, and the vertical
 * `mode3` tie-breaks.  A twin that clamped (replicated) the out-of-image
 * neighbours instead of zero-padding them, or that overwrote row 0 / row
 * height-1 in the vertical pass, still scored identically on fixture A and the
 * parity gate stayed green while real content drifted by 2.7e-3 (see
 * `docs/state.md` row T-GPU-CAMBI-PARITY-DRIFT-2026-09-05).
 *
 * Fixture B therefore adds what real content has and fixture A lacks: a
 * vertical gradient component, a deterministic per-pixel dither, and a border
 * that is not a continuation of its neighbour row/column.  It is generated by
 * an LCG so it is reproducible on every platform and needs no test asset. */
static uint32_t fixture_lcg(uint32_t x)
{
    return x * 1664525u + 1013904223u;
}

static int fill_pic(VmafPicture *pic, unsigned salt, int textured)
{
    int err = vmaf_picture_alloc(pic, VMAF_PIX_FMT_YUV420P, FIXTURE_BPC, FIXTURE_W, FIXTURE_H);
    if (err)
        return err;
    /* Textured variant: horizontal 32-px bands + a 48-row vertical ramp + a
     * ~19% deterministic +1 dither, and an inverted border ring so the first
     * and last row/column differ from their neighbours. */
    if (textured) {
        uint8_t *yt = (uint8_t *)pic->data[0];
        for (unsigned row = 0u; row < pic->h[0]; row++) {
            for (unsigned col = 0u; col < pic->w[0]; col++) {
                unsigned v = (col / 32u) * 24u + (row / 48u) * 5u + salt * 3u;
                const uint32_t h = fixture_lcg(row * 8191u + col * 131u + salt * 7919u);
                if ((h >> 29) < 3u)
                    v += 1u;
                if (row == 0u || row + 1u == pic->h[0] || col == 0u || col + 1u == pic->w[0])
                    v += 17u;
                yt[row * pic->stride[0] + col] = (uint8_t)(v & 0xFFu);
            }
        }
        for (unsigned p = 1u; p < 3u; p++) {
            uint8_t *plane = (uint8_t *)pic->data[p];
            for (unsigned row = 0u; row < pic->h[p]; row++) {
                memset(plane + row * pic->stride[p], 128, pic->w[p]);
            }
        }
        return 0;
    }
    /* 8-step quantised gradient (32-px bands) — a textbook banding
     * artefact that drives CAMBI to a non-zero score. */
    uint8_t *y = (uint8_t *)pic->data[0];
    for (unsigned row = 0u; row < pic->h[0]; row++) {
        for (unsigned col = 0u; col < pic->w[0]; col++) {
            const unsigned base = (col / 32u) * 32u + salt * 4u;
            y[row * pic->stride[0] + col] = (uint8_t)(base & 0xFFu);
        }
    }
    /* Flat neutral chroma — CAMBI is luma-only. */
    for (unsigned p = 1u; p < 3u; p++) {
        uint8_t *plane = (uint8_t *)pic->data[p];
        for (unsigned row = 0u; row < pic->h[p]; row++) {
            memset(plane + row * pic->stride[p], 128, pic->w[p]);
        }
    }
    return 0;
}

/* Feed one ref/dist pair then flush with an EOS marker. */
static char *feed_one_frame(VmafContext *vmaf, unsigned ref_salt, unsigned dist_salt, int textured)
{
    VmafPicture ref;
    VmafPicture dist;
    int err = fill_pic(&ref, ref_salt, textured);
    mu_assert("fill_pic(ref) failed", !err);
    err = fill_pic(&dist, dist_salt, textured);
    if (err) {
        vmaf_picture_unref(&ref);
        mu_assert("fill_pic(dist) failed", !err);
    }
    err = vmaf_read_pictures(vmaf, &ref, &dist, 0u);
    mu_assert("vmaf_read_pictures failed", !err);
    err = vmaf_read_pictures(vmaf, NULL, NULL, 0);
    mu_assert("vmaf_read_pictures(EOS) failed", !err);
    return NULL;
}

static char *run_cpu_cambi(double *score, int textured)
{
    VmafConfiguration cfg = {.log_level = VMAF_LOG_LEVEL_NONE};
    VmafContext *vmaf = NULL;
    int err = vmaf_init(&vmaf, cfg);
    mu_assert("CPU: vmaf_init failed", !err);
    err = vmaf_use_feature(vmaf, "cambi", NULL);
    mu_assert("CPU: vmaf_use_feature(cambi) failed", !err);
    char *msg = feed_one_frame(vmaf, 0u, 1u, textured);
    if (msg)
        return msg;
    err = vmaf_feature_score_at_index(vmaf, "Cambi_feature_cambi_score", score, 0u);
    mu_assert("CPU: Cambi_feature_cambi_score missing", !err);
    err = vmaf_close(vmaf);
    mu_assert("CPU: vmaf_close failed", !err);
    return NULL;
}

static char *run_sycl_cambi(double *score, int *device_present, int textured)
{
    *score = NAN;
    *device_present = 0;
    VmafSyclState *sycl_state = NULL;
    VmafSyclConfiguration sycl_cfg = {.device_index = -1};
    int err = vmaf_sycl_state_init(&sycl_state, sycl_cfg);
    if (err != 0 || sycl_state == NULL) {
        (void)fprintf(stderr, "[skip: no SYCL device] ");
        return NULL;
    }
    *device_present = 1;
    VmafConfiguration cfg = {.log_level = VMAF_LOG_LEVEL_NONE};
    VmafContext *vmaf = NULL;
    err = vmaf_init(&vmaf, cfg);
    mu_assert("SYCL: vmaf_init failed", !err);
    err = vmaf_sycl_import_state(vmaf, sycl_state);
    mu_assert("SYCL: vmaf_sycl_import_state failed", !err);
    err = vmaf_use_feature(vmaf, "cambi_sycl", NULL);
    mu_assert("SYCL: vmaf_use_feature(cambi_sycl) failed", !err);
    char *msg = feed_one_frame(vmaf, 0u, 1u, textured);
    if (msg) {
        (void)vmaf_close(vmaf);
        vmaf_sycl_state_free(&sycl_state);
        return msg;
    }
    err = vmaf_feature_score_at_index(vmaf, "Cambi_feature_cambi_score", score, 0u);
    mu_assert("SYCL: Cambi_feature_cambi_score missing", !err);
    err = vmaf_close(vmaf);
    mu_assert("SYCL: vmaf_close failed", !err);
    vmaf_sycl_state_free(&sycl_state);
    return NULL;
}

static char *test_cambi_sycl_registered(void)
{
    VmafFeatureExtractor *fex = vmaf_get_feature_extractor_by_name("cambi_sycl");
    mu_assert("cambi_sycl extractor must be registered", fex != NULL);
    mu_assert("cambi_sycl name matches", !strcmp(fex->name, "cambi_sycl"));
    return NULL;
}

static char *cambi_parity_for_fixture(int textured)
{
    double cpu_score = 0.0;
    double sycl_score = NAN;
    int device_present = 0;

    char *msg = run_cpu_cambi(&cpu_score, textured);
    if (msg)
        return msg;
    msg = run_sycl_cambi(&sycl_score, &device_present, textured);
    if (msg)
        return msg;
    if (!device_present)
        return NULL;

    const double delta = fabs(cpu_score - sycl_score);
    if (delta > PARITY_TOL) {
        (void)fprintf(stderr,
                      "\ncambi parity FAIL (%s fixture): cpu=%.8f sycl=%.8f delta=%.2e tol=%.2e\n",
                      textured ? "textured" : "gradient", cpu_score, sycl_score, delta, PARITY_TOL);
    }
    mu_assert("cambi CPU vs. SYCL delta exceeds ADR-0214 places=4 tolerance (1e-4)",
              delta <= PARITY_TOL);
    return NULL;
}

static char *test_cambi_cpu_sycl_parity(void)
{
    return cambi_parity_for_fixture(0);
}

/* Regression gate for the shared host-side drift fixed on branch
 * fix/gpu-cambi-parity-drift: the twin must mirror cambi.c's zero-padded
 * spatial-mask box sum and its untouched filter_mode border rows. */
static char *test_cambi_cpu_sycl_parity_textured(void)
{
    return cambi_parity_for_fixture(1);
}

char *run_tests(void)
{
    mu_run_test(test_cambi_sycl_registered);
    mu_run_test(test_cambi_cpu_sycl_parity);
    mu_run_test(test_cambi_cpu_sycl_parity_textured);
    return NULL;
}
