/**
 *
 *  Copyright 2026 Lusoris
 *
 *     Licensed under the BSD+Patent License (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         https://opensource.org/licenses/BSDplusPatent
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

/*
 * Round-2 GPU-kernel coverage gap-fill — cambi CPU vs. CUDA parity.
 *
 * CAMBI (Contrast-Aware Multiscale Banding Index) is a JND-tuned banding
 * detector with non-trivial multi-scale filtering. It is implemented by
 * cambi.c (CPU scalar) and integer_cambi_cuda.c + integer_cambi/cambi_score.cu
 * (CUDA kernel). Both backends require ≥ 216×216 input — see
 * CAMBI_MIN_WIDTH_HEIGHT in cambi.c / integer_cambi_cuda.c.
 *
 * A round-trip parity gate matters because CAMBI feeds the libvmaf-2.x.x
 * "vmaf_v0.6.1neg" + "vmaf_4k_v0.6.1" model lineages — silent CUDA drift
 * would bias every CHUG re-extract that uses one of those models.
 *
 * Skip behaviour: skips with "[skip: no CUDA device]" when no CUDA driver.
 */

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "test.h"

#include "feature/feature_extractor.h"
#include "libvmaf/libvmaf.h"
#include "libvmaf/libvmaf_cuda.h"
#include "libvmaf/picture.h"

/* CAMBI requires ≥ 216 on at least one dimension. 256x256 is comfortably
 * above the threshold and still cheap to run in CI. */
#define FIXTURE_W 256u
#define FIXTURE_H 256u
#define FIXTURE_BPC 8u

#define PARITY_TOL 1e-4

/* Fixture B ("textured"): the quantised-gradient fixture above is flat in the
 * vertical direction and flat along every image border, which makes three
 * host-side CAMBI stages unobservable — the spatial-mask box sum at the image
 * edge, `filter_mode`'s untouched first/last output rows, and the vertical
 * `mode3` tie-breaks.  A twin that clamped (replicated) the out-of-image
 * neighbours instead of zero-padding them, or that overwrote row 0 / row
 * height-1 in the vertical pass, still scored identically on fixture A and the
 * parity gate stayed green while real content drifted by 2.7e-3 (see
 * `docs/state.md` row T-GPU-CAMBI-PARITY-DRIFT-2026-09-05).
 *
 * Fixture B therefore adds what real content has and fixture A lacks: a
 * vertical gradient component, a deterministic per-pixel dither, and a border
 * that is not a continuation of its neighbour row/column.  It is generated by
 * an LCG so it is reproducible on every platform and needs no test asset. */
static uint32_t fixture_lcg(uint32_t x)
{
    return x * 1664525u + 1013904223u;
}

static int fill_pic(VmafPicture *pic, unsigned salt, int textured)
{
    int err = vmaf_picture_alloc(pic, VMAF_PIX_FMT_YUV420P, FIXTURE_BPC, FIXTURE_W, FIXTURE_H);
    if (err)
        return err;
    /* Textured variant: horizontal 32-px bands + a 48-row vertical ramp + a
     * ~19% deterministic +1 dither, and an inverted border ring so the first
     * and last row/column differ from their neighbours. */
    if (textured) {
        uint8_t *yt = (uint8_t *)pic->data[0];
        for (unsigned row = 0u; row < pic->h[0]; row++) {
            for (unsigned col = 0u; col < pic->w[0]; col++) {
                unsigned v = (col / 32u) * 24u + (row / 48u) * 5u + salt * 3u;
                const uint32_t h = fixture_lcg(row * 8191u + col * 131u + salt * 7919u);
                if ((h >> 29) < 3u)
                    v += 1u;
                if (row == 0u || row + 1u == pic->h[0] || col == 0u || col + 1u == pic->w[0])
                    v += 17u;
                yt[row * pic->stride[0] + col] = (uint8_t)(v & 0xFFu);
            }
        }
        for (unsigned p = 1u; p < 3u; p++) {
            uint8_t *plane = (uint8_t *)pic->data[p];
            for (unsigned row = 0u; row < pic->h[p]; row++) {
                memset(plane + row * pic->stride[p], 128, pic->w[p]);
            }
        }
        return 0;
    }
    /* Build a luma pattern with step-function banding-prone gradients so
     * CAMBI emits a non-trivial score in both backends. */
    uint8_t *y = (uint8_t *)pic->data[0];
    for (unsigned row = 0; row < pic->h[0]; row++) {
        for (unsigned col = 0; col < pic->w[0]; col++) {
            /* 8-step quantised gradient — classic banding artefact pattern. */
            const unsigned base = (col / 32u) * 32u + salt * 4u;
            y[row * pic->stride[0] + col] = (uint8_t)(base & 0xFFu);
        }
    }
    for (unsigned p = 1; p < 3; p++) {
        uint8_t *plane = (uint8_t *)pic->data[p];
        for (unsigned row = 0; row < pic->h[p]; row++) {
            memset(plane + row * pic->stride[p], 128, pic->w[p]);
        }
    }
    return 0;
}

static char *feed_one_frame(VmafContext *vmaf, unsigned ref_salt, unsigned dist_salt, int textured)
{
    VmafPicture ref;
    VmafPicture dist;
    int err = fill_pic(&ref, ref_salt, textured);
    mu_assert("fill_pic(ref) failed", !err);
    err = fill_pic(&dist, dist_salt, textured);
    mu_assert("fill_pic(dist) failed", !err);
    err = vmaf_read_pictures(vmaf, &ref, &dist, 0u);
    mu_assert("vmaf_read_pictures failed", !err);
    err = vmaf_read_pictures(vmaf, NULL, NULL, 0);
    mu_assert("vmaf_read_pictures(EOS) failed", !err);
    return NULL;
}

static char *run_cpu_cambi(double *score, int textured)
{
    VmafConfiguration cfg = {.log_level = VMAF_LOG_LEVEL_NONE};
    VmafContext *vmaf = NULL;
    int err = vmaf_init(&vmaf, cfg);
    mu_assert("CPU: vmaf_init failed", !err);

    err = vmaf_use_feature(vmaf, "cambi", NULL);
    mu_assert("CPU: vmaf_use_feature(cambi) failed", !err);

    char *msg = feed_one_frame(vmaf, 0u, 1u, textured);
    if (msg)
        return msg;

    err = vmaf_feature_score_at_index(vmaf, "Cambi_feature_cambi_score", score, 0u);
    mu_assert("CPU: vmaf_feature_score_at_index(cambi) failed", !err);
    err = vmaf_close(vmaf);
    mu_assert("CPU: vmaf_close failed", !err);
    return NULL;
}

static char *run_cuda_cambi(double *score, int textured)
{
    *score = NAN;
    VmafCudaState *cu_state = NULL;
    VmafCudaConfiguration cuda_cfg = {0};
    int err = vmaf_cuda_state_init(&cu_state, cuda_cfg);
    if (err != 0 || cu_state == NULL) {
        (void)fprintf(stderr, "[skip: no CUDA device] ");
        return NULL;
    }

    VmafConfiguration cfg = {.log_level = VMAF_LOG_LEVEL_NONE};
    VmafContext *vmaf = NULL;
    err = vmaf_init(&vmaf, cfg);
    mu_assert("CUDA: vmaf_init failed", !err);

    err = vmaf_cuda_import_state(vmaf, cu_state);
    mu_assert("CUDA: vmaf_cuda_import_state failed", !err);

    err = vmaf_use_feature(vmaf, "cambi_cuda", NULL);
    mu_assert("CUDA: vmaf_use_feature(cambi_cuda) failed", !err);

    char *msg = feed_one_frame(vmaf, 0u, 1u, textured);
    if (msg)
        return msg;

    err = vmaf_feature_score_at_index(vmaf, "Cambi_feature_cambi_score", score, 0u);
    mu_assert("CUDA: vmaf_feature_score_at_index(cambi) failed", !err);
    err = vmaf_close(vmaf);
    mu_assert("CUDA: vmaf_close failed", !err);
    err = vmaf_cuda_state_free(cu_state);
    mu_assert("CUDA: vmaf_cuda_state_free failed", !err);
    return NULL;
}

static char *test_cambi_cuda_registered(void)
{
    VmafFeatureExtractor *fex = vmaf_get_feature_extractor_by_name("cambi_cuda");
    mu_assert("cambi_cuda extractor must be registered", fex != NULL);
    mu_assert("cambi_cuda name matches", !strcmp(fex->name, "cambi_cuda"));
    return NULL;
}

static char *cambi_parity_for_fixture(int textured)
{
    double cpu = 0.0;
    double gpu = NAN;

    char *msg = run_cpu_cambi(&cpu, textured);
    if (msg)
        return msg;
    msg = run_cuda_cambi(&gpu, textured);
    if (msg)
        return msg;
    if (isnan(gpu))
        return NULL;

    const double delta = fabs(cpu - gpu);
    if (delta > PARITY_TOL) {
        (void)fprintf(stderr,
                      "\ncambi parity FAIL (%s fixture): cpu=%.8f cuda=%.8f delta=%.2e tol=%.2e\n",
                      textured ? "textured" : "gradient", cpu, gpu, delta, PARITY_TOL);
    }
    mu_assert("cambi CPU vs. CUDA delta exceeds places=4 tolerance (1e-4)", delta <= PARITY_TOL);
    return NULL;
}

static char *test_cambi_cpu_cuda_parity(void)
{
    return cambi_parity_for_fixture(0);
}

/* Regression gate for the shared host-side drift fixed on branch
 * fix/gpu-cambi-parity-drift: the twin must mirror cambi.c's zero-padded
 * spatial-mask box sum and its untouched filter_mode border rows. */
static char *test_cambi_cpu_cuda_parity_textured(void)
{
    return cambi_parity_for_fixture(1);
}

char *run_tests(void)
{
    mu_run_test(test_cambi_cuda_registered);
    mu_run_test(test_cambi_cpu_cuda_parity);
    mu_run_test(test_cambi_cpu_cuda_parity_textured);
    return NULL;
}
