/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * SYCL parity round 5 — CAMBI CPU vs. SYCL parity (ADR-1001).
 *
 * CAMBI (Contrast-Aware Multiscale Banding Index) is implemented by
 * cambi.c (CPU scalar / AVX2 / AVX-512 / NEON) and by
 * integer_cambi_sycl.cpp::vmaf_fex_cambi_sycl (SYCL GPU port of the
 * multi-scale banding detector: luminance masking, topk
 * accumulation, temporal integration).  ADR-0415 § "bit-for-bit" notes
 * the SYCL kernel is designed to match the CPU integer path.
 *
 * Prior state: test_integer_cambi_sycl.c was a smoke test only (the
 * file itself says "This is NOT a numerical-correctness test").  ADR-0957
 * claimed 16/18 registered SYCL extractors had active parity tests,
 * correctly excluding the two dormant SpEED twins but incorrectly
 * treating the smoke test as equivalent to a parity gate.  This test
 * fills that gap.
 *
 * Fixture: 256×256 — the CAMBI minimum is 216×216 (both dimensions;
 * see CAMBI_MIN_WIDTH_HEIGHT in cambi.c).  Two fixtures: a quantised
 * gradient (8-step / 32-pixel bands) and a "textured" one (below).  The
 * gradient's 32-code steps lie outside CAMBI's contrast range, so it scores
 * 0 but still drives the mask, filter and histogram stages; the textured
 * fixture's +1 dither scores non-zero and is asserted to.
 *
 * Tolerance: none. Since ADR-1357 the SYCL twin runs every stage on the
 * device with integer or float-for-float arithmetic and an exact top-K sum,
 * so each of the PARITY_FRAMES frames must match the CPU score bit for bit
 * (the ADR-0214 places=4 gate in scripts/ci/cross_backend_parity_gate.py is
 * the looser, cross-resolution contract).
 *
 * Skip behaviour: if vmaf_sycl_state_init() fails (no oneAPI runtime or
 * no device visible) the test emits "[skip: no SYCL device]" and passes,
 * mirroring test_sycl_motion3_parity.c and all subsequent round tests.
 */

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "test.h"

#include "feature/feature_extractor.h"
#include "libvmaf/feature.h"
#include "libvmaf/libvmaf.h"
#include "libvmaf/libvmaf_sycl.h"
#include "libvmaf/picture.h"

/* NOLINTBEGIN(modernize-use-nullptr): C translation unit. The fork builds C as
 * C23, where clang-tidy also proposes the `nullptr` keyword, but this is a C
 * translation unit whose sources spell the null pointer constant `NULL` and
 * MSVC's documented /std:clatest C23 feature set does not include `nullptr`
 * while the required Windows build compiles this TU with cl.exe. ADR-1138. */

/* CAMBI minimum: 216×216.  Use 256×256 so both dimensions clear the
 * threshold and the cost stays small for CI. */
#ifndef FIXTURE_W
#define FIXTURE_W 256u
#endif
#ifndef FIXTURE_H
#define FIXTURE_H 256u
#endif
#define FIXTURE_BPC 8u

/* Fixture B ("textured"): the quantised-gradient fixture above is flat in the
 * vertical direction and flat along every image border, which makes three
 * host-side CAMBI stages unobservable — the spatial-mask box sum at the image
 * edge, `filter_mode`'s untouched first/last output rows, and the vertical
 * `mode3` tie-breaks.  A twin that clamped (replicated) the out-of-image
 * neighbours instead of zero-padding them, or that overwrote row 0 / row
 * height-1 in the vertical pass, still scored identically on fixture A and the
 * parity gate stayed green while real content drifted by 2.7e-3 (see
 * `docs/state.md` row T-GPU-CAMBI-PARITY-DRIFT-2026-09-05).
 *
 * Fixture B therefore adds what real content has and fixture A lacks: a
 * vertical gradient component, a deterministic per-pixel dither, and a border
 * that is not a continuation of its neighbour row/column.  It is generated by
 * an LCG so it is reproducible on every platform and needs no test asset. */
static uint32_t fixture_lcg(uint32_t x)
{
    return x * 1664525u + 1013904223u;
}

static int fill_pic(VmafPicture *pic, unsigned salt, int textured)
{
    int err = vmaf_picture_alloc(pic, VMAF_PIX_FMT_YUV420P, FIXTURE_BPC, FIXTURE_W, FIXTURE_H);
    if (err)
        return err;
    /* Textured variant: horizontal 32-px bands + a 48-row vertical ramp + a
     * ~19% deterministic +1 dither, and an inverted border ring so the first
     * and last row/column differ from their neighbours. */
    if (textured) {
        uint8_t *yt = (uint8_t *)pic->data[0];
        for (unsigned row = 0u; row < pic->h[0]; row++) {
            for (unsigned col = 0u; col < pic->w[0]; col++) {
                unsigned v = (col / 32u) * 24u + (row / 48u) * 5u + salt * 3u;
                const uint32_t h = fixture_lcg(row * 8191u + col * 131u + salt * 7919u);
                if ((h >> 29) < 3u)
                    v += 1u;
                if (row == 0u || row + 1u == pic->h[0] || col == 0u || col + 1u == pic->w[0])
                    v += 17u;
                yt[row * pic->stride[0] + col] = (uint8_t)(v & 0xFFu);
            }
        }
        for (unsigned p = 1u; p < 3u; p++) {
            uint8_t *plane = (uint8_t *)pic->data[p];
            for (unsigned row = 0u; row < pic->h[p]; row++) {
                memset(plane + row * pic->stride[p], 128, pic->w[p]);
            }
        }
        return 0;
    }
    /* 8-step quantised gradient (32-px bands) — a textbook banding
     * artefact that drives CAMBI to a non-zero score. */
    uint8_t *y = (uint8_t *)pic->data[0];
    for (unsigned row = 0u; row < pic->h[0]; row++) {
        for (unsigned col = 0u; col < pic->w[0]; col++) {
            const unsigned base = (col / 32u) * 32u + salt * 4u;
            y[row * pic->stride[0] + col] = (uint8_t)(base & 0xFFu);
        }
    }
    /* Flat neutral chroma — CAMBI is luma-only. */
    for (unsigned p = 1u; p < 3u; p++) {
        uint8_t *plane = (uint8_t *)pic->data[p];
        for (unsigned row = 0u; row < pic->h[p]; row++) {
            memset(plane + row * pic->stride[p], 128, pic->w[p]);
        }
    }
    return 0;
}

/* Frames per run. Several frames exercise the double-buffered submit/collect
 * path (collect(N - 1) runs before submit(N)) and the per-frame reset of the
 * device-side selection state (ADR-1357). */
#define PARITY_FRAMES 4u

/* Feed PARITY_FRAMES ref/dist pairs (distorted salt varies per frame) then
 * flush with an EOS marker. */
static char *feed_frames(VmafContext *vmaf, int textured)
{
    for (unsigned frame = 0u; frame < PARITY_FRAMES; frame++) {
        VmafPicture ref;
        VmafPicture dist;
        int err = fill_pic(&ref, 0u, textured);
        mu_assert("fill_pic(ref) failed", !err);
        err = fill_pic(&dist, 1u + frame, textured);
        if (err) {
            vmaf_picture_unref(&ref);
            mu_assert("fill_pic(dist) failed", !err);
        }
        err = vmaf_read_pictures(vmaf, &ref, &dist, frame);
        mu_assert("vmaf_read_pictures failed", !err);
    }
    const int err = vmaf_read_pictures(vmaf, NULL, NULL, 0);
    mu_assert("vmaf_read_pictures(EOS) failed", !err);
    return NULL;
}

static char *collect_scores(VmafContext *vmaf, double *scores)
{
    for (unsigned frame = 0u; frame < PARITY_FRAMES; frame++) {
        const int err =
            vmaf_feature_score_at_index(vmaf, "Cambi_feature_cambi_score", &scores[frame], frame);
        mu_assert("Cambi_feature_cambi_score missing", !err);
    }
    return NULL;
}

static char *run_cpu_cambi(double *scores, int textured)
{
    VmafConfiguration cfg = {.log_level = VMAF_LOG_LEVEL_NONE};
    VmafContext *vmaf = NULL;
    int err = vmaf_init(&vmaf, cfg);
    mu_assert("CPU: vmaf_init failed", !err);
    err = vmaf_use_feature(vmaf, "cambi", NULL);
    mu_assert("CPU: vmaf_use_feature(cambi) failed", !err);
    char *msg = feed_frames(vmaf, textured);
    if (!msg)
        msg = collect_scores(vmaf, scores);
    err = vmaf_close(vmaf);
    if (msg)
        return msg;
    mu_assert("CPU: vmaf_close failed", !err);
    return NULL;
}

static char *run_sycl_cambi(double *scores, int *device_present, int textured)
{
    *device_present = 0;
    VmafSyclState *sycl_state = NULL;
    VmafSyclConfiguration sycl_cfg = {.device_index = -1};
    int err = vmaf_sycl_state_init(&sycl_state, sycl_cfg);
    if (err != 0 || sycl_state == NULL) {
        (void)fprintf(stderr, "[skip: no SYCL device] ");
        return NULL;
    }
    *device_present = 1;
    VmafConfiguration cfg = {.log_level = VMAF_LOG_LEVEL_NONE};
    VmafContext *vmaf = NULL;
    err = vmaf_init(&vmaf, cfg);
    mu_assert("SYCL: vmaf_init failed", !err);
    err = vmaf_sycl_import_state(vmaf, sycl_state);
    mu_assert("SYCL: vmaf_sycl_import_state failed", !err);
    err = vmaf_use_feature(vmaf, "cambi_sycl", NULL);
    mu_assert("SYCL: vmaf_use_feature(cambi_sycl) failed", !err);
    char *msg = feed_frames(vmaf, textured);
    if (!msg)
        msg = collect_scores(vmaf, scores);
    err = vmaf_close(vmaf);
    vmaf_sycl_state_free(&sycl_state);
    if (msg)
        return msg;
    mu_assert("SYCL: vmaf_close failed", !err);
    return NULL;
}

static char *test_cambi_sycl_registered(void)
{
    VmafFeatureExtractor *fex = vmaf_get_feature_extractor_by_name("cambi_sycl");
    mu_assert("cambi_sycl extractor must be registered", fex != NULL);
    mu_assert("cambi_sycl name matches", !strcmp(fex->name, "cambi_sycl"));
    return NULL;
}

/* Bit-exact per frame: every stage is integer or float-for-float with
 * cambi.c, and the device top-K sum is exact. cambi.c's own double sum is
 * exact too while the top-K sum stays below 2^29: at 256x256 the window is
 * 5x5, every c-value is below 2^6 and the top-K sum below 2^22; in the
 * 960x540 `_large` build the window is 17x17, every c-value is below 2^10
 * and the top-K sum (311040 values) below 2^28, so the two
 * agree to the last bit here (ADR-1357). */
static char *cambi_parity_for_fixture(int textured)
{
    double cpu_scores[PARITY_FRAMES] = {0};
    double sycl_scores[PARITY_FRAMES] = {0};
    int device_present = 0;

    char *msg = run_cpu_cambi(cpu_scores, textured);
    if (msg)
        return msg;
    msg = run_sycl_cambi(sycl_scores, &device_present, textured);
    if (msg)
        return msg;
    if (!device_present)
        return NULL;

    for (unsigned frame = 0u; frame < PARITY_FRAMES; frame++) {
        if (cpu_scores[frame] != sycl_scores[frame]) {
            (void)fprintf(
                stderr, "\ncambi parity FAIL (%s fixture, frame %u): cpu=%.17g sycl=%.17g\n",
                textured ? "textured" : "gradient", frame, cpu_scores[frame], sycl_scores[frame]);
        }
        mu_assert("cambi CPU vs. SYCL score is not bit-exact",
                  cpu_scores[frame] == sycl_scores[frame]);
    }
    /* At 256x256 the textured fixture's +1 dither is a 4-code step at 10 bit,
     * inside the contrast range, so it must exercise non-zero c-values; the
     * gradient's 32-code steps are not banding to CAMBI and score 0. The
     * 960x540 `_large` build scores 0 on both fixtures and checks parity only. */
    if (textured && FIXTURE_W == 256u)
        mu_assert("textured cambi fixture must score non-zero", cpu_scores[0] > 0.0);
    return NULL;
}

static char *test_cambi_cpu_sycl_parity(void)
{
    return cambi_parity_for_fixture(0);
}

/* Regression gate for the shared host-side drift fixed on branch
 * fix/gpu-cambi-parity-drift: the twin must mirror cambi.c's zero-padded
 * spatial-mask box sum and its untouched filter_mode border rows. */
static char *test_cambi_cpu_sycl_parity_textured(void)
{
    return cambi_parity_for_fixture(1);
}

/* Window-size guard (ADR-1357): cambi.c::init rejects any configuration whose
 * adjusted window (encode or source resolution, after the high-res speed-up)
 * has window^2 >= CAMBI_RECIPROCAL_LUT_SIZE (4226), i.e. above 65 x 65, with
 * -EINVAL. cambi_sycl must accept and reject exactly the same set. The cases
 * are init-only, at 3840x2160 where the default window_size of 65 adjusts to
 * a 65-pixel window, the largest accepted:
 *   window_size 65                    -> 65                accepted (boundary)
 *   window_size 66                    -> 67                rejected
 *   window_size 66, enc 1920x1080     -> 33 enc / 67 source rejected
 *   window_size 127, hrs 2160         -> 127 halved to 65  accepted
 *   window_size 127                   -> 127               rejected */
typedef struct {
    const char *window_size;
    const char *enc_width;
    const char *enc_height;
    const char *high_res_speedup;
    int expected;
} CambiWindowCase;

static const CambiWindowCase cambi_window_cases[] = {
    {"65", NULL, NULL, NULL, 0},           {"66", NULL, NULL, NULL, -EINVAL},
    {"66", "1920", "1080", NULL, -EINVAL}, {"127", NULL, NULL, "2160", 0},
    {"127", NULL, NULL, NULL, -EINVAL},
};

static int cambi_window_options(const CambiWindowCase *c, VmafFeatureDictionary **opts)
{
    int err = vmaf_feature_dictionary_set(opts, "window_size", c->window_size);
    if (!err && c->enc_width)
        err = vmaf_feature_dictionary_set(opts, "enc_width", c->enc_width);
    if (!err && c->enc_height)
        err = vmaf_feature_dictionary_set(opts, "enc_height", c->enc_height);
    if (!err && c->high_res_speedup)
        err = vmaf_feature_dictionary_set(opts, "cambi_high_res_speedup", c->high_res_speedup);
    return err;
}

/* Initialise `name` for a 3840x2160 8-bit picture with the case's options and
 * return init's code (tearing the context down either way). */
static char *cambi_window_init_rc(const char *name, VmafSyclState *sycl_state,
                                  const CambiWindowCase *c, int *rc)
{
    const VmafFeatureExtractor *fex = vmaf_get_feature_extractor_by_name(name);
    mu_assert("cambi extractor must be registered", fex != NULL);
    VmafFeatureDictionary *opts = NULL;
    mu_assert("cambi window options", !cambi_window_options(c, &opts));
    VmafFeatureExtractorContext *ctx = NULL;
    int err = vmaf_feature_extractor_context_create(&ctx, fex, (VmafDictionary *)opts);
    mu_assert("cambi context create", !err);
    ctx->fex->sycl_state = sycl_state;
    *rc = vmaf_feature_extractor_context_init(ctx, VMAF_PIX_FMT_YUV420P, 8u, 3840u, 2160u);
    if (*rc == 0) {
        err = vmaf_feature_extractor_context_close(ctx);
        mu_assert("cambi context close", !err);
    }
    err = vmaf_feature_extractor_context_destroy(ctx);
    mu_assert("cambi context destroy", !err);
    return NULL;
}

static char *test_cambi_window_lut_guard(void)
{
    VmafSyclState *sycl_state = NULL;
    VmafSyclConfiguration sycl_cfg = {.device_index = -1};
    const int sycl_err = vmaf_sycl_state_init(&sycl_state, sycl_cfg);
    const int device_present = sycl_err == 0 && sycl_state != NULL;
    if (!device_present)
        (void)fprintf(stderr, "[skip SYCL half: no SYCL device] ");
    char *msg = NULL;
    const size_t n_cases = sizeof(cambi_window_cases) / sizeof(cambi_window_cases[0]);
    for (size_t i = 0; i < n_cases && !msg; i++) {
        const CambiWindowCase *c = &cambi_window_cases[i];
        int cpu_rc = 1;
        int sycl_rc = 1;
        msg = cambi_window_init_rc("cambi", NULL, c, &cpu_rc);
        if (!msg && device_present)
            msg = cambi_window_init_rc("cambi_sycl", sycl_state, c, &sycl_rc);
        if (msg)
            break;
        if (cpu_rc != c->expected || (device_present && sycl_rc != cpu_rc)) {
            (void)fprintf(stderr,
                          "\ncambi window case %zu (window_size=%s): cpu=%d sycl=%d want=%d\n", i,
                          c->window_size, cpu_rc, sycl_rc, c->expected);
            msg = "cambi window-size guard differs between CPU, SYCL and the LUT bound";
        }
    }
    if (device_present)
        vmaf_sycl_state_free(&sycl_state);
    return msg;
}

char *run_tests(void)
{
    mu_run_test(test_cambi_sycl_registered);
    mu_run_test(test_cambi_cpu_sycl_parity);
    mu_run_test(test_cambi_cpu_sycl_parity_textured);
    mu_run_test(test_cambi_window_lut_guard);
    return NULL;
}

/* NOLINTEND(modernize-use-nullptr) */
