// Copyright 2026 Lusoris
// SPDX-License-Identifier: BSD-3-Clause-Plus-Patent OR MIT
//
// pkg/fast/jsonfloat_test.go — byte-compatibility tests for the Python
// float-repr encoder that keeps the `fast` JSON payload identical between
// the Go and Python implementations.

package fast

import (
	"encoding/json"
	"math"
	"strconv"
	"testing"
)

// TestPythonFloatRepr pins the formatter against CPython's repr(float).
//
// The want column was generated by:
//
//	python3 -c "
//	for v in [0.0, -0.0, 1.0, 90.0, -12.5, 0.1, 0.0001, 1e-05, 1e-06,
//	          1e15, 1e16, 1e17, 1234567.0, 3486.832605990455,
//	          90.3551546220283, 99.0, 52.0, 1e6, 123456789012345678.0,
//	          2.5e-10, 5e-324, 1.7976931348623157e308,
//	          0.30000000000000004, 123.456]:
//	    print(repr(v))"
func TestPythonFloatRepr(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   float64
		want string
	}{
		{name: "zero gains a .0", in: 0.0, want: "0.0"},
		{name: "negative zero keeps its sign", in: math.Copysign(0, -1), want: "-0.0"},
		{name: "one", in: 1.0, want: "1.0"},
		{name: "integral VMAF target", in: 90.0, want: "90.0"},
		{name: "negative fractional", in: -12.5, want: "-12.5"},
		{name: "one tenth", in: 0.1, want: "0.1"},
		{name: "1e-4 stays fixed", in: 0.0001, want: "0.0001"},
		{name: "1e-5 flips to exponential", in: 1e-05, want: "1e-05"},
		{name: "1e-6 exponential", in: 1e-06, want: "1e-06"},
		{name: "1e15 stays fixed", in: 1e15, want: "1000000000000000.0"},
		{name: "1e16 flips to exponential", in: 1e16, want: "1e+16"},
		{name: "1e17 exponential", in: 1e17, want: "1e+17"},
		{name: "integral 7-digit bitrate", in: 1234567.0, want: "1234567.0"},
		{name: "probe bitrate", in: 3486.832605990455, want: "3486.832605990455"},
		{name: "predicted VMAF", in: 90.3551546220283, want: "90.3551546220283"},
		{name: "smoke curve top", in: 99.0, want: "99.0"},
		{name: "smoke curve floor", in: 52.0, want: "52.0"},
		{name: "1e6 must not become 1e+06", in: 1e6, want: "1000000.0"},
		{name: "large integral rounds to 17 sig digits", in: 123456789012345678.0, want: "1.2345678901234568e+17"},
		{name: "small exponential", in: 2.5e-10, want: "2.5e-10"},
		{name: "smallest subnormal", in: 5e-324, want: "5e-324"},
		{name: "max float64", in: 1.7976931348623157e308, want: "1.7976931348623157e+308"},
		{name: "float artefact keeps every digit", in: 0.30000000000000004, want: "0.30000000000000004"},
		{name: "plain fractional", in: 123.456, want: "123.456"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := pythonFloatRepr(tc.in); got != tc.want {
				t.Errorf("pythonFloatRepr(%v) = %q, want %q (CPython repr)", tc.in, got, tc.want)
			}
		})
	}
}

// TestPythonFloatReprRoundTrips checks the formatter never loses precision:
// every rendered value must parse back to the identical float64.
func TestPythonFloatReprRoundTrips(t *testing.T) {
	t.Parallel()

	values := []float64{
		0, 1, -1, 0.1, 90.3551546220283, 3486.832605990455, 1e-5, 1e15, 1e16,
		1e6, 5e-324, 1.7976931348623157e308, 0.30000000000000004, -12.5,
		math.Pi, math.SmallestNonzeroFloat64, math.MaxFloat64,
	}
	for _, v := range values {
		s := pythonFloatRepr(v)
		back, err := strconv.ParseFloat(s, 64)
		if err != nil {
			t.Errorf("pythonFloatRepr(%v) = %q which does not parse: %v", v, s, err)
			continue
		}
		if back != v {
			t.Errorf("round-trip lost precision: %v -> %q -> %v", v, s, back)
		}
	}
}

// TestJSONNumberNonFinite checks the null coercion for NaN / Inf. Python
// would emit the non-standard NaN / Infinity tokens here; the Go surface
// follows the house rule set by compare.go's sweep emitter and coerces to
// JSON null so the document stays parseable.
func TestJSONNumberNonFinite(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   float64
	}{
		{name: "NaN", in: math.NaN()},
		{name: "+Inf", in: math.Inf(1)},
		{name: "-Inf", in: math.Inf(-1)},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := string(jsonNumber(tc.in)); got != "null" {
				t.Errorf("jsonNumber(%v) = %q, want \"null\"", tc.in, got)
			}
			if got := pythonFloatRepr(tc.in); got != "" {
				t.Errorf("pythonFloatRepr(%v) = %q, want \"\"", tc.in, got)
			}
		})
	}

	if got := string(jsonNumberPtr(nil)); got != "null" {
		t.Errorf("jsonNumberPtr(nil) = %q, want \"null\"", got)
	}
	v := 1.5
	if got := string(jsonNumberPtr(&v)); got != "1.5" {
		t.Errorf("jsonNumberPtr(&1.5) = %q, want \"1.5\"", got)
	}
}

// TestRecommendResultMarshalMatchesPython pins the whole payload against the
// bytes Python emits.
//
// Reference (smoke payload for --target-vmaf 90):
//
//	python3 -c "
//	import json
//	print(json.dumps({'encoder':'libx264','n_trials':50,'notes':'x',
//	    'predicted_kbps':3486.832605990455,'predicted_vmaf':90.3551546220283,
//	    'proxy_verify_gap':None,'recommended_crf':20,'smoke':True,
//	    'target_vmaf':90.0,'verify_vmaf':None}, indent=2, sort_keys=True))"
func TestRecommendResultMarshalMatchesPython(t *testing.T) {
	t.Parallel()

	gap := 0.75
	verify := 89.5

	tests := []struct {
		name string
		in   RecommendResult
		want string
	}{
		{
			name: "smoke payload leaves verify fields null",
			in: RecommendResult{
				Encoder:        "libx264",
				NTrials:        50,
				Notes:          "x",
				PredictedKbps:  3486.832605990455,
				PredictedVMAF:  90.3551546220283,
				RecommendedCRF: 20,
				Smoke:          true,
				TargetVMAF:     90.0,
			},
			want: `{
  "encoder": "libx264",
  "n_trials": 50,
  "notes": "x",
  "predicted_kbps": 3486.832605990455,
  "predicted_vmaf": 90.3551546220283,
  "proxy_verify_gap": null,
  "recommended_crf": 20,
  "smoke": true,
  "target_vmaf": 90.0,
  "verify_vmaf": null
}`,
		},
		{
			name: "production payload carries score_backend and the gap",
			in: RecommendResult{
				Encoder:        "libx265",
				NTrials:        30,
				Notes:          "production",
				PredictedKbps:  1000000.0,
				PredictedVMAF:  90.25,
				ProxyVerifyGap: &gap,
				RecommendedCRF: 24,
				ScoreBackend:   "cuda",
				Smoke:          false,
				TargetVMAF:     90.0,
				VerifyVMAF:     &verify,
			},
			want: `{
  "encoder": "libx265",
  "n_trials": 30,
  "notes": "production",
  "predicted_kbps": 1000000.0,
  "predicted_vmaf": 90.25,
  "proxy_verify_gap": 0.75,
  "recommended_crf": 24,
  "score_backend": "cuda",
  "smoke": false,
  "target_vmaf": 90.0,
  "verify_vmaf": 89.5
}`,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, err := json.MarshalIndent(tc.in, "", "  ")
			if err != nil {
				t.Fatalf("MarshalIndent: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("payload mismatch:\n got:\n%s\nwant:\n%s", got, tc.want)
			}
		})
	}
}

// TestRecommendResultRoundTrip verifies a payload survives Marshal ->
// Unmarshal, so Go consumers can read documents either implementation wrote.
func TestRecommendResultRoundTrip(t *testing.T) {
	t.Parallel()

	gap := 1.25
	verify := 88.75
	original := RecommendResult{
		Encoder:        "libx264",
		NTrials:        30,
		Notes:          "production: TPE over 30 trials",
		PredictedKbps:  2952.122483622292,
		PredictedVMAF:  88.24093019754717,
		ProxyVerifyGap: &gap,
		RecommendedCRF: 22,
		ScoreBackend:   "sycl",
		Smoke:          false,
		TargetVMAF:     88.0,
		VerifyVMAF:     &verify,
	}

	raw, err := json.Marshal(original)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	var back RecommendResult
	if err := json.Unmarshal(raw, &back); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}

	if back.Encoder != original.Encoder ||
		back.NTrials != original.NTrials ||
		back.Notes != original.Notes ||
		back.PredictedKbps != original.PredictedKbps ||
		back.PredictedVMAF != original.PredictedVMAF ||
		back.RecommendedCRF != original.RecommendedCRF ||
		back.ScoreBackend != original.ScoreBackend ||
		back.Smoke != original.Smoke ||
		back.TargetVMAF != original.TargetVMAF {
		t.Errorf("round-trip changed scalar fields:\n got %+v\nwant %+v", back, original)
	}
	if back.ProxyVerifyGap == nil || *back.ProxyVerifyGap != gap {
		t.Errorf("round-trip lost proxy_verify_gap: %v", back.ProxyVerifyGap)
	}
	if back.VerifyVMAF == nil || *back.VerifyVMAF != verify {
		t.Errorf("round-trip lost verify_vmaf: %v", back.VerifyVMAF)
	}
}

// TestRecommendResultUnmarshalRejectsGarbage covers the parse-error path.
func TestRecommendResultUnmarshalRejectsGarbage(t *testing.T) {
	t.Parallel()

	var r RecommendResult
	if err := json.Unmarshal([]byte(`{"n_trials": "fifty"}`), &r); err == nil {
		t.Fatal("want an error for a type-mismatched payload, got nil")
	}
}
