/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

/** Contexts: options, feature and model registration, submit, flush, extractor introspection. */

#ifndef VMAFX_CONTEXT_H
#define VMAFX_CONTEXT_H

#include <stddef.h>
#include <stdint.h>
#include <vmafx/types.h>
#include <vmafx/error.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * One scoring session.
 * @since 0.1
 */
typedef struct VmafxContext VmafxContext;

typedef struct VmafxContextConfig VmafxContextConfig;
typedef struct VmafxExtractorInfo VmafxExtractorInfo;

/**
 * Context configuration. Initialise with VMAFX_CONTEXT_CONFIG_INIT.
 * @since 0.1
 */
struct VmafxContextConfig {
    /** Size of this struct as the caller compiled it; set by the _INIT macro. */
    uint32_t struct_size;
    /** Log verbosity. Values: VmafxLogLevel. */
    uint32_t log_level;
    /** Worker threads; 0 runs extractors on the calling thread. */
    uint32_t n_threads;
    /** Score every n-th frame; 0 and 1 score every frame. */
    uint32_t n_subsample;
    /** CPU instruction-set bits to disable. */
    uint64_t cpumask;
    /** GPU dispatch bits to disable. */
    uint64_t gpumask;
};

/** Initialiser that sets `struct_size`; every other field is zero. */
#define VMAFX_CONTEXT_CONFIG_INIT {.struct_size = sizeof(VmafxContextConfig)}

/**
 * One registered feature extractor.
 * @since 0.1
 */
struct VmafxExtractorInfo {
    /** Size of this struct as the caller compiled it; set by the _INIT macro. */
    uint32_t struct_size;
    /** Backend the extractor runs on. Values: VmafxBackend. */
    uint32_t backend;
    /** Extractor name (for example `psnr`, `adm_cuda`). */
    const char *name;
};

/** Initialiser that sets `struct_size`; every other field is zero. */
#define VMAFX_EXTRACTOR_INFO_INIT {.struct_size = sizeof(VmafxExtractorInfo)}

/**
 * Create a context. `config` may be NULL for the defaults; `*out` is NULL on failure.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_context_create(const VmafxContextConfig *config, VmafxContext **out,
                                              VmafxError **error);

/**
 * Destroy a context. On a nonzero status the context stays valid and may be destroyed again
 * (ADR-1336).
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_context_destroy(VmafxContext *context, VmafxError **error);

/**
 * Describe registered extractor `index`; VMAFX_E_NOTFOUND past the last one.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_context_extractor_info(const VmafxContext *context, uint32_t index,
                                                      VmafxExtractorInfo *out, VmafxError **error);

#ifdef __cplusplus
}
#endif

#endif /* VMAFX_CONTEXT_H */
