/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

/** Tiny-AI models. */

#ifndef VMAFX_DNN_H
#define VMAFX_DNN_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* No declarations yet: later RC4 work packages fill this header. */

#ifdef __cplusplus
}
#endif

#endif /* VMAFX_DNN_H */
