/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

/** Errors that name what failed. */

#ifndef VMAFX_ERROR_H
#define VMAFX_ERROR_H

#include <stddef.h>
#include <stdint.h>
#include <vmafx/types.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * What the subject of a VmafxError names.
 * @since 0.1
 */
typedef enum VmafxSubjectKind {
    /** No subject. */
    VMAFX_SUBJECT_NONE = 0,
    /** A parameter or a struct field (`desc.w`). */
    VMAFX_SUBJECT_PARAMETER = 1,
    /** The context. */
    VMAFX_SUBJECT_CONTEXT = 2,
    /** An option key. */
    VMAFX_SUBJECT_OPTION = 3,
    /** A feature name. */
    VMAFX_SUBJECT_FEATURE = 4,
    /** A feature extractor. */
    VMAFX_SUBJECT_EXTRACTOR = 5,
    /** A model name, version or model set. */
    VMAFX_SUBJECT_MODEL = 6,
    /** A frame or a frame index. */
    VMAFX_SUBJECT_FRAME = 7,
    /** A plane of a frame. */
    VMAFX_SUBJECT_PLANE = 8,
    /** A device. */
    VMAFX_SUBJECT_DEVICE = 9,
    /** A backend. */
    VMAFX_SUBJECT_BACKEND = 10,
    /** A file path. */
    VMAFX_SUBJECT_PATH = 11,
    /** A fence. */
    VMAFX_SUBJECT_FENCE = 12,
} VmafxSubjectKind;

/**
 * A failure: status, message, the named subject and the engine's errno.
 * @since 0.1
 */
typedef struct VmafxError VmafxError;

/**
 * Name of a status code (`VMAFX_E_INVALID`), or `VMAFX_UNKNOWN_STATUS`.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_status_name(VmafxStatus status);

/**
 * Status of an error; VMAFX_E_INVALID for NULL.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_error_status(const VmafxError *error);

/**
 * Message formatted at the failure site; empty string for NULL.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_error_message(const VmafxError *error);

/**
 * Name of the parameter, feature, extractor or backend that failed; empty string when none.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_error_subject(const VmafxError *error);

/**
 * Negative errno the engine reported, 0 when the failure did not come from the engine.
 * @since 0.1
 */
VMAFX_EXPORT int32_t vmafx_error_errno(const VmafxError *error);

/**
 * Release an error; NULL is a no-op.
 * @since 0.1
 */
VMAFX_EXPORT void vmafx_error_free(VmafxError *error);

/**
 * What the subject names (a VmafxSubjectKind); VMAFX_SUBJECT_NONE for NULL.
 * @since 0.1
 */
VMAFX_EXPORT uint32_t vmafx_error_subject_kind(const VmafxError *error);

/**
 * Name of the library function that failed; empty string for NULL.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_error_function(const VmafxError *error);

#ifdef __cplusplus
}
#endif

#endif /* VMAFX_ERROR_H */
