/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

/** Models and model sets. */

#ifndef VMAFX_MODEL_H
#define VMAFX_MODEL_H

#include <stddef.h>
#include <stdint.h>
#include <vmafx/types.h>
#include <vmafx/error.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * VmafxModelFlags: Model load flags (bit values equal enum VmafModelFlags). Bits of a u64 field.
 * @since 0.1
 */
/** Do not clip the score to the model's range. */
#define VMAFX_MODEL_DISABLE_CLIP (UINT64_C(1) << 0U)
/** Apply the model's score transform. */
#define VMAFX_MODEL_ENABLE_TRANSFORM (UINT64_C(1) << 1U)
/** Do not apply the model's score transform. */
#define VMAFX_MODEL_DISABLE_TRANSFORM (UINT64_C(1) << 2U)

/**
 * A loaded model. Refcounted; a context that uses it holds a reference (ADR-1755).
 * @since 0.1
 */
typedef struct VmafxModel VmafxModel;

/**
 * A bootstrap model set: a lead model and its member models. Refcounted.
 * @since 0.1
 */
typedef struct VmafxModelSet VmafxModelSet;

typedef struct VmafxModelConfig VmafxModelConfig;

/**
 * How to load a model. Initialise with VMAFX_MODEL_CONFIG_INIT.
 * @since 0.1
 */
struct VmafxModelConfig {
    /** Size of this struct as the caller compiled it; set by the _INIT macro. */
    uint32_t struct_size;
    /** Name of the model's scores (copied); NULL: `vmaf`. */
    const char *name;
    /** Load flags; 0 keeps the model file's defaults. Bits: VmafxModelFlags. */
    uint64_t flags;
    /** Level of the messages `log_callback` receives. Values: VmafxLogLevel. */
    uint32_t log_level;
    /**
     * Receives the messages raised while loading (a model belongs to no context) at or below
     * `log_level`, and a load failure reported without an error out-parameter; NULL: the process
     * log.
     */
    VmafxLogCallback log_callback;
    /** Passed to `log_callback`. */
    void *log_user;
};

/** Initialiser that sets `struct_size`; every other field is zero. */
#define VMAFX_MODEL_CONFIG_INIT {.struct_size = sizeof(VmafxModelConfig)}

/**
 * Load the built-in model `version` (see vmafx_model_builtin_next()). `config` may be NULL.
 * VMAFX_E_NOTFOUND names an unknown version.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_model_load(const VmafxModelConfig *config, const char *version,
                                          VmafxModel **out, VmafxError **error);

/**
 * Load a JSON model file (UTF-8 path). VMAFX_E_IO names a file that cannot be read, VMAFX_E_INVALID
 * one that is not a single model, VMAFX_E_NOTSUP a `.pkl` file.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_model_load_file(const VmafxModelConfig *config, const char *path,
                                               VmafxModel **out, VmafxError **error);

/**
 * Merge `options` (copied) into the options the model passes to `extractor`. Only while the caller
 * holds the only reference: a model a context uses is immutable (VMAFX_E_BUSY).
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_model_override_feature(VmafxModel *model, const char *extractor,
                                                      const VmafxOptions *options,
                                                      VmafxError **error);

/**
 * Take one more reference; returns `model` (NULL for NULL).
 * @since 0.1
 */
VMAFX_EXPORT VmafxModel *vmafx_model_ref(VmafxModel *model);

/**
 * Drop one reference; the last one releases the model. NULL is a no-op.
 * @since 0.1
 */
VMAFX_EXPORT void vmafx_model_unref(VmafxModel *model);

/**
 * Name the model's scores are recorded under; NULL for NULL.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_model_name(const VmafxModel *model);

/**
 * Number of features the model reads; 0 for NULL.
 * @since 0.1
 */
VMAFX_EXPORT uint32_t vmafx_model_feature_count(const VmafxModel *model);

/**
 * Name of feature `index`, or NULL past the last one.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_model_feature_name(const VmafxModel *model, uint32_t index);

/**
 * SHA-256 of the model bytes as loaded, 64 lowercase hex digits (equal to `sha256sum` of the file);
 * lives as long as the model. NULL for NULL.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_model_hash(const VmafxModel *model);

/**
 * The built-in model version after `previous`, the first one for NULL, NULL after the last or for
 * an unknown `previous`. Built-in model sets are listed too.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_model_builtin_next(const char *previous);

/**
 * Version of the default model (`vmaf_v1.0.16_3d0h`).
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_model_default_version(void);

/**
 * Load the built-in model set `version` (for example `vmaf_b_v0.6.3`). `config` may be NULL.
 * VMAFX_E_NOTFOUND names an unknown version, VMAFX_E_INVALID one that is not a set.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_model_set_load(const VmafxModelConfig *config, const char *version,
                                              VmafxModelSet **out, VmafxError **error);

/**
 * Load a JSON model set file (UTF-8 path); failures as vmafx_model_load_file().
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_model_set_load_file(const VmafxModelConfig *config, const char *path,
                                                   VmafxModelSet **out, VmafxError **error);

/**
 * vmafx_model_override_feature() for the lead model and every member; VMAFX_E_BUSY once the set is
 * shared.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_model_set_override_feature(VmafxModelSet *set, const char *extractor,
                                                          const VmafxOptions *options,
                                                          VmafxError **error);

/**
 * Take one more reference; returns `set` (NULL for NULL).
 * @since 0.1
 */
VMAFX_EXPORT VmafxModelSet *vmafx_model_set_ref(VmafxModelSet *set);

/**
 * Drop one reference; the last one releases the set and its models. NULL is a no-op.
 * @since 0.1
 */
VMAFX_EXPORT void vmafx_model_set_unref(VmafxModelSet *set);

/**
 * The set's lead model, borrowed: valid as long as the set; take a reference with vmafx_model_ref()
 * to keep it longer. NULL for NULL.
 * @since 0.1
 */
VMAFX_EXPORT VmafxModel *vmafx_model_set_lead(const VmafxModelSet *set);

/**
 * Number of member models, without the lead; 0 for NULL.
 * @since 0.1
 */
VMAFX_EXPORT uint32_t vmafx_model_set_size(const VmafxModelSet *set);

/**
 * SHA-256 of the set's bytes as loaded, as vmafx_model_hash(); NULL for NULL.
 * @since 0.1
 */
VMAFX_EXPORT const char *vmafx_model_set_hash(const VmafxModelSet *set);

/**
 * Load the model a specification string names, as the `model` option of the FFmpeg filter and the
 * GStreamer element spells it: `key=value` items separated by `:`, keys `version` (a built-in
 * model) or `path` (a model file), `name` (the name of its scores), `disable_clip` and
 * `enable_transform` (`true` when given without a value), and `<extractor>.<option>=<value>`
 * overrides, applied in order. A backslash escapes the next `:`, `=`, `.` or backslash; any other
 * backslash is kept (Windows paths). An empty `spec` is the library's default model
 * (vmafx_model_default_version()). `config.name` and `config.flags` are the defaults the string
 * overrides. VMAFX_E_INVALID names the item that is not understood (both `version` and `path`, a
 * key without a value, an override without an option), VMAFX_E_RANGE a string over 4096 bytes or
 * more than 64 items; a load failure is vmafx_model_load()'s or vmafx_model_load_file()'s. Added in
 * ABI 0.1.10.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_model_load_spec(const VmafxModelConfig *config, const char *spec,
                                               VmafxModel **out, VmafxError **error);

#ifdef __cplusplus
}
#endif

#endif /* VMAFX_MODEL_H */
