/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

/** Provenance records: how the scores of a context are made. */

#ifndef VMAFX_PROVENANCE_H
#define VMAFX_PROVENANCE_H

#include <stddef.h>
#include <stdint.h>
#include <vmafx/types.h>
#include <vmafx/error.h>
#include <vmafx/context.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct VmafxProvenance VmafxProvenance;

/**
 * How the scores of a context are made (#2142). Strings live as long as the context.
 * @since 0.1
 */
struct VmafxProvenance {
    /** Size of this struct as the caller compiled it; set by the _INIT macro. */
    uint32_t struct_size;
    /** ABI major version of the library that ran. */
    uint32_t abi_major;
    /** ABI minor version. */
    uint32_t abi_minor;
    /** ABI patch version. */
    uint32_t abi_patch;
    /** Backend imported into the context. Values: VmafxBackend. */
    uint32_t active_backend;
    /** Registered feature extractors; see vmafx_context_extractor_info(). */
    uint32_t n_extractors;
    /** Build version (git describe). */
    const char *version;
};

/** Initialiser that sets `struct_size`; every other field is zero. */
#define VMAFX_PROVENANCE_INIT {.struct_size = sizeof(VmafxProvenance)}

/**
 * Fill the provenance record of a context.
 * @since 0.1
 */
VMAFX_EXPORT VmafxStatus vmafx_context_provenance(const VmafxContext *context, VmafxProvenance *out,
                                                  VmafxError **error);

#ifdef __cplusplus
}
#endif

#endif /* VMAFX_PROVENANCE_H */
