/**
 *  Copyright 2026 Lusoris
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 *  speed_chroma feature extractor — HIP backend with real on-device
 *  GPU kernels (ADR-0567).
 *
 *  Algorithm split: identical to speed_chroma_cuda.c.  See that file
 *  and ADR-0567 for the full GPU/CPU split rationale.
 *
 *  GPU kernels (HIP Module API): means, covariance, indterm,
 *  backward-substitution, score.
 *  CPU: filter_and_downscale, 25×25 eigendecomp, QR factorize, Qt×B.
 *
 *  HIP adaptation vs CUDA twin:
 *  - Wavefront size varies: 64 on GCN/RDNA1, 32 on RDNA2+.  The solve
 *    kernel is launched with blockDim.x = device wavefront size (queried
 *    via hipDeviceProp_t.warpSize at init time, stored in state->solve_warp).
 *    Threads >= SP_ELEMENTS are idle (25 active out of 32 or 64).
 *    __builtin_amdgcn_wave_barrier() replaces __syncwarp().
 *  - Covariance kernel launched with 256 threads and 256*sizeof(double)
 *    shared memory for the tree reduction (not warp-size dependent).
 *  - hipMalloc/hipFree/hipMemcpyAsync for device memory.
 *  - hipMemAllocHost replaced by hipHostMalloc for pinned host memory.
 *  - hipModuleLoadData / hipModuleLaunchKernel for kernel dispatch.
 *  - HAVE_HIPCC guards: without hipcc the init returns -ENOSYS.
 */

#include <errno.h>
#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "feature_collector.h"
#include "feature_extractor.h"
#include "feature_name.h"
#include "log.h"
#include "mem.h"
#include "picture.h"
#include "picture_copy.h"

#include "feature/speed_internal.h"
#include "hip/speed_chroma_hip.h"

#ifdef HAVE_HIPCC
#define __HIP_PLATFORM_AMD__ 1
#include <hip/hip_runtime_api.h>

/* Embedded HSACO blob generated by meson / xxd from speed_score.hip. */
extern const unsigned char speed_score_hsaco[];
extern const unsigned int speed_score_hsaco_len;
#endif /* HAVE_HIPCC */

#define SC_BLOCK_SIZE (5u)
#define SC_ELEMENTS (25u)
#define SC_COV_BLOCK (256u)
#define SC_MEANS_BLOCK (256u)
#define SC_INDTERM_BLOCK (256u)
#define SC_SCORE_BLOCK (256u)
/* SC_SOLVE_WARP is no longer a compile-time constant; the actual wavefront
 * size is queried at init time from hipDeviceProp_t.warpSize and stored in
 * SpeedChromaHipState.solve_warp.  This default covers GCN/RDNA1. */
#define SC_SOLVE_WARP_DEFAULT (64u)

#define SC_DEFAULT_SIGMA_NN (0.29)
#define SC_DEFAULT_MAX_VAL (1000.0)
#define SC_DEFAULT_NN_FLOOR (0.0)
#define SC_DEFAULT_KERNELSCALE (1.0)
#define SC_DEFAULT_PRESCALE (1.0)
#define SC_DEFAULT_PRESCALE_METHOD ("nearest")

/* ------------------------------------------------------------------ */
/* Private extractor state                                             */
/* ------------------------------------------------------------------ */

typedef struct SpeedChromaHipState {
#ifdef HAVE_HIPCC
    hipModule_t module;
    hipFunction_t func_means;
    hipFunction_t func_cov;
    hipFunction_t func_indterm;
    hipFunction_t func_solve;
    hipFunction_t func_score;
    hipStream_t stream;
    unsigned solve_warp; /* actual device wavefront size (32 or 64) */
#endif

    SpeedInternalDimensions dim;
    SpeedInternalOptions opt;
    size_t float_stride;

#ifdef HAVE_HIPCC
    /* Device buffers. */
    void *d_plane;
    void *d_means;
    void *d_cov_mat;
    void *d_indterm_ref;
    void *d_indterm_dis;
    void *d_sol_ref;
    void *d_sol_dis;
    void *d_R;
    void *d_eigenvalues;     /* dis eigenvalues after the dis linalg pass */
    void *d_eigenvalues_ref; /* ref eigenvalues, stashed before the dis linalg
                              * overwrites the shared d_eigenvalues buffer */
    void *d_ref_ent;
    void *d_ref_var;
    void *d_dis_ent;
    void *d_dis_var;

    /* Pinned host buffers. */
    float *h_cov_mat;
    float *h_ref_ent;
    float *h_ref_var;
    float *h_dis_ent;
    float *h_dis_var;
#endif /* HAVE_HIPCC */

    /* CPU-only scratch buffers (allocated with aligned_malloc). */
    float *h_plane_ref;
    float *h_plane_dis;
    float *h_eigenvalues;
    float *h_eig_scratch;
    float *h_Q;
    float *h_R;
    float *h_qr_scratch;
    float *h_indterm_ref;
    float *h_indterm_dis;
    float *h_qt_scratch;

    /* User options. */
    double speed_chroma_kernelscale;
    double speed_chroma_prescale;
    char *speed_chroma_prescale_method;
    double speed_chroma_sigma_nn;
    double speed_chroma_nn_floor;
    double speed_chroma_max_val;
    int speed_weight_var_mode;

    VmafDictionary *feature_name_dict;
} SpeedChromaHipState;

static const VmafOption options_chroma[] = {
    {
        .name = "speed_kernelscale",
        .help = "scaling factor for the Gaussian kernel",
        .offset = offsetof(SpeedChromaHipState, speed_chroma_kernelscale),
        .type = VMAF_OPT_TYPE_DOUBLE,
        .default_val.d = SC_DEFAULT_KERNELSCALE,
        .min = 0.1,
        .max = 4.0,
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,
        .alias = "ks",
    },
    {
        .name = "speed_prescale",
        .help = "scaling factor for the frame",
        .offset = offsetof(SpeedChromaHipState, speed_chroma_prescale),
        .type = VMAF_OPT_TYPE_DOUBLE,
        .default_val.d = SC_DEFAULT_PRESCALE,
        .min = 0.1,
        .max = 4.0,
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,
        .alias = "ps",
    },
    {
        .name = "speed_prescale_method",
        .help = "scaling method [nearest, bilinear, bicubic, lanczos4]",
        .offset = offsetof(SpeedChromaHipState, speed_chroma_prescale_method),
        .type = VMAF_OPT_TYPE_STRING,
        .default_val.s = SC_DEFAULT_PRESCALE_METHOD,
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,
        .alias = "psm",
    },
    {
        .name = "speed_sigma_nn",
        .help = "standard deviation of neural noise",
        .offset = offsetof(SpeedChromaHipState, speed_chroma_sigma_nn),
        .type = VMAF_OPT_TYPE_DOUBLE,
        .default_val.d = SC_DEFAULT_SIGMA_NN,
        .min = 0.1,
        .max = 2.0,
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,
        .alias = "snn",
    },
    {
        .name = "speed_nn_floor",
        .help = "neural noise floor fraction",
        .offset = offsetof(SpeedChromaHipState, speed_chroma_nn_floor),
        .type = VMAF_OPT_TYPE_DOUBLE,
        .default_val.d = SC_DEFAULT_NN_FLOOR,
        .min = 0.0,
        .max = 1.0,
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,
        .alias = "nnf",
    },
    {
        .name = "speed_max_val",
        .help = "clip output to this maximum",
        .offset = offsetof(SpeedChromaHipState, speed_chroma_max_val),
        .type = VMAF_OPT_TYPE_DOUBLE,
        .default_val.d = SC_DEFAULT_MAX_VAL,
        .min = 0.0,
        .max = 1000.0,
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,
        .alias = "mxv",
    },
    {
        .name = "speed_weight_var_mode",
        .help = "variance weighting mode (0-6)",
        .offset = offsetof(SpeedChromaHipState, speed_weight_var_mode),
        .type = VMAF_OPT_TYPE_INT,
        .default_val.d = 0,
        .min = 0,
        .max = 6,
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,
        .alias = "wvm",
    },
    {0},
};

/* ------------------------------------------------------------------ */
/* HIP helpers (compiled only when hipcc is present)                  */
/* ------------------------------------------------------------------ */

#ifdef HAVE_HIPCC

static int hip_rc(hipError_t rc)
{
    if (rc == hipSuccess)
        return 0;
    switch (rc) {
    case hipErrorOutOfMemory:
        return -ENOMEM;
    case hipErrorInvalidValue:
        return -EINVAL;
    case hipErrorNoDevice:
        return -ENODEV;
    case hipErrorNotSupported:
        return -ENOSYS;
    default:
        return -EIO;
    }
}

static void free_hip_buffers(SpeedChromaHipState *s)
{
#define FD(p)                                                                                      \
    do {                                                                                           \
        if ((p)) {                                                                                 \
            (void)hipFree((p));                                                                    \
            (p) = NULL;                                                                            \
        }                                                                                          \
    } while (0)
#define FH(p)                                                                                      \
    do {                                                                                           \
        if ((p)) {                                                                                 \
            (void)hipHostFree((p));                                                                \
            (p) = NULL;                                                                            \
        }                                                                                          \
    } while (0)
    FD(s->d_plane);
    FD(s->d_means);
    FD(s->d_cov_mat);
    FD(s->d_indterm_ref);
    FD(s->d_indterm_dis);
    FD(s->d_sol_ref);
    FD(s->d_sol_dis);
    FD(s->d_R);
    FD(s->d_eigenvalues);
    FD(s->d_eigenvalues_ref);
    FD(s->d_ref_ent);
    FD(s->d_ref_var);
    FD(s->d_dis_ent);
    FD(s->d_dis_var);
    FH(s->h_cov_mat);
    FH(s->h_ref_ent);
    FH(s->h_ref_var);
    FH(s->h_dis_ent);
    FH(s->h_dis_var);
    if (s->module) {
        (void)hipModuleUnload(s->module);
        s->module = NULL;
    }
    if (s->stream) {
        (void)hipStreamDestroy(s->stream);
        s->stream = NULL;
    }
#undef FD
#undef FH
}

/* Load HSACO module and look up all 5 kernel entry points. */
static int sc_hip_module_load(SpeedChromaHipState *s)
{
    hipError_t rc = hipModuleLoadData(&s->module, speed_score_hsaco);
    if (rc != hipSuccess)
        return hip_rc(rc);

#define GET_FN(field, name)                                                                        \
    do {                                                                                           \
        rc = hipModuleGetFunction(&(s->field), s->module, (name));                                 \
        if (rc != hipSuccess) {                                                                    \
            (void)hipModuleUnload(s->module);                                                      \
            s->module = NULL;                                                                      \
            return hip_rc(rc);                                                                     \
        }                                                                                          \
    } while (0)

    GET_FN(func_means, "speed_means_hip_kernel");
    GET_FN(func_cov, "speed_cov_hip_kernel");
    GET_FN(func_indterm, "speed_indterm_hip_kernel");
    GET_FN(func_solve, "speed_solve_hip_kernel");
    GET_FN(func_score, "speed_score_hip_kernel");
#undef GET_FN
    return 0;
}

/* Allocate all device + pinned host buffers. */
static int sc_hip_bufs_alloc(SpeedChromaHipState *s)
{
    const size_t stride_px = s->float_stride / sizeof(float);
    const size_t nb = s->dim.num_blocks;
    const size_t plane_bytes = s->dim.alloc_height * stride_px * sizeof(float);
    const size_t indterm_bytes = SC_ELEMENTS * nb * sizeof(float);
    const size_t cov_bytes = SC_ELEMENTS * SC_ELEMENTS * sizeof(float);
    const size_t score_bytes = nb * sizeof(float);

#define AD(field, sz)                                                                              \
    do {                                                                                           \
        if (hipMalloc(&(s->field), (sz)) != hipSuccess)                                            \
            return -ENOMEM;                                                                        \
    } while (0)
#define AH(field, sz)                                                                              \
    do {                                                                                           \
        if (hipHostMalloc((void **)&(s->field), (sz), 0) != hipSuccess)                            \
            return -ENOMEM;                                                                        \
    } while (0)

    AD(d_plane, plane_bytes);
    AD(d_means, indterm_bytes);
    AD(d_cov_mat, cov_bytes);
    AD(d_indterm_ref, indterm_bytes);
    AD(d_indterm_dis, indterm_bytes);
    AD(d_sol_ref, indterm_bytes);
    AD(d_sol_dis, indterm_bytes);
    AD(d_R, cov_bytes);
    AD(d_eigenvalues, SC_ELEMENTS * sizeof(float));
    AD(d_eigenvalues_ref, SC_ELEMENTS * sizeof(float));
    AD(d_ref_ent, score_bytes);
    AD(d_ref_var, score_bytes);
    AD(d_dis_ent, score_bytes);
    AD(d_dis_var, score_bytes);
    AH(h_cov_mat, cov_bytes);
    AH(h_ref_ent, score_bytes);
    AH(h_ref_var, score_bytes);
    AH(h_dis_ent, score_bytes);
    AH(h_dis_var, score_bytes);
#undef AD
#undef AH
    return 0;
}

/* Run GPU kernels K1-K3 and download cov_mat + indterm. */
static int run_gpu_pipeline_sc(SpeedChromaHipState *s, const float *h_plane, void *d_indterm,
                               float *h_indterm)
{
    const uint32_t num_blocks = (uint32_t)s->dim.num_blocks;
    const uint32_t num_blocks_h = (uint32_t)s->dim.num_blocks_horizontal;
    const uint32_t op_w = (uint32_t)s->dim.truncated_width;
    const uint32_t stride_px = (uint32_t)(s->float_stride / sizeof(float));
    const uint32_t submatrix_w = (uint32_t)s->dim.submatrix_width;
    const uint32_t submatrix_h = (uint32_t)s->dim.submatrix_height;
    const size_t plane_bytes = s->dim.truncated_height * stride_px * sizeof(float);
    const size_t indterm_bytes = (size_t)SC_ELEMENTS * num_blocks * sizeof(float);

    hipError_t rc =
        hipMemcpyAsync(s->d_plane, h_plane, plane_bytes, hipMemcpyHostToDevice, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);

    /* K1: means */
    {
        const uint32_t grid_x = (num_blocks + SC_MEANS_BLOCK - 1u) / SC_MEANS_BLOCK;
        void *args[] = {&s->d_plane,   &s->d_means, &op_w,        &stride_px,
                        &num_blocks_h, &num_blocks, &submatrix_w, &submatrix_h};
        rc = hipModuleLaunchKernel(s->func_means, grid_x, 1u, 1u, SC_MEANS_BLOCK, 1u, 1u, 0u,
                                   s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }
    /* K2: covariance — SP_ELEMENTS×SP_ELEMENTS blocks, 256 threads, shared=256*sizeof(double) */
    {
        const size_t smem = SC_COV_BLOCK * sizeof(double);
        void *args[] = {&s->d_plane,   &s->d_means, &s->d_cov_mat, &stride_px,
                        &num_blocks_h, &num_blocks, &submatrix_w,  &submatrix_h};
        rc = hipModuleLaunchKernel(s->func_cov, SC_ELEMENTS, SC_ELEMENTS, 1u, SC_COV_BLOCK, 1u, 1u,
                                   (uint32_t)smem, s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }
    /* K3: indterm */
    {
        const uint32_t total = SC_ELEMENTS * num_blocks;
        const uint32_t grid_x = (total + SC_INDTERM_BLOCK - 1u) / SC_INDTERM_BLOCK;
        void *args[] = {&s->d_plane, &d_indterm, &stride_px, &num_blocks_h, &num_blocks};
        rc = hipModuleLaunchKernel(s->func_indterm, grid_x, 1u, 1u, SC_INDTERM_BLOCK, 1u, 1u, 0u,
                                   s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }

    /* D2H: cov_mat and indterm. */
    rc = hipMemcpyAsync(s->h_cov_mat, s->d_cov_mat, SC_ELEMENTS * SC_ELEMENTS * sizeof(float),
                        hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipMemcpyAsync(h_indterm, d_indterm, indterm_bytes, hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipStreamSynchronize(s->stream);
    return hip_rc(rc);
}

/* CPU linear algebra + upload R/solution + K4 solve. */
static int run_cpu_linalg_sc(SpeedChromaHipState *s, float *h_indterm, void *d_sol)
{
    const int sz = (int)SC_ELEMENTS;
    const int nb = (int)s->dim.num_blocks;
    const size_t indterm_bytes = (size_t)SC_ELEMENTS * (size_t)nb * sizeof(float);

    speed_internal_compute_eigenvalues(s->h_cov_mat, s->h_eigenvalues, sz, s->h_eig_scratch);
    bool regular = speed_internal_is_matrix_regular(s->h_eigenvalues, (size_t)sz);

    hipError_t rc = hipSuccess;
    if (!regular) {
        vmaf_log(VMAF_LOG_LEVEL_WARNING,
                 "speed_chroma_hip: covariance matrix singular, zeroing solution\n");
        (void)memset(h_indterm, 0, indterm_bytes);
    } else {
        (void)speed_internal_qr_factorize(s->h_cov_mat, sz, s->h_Q, s->h_R, s->h_qr_scratch);
        speed_internal_qt_multiply(s->h_Q, h_indterm, sz, nb, s->h_qt_scratch);

        /* H2D: R and Q^T×indterm (= initial rhs for solve kernel). */
        rc = hipMemcpyAsync(s->d_R, s->h_R, (size_t)sz * (size_t)sz * sizeof(float),
                            hipMemcpyHostToDevice, s->stream);
        if (rc != hipSuccess)
            return hip_rc(rc);
        rc = hipMemcpyAsync(d_sol, h_indterm, indterm_bytes, hipMemcpyHostToDevice, s->stream);
        if (rc != hipSuccess)
            return hip_rc(rc);

        /* K4: backward substitution — one wavefront per column.
         * blockDim.x = s->solve_warp (32 on RDNA2+, 64 on GCN/RDNA1). */
        const uint32_t u_nb = (uint32_t)nb;
        void *args[] = {&s->d_R, &d_sol, &u_nb};
        rc = hipModuleLaunchKernel(s->func_solve, u_nb, 1u, 1u, s->solve_warp, 1u, 1u, 0u,
                                   s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
        rc = hipStreamSynchronize(s->stream);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }

    /* H2D eigenvalues for the score kernel. Each pass uploads its own
     * eigenvalues into the shared d_eigenvalues buffer; the caller stashes the
     * ref eigenvalues into d_eigenvalues_ref between the ref and dis passes. */
    rc = hipMemcpyAsync(s->d_eigenvalues, s->h_eigenvalues, SC_ELEMENTS * sizeof(float),
                        hipMemcpyHostToDevice, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipStreamSynchronize(s->stream);
    return hip_rc(rc);
}

/* K5 score + D2H + CPU aggregate. */
static int run_score_sc(SpeedChromaHipState *s, float *score_out)
{
    const uint32_t num_blocks = (uint32_t)s->dim.num_blocks;
    const float sigma_nn = (float)s->opt.speed_sigma_nn;
    hipError_t rc = hipSuccess;

    /* K5: entropy + score. The kernel reads d_eigenvalues_ref for the ref
     * entropy and d_eigenvalues (the dis eigenvalues uploaded by the dis
     * run_cpu_linalg_sc pass) for the dis entropy. */
    {
        const uint32_t grid = (num_blocks + SC_SCORE_BLOCK - 1u) / SC_SCORE_BLOCK;
        void *args[] = {&s->d_eigenvalues_ref, &s->d_eigenvalues, &s->d_sol_ref, &s->d_sol_dis,
                        &s->d_indterm_ref,     &s->d_indterm_dis, &s->d_ref_ent, &s->d_ref_var,
                        &s->d_dis_ent,         &s->d_dis_var,     &num_blocks,   &sigma_nn};
        rc = hipModuleLaunchKernel(s->func_score, grid, 1u, 1u, SC_SCORE_BLOCK, 1u, 1u, 0u,
                                   s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }

    const size_t ab = (size_t)num_blocks * sizeof(float);
    rc = hipMemcpyAsync(s->h_ref_ent, s->d_ref_ent, ab, hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipMemcpyAsync(s->h_ref_var, s->d_ref_var, ab, hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipMemcpyAsync(s->h_dis_ent, s->d_dis_ent, ab, hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipMemcpyAsync(s->h_dis_var, s->d_dis_var, ab, hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipStreamSynchronize(s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);

    const float base_entropy =
        (float)SC_ELEMENTS *
        (log2f((1.0f + (float)s->opt.speed_nn_floor) * (float)s->opt.speed_sigma_nn) +
         log2f(2.0f * 3.14159265358979323846f * 2.71828182845904523536f));

    float total = 0.0f;
    for (uint32_t i = 0; i < num_blocks; ++i) {
        const float re = s->h_ref_ent[i];
        const float de = s->h_dis_ent[i];
        if (re < base_entropy && de < base_entropy)
            continue;
        const float rv = s->h_ref_var[i];
        const float dv = s->h_dis_var[i];
        const int wvm = s->opt.speed_weight_var_mode;
        float sr = 0.0f;
        float sd = 0.0f;
        if (wvm == 0) {
            sr = re * log2f(1.0f + rv);
            sd = de * log2f(1.0f + dv);
        } else if (wvm == 1) {
            sr = re * log2f(1.0f + rv);
            sd = de * log2f(1.0f + rv);
        } else if (wvm == 2) {
            sr = re * log2f(1.0f + dv);
            sd = de * log2f(1.0f + dv);
        } else if (wvm == 3) {
            const float mv = (rv + dv) * 0.5f;
            sr = re * log2f(1.0f + mv);
            sd = de * log2f(1.0f + mv);
        } else if (wvm == 4) {
            sr = re * log2f(1.0f + rv);
            sd = de * log2f(1.0f + (rv + dv) * 0.5f);
        } else if (wvm == 5) {
            sr = re * log2f(1.0f + rv);
            sd = de * log2f(1.0f + 0.75f * rv + 0.25f * dv);
        } else if (wvm == 6) {
            sr = re * log2f(1.0f + rv);
            sd = de * log2f(1.0f + 0.25f * rv + 0.75f * dv);
        }
        total += fabsf(sr - sd);
    }
    *score_out = total / (float)num_blocks;
    return 0;
}

#endif /* HAVE_HIPCC */

/* ------------------------------------------------------------------ */
/* Lifecycle                                                           */
/* ------------------------------------------------------------------ */

static int init_chroma_hip(VmafFeatureExtractor *fex, enum VmafPixelFormat pix_fmt, unsigned bpc,
                           unsigned w, unsigned h)
{
    (void)bpc;
    SpeedChromaHipState *s = fex->priv;

    unsigned cw = w;
    unsigned ch = h;
    switch (pix_fmt) {
    case VMAF_PIX_FMT_UNKNOWN:
    case VMAF_PIX_FMT_YUV400P:
        return -EINVAL;
    case VMAF_PIX_FMT_YUV420P:
        cw /= 2u;
        ch /= 2u;
        break;
    case VMAF_PIX_FMT_YUV422P:
        cw /= 2u;
        break;
    case VMAF_PIX_FMT_YUV444P:
        break;
    }

    s->opt = (SpeedInternalOptions){
        .speed_kernelscale = s->speed_chroma_kernelscale,
        .speed_prescale = s->speed_chroma_prescale,
        .speed_prescale_method = s->speed_chroma_prescale_method,
        .speed_sigma_nn = s->speed_chroma_sigma_nn,
        .speed_nn_floor = s->speed_chroma_nn_floor,
        .speed_weight_var_mode = s->speed_weight_var_mode,
    };

    int err = speed_internal_init_dimensions(&s->dim, (int)cw, (int)ch, s->opt.speed_prescale);
    if (err)
        return err;
    s->float_stride = speed_internal_float_stride(s->dim.alloc_width);

    const size_t stride_px = s->float_stride / sizeof(float);
    const size_t nb = s->dim.num_blocks;
    const size_t plane_bytes = s->dim.alloc_height * stride_px * sizeof(float);
    const size_t indterm_bytes = SC_ELEMENTS * nb * sizeof(float);
    const size_t cov_bytes = SC_ELEMENTS * SC_ELEMENTS * sizeof(float);

    /* CPU scratch buffers (always allocated regardless of HAVE_HIPCC). */
#define ALLOC_A(field, sz) s->field = (float *)aligned_malloc((sz), 32)
    ALLOC_A(h_plane_ref, plane_bytes);
    ALLOC_A(h_plane_dis, plane_bytes);
    ALLOC_A(h_eigenvalues, SC_ELEMENTS * sizeof(float));
    ALLOC_A(h_eig_scratch, (SC_ELEMENTS * SC_ELEMENTS + 4u * SC_ELEMENTS) * sizeof(float));
    ALLOC_A(h_Q, cov_bytes);
    ALLOC_A(h_R, cov_bytes);
    ALLOC_A(h_qr_scratch, 4u * cov_bytes);
    ALLOC_A(h_indterm_ref, indterm_bytes);
    ALLOC_A(h_indterm_dis, indterm_bytes);
    ALLOC_A(h_qt_scratch, indterm_bytes);
#undef ALLOC_A

    if (!s->h_plane_ref || !s->h_plane_dis || !s->h_eigenvalues || !s->h_Q || !s->h_R) {
        err = -ENOMEM;
        goto free_cpu;
    }

#ifdef HAVE_HIPCC
    err = sc_hip_module_load(s);
    if (err)
        goto free_cpu;

    err = hipStreamCreate(&s->stream);
    if (err != hipSuccess) {
        err = -EIO;
        goto free_module;
    }

    /* Query actual wavefront size — 64 on GCN/RDNA1, 32 on RDNA2+.
     * Used as blockDim.x for speed_solve_hip_kernel. */
    {
        int dev = 0;
        hipDeviceProp_t prop;
        (void)hipGetDevice(&dev);
        s->solve_warp = (hipGetDeviceProperties(&prop, dev) == hipSuccess) ?
                            (unsigned)prop.warpSize :
                            SC_SOLVE_WARP_DEFAULT;
    }

    err = sc_hip_bufs_alloc(s);
    if (err)
        goto free_hip;
#else
    /* Without hipcc this extractor reports ENOSYS. */
    return -ENOSYS;
#endif /* HAVE_HIPCC */

    s->feature_name_dict =
        vmaf_feature_name_dict_from_provided_features(fex->provided_features, fex->options, s);
    if (!s->feature_name_dict) {
        err = -ENOMEM;
#ifdef HAVE_HIPCC
        goto free_hip;
#endif
    }

    return 0;

#ifdef HAVE_HIPCC
free_hip:
    free_hip_buffers(s);
    goto free_cpu;
free_module:
    if (s->module) {
        (void)hipModuleUnload(s->module);
        s->module = NULL;
    }
#endif /* HAVE_HIPCC */
free_cpu:
    aligned_free(s->h_plane_ref);
    aligned_free(s->h_plane_dis);
    aligned_free(s->h_eigenvalues);
    aligned_free(s->h_eig_scratch);
    aligned_free(s->h_Q);
    aligned_free(s->h_R);
    aligned_free(s->h_qr_scratch);
    aligned_free(s->h_indterm_ref);
    aligned_free(s->h_indterm_dis);
    aligned_free(s->h_qt_scratch);
    return err;
}

static int extract_chroma_hip(VmafFeatureExtractor *fex, VmafPicture *ref_pic,
                              VmafPicture *ref_pic_90, VmafPicture *dist_pic,
                              VmafPicture *dist_pic_90, unsigned index,
                              VmafFeatureCollector *feature_collector)
{
    (void)ref_pic_90;
    (void)dist_pic_90;

#ifndef HAVE_HIPCC
    (void)fex;
    (void)ref_pic;
    (void)dist_pic;
    (void)index;
    (void)feature_collector;
    return -ENOSYS;
#else
    SpeedChromaHipState *s = fex->priv;

    const size_t stride_px = s->float_stride / sizeof(float);
    const size_t tmp_size = 2u * s->dim.alloc_height * stride_px;
    float *tmp_filter = (float *)aligned_malloc(tmp_size * sizeof(float), 32);
    if (!tmp_filter)
        return -ENOMEM;

    float score_u = 0.0f;
    float score_v = 0.0f;
    int err_u = 0;
    int err_v = 0;

    for (int ch = 1; ch <= 2; ++ch) {
        /* Reuse h_plane_ref/dis for ref/dis of each chroma channel. */
        picture_copy(s->h_plane_ref, s->float_stride, ref_pic, -128, ref_pic->bpc, ch);
        speed_internal_filter_and_downscale(&s->dim, &s->opt, s->h_plane_ref, tmp_filter,
                                            s->float_stride);
        picture_copy(s->h_plane_dis, s->float_stride, dist_pic, -128, dist_pic->bpc, ch);
        speed_internal_filter_and_downscale(&s->dim, &s->opt, s->h_plane_dis, tmp_filter,
                                            s->float_stride);

        /* Reference: means → cov → indterm, then eigendecomp + QR. Uploads ref
         * eigenvalues into the shared d_eigenvalues buffer. */
        int e = run_gpu_pipeline_sc(s, s->h_plane_ref, s->d_indterm_ref, s->h_indterm_ref);
        if (e) {
            (ch == 1) ? (err_u = e) : (err_v = e);
            continue;
        }
        e = run_cpu_linalg_sc(s, s->h_indterm_ref, s->d_sol_ref);
        if (e) {
            (ch == 1) ? (err_u = e) : (err_v = e);
            continue;
        }

        /* Stash the reference eigenvalues aside before the distorted linalg
         * pass overwrites d_eigenvalues. The CPU reference (est_params in
         * speed.c) computes SEPARATE ref and dis covariance + eigenvalues; the
         * score kernel needs both. run_cpu_linalg_sc synchronizes the stream
         * after its eigenvalue H2D, so this DtoD copy is correctly ordered. */
        hipError_t drc =
            hipMemcpyDtoD(s->d_eigenvalues_ref, s->d_eigenvalues, SC_ELEMENTS * sizeof(float));
        if (drc != hipSuccess) {
            (ch == 1) ? (err_u = hip_rc(drc)) : (err_v = hip_rc(drc));
            continue;
        }

        /* Distorted: means → cov → indterm (keeps the DIS covariance in
         * h_cov_mat — no save/restore of the ref covariance), then eigendecomp
         * + QR. Uploads dis eigenvalues into d_eigenvalues. */
        e = run_gpu_pipeline_sc(s, s->h_plane_dis, s->d_indterm_dis, s->h_indterm_dis);
        if (!e)
            e = run_cpu_linalg_sc(s, s->h_indterm_dis, s->d_sol_dis);

        float sc = 0.0f;
        if (!e)
            e = run_score_sc(s, &sc);

        if (ch == 1) {
            err_u = e;
            score_u = sc;
        } else {
            err_v = e;
            score_v = sc;
        }
    }

    aligned_free(tmp_filter);

    float score_uv;
    if (err_u && !err_v)
        score_uv = score_v;
    else if (err_v && !err_u)
        score_uv = score_u;
    else
        score_uv = (score_u + score_v) * 0.5f;

    const double mxv = s->speed_chroma_max_val;
    int err = 0;
    err |= vmaf_feature_collector_append_with_dict(
        feature_collector, s->feature_name_dict, "Speed_chroma_feature_speed_chroma_u_score",
        (double)score_u < mxv ? (double)score_u : mxv, index);
    err |= vmaf_feature_collector_append_with_dict(
        feature_collector, s->feature_name_dict, "Speed_chroma_feature_speed_chroma_v_score",
        (double)score_v < mxv ? (double)score_v : mxv, index);
    err |= vmaf_feature_collector_append_with_dict(
        feature_collector, s->feature_name_dict, "Speed_chroma_feature_speed_chroma_uv_score",
        (double)score_uv < mxv ? (double)score_uv : mxv, index);
    return err;
#endif /* HAVE_HIPCC */
}

static int close_chroma_hip(VmafFeatureExtractor *fex)
{
    SpeedChromaHipState *s = fex->priv;
#ifdef HAVE_HIPCC
    free_hip_buffers(s);
#endif
    aligned_free(s->h_plane_ref);
    aligned_free(s->h_plane_dis);
    aligned_free(s->h_eigenvalues);
    aligned_free(s->h_eig_scratch);
    aligned_free(s->h_Q);
    aligned_free(s->h_R);
    aligned_free(s->h_qr_scratch);
    aligned_free(s->h_indterm_ref);
    aligned_free(s->h_indterm_dis);
    aligned_free(s->h_qt_scratch);
    if (s->feature_name_dict)
        vmaf_dictionary_free(&s->feature_name_dict);
    return 0;
}

static const char *provided_features_chroma[] = {
    "Speed_chroma_feature_speed_chroma_u_score",
    "Speed_chroma_feature_speed_chroma_v_score",
    "Speed_chroma_feature_speed_chroma_uv_score",
    NULL,
};

/* ADR-0567: real HIP GPU kernels for speed_chroma. */
VmafFeatureExtractor vmaf_fex_speed_chroma_hip = {
    .name = "speed_chroma_hip",
    .init = init_chroma_hip,
    .extract = extract_chroma_hip,
    .close = close_chroma_hip,
    .options = options_chroma,
    .priv_size = sizeof(SpeedChromaHipState),
    .provided_features = provided_features_chroma,
    .flags = VMAF_FEATURE_EXTRACTOR_HIP,
};
