/**
 *  Copyright 2016-2025 Netflix, Inc.
 *  Copyright 2026 Lusoris
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 *  speed_chroma feature extractor — HIP backend with real on-device
 *  GPU kernels (ADR-0567).
 *
 *  Algorithm split: identical to speed_chroma_cuda.c.  See that file
 *  and ADR-0567 for the full GPU/CPU split rationale.
 *
 *  GPU kernels (HIP Module API): means, covariance, indterm,
 *  backward-substitution, score.
 *  CPU: filter_and_downscale, 25×25 eigendecomp, QR factorize, Qt×B.
 *
 *  HIP adaptation vs CUDA twin:
 *  - Wavefront size varies: 64 on GCN/RDNA1, 32 on RDNA2+.  The solve
 *    kernel is launched with blockDim.x = device wavefront size (queried
 *    via hipDeviceProp_t.warpSize at init time, stored in state->solve_warp).
 *    Threads >= SP_ELEMENTS are idle (25 active out of 32 or 64).
 *    __builtin_amdgcn_wave_barrier() replaces __syncwarp().
 *  - Covariance kernel launched with 256 threads and 256*sizeof(double)
 *    shared memory for the tree reduction (not warp-size dependent).
 *  - hipMalloc/hipFree/hipMemcpyAsync for device memory.
 *  - hipMemAllocHost replaced by hipHostMalloc for pinned host memory.
 *  - hipModuleLoadData / hipModuleLaunchKernel for kernel dispatch.
 *  - HAVE_HIPCC guards: without hipcc the init returns -ENOSYS.
 */

#include <errno.h>
#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "feature_collector.h"
#include "feature_extractor.h"
#include "feature_name.h"
#include "log.h"
#include "mem.h"
#include "picture.h"
#include "picture_copy.h"

#include "feature/speed_internal.h"
#include "hip/speed_chroma_hip.h"

#ifdef HAVE_HIPCC
#include <hip/hip_runtime_api.h>

/* NOLINTBEGIN(modernize-use-nullptr): C translation unit. The fork builds C as
 * C23, where clang-tidy also proposes the `nullptr` keyword, but this is a C
 * translation unit whose sources spell the null pointer constant `NULL` and
 * MSVC's documented /std:clatest C23 feature set does not include `nullptr`
 * while the required Windows build compiles this TU with cl.exe. ADR-1138. */

/* Embedded HSACO blob generated by meson / xxd from speed_score.hip. */
extern const unsigned char speed_score_hsaco[];
extern const unsigned int speed_score_hsaco_len;
#endif /* HAVE_HIPCC */

#define SC_BLOCK_SIZE (5u)
#define SC_ELEMENTS (25u)
#define SC_COV_BLOCK (256u)
#define SC_MEANS_BLOCK (256u)
#define SC_INDTERM_BLOCK (256u)
#define SC_SCORE_BLOCK (256u)
/* SC_SOLVE_WARP is no longer a compile-time constant; the actual wavefront
 * size is queried at init time from hipDeviceProp_t.warpSize and stored in
 * SpeedChromaHipState.solve_warp.  This default covers GCN/RDNA1. */
#define SC_SOLVE_WARP_DEFAULT (64u)

#define SC_DEFAULT_SIGMA_NN (0.29)
#define SC_DEFAULT_MAX_VAL (1000.0)
#define SC_DEFAULT_NN_FLOOR (0.0)
#define SC_DEFAULT_KERNELSCALE (1.0)
#define SC_DEFAULT_PRESCALE (1.0)
#define SC_DEFAULT_PRESCALE_METHOD ("nearest")

/* ------------------------------------------------------------------ */
/* Private extractor state                                             */
/* ------------------------------------------------------------------ */

typedef struct SpeedChromaHipState {
#ifdef HAVE_HIPCC
    hipModule_t module;
    hipFunction_t func_means;
    hipFunction_t func_cov;
    hipFunction_t func_indterm;
    hipFunction_t func_solve;
    hipFunction_t func_score;
    hipStream_t stream;
    unsigned solve_warp; /* actual device wavefront size (32 or 64) */
#endif

    SpeedInternalDimensions dim;
    SpeedInternalOptions opt;
    size_t float_stride;

#ifdef HAVE_HIPCC
    /* Device buffers. */
    void *d_plane;
    void *d_means;
    void *d_cov_mat;
    void *d_indterm_ref;
    void *d_indterm_dis;
    void *d_sol_ref;
    void *d_sol_dis;
    void *d_R;
    void *d_eigenvalues;     /* dis eigenvalues after the dis linalg pass */
    void *d_eigenvalues_ref; /* ref eigenvalues, stashed before the dis linalg
                              * overwrites the shared d_eigenvalues buffer */
    void *d_ref_ent;
    void *d_ref_var;
    void *d_dis_ent;
    void *d_dis_var;

    /* Pinned host buffers. */
    float *h_cov_mat;
    float *h_ref_ent;
    float *h_ref_var;
    float *h_dis_ent;
    float *h_dis_var;
#endif /* HAVE_HIPCC */

    /* CPU-only scratch buffers (allocated with aligned_malloc). */
    float *h_plane_ref;
    float *h_plane_dis;
    float *h_eigenvalues;
    float *h_eig_scratch;
    float *h_Q;
    float *h_R;
    float *h_qr_scratch;
    float *h_indterm_ref;
    float *h_indterm_dis;
    float *h_qt_scratch;

    /* User options. */
    double speed_chroma_kernelscale;
    double speed_chroma_prescale;
    char *speed_chroma_prescale_method;
    double speed_chroma_sigma_nn;
    double speed_chroma_nn_floor;
    double speed_chroma_max_val;
    int speed_weight_var_mode;

    VmafDictionary *feature_name_dict;
    /* Singular covariance matrices are counted, not logged per solve. */
    SpeedInternalSingularTally singular_tally;
} SpeedChromaHipState;

#define SPEED_CHROMA_DOUBLE_OPTION(name_, alias_, help_, member_, default_, min_, max_)            \
    {                                                                                              \
        .name = name_,                                                                             \
        .help = help_,                                                                             \
        .alias = alias_,                                                                           \
        .offset = offsetof(SpeedChromaHipState, member_),                                          \
        .type = VMAF_OPT_TYPE_DOUBLE,                                                              \
        .default_val.d = default_,                                                                 \
        .min = min_,                                                                               \
        .max = max_,                                                                               \
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,                                                      \
    }
#define SPEED_CHROMA_STRING_OPTION(name_, alias_, help_, member_, default_)                        \
    {                                                                                              \
        .name = name_,                                                                             \
        .help = help_,                                                                             \
        .alias = alias_,                                                                           \
        .offset = offsetof(SpeedChromaHipState, member_),                                          \
        .type = VMAF_OPT_TYPE_STRING,                                                              \
        .default_val.s = default_,                                                                 \
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,                                                      \
    }
#define SPEED_CHROMA_INT_OPTION(name_, alias_, help_, member_, default_, min_, max_)               \
    {                                                                                              \
        .name = name_,                                                                             \
        .help = help_,                                                                             \
        .alias = alias_,                                                                           \
        .offset = offsetof(SpeedChromaHipState, member_),                                          \
        .type = VMAF_OPT_TYPE_INT,                                                                 \
        .default_val.i = default_,                                                                 \
        .min = min_,                                                                               \
        .max = max_,                                                                               \
        .flags = VMAF_OPT_FLAG_FEATURE_PARAM,                                                      \
    }

static const VmafOption options_chroma[] = {
    SPEED_CHROMA_DOUBLE_OPTION("speed_kernelscale", "ks", "scaling factor for the Gaussian kernel",
                               speed_chroma_kernelscale, SC_DEFAULT_KERNELSCALE, 0.1, 4.0),
    SPEED_CHROMA_DOUBLE_OPTION("speed_prescale", "ps", "scaling factor for the frame",
                               speed_chroma_prescale, SC_DEFAULT_PRESCALE, 0.1, 4.0),
    SPEED_CHROMA_STRING_OPTION("speed_prescale_method", "psm",
                               "scaling method [nearest, bilinear, bicubic, lanczos4]",
                               speed_chroma_prescale_method, SC_DEFAULT_PRESCALE_METHOD),
    SPEED_CHROMA_DOUBLE_OPTION("speed_sigma_nn", "snn", "standard deviation of neural noise",
                               speed_chroma_sigma_nn, SC_DEFAULT_SIGMA_NN, 0.1, 2.0),
    SPEED_CHROMA_DOUBLE_OPTION("speed_nn_floor", "nnf", "neural noise floor fraction",
                               speed_chroma_nn_floor, SC_DEFAULT_NN_FLOOR, 0.0, 1.0),
    SPEED_CHROMA_DOUBLE_OPTION("speed_max_val", "mxv", "clip output to this maximum",
                               speed_chroma_max_val, SC_DEFAULT_MAX_VAL, 0.0, 1000.0),
    SPEED_CHROMA_INT_OPTION("speed_weight_var_mode", "wvm", "variance weighting mode (0-6)",
                            speed_weight_var_mode, 0, 0, 6),
    {0}};

/* ------------------------------------------------------------------ */
/* HIP helpers (compiled only when hipcc is present)                  */
/* ------------------------------------------------------------------ */

#ifdef HAVE_HIPCC

static int hip_rc(hipError_t rc)
{
    if (rc == hipSuccess)
        return 0;
    switch (rc) {
    case hipErrorOutOfMemory:
        return -ENOMEM;
    case hipErrorInvalidValue:
        return -EINVAL;
    case hipErrorNoDevice:
        return -ENODEV;
    case hipErrorNotSupported:
        return -ENOSYS;
    default:
        return -EIO;
    }
}

static void record_sc_hip_error(int *first_err, hipError_t rc, const char *operation)
{
    if (rc == hipSuccess)
        return;
    vmaf_log(VMAF_LOG_LEVEL_ERROR, "speed_chroma_hip %s failed with HIP error %d\n", operation,
             (int)rc);
    if (!*first_err)
        *first_err = hip_rc(rc);
}

static void release_sc_device_pointer(void **ptr, int *first_err, const char *name)
{
    if (!*ptr)
        return;
    record_sc_hip_error(first_err, hipFree(*ptr), name);
    *ptr = NULL;
}

static void release_sc_host_pointer(float **ptr, int *first_err, const char *name)
{
    if (!*ptr)
        return;
    record_sc_hip_error(first_err, hipHostFree(*ptr), name);
    *ptr = NULL;
}

static int free_hip_buffers(SpeedChromaHipState *s, bool synchronize)
{
    int first_err = 0;
    if (synchronize && s->stream)
        record_sc_hip_error(&first_err, hipStreamSynchronize(s->stream), "stream synchronize");
    release_sc_device_pointer(&s->d_plane, &first_err, "plane free");
    release_sc_device_pointer(&s->d_means, &first_err, "means free");
    release_sc_device_pointer(&s->d_cov_mat, &first_err, "covariance free");
    release_sc_device_pointer(&s->d_indterm_ref, &first_err, "reference indterm free");
    release_sc_device_pointer(&s->d_indterm_dis, &first_err, "distorted indterm free");
    release_sc_device_pointer(&s->d_sol_ref, &first_err, "reference solution free");
    release_sc_device_pointer(&s->d_sol_dis, &first_err, "distorted solution free");
    release_sc_device_pointer(&s->d_R, &first_err, "R matrix free");
    release_sc_device_pointer(&s->d_eigenvalues, &first_err, "eigenvalues free");
    release_sc_device_pointer(&s->d_eigenvalues_ref, &first_err, "reference eigenvalues free");
    release_sc_device_pointer(&s->d_ref_ent, &first_err, "reference entropy free");
    release_sc_device_pointer(&s->d_ref_var, &first_err, "reference variance free");
    release_sc_device_pointer(&s->d_dis_ent, &first_err, "distorted entropy free");
    release_sc_device_pointer(&s->d_dis_var, &first_err, "distorted variance free");
    release_sc_host_pointer(&s->h_cov_mat, &first_err, "host covariance free");
    release_sc_host_pointer(&s->h_ref_ent, &first_err, "host reference entropy free");
    release_sc_host_pointer(&s->h_ref_var, &first_err, "host reference variance free");
    release_sc_host_pointer(&s->h_dis_ent, &first_err, "host distorted entropy free");
    release_sc_host_pointer(&s->h_dis_var, &first_err, "host distorted variance free");
    if (s->module) {
        record_sc_hip_error(&first_err, hipModuleUnload(s->module), "module unload");
        s->module = NULL;
    }
    if (s->stream) {
        record_sc_hip_error(&first_err, hipStreamDestroy(s->stream), "stream destroy");
        s->stream = NULL;
    }
    return first_err;
}

/* Load HSACO module and look up all 5 kernel entry points. */
static int sc_hip_module_load(SpeedChromaHipState *s)
{
    int err = hip_rc(hipModuleLoadData(&s->module, speed_score_hsaco));
    if (!err)
        err = hip_rc(hipModuleGetFunction(&s->func_means, s->module, "speed_means_hip_kernel"));
    if (!err)
        err = hip_rc(hipModuleGetFunction(&s->func_cov, s->module, "speed_cov_hip_kernel"));
    if (!err)
        err = hip_rc(hipModuleGetFunction(&s->func_indterm, s->module, "speed_indterm_hip_kernel"));
    if (!err)
        err = hip_rc(hipModuleGetFunction(&s->func_solve, s->module, "speed_solve_hip_kernel"));
    if (!err)
        err = hip_rc(hipModuleGetFunction(&s->func_score, s->module, "speed_score_hip_kernel"));
    return err;
}

/* Allocate all device + pinned host buffers. */
static int sc_hip_bufs_alloc(SpeedChromaHipState *s)
{
    const size_t stride_px = s->float_stride / sizeof(float);
    const size_t nb = s->dim.num_blocks;
    const size_t plane_bytes = s->dim.alloc_height * stride_px * sizeof(float);
    const size_t indterm_bytes = SC_ELEMENTS * nb * sizeof(float);
    const size_t cov_bytes = SC_ELEMENTS * SC_ELEMENTS * sizeof(float);
    const size_t score_bytes = nb * sizeof(float);

    int err = hip_rc(hipMalloc(&s->d_plane, plane_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_means, indterm_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_cov_mat, cov_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_indterm_ref, indterm_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_indterm_dis, indterm_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_sol_ref, indterm_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_sol_dis, indterm_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_R, cov_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_eigenvalues, SC_ELEMENTS * sizeof(float)));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_eigenvalues_ref, SC_ELEMENTS * sizeof(float)));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_ref_ent, score_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_ref_var, score_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_dis_ent, score_bytes));
    if (!err)
        err = hip_rc(hipMalloc(&s->d_dis_var, score_bytes));
    if (!err)
        err = hip_rc(hipHostMalloc((void **)&s->h_cov_mat, cov_bytes, 0));
    if (!err)
        err = hip_rc(hipHostMalloc((void **)&s->h_ref_ent, score_bytes, 0));
    if (!err)
        err = hip_rc(hipHostMalloc((void **)&s->h_ref_var, score_bytes, 0));
    if (!err)
        err = hip_rc(hipHostMalloc((void **)&s->h_dis_ent, score_bytes, 0));
    if (!err)
        err = hip_rc(hipHostMalloc((void **)&s->h_dis_var, score_bytes, 0));
    return err;
}

/* Run GPU kernels K1-K3 and download cov_mat + indterm. */
static int run_gpu_pipeline_sc(SpeedChromaHipState *s, const float *h_plane, void *d_indterm,
                               float *h_indterm)
{
    const uint32_t num_blocks = (uint32_t)s->dim.num_blocks;
    const uint32_t num_blocks_h = (uint32_t)s->dim.num_blocks_horizontal;
    const uint32_t op_w = (uint32_t)s->dim.truncated_width;
    const uint32_t stride_px = (uint32_t)(s->float_stride / sizeof(float));
    const uint32_t submatrix_w = (uint32_t)s->dim.submatrix_width;
    const uint32_t submatrix_h = (uint32_t)s->dim.submatrix_height;
    const size_t plane_bytes = s->dim.truncated_height * stride_px * sizeof(float);
    const size_t indterm_bytes = (size_t)SC_ELEMENTS * num_blocks * sizeof(float);

    hipError_t rc =
        hipMemcpyAsync(s->d_plane, h_plane, plane_bytes, hipMemcpyHostToDevice, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);

    /* K1: means */
    {
        const uint32_t grid_x = (num_blocks + SC_MEANS_BLOCK - 1u) / SC_MEANS_BLOCK;
        void *args[] = {(void *)&s->d_plane,  (void *)&s->d_means,   (void *)&op_w,
                        (void *)&stride_px,   (void *)&num_blocks_h, (void *)&num_blocks,
                        (void *)&submatrix_w, (void *)&submatrix_h};
        rc = hipModuleLaunchKernel(s->func_means, grid_x, 1u, 1u, SC_MEANS_BLOCK, 1u, 1u, 0u,
                                   s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }
    /* K2: covariance — SP_ELEMENTS×SP_ELEMENTS blocks, 256 threads, shared=256*sizeof(double) */
    {
        const size_t smem = SC_COV_BLOCK * sizeof(double);
        void *args[] = {(void *)&s->d_plane,  (void *)&s->d_means,   (void *)&s->d_cov_mat,
                        (void *)&stride_px,   (void *)&num_blocks_h, (void *)&num_blocks,
                        (void *)&submatrix_w, (void *)&submatrix_h};
        rc = hipModuleLaunchKernel(s->func_cov, SC_ELEMENTS, SC_ELEMENTS, 1u, SC_COV_BLOCK, 1u, 1u,
                                   (uint32_t)smem, s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }
    /* K3: indterm */
    {
        const uint32_t total = SC_ELEMENTS * num_blocks;
        const uint32_t grid_x = (total + SC_INDTERM_BLOCK - 1u) / SC_INDTERM_BLOCK;
        void *args[] = {(void *)&s->d_plane, (void *)&d_indterm, (void *)&stride_px,
                        (void *)&num_blocks_h, (void *)&num_blocks};
        rc = hipModuleLaunchKernel(s->func_indterm, grid_x, 1u, 1u, SC_INDTERM_BLOCK, 1u, 1u, 0u,
                                   s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }

    /* D2H: cov_mat and indterm. */
    rc = hipMemcpyAsync(s->h_cov_mat, s->d_cov_mat, SC_ELEMENTS * SC_ELEMENTS * sizeof(float),
                        hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipMemcpyAsync(h_indterm, d_indterm, indterm_bytes, hipMemcpyDeviceToHost, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipStreamSynchronize(s->stream);
    return hip_rc(rc);
}

/* uv from u and v, imputing across a singular channel exactly as extract_fex()
 * in speed.c does. */
static float combine_chroma_uv(float score_u, float score_v, bool singular_u, bool singular_v)
{
    if (singular_u && !singular_v)
        return score_v;
    if (singular_v && !singular_u)
        return score_u;
    return (score_u + score_v) * 0.5f;
}

/* CPU linear algebra + upload R/solution + K4 solve. */
static int run_cpu_linalg_sc(SpeedChromaHipState *s, float *h_indterm, void *d_sol,
                             bool *singular_out)
{
    const int sz = (int)SC_ELEMENTS;
    const int nb = (int)s->dim.num_blocks;
    const size_t indterm_bytes = (size_t)SC_ELEMENTS * (size_t)nb * sizeof(float);

    speed_internal_compute_eigenvalues(s->h_cov_mat, s->h_eigenvalues, sz, s->h_eig_scratch);
    bool regular = speed_internal_is_matrix_regular(s->h_eigenvalues, (size_t)sz);

    hipError_t rc = hipSuccess;
    /* A singular matrix is a score condition, not a hard failure (ADR-1202). */
    *singular_out = !regular;
    speed_internal_tally_solve(&s->singular_tally, !regular, "speed_chroma_hip");
    if (!regular) {
        /* The score kernel reads the device solution; zero it for singular input. */
        rc = hipMemsetAsync(d_sol, 0, indterm_bytes, s->stream);
        if (rc != hipSuccess)
            return hip_rc(rc);
    } else {
        const int qr_err =
            speed_internal_qr_factorize(s->h_cov_mat, sz, s->h_Q, s->h_R, s->h_qr_scratch);
        if (qr_err)
            return qr_err;
        speed_internal_qt_multiply(s->h_Q, h_indterm, sz, nb, s->h_qt_scratch);

        rc = hipMemcpyAsync(s->d_R, s->h_R, (size_t)sz * (size_t)sz * sizeof(float),
                            hipMemcpyHostToDevice, s->stream);
        if (rc != hipSuccess)
            return hip_rc(rc);
        rc = hipMemcpyAsync(d_sol, h_indterm, indterm_bytes, hipMemcpyHostToDevice, s->stream);
        if (rc != hipSuccess)
            return hip_rc(rc);

        /* K4: one device wavefront performs backward substitution per column. */
        const uint32_t u_nb = (uint32_t)nb;
        void *args[] = {(void *)&s->d_R, (void *)&d_sol, (void *)&u_nb};
        rc = hipModuleLaunchKernel(s->func_solve, u_nb, 1u, 1u, s->solve_warp, 1u, 1u, 0u,
                                   s->stream, args, NULL);
        if (rc != hipSuccess)
            return hip_rc(rc);
        rc = hipStreamSynchronize(s->stream);
        if (rc != hipSuccess)
            return hip_rc(rc);
    }

    /* Each pass uploads its eigenvalues; the caller stashes the reference copy. */
    rc = hipMemcpyAsync(s->d_eigenvalues, s->h_eigenvalues, SC_ELEMENTS * sizeof(float),
                        hipMemcpyHostToDevice, s->stream);
    if (rc != hipSuccess)
        return hip_rc(rc);
    rc = hipStreamSynchronize(s->stream);
    return hip_rc(rc);
}

static int launch_score_sc(SpeedChromaHipState *s, uint32_t num_blocks)
{
    const float sigma_nn = (float)s->opt.speed_sigma_nn;
    const uint32_t grid = (num_blocks + SC_SCORE_BLOCK - 1u) / SC_SCORE_BLOCK;
    void *args[] = {
        (void *)&s->d_eigenvalues_ref, (void *)&s->d_eigenvalues, (void *)&s->d_sol_ref,
        (void *)&s->d_sol_dis,         (void *)&s->d_indterm_ref, (void *)&s->d_indterm_dis,
        (void *)&s->d_ref_ent,         (void *)&s->d_ref_var,     (void *)&s->d_dis_ent,
        (void *)&s->d_dis_var,         (void *)&num_blocks,       (void *)&sigma_nn,
    };
    return hip_rc(hipModuleLaunchKernel(s->func_score, grid, 1u, 1u, SC_SCORE_BLOCK, 1u, 1u, 0u,
                                        s->stream, args, NULL));
}

static int download_score_sc(SpeedChromaHipState *s, uint32_t num_blocks)
{
    const size_t ab = (size_t)num_blocks * sizeof(float);
    int err =
        hip_rc(hipMemcpyAsync(s->h_ref_ent, s->d_ref_ent, ab, hipMemcpyDeviceToHost, s->stream));
    if (!err)
        err = hip_rc(
            hipMemcpyAsync(s->h_ref_var, s->d_ref_var, ab, hipMemcpyDeviceToHost, s->stream));
    if (!err)
        err = hip_rc(
            hipMemcpyAsync(s->h_dis_ent, s->d_dis_ent, ab, hipMemcpyDeviceToHost, s->stream));
    if (!err)
        err = hip_rc(
            hipMemcpyAsync(s->h_dis_var, s->d_dis_var, ab, hipMemcpyDeviceToHost, s->stream));
    if (!err)
        err = hip_rc(hipStreamSynchronize(s->stream));
    return err;
}

static void speed_weighted_scores(int mode, float ref_entropy, float dis_entropy, float ref_var,
                                  float dis_var, float *ref_score, float *dis_score)
{
    const float ref_log = log2f(1.0f + ref_var);
    *ref_score = ref_entropy * ref_log;
    switch (mode) {
    case 0:
        *dis_score = dis_entropy * log2f(1.0f + dis_var);
        break;
    case 1:
        *dis_score = dis_entropy * ref_log;
        break;
    case 2:
        *ref_score = ref_entropy * log2f(1.0f + dis_var);
        *dis_score = dis_entropy * log2f(1.0f + dis_var);
        break;
    case 3:
        *ref_score = ref_entropy * log2f(1.0f + (ref_var + dis_var) * 0.5f);
        *dis_score = dis_entropy * log2f(1.0f + (ref_var + dis_var) * 0.5f);
        break;
    case 4:
        *dis_score = dis_entropy * log2f(1.0f + (ref_var + dis_var) * 0.5f);
        break;
    case 5:
        *dis_score = dis_entropy * log2f(1.0f + 0.75f * ref_var + 0.25f * dis_var);
        break;
    case 6:
        *dis_score = dis_entropy * log2f(1.0f + 0.25f * ref_var + 0.75f * dis_var);
        break;
    default:
        *ref_score = 0.0f;
        *dis_score = 0.0f;
        break;
    }
}

static float aggregate_score_sc(const SpeedChromaHipState *s, uint32_t num_blocks)
{
    const float base_entropy =
        (float)SC_ELEMENTS *
        (log2f((1.0f + (float)s->opt.speed_nn_floor) * (float)s->opt.speed_sigma_nn) +
         log2f(2.0f * 3.14159265358979323846f * 2.71828182845904523536f));
    float total = 0.0f;
    for (uint32_t i = 0; i < num_blocks; ++i) {
        const float re = s->h_ref_ent[i];
        const float de = s->h_dis_ent[i];
        if (re < base_entropy && de < base_entropy)
            continue;
        const float rv = s->h_ref_var[i];
        const float dv = s->h_dis_var[i];
        float sr = 0.0f;
        float sd = 0.0f;
        speed_weighted_scores(s->opt.speed_weight_var_mode, re, de, rv, dv, &sr, &sd);
        total += fabsf(sr - sd);
    }
    return total / (float)num_blocks;
}

/* K5 score + D2H + CPU aggregate. */
static int run_score_sc(SpeedChromaHipState *s, float *score_out)
{
    const uint32_t num_blocks = (uint32_t)s->dim.num_blocks;
    int err = launch_score_sc(s, num_blocks);
    if (!err)
        err = download_score_sc(s, num_blocks);
    if (!err)
        *score_out = aggregate_score_sc(s, num_blocks);
    return err;
}

#endif /* HAVE_HIPCC */

/* ------------------------------------------------------------------ */
/* Lifecycle                                                           */
/* ------------------------------------------------------------------ */

static void free_chroma_cpu_buffers(SpeedChromaHipState *s)
{
    aligned_free(s->h_plane_ref);
    aligned_free(s->h_plane_dis);
    aligned_free(s->h_eigenvalues);
    aligned_free(s->h_eig_scratch);
    aligned_free(s->h_Q);
    aligned_free(s->h_R);
    aligned_free(s->h_qr_scratch);
    aligned_free(s->h_indterm_ref);
    aligned_free(s->h_indterm_dis);
    aligned_free(s->h_qt_scratch);
    s->h_plane_ref = NULL;
    s->h_plane_dis = NULL;
    s->h_eigenvalues = NULL;
    s->h_eig_scratch = NULL;
    s->h_Q = NULL;
    s->h_R = NULL;
    s->h_qr_scratch = NULL;
    s->h_indterm_ref = NULL;
    s->h_indterm_dis = NULL;
    s->h_qt_scratch = NULL;
}

static int init_chroma_dimensions(SpeedChromaHipState *s, enum VmafPixelFormat pix_fmt, unsigned w,
                                  unsigned h)
{
    unsigned cw = w;
    unsigned ch = h;
    switch (pix_fmt) {
    case VMAF_PIX_FMT_UNKNOWN:
    case VMAF_PIX_FMT_YUV400P:
        return -EINVAL;
    case VMAF_PIX_FMT_YUV420P:
        cw /= 2u;
        ch /= 2u;
        break;
    case VMAF_PIX_FMT_YUV422P:
        cw /= 2u;
        break;
    case VMAF_PIX_FMT_YUV444P:
        break;
    }

    s->opt = (SpeedInternalOptions){
        .speed_kernelscale = s->speed_chroma_kernelscale,
        .speed_prescale = s->speed_chroma_prescale,
        .speed_prescale_method = s->speed_chroma_prescale_method,
        .speed_sigma_nn = s->speed_chroma_sigma_nn,
        .speed_nn_floor = s->speed_chroma_nn_floor,
        .speed_weight_var_mode = s->speed_weight_var_mode,
    };
    const int err =
        speed_internal_init_dimensions(&s->dim, (int)cw, (int)ch, s->opt.speed_prescale);
    if (err)
        return err;
    s->float_stride = speed_internal_float_stride(s->dim.alloc_width);
    return s->float_stride ? 0 : -EOVERFLOW;
}

static int allocate_chroma_cpu_buffers(SpeedChromaHipState *s)
{
    if (s->dim.alloc_height > SIZE_MAX / s->float_stride ||
        s->dim.num_blocks > SIZE_MAX / (SC_ELEMENTS * sizeof(float)))
        return -EOVERFLOW;
    const size_t plane_bytes = s->dim.alloc_height * s->float_stride;
    const size_t indterm_bytes = SC_ELEMENTS * s->dim.num_blocks * sizeof(float);
    const size_t cov_bytes = SC_ELEMENTS * SC_ELEMENTS * sizeof(float);
    s->h_plane_ref = aligned_malloc(plane_bytes, 32);
    s->h_plane_dis = aligned_malloc(plane_bytes, 32);
    s->h_eigenvalues = aligned_malloc(SC_ELEMENTS * sizeof(float), 32);
    s->h_eig_scratch =
        aligned_malloc((SC_ELEMENTS * SC_ELEMENTS + 4u * SC_ELEMENTS) * sizeof(float), 32);
    s->h_Q = aligned_malloc(cov_bytes, 32);
    s->h_R = aligned_malloc(cov_bytes, 32);
    s->h_qr_scratch = aligned_malloc(4u * cov_bytes, 32);
    s->h_indterm_ref = aligned_malloc(indterm_bytes, 32);
    s->h_indterm_dis = aligned_malloc(indterm_bytes, 32);
    s->h_qt_scratch = aligned_malloc(indterm_bytes, 32);
    if (!s->h_plane_ref || !s->h_plane_dis || !s->h_eigenvalues || !s->h_eig_scratch || !s->h_Q ||
        !s->h_R || !s->h_qr_scratch || !s->h_indterm_ref || !s->h_indterm_dis || !s->h_qt_scratch)
        return -ENOMEM;
    return 0;
}

#ifdef HAVE_HIPCC
static int init_chroma_hip_runtime(SpeedChromaHipState *s)
{
    int err = sc_hip_module_load(s);
    if (!err)
        err = hip_rc(hipStreamCreate(&s->stream));
    int device = 0;
    hipDeviceProp_t properties;
    if (!err)
        err = hip_rc(hipGetDevice(&device));
    if (!err)
        err = hip_rc(hipGetDeviceProperties(&properties, device));
    if (!err && properties.warpSize <= 0)
        err = -EIO;
    if (!err)
        s->solve_warp = (unsigned)properties.warpSize;
    if (!err)
        err = sc_hip_bufs_alloc(s);
    return err;
}
#endif

static int init_chroma_hip(VmafFeatureExtractor *fex, enum VmafPixelFormat pix_fmt, unsigned bpc,
                           unsigned w, unsigned h)
{
    (void)bpc;
    SpeedChromaHipState *const s = fex->priv;
    int err = init_chroma_dimensions(s, pix_fmt, w, h);
#ifndef HAVE_HIPCC
    return err ? err : -ENOSYS;
#else
    if (!err)
        err = allocate_chroma_cpu_buffers(s);
    if (!err)
        err = init_chroma_hip_runtime(s);
    if (!err) {
        s->feature_name_dict =
            vmaf_feature_name_dict_from_provided_features(fex->provided_features, fex->options, s);
        if (!s->feature_name_dict)
            err = -ENOMEM;
    }
    if (err) {
        const int hip_cleanup_err = free_hip_buffers(s, false);
        if (hip_cleanup_err)
            vmaf_log(VMAF_LOG_LEVEL_ERROR, "speed_chroma_hip initialization cleanup failed: %d\n",
                     hip_cleanup_err);
        free_chroma_cpu_buffers(s);
    }
    return err;
#endif
}

#ifdef HAVE_HIPCC
typedef struct ChromaChannelResult {
    float score;
    bool singular;
    int err;
} ChromaChannelResult;

static void prepare_chroma_planes(SpeedChromaHipState *s, const VmafPicture *ref_pic,
                                  const VmafPicture *dist_pic, int channel, float *tmp_filter)
{
    picture_copy(s->h_plane_ref, s->float_stride, ref_pic, -128, ref_pic->bpc, channel);
    speed_internal_filter_and_downscale(&s->dim, &s->opt, s->h_plane_ref, tmp_filter,
                                        s->float_stride);
    picture_copy(s->h_plane_dis, s->float_stride, dist_pic, -128, dist_pic->bpc, channel);
    speed_internal_filter_and_downscale(&s->dim, &s->opt, s->h_plane_dis, tmp_filter,
                                        s->float_stride);
}

static ChromaChannelResult score_chroma_channel(SpeedChromaHipState *s, const VmafPicture *ref_pic,
                                                const VmafPicture *dist_pic, int channel,
                                                float *tmp_filter)
{
    ChromaChannelResult result = {0};
    prepare_chroma_planes(s, ref_pic, dist_pic, channel, tmp_filter);
    result.err = run_gpu_pipeline_sc(s, s->h_plane_ref, s->d_indterm_ref, s->h_indterm_ref);
    bool singular_ref = false;
    if (!result.err)
        result.err = run_cpu_linalg_sc(s, s->h_indterm_ref, s->d_sol_ref, &singular_ref);
    if (!result.err)
        result.err = hip_rc(
            hipMemcpyDtoD(s->d_eigenvalues_ref, s->d_eigenvalues, SC_ELEMENTS * sizeof(float)));
    bool singular_dis = false;
    if (!result.err)
        result.err = run_gpu_pipeline_sc(s, s->h_plane_dis, s->d_indterm_dis, s->h_indterm_dis);
    if (!result.err)
        result.err = run_cpu_linalg_sc(s, s->h_indterm_dis, s->d_sol_dis, &singular_dis);
    if (!result.err && singular_ref == singular_dis)
        result.err = run_score_sc(s, &result.score);
    result.singular = singular_ref || singular_dis;
    return result;
}

static int append_chroma_scores(const SpeedChromaHipState *s, VmafFeatureCollector *collector,
                                unsigned index, const ChromaChannelResult results[2])
{
    static const char *const names[] = {"Speed_chroma_feature_speed_chroma_u_score",
                                        "Speed_chroma_feature_speed_chroma_v_score",
                                        "Speed_chroma_feature_speed_chroma_uv_score"};
    const float uv = combine_chroma_uv(results[0].score, results[1].score, results[0].singular,
                                       results[1].singular);
    const double values[] = {results[0].score, results[1].score, uv};
    int err = 0;
    for (unsigned i = 0; i < 3; i++) {
        const double clipped =
            values[i] < s->speed_chroma_max_val ? values[i] : s->speed_chroma_max_val;
        err |= vmaf_feature_collector_append_with_dict(collector, s->feature_name_dict, names[i],
                                                       clipped, index);
    }
    return err;
}
#endif

static int extract_chroma_hip(VmafFeatureExtractor *fex, VmafPicture *ref_pic,
                              VmafPicture *ref_pic_90, VmafPicture *dist_pic,
                              VmafPicture *dist_pic_90, unsigned index,
                              VmafFeatureCollector *feature_collector)
{
    (void)ref_pic_90;
    (void)dist_pic_90;

#ifndef HAVE_HIPCC
    (void)fex;
    (void)ref_pic;
    (void)dist_pic;
    (void)index;
    (void)feature_collector;
    return -ENOSYS;
#else
    SpeedChromaHipState *const s = fex->priv;
    if (s->dim.alloc_height > SIZE_MAX / s->float_stride / 2u)
        return -EOVERFLOW;
    const size_t tmp_bytes = 2u * s->dim.alloc_height * s->float_stride;
    float *const tmp_filter = aligned_malloc(tmp_bytes, 32);
    if (!tmp_filter)
        return -ENOMEM;
    ChromaChannelResult results[2];
    results[0] = score_chroma_channel(s, ref_pic, dist_pic, 1, tmp_filter);
    results[1] = score_chroma_channel(s, ref_pic, dist_pic, 2, tmp_filter);
    aligned_free(tmp_filter);
    if (results[0].err)
        return results[0].err;
    if (results[1].err)
        return results[1].err;
    return append_chroma_scores(s, feature_collector, index, results);
#endif /* HAVE_HIPCC */
}

static int close_chroma_hip(VmafFeatureExtractor *fex)
{
    SpeedChromaHipState *const s = fex->priv;
    speed_internal_report_singular(&s->singular_tally, "speed_chroma_hip");
    int err = 0;
#ifdef HAVE_HIPCC
    err = free_hip_buffers(s, true);
#endif
    free_chroma_cpu_buffers(s);
    const int dict_err = vmaf_dictionary_free(&s->feature_name_dict);
    if (dict_err) {
        vmaf_log(VMAF_LOG_LEVEL_ERROR, "speed_chroma_hip dictionary free failed: %d\n", dict_err);
        if (!err)
            err = dict_err;
    }
    return err;
}

static const char *provided_features_chroma[] = {
    "Speed_chroma_feature_speed_chroma_u_score",
    "Speed_chroma_feature_speed_chroma_v_score",
    "Speed_chroma_feature_speed_chroma_uv_score",
    NULL,
};

/* ADR-0567: real HIP GPU kernels for speed_chroma. */
VmafFeatureExtractor vmaf_fex_speed_chroma_hip = {
    .name = "speed_chroma_hip",
    .init = init_chroma_hip,
    .extract = extract_chroma_hip,
    .close = close_chroma_hip,
    .options = options_chroma,
    .priv_size = sizeof(SpeedChromaHipState),
    .provided_features = provided_features_chroma,
    .flags = VMAF_FEATURE_EXTRACTOR_HIP,
};

/* NOLINTEND(modernize-use-nullptr) */
