// Copyright 2026 Lusoris
// SPDX-License-Identifier: BSD-2-Clause-Patent

package codecadapter

import (
	"fmt"
	"slices"
	"testing"
)

// TestFFmpegCodecArgs_matchesPythonAdapters pins the argv every adapter emits
// at its own default preset and quality against the Python
// vmaftune.codec_adapters registry, captured by calling
// get_adapter(<name>).ffmpeg_codec_args(preset, quality) directly.
//
// The port integration kept one of three parallel codecadapter implementations,
// and the choice was made on codec-name coverage rather than on emitted argv.
// Two divergences survived that check: prores tier 5 emitted "4444xq" where
// FFmpeg and Python name it "xq", and libx265 fell back to ffmpeg's generic
// -pass/-passlogfile instead of -x265-params. This test compares the bytes.
func TestFFmpegCodecArgs_matchesPythonAdapters(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name    string
		preset  string
		quality int
		want    []string
		wantErr bool
	}{
		{name: "libx264", preset: "ultrafast", quality: 0, want: []string{"-c:v", "libx264", "-preset", "ultrafast", "-crf", "0"}},
		{name: "libx264", preset: "ultrafast", quality: 23, want: []string{"-c:v", "libx264", "-preset", "ultrafast", "-crf", "23"}},
		{name: "libx264", preset: "ultrafast", quality: 51, want: []string{"-c:v", "libx264", "-preset", "ultrafast", "-crf", "51"}},
		{name: "libx264", preset: "superfast", quality: 0, want: []string{"-c:v", "libx264", "-preset", "superfast", "-crf", "0"}},
		{name: "libx264", preset: "superfast", quality: 23, want: []string{"-c:v", "libx264", "-preset", "superfast", "-crf", "23"}},
		{name: "libx264", preset: "superfast", quality: 51, want: []string{"-c:v", "libx264", "-preset", "superfast", "-crf", "51"}},
		{name: "libx264", preset: "veryfast", quality: 0, want: []string{"-c:v", "libx264", "-preset", "veryfast", "-crf", "0"}},
		{name: "libx264", preset: "veryfast", quality: 23, want: []string{"-c:v", "libx264", "-preset", "veryfast", "-crf", "23"}},
		{name: "libx264", preset: "veryfast", quality: 51, want: []string{"-c:v", "libx264", "-preset", "veryfast", "-crf", "51"}},
		{name: "libx264", preset: "faster", quality: 0, want: []string{"-c:v", "libx264", "-preset", "faster", "-crf", "0"}},
		{name: "libx264", preset: "faster", quality: 23, want: []string{"-c:v", "libx264", "-preset", "faster", "-crf", "23"}},
		{name: "libx264", preset: "faster", quality: 51, want: []string{"-c:v", "libx264", "-preset", "faster", "-crf", "51"}},
		{name: "libx264", preset: "fast", quality: 0, want: []string{"-c:v", "libx264", "-preset", "fast", "-crf", "0"}},
		{name: "libx264", preset: "fast", quality: 23, want: []string{"-c:v", "libx264", "-preset", "fast", "-crf", "23"}},
		{name: "libx264", preset: "fast", quality: 51, want: []string{"-c:v", "libx264", "-preset", "fast", "-crf", "51"}},
		{name: "libx264", preset: "medium", quality: 0, want: []string{"-c:v", "libx264", "-preset", "medium", "-crf", "0"}},
		{name: "libx264", preset: "medium", quality: 23, want: []string{"-c:v", "libx264", "-preset", "medium", "-crf", "23"}},
		{name: "libx264", preset: "medium", quality: 51, want: []string{"-c:v", "libx264", "-preset", "medium", "-crf", "51"}},
		{name: "libx264", preset: "slow", quality: 0, want: []string{"-c:v", "libx264", "-preset", "slow", "-crf", "0"}},
		{name: "libx264", preset: "slow", quality: 23, want: []string{"-c:v", "libx264", "-preset", "slow", "-crf", "23"}},
		{name: "libx264", preset: "slow", quality: 51, want: []string{"-c:v", "libx264", "-preset", "slow", "-crf", "51"}},
		{name: "libx264", preset: "slower", quality: 0, want: []string{"-c:v", "libx264", "-preset", "slower", "-crf", "0"}},
		{name: "libx264", preset: "slower", quality: 23, want: []string{"-c:v", "libx264", "-preset", "slower", "-crf", "23"}},
		{name: "libx264", preset: "slower", quality: 51, want: []string{"-c:v", "libx264", "-preset", "slower", "-crf", "51"}},
		{name: "libx264", preset: "veryslow", quality: 0, want: []string{"-c:v", "libx264", "-preset", "veryslow", "-crf", "0"}},
		{name: "libx264", preset: "veryslow", quality: 23, want: []string{"-c:v", "libx264", "-preset", "veryslow", "-crf", "23"}},
		{name: "libx264", preset: "veryslow", quality: 51, want: []string{"-c:v", "libx264", "-preset", "veryslow", "-crf", "51"}},
		{name: "libx265", preset: "ultrafast", quality: 15, want: []string{"-c:v", "libx265", "-preset", "ultrafast", "-crf", "15"}},
		{name: "libx265", preset: "ultrafast", quality: 28, want: []string{"-c:v", "libx265", "-preset", "ultrafast", "-crf", "28"}},
		{name: "libx265", preset: "ultrafast", quality: 40, want: []string{"-c:v", "libx265", "-preset", "ultrafast", "-crf", "40"}},
		{name: "libx265", preset: "superfast", quality: 15, want: []string{"-c:v", "libx265", "-preset", "superfast", "-crf", "15"}},
		{name: "libx265", preset: "superfast", quality: 28, want: []string{"-c:v", "libx265", "-preset", "superfast", "-crf", "28"}},
		{name: "libx265", preset: "superfast", quality: 40, want: []string{"-c:v", "libx265", "-preset", "superfast", "-crf", "40"}},
		{name: "libx265", preset: "veryfast", quality: 15, want: []string{"-c:v", "libx265", "-preset", "veryfast", "-crf", "15"}},
		{name: "libx265", preset: "veryfast", quality: 28, want: []string{"-c:v", "libx265", "-preset", "veryfast", "-crf", "28"}},
		{name: "libx265", preset: "veryfast", quality: 40, want: []string{"-c:v", "libx265", "-preset", "veryfast", "-crf", "40"}},
		{name: "libx265", preset: "faster", quality: 15, want: []string{"-c:v", "libx265", "-preset", "faster", "-crf", "15"}},
		{name: "libx265", preset: "faster", quality: 28, want: []string{"-c:v", "libx265", "-preset", "faster", "-crf", "28"}},
		{name: "libx265", preset: "faster", quality: 40, want: []string{"-c:v", "libx265", "-preset", "faster", "-crf", "40"}},
		{name: "libx265", preset: "fast", quality: 15, want: []string{"-c:v", "libx265", "-preset", "fast", "-crf", "15"}},
		{name: "libx265", preset: "fast", quality: 28, want: []string{"-c:v", "libx265", "-preset", "fast", "-crf", "28"}},
		{name: "libx265", preset: "fast", quality: 40, want: []string{"-c:v", "libx265", "-preset", "fast", "-crf", "40"}},
		{name: "libx265", preset: "medium", quality: 15, want: []string{"-c:v", "libx265", "-preset", "medium", "-crf", "15"}},
		{name: "libx265", preset: "medium", quality: 28, want: []string{"-c:v", "libx265", "-preset", "medium", "-crf", "28"}},
		{name: "libx265", preset: "medium", quality: 40, want: []string{"-c:v", "libx265", "-preset", "medium", "-crf", "40"}},
		{name: "libx265", preset: "slow", quality: 15, want: []string{"-c:v", "libx265", "-preset", "slow", "-crf", "15"}},
		{name: "libx265", preset: "slow", quality: 28, want: []string{"-c:v", "libx265", "-preset", "slow", "-crf", "28"}},
		{name: "libx265", preset: "slow", quality: 40, want: []string{"-c:v", "libx265", "-preset", "slow", "-crf", "40"}},
		{name: "libx265", preset: "slower", quality: 15, want: []string{"-c:v", "libx265", "-preset", "slower", "-crf", "15"}},
		{name: "libx265", preset: "slower", quality: 28, want: []string{"-c:v", "libx265", "-preset", "slower", "-crf", "28"}},
		{name: "libx265", preset: "slower", quality: 40, want: []string{"-c:v", "libx265", "-preset", "slower", "-crf", "40"}},
		{name: "libx265", preset: "veryslow", quality: 15, want: []string{"-c:v", "libx265", "-preset", "veryslow", "-crf", "15"}},
		{name: "libx265", preset: "veryslow", quality: 28, want: []string{"-c:v", "libx265", "-preset", "veryslow", "-crf", "28"}},
		{name: "libx265", preset: "veryslow", quality: 40, want: []string{"-c:v", "libx265", "-preset", "veryslow", "-crf", "40"}},
		{name: "libx265", preset: "placebo", quality: 15, want: []string{"-c:v", "libx265", "-preset", "placebo", "-crf", "15"}},
		{name: "libx265", preset: "placebo", quality: 28, want: []string{"-c:v", "libx265", "-preset", "placebo", "-crf", "28"}},
		{name: "libx265", preset: "placebo", quality: 40, want: []string{"-c:v", "libx265", "-preset", "placebo", "-crf", "40"}},
		{name: "libaom-av1", preset: "placebo", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "0", "-crf", "0"}},
		{name: "libaom-av1", preset: "placebo", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "0", "-crf", "35"}},
		{name: "libaom-av1", preset: "placebo", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "0", "-crf", "63"}},
		{name: "libaom-av1", preset: "slowest", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "1", "-crf", "0"}},
		{name: "libaom-av1", preset: "slowest", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "1", "-crf", "35"}},
		{name: "libaom-av1", preset: "slowest", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "1", "-crf", "63"}},
		{name: "libaom-av1", preset: "slower", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "2", "-crf", "0"}},
		{name: "libaom-av1", preset: "slower", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "2", "-crf", "35"}},
		{name: "libaom-av1", preset: "slower", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "2", "-crf", "63"}},
		{name: "libaom-av1", preset: "slow", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "3", "-crf", "0"}},
		{name: "libaom-av1", preset: "slow", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "3", "-crf", "35"}},
		{name: "libaom-av1", preset: "slow", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "3", "-crf", "63"}},
		{name: "libaom-av1", preset: "medium", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "4", "-crf", "0"}},
		{name: "libaom-av1", preset: "medium", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "4", "-crf", "35"}},
		{name: "libaom-av1", preset: "medium", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "4", "-crf", "63"}},
		{name: "libaom-av1", preset: "fast", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "5", "-crf", "0"}},
		{name: "libaom-av1", preset: "fast", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "5", "-crf", "35"}},
		{name: "libaom-av1", preset: "fast", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "5", "-crf", "63"}},
		{name: "libaom-av1", preset: "faster", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "6", "-crf", "0"}},
		{name: "libaom-av1", preset: "faster", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "6", "-crf", "35"}},
		{name: "libaom-av1", preset: "faster", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "6", "-crf", "63"}},
		{name: "libaom-av1", preset: "veryfast", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "7", "-crf", "0"}},
		{name: "libaom-av1", preset: "veryfast", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "7", "-crf", "35"}},
		{name: "libaom-av1", preset: "veryfast", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "7", "-crf", "63"}},
		{name: "libaom-av1", preset: "superfast", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "8", "-crf", "0"}},
		{name: "libaom-av1", preset: "superfast", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "8", "-crf", "35"}},
		{name: "libaom-av1", preset: "superfast", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "8", "-crf", "63"}},
		{name: "libaom-av1", preset: "ultrafast", quality: 0, want: []string{"-c:v", "libaom-av1", "-cpu-used", "9", "-crf", "0"}},
		{name: "libaom-av1", preset: "ultrafast", quality: 35, want: []string{"-c:v", "libaom-av1", "-cpu-used", "9", "-crf", "35"}},
		{name: "libaom-av1", preset: "ultrafast", quality: 63, want: []string{"-c:v", "libaom-av1", "-cpu-used", "9", "-crf", "63"}},
		{name: "libsvtav1", preset: "placebo", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "0", "-crf", "20"}},
		{name: "libsvtav1", preset: "placebo", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "0", "-crf", "35"}},
		{name: "libsvtav1", preset: "placebo", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "0", "-crf", "50"}},
		{name: "libsvtav1", preset: "slowest", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "1", "-crf", "20"}},
		{name: "libsvtav1", preset: "slowest", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "1", "-crf", "35"}},
		{name: "libsvtav1", preset: "slowest", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "1", "-crf", "50"}},
		{name: "libsvtav1", preset: "slower", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "3", "-crf", "20"}},
		{name: "libsvtav1", preset: "slower", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "3", "-crf", "35"}},
		{name: "libsvtav1", preset: "slower", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "3", "-crf", "50"}},
		{name: "libsvtav1", preset: "slow", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "5", "-crf", "20"}},
		{name: "libsvtav1", preset: "slow", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "5", "-crf", "35"}},
		{name: "libsvtav1", preset: "slow", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "5", "-crf", "50"}},
		{name: "libsvtav1", preset: "medium", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "7", "-crf", "20"}},
		{name: "libsvtav1", preset: "medium", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "7", "-crf", "35"}},
		{name: "libsvtav1", preset: "medium", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "7", "-crf", "50"}},
		{name: "libsvtav1", preset: "fast", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "9", "-crf", "20"}},
		{name: "libsvtav1", preset: "fast", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "9", "-crf", "35"}},
		{name: "libsvtav1", preset: "fast", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "9", "-crf", "50"}},
		{name: "libsvtav1", preset: "faster", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "11", "-crf", "20"}},
		{name: "libsvtav1", preset: "faster", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "11", "-crf", "35"}},
		{name: "libsvtav1", preset: "faster", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "11", "-crf", "50"}},
		{name: "libsvtav1", preset: "veryfast", quality: 20, want: []string{"-c:v", "libsvtav1", "-preset", "13", "-crf", "20"}},
		{name: "libsvtav1", preset: "veryfast", quality: 35, want: []string{"-c:v", "libsvtav1", "-preset", "13", "-crf", "35"}},
		{name: "libsvtav1", preset: "veryfast", quality: 50, want: []string{"-c:v", "libsvtav1", "-preset", "13", "-crf", "50"}},
		{name: "libvpx-vp9", preset: "placebo", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "0", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "placebo", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "0", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "placebo", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "0", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slowest", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "0", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slowest", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "0", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slowest", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "0", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slower", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "1", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slower", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "1", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slower", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "1", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slow", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "2", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slow", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "2", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "slow", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "2", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "medium", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "3", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "medium", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "3", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "medium", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "3", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "fast", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "4", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "fast", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "4", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "fast", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "4", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "faster", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "faster", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "faster", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "veryfast", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "veryfast", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "veryfast", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "superfast", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "superfast", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "superfast", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "63", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "ultrafast", quality: 0, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "0", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "ultrafast", quality: 32, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "32", "-b:v", "0"}},
		{name: "libvpx-vp9", preset: "ultrafast", quality: 63, want: []string{"-c:v", "libvpx-vp9", "-deadline", "good", "-cpu-used", "5", "-crf", "63", "-b:v", "0"}},
		{name: "libvvenc", preset: "placebo", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "17"}},
		{name: "libvvenc", preset: "placebo", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "32"}},
		{name: "libvvenc", preset: "placebo", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "50"}},
		{name: "libvvenc", preset: "slowest", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "17"}},
		{name: "libvvenc", preset: "slowest", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "32"}},
		{name: "libvvenc", preset: "slowest", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "50"}},
		{name: "libvvenc", preset: "slower", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "17"}},
		{name: "libvvenc", preset: "slower", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "32"}},
		{name: "libvvenc", preset: "slower", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "slower", "-qp", "50"}},
		{name: "libvvenc", preset: "slow", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "slow", "-qp", "17"}},
		{name: "libvvenc", preset: "slow", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "slow", "-qp", "32"}},
		{name: "libvvenc", preset: "slow", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "slow", "-qp", "50"}},
		{name: "libvvenc", preset: "medium", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "medium", "-qp", "17"}},
		{name: "libvvenc", preset: "medium", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "medium", "-qp", "32"}},
		{name: "libvvenc", preset: "medium", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "medium", "-qp", "50"}},
		{name: "libvvenc", preset: "fast", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "fast", "-qp", "17"}},
		{name: "libvvenc", preset: "fast", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "fast", "-qp", "32"}},
		{name: "libvvenc", preset: "fast", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "fast", "-qp", "50"}},
		{name: "libvvenc", preset: "faster", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "17"}},
		{name: "libvvenc", preset: "faster", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "32"}},
		{name: "libvvenc", preset: "faster", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "50"}},
		{name: "libvvenc", preset: "veryfast", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "17"}},
		{name: "libvvenc", preset: "veryfast", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "32"}},
		{name: "libvvenc", preset: "veryfast", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "50"}},
		{name: "libvvenc", preset: "superfast", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "17"}},
		{name: "libvvenc", preset: "superfast", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "32"}},
		{name: "libvvenc", preset: "superfast", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "50"}},
		{name: "libvvenc", preset: "ultrafast", quality: 17, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "17"}},
		{name: "libvvenc", preset: "ultrafast", quality: 32, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "32"}},
		{name: "libvvenc", preset: "ultrafast", quality: 50, want: []string{"-c:v", "libvvenc", "-preset", "faster", "-qp", "50"}},
		{name: "h264_nvenc", preset: "ultrafast", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "h264_nvenc", preset: "ultrafast", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "h264_nvenc", preset: "ultrafast", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "h264_nvenc", preset: "superfast", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "h264_nvenc", preset: "superfast", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "h264_nvenc", preset: "superfast", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "h264_nvenc", preset: "veryfast", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "h264_nvenc", preset: "veryfast", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "h264_nvenc", preset: "veryfast", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "h264_nvenc", preset: "faster", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p2", "-cq", "15"}},
		{name: "h264_nvenc", preset: "faster", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p2", "-cq", "23"}},
		{name: "h264_nvenc", preset: "faster", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p2", "-cq", "40"}},
		{name: "h264_nvenc", preset: "fast", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p3", "-cq", "15"}},
		{name: "h264_nvenc", preset: "fast", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p3", "-cq", "23"}},
		{name: "h264_nvenc", preset: "fast", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p3", "-cq", "40"}},
		{name: "h264_nvenc", preset: "medium", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p4", "-cq", "15"}},
		{name: "h264_nvenc", preset: "medium", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p4", "-cq", "23"}},
		{name: "h264_nvenc", preset: "medium", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p4", "-cq", "40"}},
		{name: "h264_nvenc", preset: "slow", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p5", "-cq", "15"}},
		{name: "h264_nvenc", preset: "slow", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p5", "-cq", "23"}},
		{name: "h264_nvenc", preset: "slow", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p5", "-cq", "40"}},
		{name: "h264_nvenc", preset: "slower", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p6", "-cq", "15"}},
		{name: "h264_nvenc", preset: "slower", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p6", "-cq", "23"}},
		{name: "h264_nvenc", preset: "slower", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p6", "-cq", "40"}},
		{name: "h264_nvenc", preset: "slowest", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p7", "-cq", "15"}},
		{name: "h264_nvenc", preset: "slowest", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p7", "-cq", "23"}},
		{name: "h264_nvenc", preset: "slowest", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p7", "-cq", "40"}},
		{name: "h264_nvenc", preset: "placebo", quality: 15, want: []string{"-c:v", "h264_nvenc", "-preset", "p7", "-cq", "15"}},
		{name: "h264_nvenc", preset: "placebo", quality: 23, want: []string{"-c:v", "h264_nvenc", "-preset", "p7", "-cq", "23"}},
		{name: "h264_nvenc", preset: "placebo", quality: 40, want: []string{"-c:v", "h264_nvenc", "-preset", "p7", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "ultrafast", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "ultrafast", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "ultrafast", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "superfast", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "superfast", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "superfast", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "veryfast", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "veryfast", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "veryfast", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "faster", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p2", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "faster", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p2", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "faster", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p2", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "fast", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p3", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "fast", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p3", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "fast", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p3", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "medium", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p4", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "medium", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p4", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "medium", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p4", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "slow", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p5", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "slow", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p5", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "slow", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p5", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "slower", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p6", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "slower", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p6", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "slower", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p6", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "slowest", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p7", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "slowest", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p7", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "slowest", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p7", "-cq", "40"}},
		{name: "hevc_nvenc", preset: "placebo", quality: 15, want: []string{"-c:v", "hevc_nvenc", "-preset", "p7", "-cq", "15"}},
		{name: "hevc_nvenc", preset: "placebo", quality: 23, want: []string{"-c:v", "hevc_nvenc", "-preset", "p7", "-cq", "23"}},
		{name: "hevc_nvenc", preset: "placebo", quality: 40, want: []string{"-c:v", "hevc_nvenc", "-preset", "p7", "-cq", "40"}},
		{name: "av1_nvenc", preset: "ultrafast", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "av1_nvenc", preset: "ultrafast", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "av1_nvenc", preset: "ultrafast", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "av1_nvenc", preset: "superfast", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "av1_nvenc", preset: "superfast", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "av1_nvenc", preset: "superfast", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "av1_nvenc", preset: "veryfast", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "15"}},
		{name: "av1_nvenc", preset: "veryfast", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "23"}},
		{name: "av1_nvenc", preset: "veryfast", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p1", "-cq", "40"}},
		{name: "av1_nvenc", preset: "faster", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p2", "-cq", "15"}},
		{name: "av1_nvenc", preset: "faster", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p2", "-cq", "23"}},
		{name: "av1_nvenc", preset: "faster", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p2", "-cq", "40"}},
		{name: "av1_nvenc", preset: "fast", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p3", "-cq", "15"}},
		{name: "av1_nvenc", preset: "fast", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p3", "-cq", "23"}},
		{name: "av1_nvenc", preset: "fast", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p3", "-cq", "40"}},
		{name: "av1_nvenc", preset: "medium", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p4", "-cq", "15"}},
		{name: "av1_nvenc", preset: "medium", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p4", "-cq", "23"}},
		{name: "av1_nvenc", preset: "medium", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p4", "-cq", "40"}},
		{name: "av1_nvenc", preset: "slow", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p5", "-cq", "15"}},
		{name: "av1_nvenc", preset: "slow", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p5", "-cq", "23"}},
		{name: "av1_nvenc", preset: "slow", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p5", "-cq", "40"}},
		{name: "av1_nvenc", preset: "slower", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p6", "-cq", "15"}},
		{name: "av1_nvenc", preset: "slower", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p6", "-cq", "23"}},
		{name: "av1_nvenc", preset: "slower", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p6", "-cq", "40"}},
		{name: "av1_nvenc", preset: "slowest", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p7", "-cq", "15"}},
		{name: "av1_nvenc", preset: "slowest", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p7", "-cq", "23"}},
		{name: "av1_nvenc", preset: "slowest", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p7", "-cq", "40"}},
		{name: "av1_nvenc", preset: "placebo", quality: 15, want: []string{"-c:v", "av1_nvenc", "-preset", "p7", "-cq", "15"}},
		{name: "av1_nvenc", preset: "placebo", quality: 23, want: []string{"-c:v", "av1_nvenc", "-preset", "p7", "-cq", "23"}},
		{name: "av1_nvenc", preset: "placebo", quality: 40, want: []string{"-c:v", "av1_nvenc", "-preset", "p7", "-cq", "40"}},
		{name: "h264_amf", preset: "ultrafast", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "ultrafast", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "ultrafast", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "superfast", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "superfast", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "superfast", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "veryfast", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "veryfast", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "veryfast", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "faster", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "faster", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "faster", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "fast", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "fast", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "fast", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "medium", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "medium", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "medium", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "slow", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "slow", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "slow", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "slower", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "slower", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "slower", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "slowest", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "slowest", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "slowest", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_amf", preset: "placebo", quality: 15, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "h264_amf", preset: "placebo", quality: 23, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "h264_amf", preset: "placebo", quality: 40, want: []string{"-c:v", "h264_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "ultrafast", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "ultrafast", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "ultrafast", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "superfast", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "superfast", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "superfast", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "veryfast", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "veryfast", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "veryfast", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "faster", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "faster", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "faster", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "fast", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "fast", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "fast", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "medium", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "medium", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "medium", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "slow", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "slow", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "slow", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "slower", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "slower", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "slower", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "slowest", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "slowest", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "slowest", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "hevc_amf", preset: "placebo", quality: 15, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "hevc_amf", preset: "placebo", quality: 23, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "hevc_amf", preset: "placebo", quality: 40, want: []string{"-c:v", "hevc_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "ultrafast", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "ultrafast", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "ultrafast", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "superfast", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "superfast", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "superfast", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "veryfast", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "veryfast", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "veryfast", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "faster", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "faster", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "faster", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "fast", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "fast", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "fast", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "medium", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "medium", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "medium", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "balanced", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "slow", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "slow", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "slow", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "slower", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "slower", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "slower", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "slowest", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "slowest", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "slowest", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "av1_amf", preset: "placebo", quality: 15, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "15", "-qp_p", "15"}},
		{name: "av1_amf", preset: "placebo", quality: 23, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "23", "-qp_p", "23"}},
		{name: "av1_amf", preset: "placebo", quality: 40, want: []string{"-c:v", "av1_amf", "-quality", "quality", "-rc", "cqp", "-qp_i", "40", "-qp_p", "40"}},
		{name: "h264_qsv", preset: "veryslow", quality: 1, want: []string{"-c:v", "h264_qsv", "-preset", "veryslow", "-global_quality", "1"}},
		{name: "h264_qsv", preset: "veryslow", quality: 23, want: []string{"-c:v", "h264_qsv", "-preset", "veryslow", "-global_quality", "23"}},
		{name: "h264_qsv", preset: "veryslow", quality: 51, want: []string{"-c:v", "h264_qsv", "-preset", "veryslow", "-global_quality", "51"}},
		{name: "h264_qsv", preset: "slower", quality: 1, want: []string{"-c:v", "h264_qsv", "-preset", "slower", "-global_quality", "1"}},
		{name: "h264_qsv", preset: "slower", quality: 23, want: []string{"-c:v", "h264_qsv", "-preset", "slower", "-global_quality", "23"}},
		{name: "h264_qsv", preset: "slower", quality: 51, want: []string{"-c:v", "h264_qsv", "-preset", "slower", "-global_quality", "51"}},
		{name: "h264_qsv", preset: "slow", quality: 1, want: []string{"-c:v", "h264_qsv", "-preset", "slow", "-global_quality", "1"}},
		{name: "h264_qsv", preset: "slow", quality: 23, want: []string{"-c:v", "h264_qsv", "-preset", "slow", "-global_quality", "23"}},
		{name: "h264_qsv", preset: "slow", quality: 51, want: []string{"-c:v", "h264_qsv", "-preset", "slow", "-global_quality", "51"}},
		{name: "h264_qsv", preset: "medium", quality: 1, want: []string{"-c:v", "h264_qsv", "-preset", "medium", "-global_quality", "1"}},
		{name: "h264_qsv", preset: "medium", quality: 23, want: []string{"-c:v", "h264_qsv", "-preset", "medium", "-global_quality", "23"}},
		{name: "h264_qsv", preset: "medium", quality: 51, want: []string{"-c:v", "h264_qsv", "-preset", "medium", "-global_quality", "51"}},
		{name: "h264_qsv", preset: "fast", quality: 1, want: []string{"-c:v", "h264_qsv", "-preset", "fast", "-global_quality", "1"}},
		{name: "h264_qsv", preset: "fast", quality: 23, want: []string{"-c:v", "h264_qsv", "-preset", "fast", "-global_quality", "23"}},
		{name: "h264_qsv", preset: "fast", quality: 51, want: []string{"-c:v", "h264_qsv", "-preset", "fast", "-global_quality", "51"}},
		{name: "h264_qsv", preset: "faster", quality: 1, want: []string{"-c:v", "h264_qsv", "-preset", "faster", "-global_quality", "1"}},
		{name: "h264_qsv", preset: "faster", quality: 23, want: []string{"-c:v", "h264_qsv", "-preset", "faster", "-global_quality", "23"}},
		{name: "h264_qsv", preset: "faster", quality: 51, want: []string{"-c:v", "h264_qsv", "-preset", "faster", "-global_quality", "51"}},
		{name: "h264_qsv", preset: "veryfast", quality: 1, want: []string{"-c:v", "h264_qsv", "-preset", "veryfast", "-global_quality", "1"}},
		{name: "h264_qsv", preset: "veryfast", quality: 23, want: []string{"-c:v", "h264_qsv", "-preset", "veryfast", "-global_quality", "23"}},
		{name: "h264_qsv", preset: "veryfast", quality: 51, want: []string{"-c:v", "h264_qsv", "-preset", "veryfast", "-global_quality", "51"}},
		{name: "hevc_qsv", preset: "veryslow", quality: 1, want: []string{"-c:v", "hevc_qsv", "-preset", "veryslow", "-global_quality", "1"}},
		{name: "hevc_qsv", preset: "veryslow", quality: 23, want: []string{"-c:v", "hevc_qsv", "-preset", "veryslow", "-global_quality", "23"}},
		{name: "hevc_qsv", preset: "veryslow", quality: 51, want: []string{"-c:v", "hevc_qsv", "-preset", "veryslow", "-global_quality", "51"}},
		{name: "hevc_qsv", preset: "slower", quality: 1, want: []string{"-c:v", "hevc_qsv", "-preset", "slower", "-global_quality", "1"}},
		{name: "hevc_qsv", preset: "slower", quality: 23, want: []string{"-c:v", "hevc_qsv", "-preset", "slower", "-global_quality", "23"}},
		{name: "hevc_qsv", preset: "slower", quality: 51, want: []string{"-c:v", "hevc_qsv", "-preset", "slower", "-global_quality", "51"}},
		{name: "hevc_qsv", preset: "slow", quality: 1, want: []string{"-c:v", "hevc_qsv", "-preset", "slow", "-global_quality", "1"}},
		{name: "hevc_qsv", preset: "slow", quality: 23, want: []string{"-c:v", "hevc_qsv", "-preset", "slow", "-global_quality", "23"}},
		{name: "hevc_qsv", preset: "slow", quality: 51, want: []string{"-c:v", "hevc_qsv", "-preset", "slow", "-global_quality", "51"}},
		{name: "hevc_qsv", preset: "medium", quality: 1, want: []string{"-c:v", "hevc_qsv", "-preset", "medium", "-global_quality", "1"}},
		{name: "hevc_qsv", preset: "medium", quality: 23, want: []string{"-c:v", "hevc_qsv", "-preset", "medium", "-global_quality", "23"}},
		{name: "hevc_qsv", preset: "medium", quality: 51, want: []string{"-c:v", "hevc_qsv", "-preset", "medium", "-global_quality", "51"}},
		{name: "hevc_qsv", preset: "fast", quality: 1, want: []string{"-c:v", "hevc_qsv", "-preset", "fast", "-global_quality", "1"}},
		{name: "hevc_qsv", preset: "fast", quality: 23, want: []string{"-c:v", "hevc_qsv", "-preset", "fast", "-global_quality", "23"}},
		{name: "hevc_qsv", preset: "fast", quality: 51, want: []string{"-c:v", "hevc_qsv", "-preset", "fast", "-global_quality", "51"}},
		{name: "hevc_qsv", preset: "faster", quality: 1, want: []string{"-c:v", "hevc_qsv", "-preset", "faster", "-global_quality", "1"}},
		{name: "hevc_qsv", preset: "faster", quality: 23, want: []string{"-c:v", "hevc_qsv", "-preset", "faster", "-global_quality", "23"}},
		{name: "hevc_qsv", preset: "faster", quality: 51, want: []string{"-c:v", "hevc_qsv", "-preset", "faster", "-global_quality", "51"}},
		{name: "hevc_qsv", preset: "veryfast", quality: 1, want: []string{"-c:v", "hevc_qsv", "-preset", "veryfast", "-global_quality", "1"}},
		{name: "hevc_qsv", preset: "veryfast", quality: 23, want: []string{"-c:v", "hevc_qsv", "-preset", "veryfast", "-global_quality", "23"}},
		{name: "hevc_qsv", preset: "veryfast", quality: 51, want: []string{"-c:v", "hevc_qsv", "-preset", "veryfast", "-global_quality", "51"}},
		{name: "av1_qsv", preset: "veryslow", quality: 1, want: []string{"-c:v", "av1_qsv", "-preset", "veryslow", "-global_quality", "1"}},
		{name: "av1_qsv", preset: "veryslow", quality: 23, want: []string{"-c:v", "av1_qsv", "-preset", "veryslow", "-global_quality", "23"}},
		{name: "av1_qsv", preset: "veryslow", quality: 51, want: []string{"-c:v", "av1_qsv", "-preset", "veryslow", "-global_quality", "51"}},
		{name: "av1_qsv", preset: "slower", quality: 1, want: []string{"-c:v", "av1_qsv", "-preset", "slower", "-global_quality", "1"}},
		{name: "av1_qsv", preset: "slower", quality: 23, want: []string{"-c:v", "av1_qsv", "-preset", "slower", "-global_quality", "23"}},
		{name: "av1_qsv", preset: "slower", quality: 51, want: []string{"-c:v", "av1_qsv", "-preset", "slower", "-global_quality", "51"}},
		{name: "av1_qsv", preset: "slow", quality: 1, want: []string{"-c:v", "av1_qsv", "-preset", "slow", "-global_quality", "1"}},
		{name: "av1_qsv", preset: "slow", quality: 23, want: []string{"-c:v", "av1_qsv", "-preset", "slow", "-global_quality", "23"}},
		{name: "av1_qsv", preset: "slow", quality: 51, want: []string{"-c:v", "av1_qsv", "-preset", "slow", "-global_quality", "51"}},
		{name: "av1_qsv", preset: "medium", quality: 1, want: []string{"-c:v", "av1_qsv", "-preset", "medium", "-global_quality", "1"}},
		{name: "av1_qsv", preset: "medium", quality: 23, want: []string{"-c:v", "av1_qsv", "-preset", "medium", "-global_quality", "23"}},
		{name: "av1_qsv", preset: "medium", quality: 51, want: []string{"-c:v", "av1_qsv", "-preset", "medium", "-global_quality", "51"}},
		{name: "av1_qsv", preset: "fast", quality: 1, want: []string{"-c:v", "av1_qsv", "-preset", "fast", "-global_quality", "1"}},
		{name: "av1_qsv", preset: "fast", quality: 23, want: []string{"-c:v", "av1_qsv", "-preset", "fast", "-global_quality", "23"}},
		{name: "av1_qsv", preset: "fast", quality: 51, want: []string{"-c:v", "av1_qsv", "-preset", "fast", "-global_quality", "51"}},
		{name: "av1_qsv", preset: "faster", quality: 1, want: []string{"-c:v", "av1_qsv", "-preset", "faster", "-global_quality", "1"}},
		{name: "av1_qsv", preset: "faster", quality: 23, want: []string{"-c:v", "av1_qsv", "-preset", "faster", "-global_quality", "23"}},
		{name: "av1_qsv", preset: "faster", quality: 51, want: []string{"-c:v", "av1_qsv", "-preset", "faster", "-global_quality", "51"}},
		{name: "av1_qsv", preset: "veryfast", quality: 1, want: []string{"-c:v", "av1_qsv", "-preset", "veryfast", "-global_quality", "1"}},
		{name: "av1_qsv", preset: "veryfast", quality: 23, want: []string{"-c:v", "av1_qsv", "-preset", "veryfast", "-global_quality", "23"}},
		{name: "av1_qsv", preset: "veryfast", quality: 51, want: []string{"-c:v", "av1_qsv", "-preset", "veryfast", "-global_quality", "51"}},
		{name: "h264_videotoolbox", preset: "ultrafast", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "ultrafast", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "ultrafast", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "superfast", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "superfast", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "superfast", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "veryfast", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "veryfast", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "veryfast", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "faster", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "faster", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "faster", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "fast", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "fast", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "fast", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "medium", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "medium", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "medium", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "slow", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "slow", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "slow", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "slower", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "slower", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "slower", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "h264_videotoolbox", preset: "veryslow", quality: 0, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "h264_videotoolbox", preset: "veryslow", quality: 50, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "h264_videotoolbox", preset: "veryslow", quality: 100, want: []string{"-c:v", "h264_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "ultrafast", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "ultrafast", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "ultrafast", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "superfast", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "superfast", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "superfast", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "veryfast", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "veryfast", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "veryfast", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "faster", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "faster", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "faster", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "fast", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "fast", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "fast", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "1", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "medium", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "medium", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "medium", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "slow", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "slow", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "slow", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "slower", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "slower", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "slower", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "hevc_videotoolbox", preset: "veryslow", quality: 0, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "0"}},
		{name: "hevc_videotoolbox", preset: "veryslow", quality: 50, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "50"}},
		{name: "hevc_videotoolbox", preset: "veryslow", quality: 100, want: []string{"-c:v", "hevc_videotoolbox", "-realtime", "0", "-q:v", "100"}},
		{name: "prores_videotoolbox", preset: "ultrafast", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "ultrafast", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "ultrafast", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "ultrafast", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "ultrafast", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "ultrafast", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "superfast", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "superfast", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "superfast", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "superfast", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "superfast", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "superfast", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "veryfast", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "veryfast", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "veryfast", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "veryfast", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "veryfast", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "veryfast", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "faster", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "faster", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "faster", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "faster", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "faster", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "faster", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "fast", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "fast", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "fast", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "fast", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "fast", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "fast", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "1", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "medium", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "medium", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "medium", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "medium", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "medium", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "medium", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "slow", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "slow", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "slow", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "slow", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "slow", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "slow", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "slower", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "slower", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "slower", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "slower", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "slower", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "slower", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "xq"}},
		{name: "prores_videotoolbox", preset: "veryslow", quality: 0, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "proxy"}},
		{name: "prores_videotoolbox", preset: "veryslow", quality: 1, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "lt"}},
		{name: "prores_videotoolbox", preset: "veryslow", quality: 2, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "standard"}},
		{name: "prores_videotoolbox", preset: "veryslow", quality: 3, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "hq"}},
		{name: "prores_videotoolbox", preset: "veryslow", quality: 4, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "4444"}},
		{name: "prores_videotoolbox", preset: "veryslow", quality: 5, want: []string{"-c:v", "prores_videotoolbox", "-realtime", "0", "-profile:v", "xq"}},
		{name: "av1_videotoolbox", preset: "ultrafast", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "ultrafast", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "ultrafast", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "superfast", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "superfast", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "superfast", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "veryfast", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "veryfast", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "veryfast", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "faster", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "faster", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "faster", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "fast", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "fast", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "fast", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "medium", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "medium", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "medium", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "slow", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "slow", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "slow", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "slower", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "slower", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "slower", quality: 100, wantErr: true},
		{name: "av1_videotoolbox", preset: "veryslow", quality: 0, wantErr: true},
		{name: "av1_videotoolbox", preset: "veryslow", quality: 50, wantErr: true},
		{name: "av1_videotoolbox", preset: "veryslow", quality: 100, wantErr: true},
	} {
		tc := tc
		t.Run(fmt.Sprintf("%s/%s/%d", tc.name, tc.preset, tc.quality), func(t *testing.T) {
			t.Parallel()
			a, err := Get(tc.name)
			if err != nil {
				t.Fatalf("Get(%q): %v", tc.name, err)
			}
			got, argErr := a.FFmpegCodecArgs(tc.preset, tc.quality)
			if tc.wantErr {
				if argErr == nil {
					t.Errorf("expected an error, got argv %v", got)
				}
				return
			}
			if argErr != nil {
				t.Fatalf("FFmpegCodecArgs: %v", argErr)
			}
			if !slices.Equal(got, tc.want) {
				t.Errorf("argv mismatch\n got: %v\nwant: %v (Python)", got, tc.want)
			}
		})
	}
}

// TestTwoPassArgs_matchesPythonAdapters pins the 2-pass argv shape per codec.
// libx265 carries its pass state in -x265-params; everything else that supports
// 2-pass uses ffmpeg's generic pair.
func TestTwoPassArgs_matchesPythonAdapters(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name string
		want []string
	}{
		{"libx264", []string{"-pass", "1", "-passlogfile", "/tmp/s"}},
		{"libx265", []string{"-x265-params", "pass=1:stats=/tmp/s"}},
		{"libaom-av1", []string{"-pass", "1", "-passlogfile", "/tmp/s"}},
		{"libvpx-vp9", []string{"-pass", "1", "-passlogfile", "/tmp/s"}},
		{"libvvenc", []string{"-pass", "1", "-passlogfile", "/tmp/s"}},
	} {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			a, err := Get(tc.name)
			if err != nil {
				t.Fatalf("Get(%q): %v", tc.name, err)
			}
			got, err := a.TwoPassArgs(1, "/tmp/s")
			if err != nil {
				t.Fatalf("TwoPassArgs: %v", err)
			}
			if !slices.Equal(got, tc.want) {
				t.Errorf("two-pass argv mismatch\n got: %v\nwant: %v (Python)", got, tc.want)
			}
		})
	}
}
