apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmafx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vmafx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vmafx.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  {{- range .Values.service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
