{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vmafx.fullname" . }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "vmafx.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "vmafx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.monitoring.serviceMonitor.honorLabels }}
{{- end }}
