#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Derive praetor's exception inputs from the repository's own sources of truth.

Praetor's gate (``praetorctl audit``, ``praetorctl ci tidy-coverage``) reads a lane file list and
the ``exceptions`` list of ``.standards.yaml``. The repository already records the same facts once:
the units each lane measured (``measured_sources`` of ``scripts/ci/tidy-baseline-*.json``) and the
declared exceptions (``.config/lint-exceptions.d/clang-tidy-coverage.toml``, checked by
``scripts/ci/check-tidy-coverage.py``). This script writes both praetor inputs from them, so there
is one list and two renderings (HISS-19), and ``--check`` fails when a rendering is stale.

The same block carries the repository list's entries for the praetor rules in ``PRAETOR_RULES``
(``.config/lint-exceptions.d/HISS-11.toml``: a supply-chain gap the audit measures), with the same
expiry cap, because praetor reads one ``exceptions`` key.

  .config/clang-tidy/measured-sources.txt   the union of every lane's measured_sources
  .standards.yaml                           the block between the BEGIN/END markers below

Praetor refuses an exception that expires more than 90 days out, so each rendered entry expires
on the earlier of its own date and ``PRAETOR_EXPIRY_CAP``; renew the cap with the entries.

Usage: praetor_tidy_coverage.py [--write | --check]    (default --check)
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import lint_exceptions  # noqa: E402 -- the shared exception list reader

LANE_FILE = Path(".config/clang-tidy/measured-sources.txt")
MANIFEST = Path(".standards.yaml")
BEGIN = "# BEGIN generated by scripts/ci/praetor_tidy_coverage.py: do not edit by hand"
END = "# END generated by scripts/ci/praetor_tidy_coverage.py"
RULE = "clang-tidy-coverage"
# Praetor rules whose repository-list entries this block copies (expiry capped as below).
PRAETOR_RULES = ("HISS-11",)
# Praetor counts these suffixes as translation units (internal/tidycoverage); `.metal` is not one.
PRAETOR_UNITS = (".c", ".cc", ".cpp", ".cxx", ".c++", ".cppm", ".cu", ".hip", ".mm")
# The latest date praetor accepts for an exception written on 2026-10-06 (90 days).
PRAETOR_EXPIRY_CAP = datetime.date(2027, 1, 4)
DATA_PREFIX = "scripts/ci/exact_twins.d/"
DATA_REASON = (
    "Parity-gate data fragment that borrows the .hip extension (ADR-1428): one line of fields, "
    "no C or HIP source, nothing for clang-tidy to read."
)
INCLUDED_HEADERS = {
    "core/src/feature/hip/integer_adm/adm_decouple_inline.hip": (
        "A header named like a HIP unit: adm_cm.hip and adm_csf.hip include it and clang-tidy "
        "reads it through them (core/src/feature/hip/integer_adm/AGENTS.d)."
    )
}


def tracked_units(root: Path) -> list[str]:
    tracked = lint_exceptions.tracked_files(root)
    return sorted(p for p in tracked if p.lower().endswith(PRAETOR_UNITS))


def measured(root: Path) -> list[str]:
    seen: set[str] = set()
    for path in sorted((root / "scripts/ci").glob("tidy-baseline-*.json")):
        seen.update(json.loads(path.read_text(encoding="utf-8")).get("measured_sources", []))
    return sorted(seen)


def exceptions(root: Path) -> list[tuple[str, str, datetime.date]]:
    """(path, reason, expiry) of every tracked unit no lane measures, from the repository's lists."""
    entries, _ = lint_exceptions.load(root)
    declared = {e.path: (e.reason, e.expires) for e in entries if e.rule == RULE}
    covered = set(measured(root))
    out: list[tuple[str, str, datetime.date]] = []
    for unit in tracked_units(root):
        if unit in covered:
            continue
        if unit.startswith(DATA_PREFIX):
            reason, expires = DATA_REASON, PRAETOR_EXPIRY_CAP
        elif unit in INCLUDED_HEADERS:
            reason, expires = INCLUDED_HEADERS[unit], PRAETOR_EXPIRY_CAP
        elif unit in declared:
            reason, expires = declared[unit]
        else:
            continue  # a unit nobody covers or excuses: check-tidy-coverage.py names it
        out.append((unit, " ".join(reason.split()), min(expires, PRAETOR_EXPIRY_CAP)))
    return out


def declared(root: Path) -> list[tuple[str, str, str, datetime.date]]:
    """(rule, path, reason, expiry) of the repository list's entries for ``PRAETOR_RULES``."""
    entries, _ = lint_exceptions.load(root)
    return sorted(
        (e.rule, e.path, " ".join(e.reason.split()), min(e.expires, PRAETOR_EXPIRY_CAP))
        for e in entries
        if e.rule in PRAETOR_RULES
    )


def render_block(root: Path) -> str:
    lines = [BEGIN, "exceptions:"]
    rows = declared(root) + [(RULE, *entry) for entry in exceptions(root)]
    for rule, path, reason, expires in rows:
        quoted = reason.replace("\\", "\\\\").replace('"', '\\"')
        lines += [
            f"  - rule: {rule}",
            f'    path: "{path}"',
            f'    reason: "{quoted}"',
            f'    expires: "{expires.isoformat()}"',
        ]
    lines.append(END)
    return "\n".join(lines) + "\n"


def rewrite(manifest: str, block: str) -> str:
    """The manifest text with the generated block replaced (or appended when absent)."""
    if BEGIN in manifest and END in manifest:
        head, rest = manifest.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail.removeprefix("\n")
    return manifest.rstrip("\n") + "\n" + block


def render(root: Path) -> dict[Path, str]:
    manifest = (root / MANIFEST).read_text(encoding="utf-8")
    return {
        LANE_FILE: "\n".join(measured(root)) + "\n",
        MANIFEST: rewrite(manifest, render_block(root)),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=ROOT)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root: Path = args.root
    try:
        wanted = render(root)
    except (OSError, ValueError, SystemExit) as exc:
        print(f"praetor-tidy-coverage: {exc}", file=sys.stderr)
        return 2
    stale = [
        p
        for p, text in wanted.items()
        if not (root / p).is_file() or (root / p).read_text(encoding="utf-8") != text
    ]
    if args.write:
        for p in stale:
            (root / p).parent.mkdir(parents=True, exist_ok=True)
            (root / p).write_text(wanted[p], encoding="utf-8")
            print(f"praetor-tidy-coverage: wrote {p}")
        return 0
    for p in stale:
        print(
            f"praetor-tidy-coverage: {p} is stale; run scripts/ci/praetor_tidy_coverage.py --write"
        )
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
