// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package pgdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelJob = `-- name: CancelJob :one
WITH prev AS (
    SELECT j.id, j.status FROM jobs j
    WHERE j.id = $1 AND j.tenant_id = $2 AND j.status IN ('pending', 'running')
    FOR UPDATE
)
UPDATE jobs
SET status = 'cancelled', lease_session = NULL, lease_expires_at = NULL,
    finished_at = now(), updated_at = now()
FROM prev
WHERE jobs.id = prev.id
RETURNING jobs.attempt, prev.status AS previous_status
`

type CancelJobParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID string    `json:"tenant_id"`
}

type CancelJobRow struct {
	Attempt        int32  `json:"attempt"`
	PreviousStatus string `json:"previous_status"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (CancelJobRow, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.ID, arg.TenantID)
	var i CancelJobRow
	err := row.Scan(&i.Attempt, &i.PreviousStatus)
	return i, err
}

const cancelledAmong = `-- name: CancelledAmong :many
SELECT id FROM jobs
WHERE tenant_id = $1 AND status = 'cancelled' AND id = ANY($2::uuid[])
`

type CancelledAmongParams struct {
	TenantID string      `json:"tenant_id"`
	Ids      []uuid.UUID `json:"ids"`
}

func (q *Queries) CancelledAmong(ctx context.Context, arg CancelledAmongParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, cancelledAmong, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActive = `-- name: CountActive :many
SELECT status, backend, count(*)::bigint AS jobs
FROM jobs
WHERE status IN ('pending', 'running')
GROUP BY status, backend
ORDER BY status, backend
`

type CountActiveRow struct {
	Status  string `json:"status"`
	Backend string `json:"backend"`
	Jobs    int64  `json:"jobs"`
}

func (q *Queries) CountActive(ctx context.Context) ([]CountActiveRow, error) {
	rows, err := q.db.Query(ctx, countActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveRow{}
	for rows.Next() {
		var i CountActiveRow
		if err := rows.Scan(&i.Status, &i.Backend, &i.Jobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, tenant_id, idempotency_key, status, spec, backend, priority, attempt, lost_attempts, max_lost_attempts, available_at, lease_session, assigned_node, lease_expires_at, score, features, error, created_at, updated_at, finished_at FROM jobs WHERE id = $1 AND tenant_id = $2
`

type GetJobParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID string    `json:"tenant_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.TenantID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Spec,
		&i.Backend,
		&i.Priority,
		&i.Attempt,
		&i.LostAttempts,
		&i.MaxLostAttempts,
		&i.AvailableAt,
		&i.LeaseSession,
		&i.AssignedNode,
		&i.LeaseExpiresAt,
		&i.Score,
		&i.Features,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, tenant_id, idempotency_key, status, spec, backend, priority, attempt, lost_attempts, max_lost_attempts, available_at, lease_session, assigned_node, lease_expires_at, score, features, error, created_at, updated_at, finished_at FROM jobs WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetJobByIdempotencyKeyParams struct {
	TenantID       string  `json:"tenant_id"`
	IdempotencyKey *string `json:"idempotency_key"`
}

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Spec,
		&i.Backend,
		&i.Priority,
		&i.Attempt,
		&i.LostAttempts,
		&i.MaxLostAttempts,
		&i.AvailableAt,
		&i.LeaseSession,
		&i.AssignedNode,
		&i.LeaseExpiresAt,
		&i.Score,
		&i.Features,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const importJob = `-- name: ImportJob :execrows
INSERT INTO jobs (id, tenant_id, status, spec, backend, assigned_node, score, features, error,
                  created_at, updated_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12)
ON CONFLICT (id) DO NOTHING
`

type ImportJobParams struct {
	ID           uuid.UUID  `json:"id"`
	TenantID     string     `json:"tenant_id"`
	Status       string     `json:"status"`
	Spec         []byte     `json:"spec"`
	Backend      string     `json:"backend"`
	AssignedNode *string    `json:"assigned_node"`
	Score        *float64   `json:"score"`
	Features     []byte     `json:"features"`
	Error        *string    `json:"error"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	FinishedAt   *time.Time `json:"finished_at"`
}

func (q *Queries) ImportJob(ctx context.Context, arg ImportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, importJob,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Spec,
		arg.Backend,
		arg.AssignedNode,
		arg.Score,
		arg.Features,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (id, tenant_id, idempotency_key, spec, backend, priority, max_lost_attempts)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, tenant_id, idempotency_key, status, spec, backend, priority, attempt, lost_attempts, max_lost_attempts, available_at, lease_session, assigned_node, lease_expires_at, score, features, error, created_at, updated_at, finished_at
`

type InsertJobParams struct {
	ID              uuid.UUID `json:"id"`
	TenantID        string    `json:"tenant_id"`
	IdempotencyKey  *string   `json:"idempotency_key"`
	Spec            []byte    `json:"spec"`
	Backend         string    `json:"backend"`
	Priority        int32     `json:"priority"`
	MaxLostAttempts int32     `json:"max_lost_attempts"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.ID,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Spec,
		arg.Backend,
		arg.Priority,
		arg.MaxLostAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Spec,
		&i.Backend,
		&i.Priority,
		&i.Attempt,
		&i.LostAttempts,
		&i.MaxLostAttempts,
		&i.AvailableAt,
		&i.LeaseSession,
		&i.AssignedNode,
		&i.LeaseExpiresAt,
		&i.Score,
		&i.Features,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, tenant_id, idempotency_key, status, spec, backend, priority, attempt, lost_attempts, max_lost_attempts, available_at, lease_session, assigned_node, lease_expires_at, score, features, error, created_at, updated_at, finished_at FROM jobs
WHERE tenant_id = $1
  AND (cardinality($2::text[]) = 0 OR status = ANY($2::text[]))
ORDER BY created_at, id
LIMIT $3
`

type ListJobsParams struct {
	TenantID string   `json:"tenant_id"`
	Statuses []string `json:"statuses"`
	MaxRows  int32    `json:"max_rows"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.TenantID, arg.Statuses, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.Spec,
			&i.Backend,
			&i.Priority,
			&i.Attempt,
			&i.LostAttempts,
			&i.MaxLostAttempts,
			&i.AvailableAt,
			&i.LeaseSession,
			&i.AssignedNode,
			&i.LeaseExpiresAt,
			&i.Score,
			&i.Features,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyJobs = `-- name: NotifyJobs :exec
SELECT pg_notify('vmafx_jobs', $1::text)
`

func (q *Queries) NotifyJobs(ctx context.Context, backend string) error {
	_, err := q.db.Exec(ctx, notifyJobs, backend)
	return err
}

const setMaintenance = `-- name: SetMaintenance :exec
SELECT set_config('vmafx.maintenance', 'on', true)
`

func (q *Queries) SetMaintenance(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setMaintenance)
	return err
}

const setTenant = `-- name: SetTenant :exec

SELECT set_config('vmafx.tenant_id', $1::text, true)
`

// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris
//
// Job queries of the PostgreSQL store (sqlc input, ADR-2350 D2). Every tenant
// query names the tenant in its WHERE clause; row-level security is the
// second wall, not the first.
func (q *Queries) SetTenant(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, setTenant, tenantID)
	return err
}

const tenantStats = `-- name: TenantStats :many
SELECT tenant_id, status, count(*)::bigint AS jobs, min(created_at)::timestamptz AS oldest
FROM jobs
WHERE status IN ('pending', 'running')
GROUP BY tenant_id, status
ORDER BY tenant_id, status
`

type TenantStatsRow struct {
	TenantID string    `json:"tenant_id"`
	Status   string    `json:"status"`
	Jobs     int64     `json:"jobs"`
	Oldest   time.Time `json:"oldest"`
}

func (q *Queries) TenantStats(ctx context.Context) ([]TenantStatsRow, error) {
	rows, err := q.db.Query(ctx, tenantStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantStatsRow{}
	for rows.Next() {
		var i TenantStatsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Status,
			&i.Jobs,
			&i.Oldest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
