// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const claimNext = `-- name: ClaimNext :one

WITH next AS (
    SELECT j.id FROM jobs j
    WHERE j.tenant_id = $4
      AND j.status = 'pending'
      AND j.available_at <= now()
      AND (j.backend = '' OR j.backend = ANY($5::text[]))
    ORDER BY j.priority DESC, j.created_at, j.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET status = 'running', attempt = jobs.attempt + 1, lease_session = $1::uuid,
    lease_node = $2::text, lease_expires_at = now() + make_interval(secs => $3::float8),
    updated_at = now()
FROM next
WHERE jobs.id = next.id
RETURNING jobs.id, jobs.tenant_id, jobs.idempotency_key, jobs.status, jobs.spec, jobs.backend, jobs.priority, jobs.attempt, jobs.lost_attempts, jobs.max_lost_attempts, jobs.available_at, jobs.lease_session, jobs.lease_node, jobs.lease_expires_at, jobs.score, jobs.features, jobs.error, jobs.created_at, jobs.updated_at, jobs.finished_at
`

type ClaimNextParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	NodeID       string    `json:"node_id"`
	LeaseSeconds float64   `json:"lease_seconds"`
	TenantID     string    `json:"tenant_id"`
	Backends     []string  `json:"backends"`
}

// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris
//
// Leased claims of node work (sqlc input, ADR-2350 D2). The attempt number is
// the fencing token: every write of a running attempt compares it together
// with the session that holds the lease.
func (q *Queries) ClaimNext(ctx context.Context, arg ClaimNextParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimNext,
		arg.SessionID,
		arg.NodeID,
		arg.LeaseSeconds,
		arg.TenantID,
		arg.Backends,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Spec,
		&i.Backend,
		&i.Priority,
		&i.Attempt,
		&i.LostAttempts,
		&i.MaxLostAttempts,
		&i.AvailableAt,
		&i.LeaseSession,
		&i.LeaseNode,
		&i.LeaseExpiresAt,
		&i.Score,
		&i.Features,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const endAttempt = `-- name: EndAttempt :exec
UPDATE job_attempts
SET ended_at = now(), outcome = $1::text, error = $2
WHERE job_id = $3 AND attempt = $4 AND ended_at IS NULL
`

type EndAttemptParams struct {
	Outcome string    `json:"outcome"`
	Error   *string   `json:"error"`
	JobID   uuid.UUID `json:"job_id"`
	Attempt int32     `json:"attempt"`
}

func (q *Queries) EndAttempt(ctx context.Context, arg EndAttemptParams) error {
	_, err := q.db.Exec(ctx, endAttempt,
		arg.Outcome,
		arg.Error,
		arg.JobID,
		arg.Attempt,
	)
	return err
}

const expiredLeases = `-- name: ExpiredLeases :many
SELECT id, tenant_id, attempt, lost_attempts, max_lost_attempts FROM jobs
WHERE status = 'running' AND lease_expires_at < now()
ORDER BY lease_expires_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ExpiredLeasesRow struct {
	ID              uuid.UUID `json:"id"`
	TenantID        string    `json:"tenant_id"`
	Attempt         int32     `json:"attempt"`
	LostAttempts    int32     `json:"lost_attempts"`
	MaxLostAttempts int32     `json:"max_lost_attempts"`
}

func (q *Queries) ExpiredLeases(ctx context.Context, maxRows int32) ([]ExpiredLeasesRow, error) {
	rows, err := q.db.Query(ctx, expiredLeases, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredLeasesRow{}
	for rows.Next() {
		var i ExpiredLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Attempt,
			&i.LostAttempts,
			&i.MaxLostAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const extendLeases = `-- name: ExtendLeases :execrows
UPDATE jobs
SET lease_expires_at = now() + make_interval(secs => $1::float8), updated_at = now()
WHERE tenant_id = $2 AND lease_session = $3::uuid AND status = 'running'
  AND id = ANY($4::uuid[])
`

type ExtendLeasesParams struct {
	LeaseSeconds float64     `json:"lease_seconds"`
	TenantID     string      `json:"tenant_id"`
	SessionID    uuid.UUID   `json:"session_id"`
	Ids          []uuid.UUID `json:"ids"`
}

func (q *Queries) ExtendLeases(ctx context.Context, arg ExtendLeasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendLeases,
		arg.LeaseSeconds,
		arg.TenantID,
		arg.SessionID,
		arg.Ids,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failExpired = `-- name: FailExpired :exec
UPDATE jobs
SET status = 'failed', lost_attempts = lost_attempts + 1, error = $1::text,
    lease_session = NULL, lease_node = NULL, lease_expires_at = NULL,
    finished_at = now(), updated_at = now()
WHERE id = $2 AND attempt = $3 AND status = 'running'
`

type FailExpiredParams struct {
	Error   string    `json:"error"`
	ID      uuid.UUID `json:"id"`
	Attempt int32     `json:"attempt"`
}

func (q *Queries) FailExpired(ctx context.Context, arg FailExpiredParams) error {
	_, err := q.db.Exec(ctx, failExpired, arg.Error, arg.ID, arg.Attempt)
	return err
}

const finishAttempt = `-- name: FinishAttempt :execrows
UPDATE jobs
SET status = $1, score = $2, features = $3,
    error = $4, lease_session = NULL, lease_node = NULL, lease_expires_at = NULL,
    finished_at = now(), updated_at = now()
WHERE id = $5 AND tenant_id = $6 AND attempt = $7 AND status = 'running'
  AND lease_session = $8::uuid
`

type FinishAttemptParams struct {
	Status    string    `json:"status"`
	Score     *float64  `json:"score"`
	Features  []byte    `json:"features"`
	Error     *string   `json:"error"`
	ID        uuid.UUID `json:"id"`
	TenantID  string    `json:"tenant_id"`
	Attempt   int32     `json:"attempt"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAttempt,
		arg.Status,
		arg.Score,
		arg.Features,
		arg.Error,
		arg.ID,
		arg.TenantID,
		arg.Attempt,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttempt = `-- name: GetAttempt :one
SELECT job_id, attempt, tenant_id, session_id, node_id, started_at, ended_at, outcome, error FROM job_attempts WHERE job_id = $1 AND attempt = $2 AND tenant_id = $3
`

type GetAttemptParams struct {
	JobID    uuid.UUID `json:"job_id"`
	Attempt  int32     `json:"attempt"`
	TenantID string    `json:"tenant_id"`
}

func (q *Queries) GetAttempt(ctx context.Context, arg GetAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, arg.JobID, arg.Attempt, arg.TenantID)
	var i JobAttempt
	err := row.Scan(
		&i.JobID,
		&i.Attempt,
		&i.TenantID,
		&i.SessionID,
		&i.NodeID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.Error,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO job_attempts (job_id, attempt, tenant_id, session_id, node_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAttemptParams struct {
	JobID     uuid.UUID `json:"job_id"`
	Attempt   int32     `json:"attempt"`
	TenantID  string    `json:"tenant_id"`
	SessionID uuid.UUID `json:"session_id"`
	NodeID    string    `json:"node_id"`
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.JobID,
		arg.Attempt,
		arg.TenantID,
		arg.SessionID,
		arg.NodeID,
	)
	return err
}

const releaseAttempt = `-- name: ReleaseAttempt :execrows
UPDATE jobs
SET status = 'pending', lease_session = NULL, lease_node = NULL, lease_expires_at = NULL,
    available_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND attempt = $3 AND status = 'running'
  AND lease_session = $4::uuid
`

type ReleaseAttemptParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  string    `json:"tenant_id"`
	Attempt   int32     `json:"attempt"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) ReleaseAttempt(ctx context.Context, arg ReleaseAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseAttempt,
		arg.ID,
		arg.TenantID,
		arg.Attempt,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueExpired = `-- name: RequeueExpired :exec
UPDATE jobs
SET status = 'pending', lost_attempts = lost_attempts + 1,
    available_at = now() + make_interval(secs => $1::float8),
    lease_session = NULL, lease_node = NULL, lease_expires_at = NULL, updated_at = now()
WHERE id = $2 AND attempt = $3 AND status = 'running'
`

type RequeueExpiredParams struct {
	DelaySeconds float64   `json:"delay_seconds"`
	ID           uuid.UUID `json:"id"`
	Attempt      int32     `json:"attempt"`
}

func (q *Queries) RequeueExpired(ctx context.Context, arg RequeueExpiredParams) error {
	_, err := q.db.Exec(ctx, requeueExpired, arg.DelaySeconds, arg.ID, arg.Attempt)
	return err
}
