// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM node_sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO node_sessions (id, tenant_id, node_id, token_sha256, capability, expires_at)
VALUES ($1, $2, $3, $4, $5,
        now() + make_interval(secs => $6::float8))
`

type InsertSessionParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       string    `json:"tenant_id"`
	NodeID         string    `json:"node_id"`
	TokenSha256    []byte    `json:"token_sha256"`
	Capability     []byte    `json:"capability"`
	SessionSeconds float64   `json:"session_seconds"`
}

// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris
//
// Node sessions (sqlc input, ADR-2350 D2). The token is stored as its SHA-256;
// a session belongs to one tenant (ADR-1522).
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.TenantID,
		arg.NodeID,
		arg.TokenSha256,
		arg.Capability,
		arg.SessionSeconds,
	)
	return err
}

const liveSession = `-- name: LiveSession :one
SELECT id, tenant_id, node_id, token_sha256, capability, created_at, last_seen_at, expires_at FROM node_sessions
WHERE id = $1 AND tenant_id = $2 AND token_sha256 = $3 AND expires_at > now()
FOR SHARE
`

type LiveSessionParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    string    `json:"tenant_id"`
	TokenSha256 []byte    `json:"token_sha256"`
}

func (q *Queries) LiveSession(ctx context.Context, arg LiveSessionParams) (NodeSession, error) {
	row := q.db.QueryRow(ctx, liveSession, arg.ID, arg.TenantID, arg.TokenSha256)
	var i NodeSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeID,
		&i.TokenSha256,
		&i.Capability,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE node_sessions
SET last_seen_at = now(), expires_at = now() + make_interval(secs => $1::float8)
WHERE id = $2 AND tenant_id = $3 AND token_sha256 = $4 AND expires_at > now()
`

type TouchSessionParams struct {
	SessionSeconds float64   `json:"session_seconds"`
	ID             uuid.UUID `json:"id"`
	TenantID       string    `json:"tenant_id"`
	TokenSha256    []byte    `json:"token_sha256"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession,
		arg.SessionSeconds,
		arg.ID,
		arg.TenantID,
		arg.TokenSha256,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
