# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
#
# GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
# Do not edit: change the definition and run
# `python3 scripts/codegen/vmafx-api.py --write`.
"""ctypes binding of the VMAFx C API (generated)."""

from __future__ import annotations

import ctypes
import enum
import os
from dataclasses import dataclass

ABI_VERSION = (0, 1, 2)


class Status(enum.IntEnum):
    """VmafxStatus codes."""

    OK = 0
    PENDING = 1
    E_INVALID = -1
    E_NOMEM = -2
    E_NOTSUP = -3
    E_NOTFOUND = -4
    E_BUSY = -5
    E_DEVICE = -6
    E_IO = -7
    E_RANGE = -8
    E_INTERNAL = -9
    E_TIMEOUT = -10
    E_ABI = -11


class LogLevel(enum.IntEnum):
    """VmafxLogLevel."""

    NONE = 0
    ERROR = 1
    WARNING = 2
    INFO = 3
    DEBUG = 4


class Backend(enum.IntEnum):
    """VmafxBackend."""

    CPU = 0
    CUDA = 1
    SYCL = 2
    METAL = 3
    HIP = 4


class PixelFormat(enum.IntEnum):
    """VmafxPixelFormat."""

    UNKNOWN = 0
    YUV420P = 1
    YUV422P = 2
    YUV444P = 3
    YUV400P = 4
    NV12 = 16
    P010 = 17
    P016 = 18


class Pool(enum.IntEnum):
    """VmafxPool."""

    NONE = 0
    MIN = 1
    MAX = 2
    MEAN = 3
    HARMONIC_MEAN = 4
    MEDIAN = 5
    PERC5 = 6
    PERC10 = 7
    PERC20 = 8


class SubjectKind(enum.IntEnum):
    """VmafxSubjectKind."""

    NONE = 0
    PARAMETER = 1
    CONTEXT = 2
    OPTION = 3
    FEATURE = 4
    EXTRACTOR = 5
    MODEL = 6
    FRAME = 7
    PLANE = 8
    DEVICE = 9
    BACKEND = 10
    PATH = 11
    FENCE = 12


class MemoryKind(enum.IntEnum):
    """VmafxMemoryKind."""

    NONE = 0
    HOST = 1
    DEVICE_POINTER = 2
    DEVICE_ARRAY = 3
    DMABUF = 4
    METAL_SURFACE = 5
    METAL_TEXTURE = 6
    WIN32_SHARED = 7


class FenceKind(enum.IntEnum):
    """VmafxFenceKind."""

    NONE = 0
    HOST = 1
    CUDA_EVENT = 2
    HIP_EVENT = 3
    SYCL_EVENT = 4
    SYNC_FILE = 5
    METAL_SHARED_EVENT = 6
    WIN32_SHARED = 7


class ModelFlags(enum.IntFlag):
    """VmafxModelFlags bits."""

    DISABLE_CLIP = 1
    ENABLE_TRANSFORM = 2
    DISABLE_TRANSFORM = 4


class ImportFlags(enum.IntFlag):
    """VmafxImportFlags bits."""

    ALLOW_COPY = 1


class DeviceFlags(enum.IntFlag):
    """VmafxDeviceFlags bits."""

    PROFILING = 1


class VmafxContextConfig(ctypes.Structure):
    """C struct VmafxContextConfig."""


class VmafxProvenance(ctypes.Structure):
    """C struct VmafxProvenance."""


class VmafxExtractorInfo(ctypes.Structure):
    """C struct VmafxExtractorInfo."""


class VmafxScore(ctypes.Structure):
    """C struct VmafxScore."""


class VmafxFeatureResolution(ctypes.Structure):
    """C struct VmafxFeatureResolution."""


class VmafxDeviceDesc(ctypes.Structure):
    """C struct VmafxDeviceDesc."""


class VmafxDeviceInfo(ctypes.Structure):
    """C struct VmafxDeviceInfo."""


class VmafxFence(ctypes.Structure):
    """C struct VmafxFence."""


class VmafxImportPlane(ctypes.Structure):
    """C struct VmafxImportPlane."""


class VmafxFrameImport(ctypes.Structure):
    """C struct VmafxFrameImport."""


class VmafxModelConfig(ctypes.Structure):
    """C struct VmafxModelConfig."""


class VmafxFrameDesc(ctypes.Structure):
    """C struct VmafxFrameDesc."""


class VmafxHostPlanes(ctypes.Structure):
    """C struct VmafxHostPlanes."""


class VmafxFramePlanes(ctypes.Structure):
    """C struct VmafxFramePlanes."""


class VmafxPooledScore(ctypes.Structure):
    """C struct VmafxPooledScore."""


class VmafxModelSetScore(ctypes.Structure):
    """C struct VmafxModelSetScore."""


VmafxLogCallback = ctypes.CFUNCTYPE(None, ctypes.c_uint32, ctypes.c_char_p, ctypes.c_void_p)


VmafxFrameReleaseCallback = ctypes.CFUNCTYPE(None, ctypes.c_void_p)


VmafxContextConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("log_level", ctypes.c_uint32),
    ("n_threads", ctypes.c_uint32),
    ("n_subsample", ctypes.c_uint32),
    ("cpumask", ctypes.c_uint64),
    ("gpumask", ctypes.c_uint64),
    ("log_callback", VmafxLogCallback),
    ("log_user", ctypes.c_void_p),
)

VmafxProvenance._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("abi_major", ctypes.c_uint32),
    ("abi_minor", ctypes.c_uint32),
    ("abi_patch", ctypes.c_uint32),
    ("active_backend", ctypes.c_uint32),
    ("n_extractors", ctypes.c_uint32),
    ("version", ctypes.c_char_p),
)

VmafxExtractorInfo._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("name", ctypes.c_char_p),
)

VmafxScore._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("index", ctypes.c_uint64),
    ("value", ctypes.c_double),
    ("feature", ctypes.c_char_p),
    ("extractor", ctypes.c_char_p),
)

VmafxFeatureResolution._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("extractor", ctypes.c_char_p),
    ("unsupported_option", ctypes.c_char_p),
)

VmafxDeviceDesc._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("index", ctypes.c_int32),
    ("flags", ctypes.c_uint32),
    ("external", ctypes.c_size_t * 2),
)

VmafxDeviceInfo._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("index", ctypes.c_int32),
    ("flags", ctypes.c_uint32),
    ("memory_kinds", ctypes.c_uint32),
    ("fence_kinds", ctypes.c_uint32),
    ("total_memory", ctypes.c_uint64),
    ("name", ctypes.c_char_p),
)

VmafxFence._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("kind", ctypes.c_uint32),
    ("handle", ctypes.c_size_t),
    ("value", ctypes.c_uint64),
    ("fd", ctypes.c_int32),
    ("reserved", ctypes.c_uint32),
)

VmafxImportPlane._fields_ = (
    ("handle", ctypes.c_size_t),
    ("fd", ctypes.c_int32),
    ("plane_index", ctypes.c_uint32),
    ("offset", ctypes.c_uint64),
    ("pitch", ctypes.c_uint64),
    ("modifier", ctypes.c_uint64),
    ("size", ctypes.c_uint64),
)

VmafxFrameImport._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("memory", ctypes.c_uint32),
    ("pix_fmt", ctypes.c_uint32),
    ("bpc", ctypes.c_uint32),
    ("w", ctypes.c_uint32),
    ("h", ctypes.c_uint32),
    ("n_planes", ctypes.c_uint32),
    ("plane", VmafxImportPlane * 3),
    ("acquire", VmafxFence),
    ("flags", ctypes.c_uint32),
)

VmafxModelConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("name", ctypes.c_char_p),
    ("flags", ctypes.c_uint64),
    ("log_level", ctypes.c_uint32),
    ("log_callback", VmafxLogCallback),
    ("log_user", ctypes.c_void_p),
)

VmafxFrameDesc._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pix_fmt", ctypes.c_uint32),
    ("bpc", ctypes.c_uint32),
    ("w", ctypes.c_uint32),
    ("h", ctypes.c_uint32),
)

VmafxHostPlanes._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("data", ctypes.c_void_p * 3),
    ("stride", ctypes.c_uint64 * 3),
    ("release", VmafxFrameReleaseCallback),
    ("user", ctypes.c_void_p),
)

VmafxFramePlanes._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pix_fmt", ctypes.c_uint32),
    ("bpc", ctypes.c_uint32),
    ("n_planes", ctypes.c_uint32),
    ("w", ctypes.c_uint32 * 3),
    ("h", ctypes.c_uint32 * 3),
    ("stride", ctypes.c_uint64 * 3),
    ("data", ctypes.c_void_p * 3),
)

VmafxPooledScore._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pool", ctypes.c_uint32),
    ("first", ctypes.c_uint64),
    ("last", ctypes.c_uint64),
    ("value", ctypes.c_double),
    ("feature", ctypes.c_char_p),
)

VmafxModelSetScore._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pool", ctypes.c_uint32),
    ("first", ctypes.c_uint64),
    ("last", ctypes.c_uint64),
    ("bagging", ctypes.c_double),
    ("stddev", ctypes.c_double),
    ("ci95_lo", ctypes.c_double),
    ("ci95_hi", ctypes.c_double),
    ("name", ctypes.c_char_p),
)


LAYOUT = {
    VmafxContextConfig: (
        48,
        (
            ("struct_size", 0),
            ("log_level", 4),
            ("n_threads", 8),
            ("n_subsample", 12),
            ("cpumask", 16),
            ("gpumask", 24),
            ("log_callback", 32),
            ("log_user", 40),
        ),
    ),
    VmafxProvenance: (
        32,
        (
            ("struct_size", 0),
            ("abi_major", 4),
            ("abi_minor", 8),
            ("abi_patch", 12),
            ("active_backend", 16),
            ("n_extractors", 20),
            ("version", 24),
        ),
    ),
    VmafxExtractorInfo: (
        16,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("name", 8),
        ),
    ),
    VmafxScore: (
        40,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("index", 8),
            ("value", 16),
            ("feature", 24),
            ("extractor", 32),
        ),
    ),
    VmafxFeatureResolution: (
        24,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("extractor", 8),
            ("unsupported_option", 16),
        ),
    ),
    VmafxDeviceDesc: (
        32,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("index", 8),
            ("flags", 12),
            ("external", 16),
        ),
    ),
    VmafxDeviceInfo: (
        40,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("index", 8),
            ("flags", 12),
            ("memory_kinds", 16),
            ("fence_kinds", 20),
            ("total_memory", 24),
            ("name", 32),
        ),
    ),
    VmafxFence: (
        32,
        (
            ("struct_size", 0),
            ("kind", 4),
            ("handle", 8),
            ("value", 16),
            ("fd", 24),
            ("reserved", 28),
        ),
    ),
    VmafxImportPlane: (
        48,
        (
            ("handle", 0),
            ("fd", 8),
            ("plane_index", 12),
            ("offset", 16),
            ("pitch", 24),
            ("modifier", 32),
            ("size", 40),
        ),
    ),
    VmafxFrameImport: (
        216,
        (
            ("struct_size", 0),
            ("memory", 4),
            ("pix_fmt", 8),
            ("bpc", 12),
            ("w", 16),
            ("h", 20),
            ("n_planes", 24),
            ("plane", 32),
            ("acquire", 176),
            ("flags", 208),
        ),
    ),
    VmafxModelConfig: (
        48,
        (
            ("struct_size", 0),
            ("name", 8),
            ("flags", 16),
            ("log_level", 24),
            ("log_callback", 32),
            ("log_user", 40),
        ),
    ),
    VmafxFrameDesc: (
        20,
        (
            ("struct_size", 0),
            ("pix_fmt", 4),
            ("bpc", 8),
            ("w", 12),
            ("h", 16),
        ),
    ),
    VmafxHostPlanes: (
        72,
        (
            ("struct_size", 0),
            ("data", 8),
            ("stride", 32),
            ("release", 56),
            ("user", 64),
        ),
    ),
    VmafxFramePlanes: (
        88,
        (
            ("struct_size", 0),
            ("pix_fmt", 4),
            ("bpc", 8),
            ("n_planes", 12),
            ("w", 16),
            ("h", 28),
            ("stride", 40),
            ("data", 64),
        ),
    ),
    VmafxPooledScore: (
        40,
        (
            ("struct_size", 0),
            ("pool", 4),
            ("first", 8),
            ("last", 16),
            ("value", 24),
            ("feature", 32),
        ),
    ),
    VmafxModelSetScore: (
        64,
        (
            ("struct_size", 0),
            ("pool", 4),
            ("first", 8),
            ("last", 16),
            ("bagging", 24),
            ("stddev", 32),
            ("ci95_lo", 40),
            ("ci95_hi", 48),
            ("name", 56),
        ),
    ),
}


SIGNATURES = {
    "vmafx_version_string": (
        ctypes.c_char_p,
        (),
    ),
    "vmafx_abi_version": (
        None,
        (
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_uint32),
        ),
    ),
    "vmafx_status_name": (
        ctypes.c_char_p,
        (ctypes.c_int32,),
    ),
    "vmafx_error_status": (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_message": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_subject": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_errno": (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_free": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_create": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxContextConfig),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_destroy": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_provenance": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxProvenance),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_extractor_info": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxExtractorInfo),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_feature_score": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_error_subject_kind": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_function": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_options_set": (
        ctypes.c_int32,
        (
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_options_free": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_set_option": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_feature": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_model": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_model_set": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_import_score": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint64,
            ctypes.c_double,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_extractor_count": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_feature_resolve": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.POINTER(VmafxFeatureResolution),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_frame_retention": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_submit": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_flush": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_create": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxDeviceDesc),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_device_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_device_backend": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_device_count": (
        ctypes.c_int32,
        (
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_info": (
        ctypes.c_int32,
        (
            ctypes.c_uint32,
            ctypes.c_int32,
            ctypes.POINTER(VmafxDeviceInfo),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_describe": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxDeviceInfo),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_profile": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_char_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_device": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_create_host": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_wrap_host": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.POINTER(VmafxHostPlanes),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_planes": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFramePlanes),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_frame_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_frame_import": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameImport),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_release_fence": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_create": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_signal": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_wait": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxFence),
            ctypes.c_uint64,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_destroy": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_pool_create": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_pool_acquire": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_pool_destroy": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_admit": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_import_frame": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameImport),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_load": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_load_file": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_override_feature": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_name": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_feature_count": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_feature_name": (
        ctypes.c_char_p,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
        ),
    ),
    "vmafx_model_hash": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_builtin_next": (
        ctypes.c_char_p,
        (ctypes.c_char_p,),
    ),
    "vmafx_model_default_version": (
        ctypes.c_char_p,
        (),
    ),
    "vmafx_model_set_load": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_set_load_file": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_set_override_feature": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_set_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_lead": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_size": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_hash": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_score_frame": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_score_frame_model_set": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxModelSetScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_score_pooled": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.c_uint64,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxPooledScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_feature_score_pooled": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint32,
            ctypes.c_uint64,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxPooledScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_score_pooled_model_set": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.c_uint64,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxModelSetScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_from_libvmaf": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_libvmaf_handle": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
}


class VmafxError(Exception):
    """A failed VMAFx call: status, message, the named subject and the engine's errno."""

    def __init__(
        self, function: str, status: int, message: str, subject: str, errno_value: int
    ) -> None:
        self.function = function
        self.status = status
        self.message = message
        self.subject = subject
        self.errno = errno_value
        name = Status(status).name if status in Status.__members__.values() else str(status)
        detail = f" [{subject}]" if subject else ""
        super().__init__(f"{function}: {name}: {message}{detail}")


class VmafxPending(VmafxError):
    """The requested score is not final yet (VMAFX_PENDING)."""


def _text(raw: bytes | None) -> str | None:
    return raw.decode() if raw is not None else None


def _check_layout() -> None:
    """Refuse a binding whose structs disagree with the definition's layout."""
    for struct, (size, offsets) in LAYOUT.items():
        if ctypes.sizeof(struct) != size:
            raise ImportError(f"{struct.__name__}: size {ctypes.sizeof(struct)} != {size}")
        for name, offset in offsets:
            actual = getattr(struct, name).offset
            if actual != offset:
                raise ImportError(f"{struct.__name__}.{name}: offset {actual} != {offset}")


def load(path: str | None = None) -> ctypes.CDLL:
    """Load the library from `path` or $VMAFX_LIBRARY. There is no search fallback."""
    chosen = path or os.environ.get("VMAFX_LIBRARY")
    if not chosen:
        raise OSError("set VMAFX_LIBRARY or pass the path of the VMAFx shared library")
    lib = ctypes.CDLL(chosen)
    for name, (restype, argtypes) in SIGNATURES.items():
        function = getattr(lib, name)
        function.restype = restype
        function.argtypes = argtypes
    return lib


def _raise(lib: ctypes.CDLL, status: int, error: ctypes.c_void_p, function: str) -> None:
    if status == Status.OK:
        return
    message = _text(lib.vmafx_error_message(error)) or ""
    subject = _text(lib.vmafx_error_subject(error)) or ""
    errno_value = lib.vmafx_error_errno(error)
    lib.vmafx_error_free(error)
    kind = VmafxPending if status == Status.PENDING else VmafxError
    raise kind(function, status, message, subject, errno_value)


@dataclass(frozen=True)
class ContextConfig:
    """Context configuration. Initialise with VMAFX_CONTEXT_CONFIG_INIT."""

    log_level: int
    n_threads: int
    n_subsample: int
    cpumask: int
    gpumask: int

    @classmethod
    def from_c(cls, raw: VmafxContextConfig) -> ContextConfig:
        return cls(
            log_level=raw.log_level,
            n_threads=raw.n_threads,
            n_subsample=raw.n_subsample,
            cpumask=raw.cpumask,
            gpumask=raw.gpumask,
        )

    def to_c(self) -> VmafxContextConfig:
        raw = VmafxContextConfig()
        raw.struct_size = ctypes.sizeof(raw)
        raw.log_level = self.log_level
        raw.n_threads = self.n_threads
        raw.n_subsample = self.n_subsample
        raw.cpumask = self.cpumask
        raw.gpumask = self.gpumask
        return raw


@dataclass(frozen=True)
class Provenance:
    """How the scores of a context are made (#2142). Strings live as long as the context."""

    abi_major: int
    abi_minor: int
    abi_patch: int
    active_backend: int
    n_extractors: int
    version: str | None

    @classmethod
    def from_c(cls, raw: VmafxProvenance) -> Provenance:
        return cls(
            abi_major=raw.abi_major,
            abi_minor=raw.abi_minor,
            abi_patch=raw.abi_patch,
            active_backend=raw.active_backend,
            n_extractors=raw.n_extractors,
            version=_text(raw.version),
        )


@dataclass(frozen=True)
class ExtractorInfo:
    """One registered feature extractor."""

    backend: int
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxExtractorInfo) -> ExtractorInfo:
        return cls(
            backend=raw.backend,
            name=_text(raw.name),
        )


@dataclass(frozen=True)
class Score:
    """One score and the extractor that produced it."""

    backend: int
    index: int
    value: float
    feature: str | None
    extractor: str | None

    @classmethod
    def from_c(cls, raw: VmafxScore) -> Score:
        return cls(
            backend=raw.backend,
            index=raw.index,
            value=raw.value,
            feature=_text(raw.feature),
            extractor=_text(raw.extractor),
        )


@dataclass(frozen=True)
class FeatureResolution:
    """Which extractor computes a feature on a context (ADR-1359). Strings live for the process lifetime."""

    backend: int
    extractor: str | None
    unsupported_option: str | None

    @classmethod
    def from_c(cls, raw: VmafxFeatureResolution) -> FeatureResolution:
        return cls(
            backend=raw.backend,
            extractor=_text(raw.extractor),
            unsupported_option=_text(raw.unsupported_option),
        )


@dataclass(frozen=True)
class DeviceDesc:
    """Which device to create. Initialise with VMAFX_DEVICE_DESC_INIT."""

    backend: int
    index: int
    flags: int
    external: tuple[int, ...]

    @classmethod
    def from_c(cls, raw: VmafxDeviceDesc) -> DeviceDesc:
        return cls(
            backend=raw.backend,
            index=raw.index,
            flags=raw.flags,
            external=tuple(raw.external),
        )


@dataclass(frozen=True)
class DeviceInfo:
    """What a device is and what it imports. Grows at the end: the format envelope of each device (largest frame, bit depths, chroma layouts; PR #2185) is appended by the generated capability tables of RC6 / RC7. Strings live for the process lifetime."""

    backend: int
    index: int
    flags: int
    memory_kinds: int
    fence_kinds: int
    total_memory: int
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxDeviceInfo) -> DeviceInfo:
        return cls(
            backend=raw.backend,
            index=raw.index,
            flags=raw.flags,
            memory_kinds=raw.memory_kinds,
            fence_kinds=raw.fence_kinds,
            total_memory=raw.total_memory,
            name=_text(raw.name),
        )


@dataclass(frozen=True)
class Fence:
    """A synchronisation point between the producer of a frame and the library. Passed by pointer; embedded by value in VmafxFrameImport, so it never grows. A fence the library returns (vmafx_fence_create(), vmafx_frame_release_fence()) belongs to the caller, who releases it once with vmafx_fence_destroy(). Initialise with VMAFX_FENCE_INIT."""

    kind: int
    handle: int
    value: int
    fd: int
    reserved: int

    @classmethod
    def from_c(cls, raw: VmafxFence) -> Fence:
        return cls(
            kind=raw.kind,
            handle=raw.handle,
            value=raw.value,
            fd=raw.fd,
            reserved=raw.reserved,
        )

    def to_c(self) -> VmafxFence:
        raw = VmafxFence()
        raw.struct_size = ctypes.sizeof(raw)
        raw.kind = self.kind
        raw.handle = self.handle
        raw.value = self.value
        raw.fd = self.fd
        raw.reserved = self.reserved
        return raw


@dataclass(frozen=True)
class ImportPlane:
    """Where one plane of an imported frame lives. Embedded by value in VmafxFrameImport: never grows. Fields a memory kind does not use are ignored."""

    handle: int
    fd: int
    plane_index: int
    offset: int
    pitch: int
    modifier: int
    size: int

    @classmethod
    def from_c(cls, raw: VmafxImportPlane) -> ImportPlane:
        return cls(
            handle=raw.handle,
            fd=raw.fd,
            plane_index=raw.plane_index,
            offset=raw.offset,
            pitch=raw.pitch,
            modifier=raw.modifier,
            size=raw.size,
        )

    def to_c(self) -> VmafxImportPlane:
        raw = VmafxImportPlane()
        raw.handle = self.handle
        raw.fd = self.fd
        raw.plane_index = self.plane_index
        raw.offset = self.offset
        raw.pitch = self.pitch
        raw.modifier = self.modifier
        raw.size = self.size
        return raw


@dataclass(frozen=True)
class FrameImport:
    """A frame the producer already holds in memory a device reads (design section 2.7). Initialise with VMAFX_FRAME_IMPORT_INIT."""

    memory: int
    pix_fmt: int
    bpc: int
    w: int
    h: int
    n_planes: int
    plane: tuple[ImportPlane, ...]
    acquire: Fence
    flags: int

    @classmethod
    def from_c(cls, raw: VmafxFrameImport) -> FrameImport:
        return cls(
            memory=raw.memory,
            pix_fmt=raw.pix_fmt,
            bpc=raw.bpc,
            w=raw.w,
            h=raw.h,
            n_planes=raw.n_planes,
            plane=tuple(ImportPlane.from_c(x) for x in raw.plane),
            acquire=Fence.from_c(raw.acquire),
            flags=raw.flags,
        )


@dataclass(frozen=True)
class ModelConfig:
    """How to load a model. Initialise with VMAFX_MODEL_CONFIG_INIT."""

    name: str | None
    flags: int
    log_level: int

    @classmethod
    def from_c(cls, raw: VmafxModelConfig) -> ModelConfig:
        return cls(
            name=_text(raw.name),
            flags=raw.flags,
            log_level=raw.log_level,
        )


@dataclass(frozen=True)
class FrameDesc:
    """Geometry of a frame. Initialise with VMAFX_FRAME_DESC_INIT."""

    pix_fmt: int
    bpc: int
    w: int
    h: int

    @classmethod
    def from_c(cls, raw: VmafxFrameDesc) -> FrameDesc:
        return cls(
            pix_fmt=raw.pix_fmt,
            bpc=raw.bpc,
            w=raw.w,
            h=raw.h,
        )

    def to_c(self) -> VmafxFrameDesc:
        raw = VmafxFrameDesc()
        raw.struct_size = ctypes.sizeof(raw)
        raw.pix_fmt = self.pix_fmt
        raw.bpc = self.bpc
        raw.w = self.w
        raw.h = self.h
        return raw


@dataclass(frozen=True)
class HostPlanes:
    """Caller-owned host planes a frame borrows. Initialise with VMAFX_HOST_PLANES_INIT."""

    stride: tuple[int, ...]

    @classmethod
    def from_c(cls, raw: VmafxHostPlanes) -> HostPlanes:
        return cls(
            stride=tuple(raw.stride),
        )


@dataclass(frozen=True)
class FramePlanes:
    """Where the samples of a frame are. The data pointers live as long as the frame."""

    pix_fmt: int
    bpc: int
    n_planes: int
    w: tuple[int, ...]
    h: tuple[int, ...]
    stride: tuple[int, ...]

    @classmethod
    def from_c(cls, raw: VmafxFramePlanes) -> FramePlanes:
        return cls(
            pix_fmt=raw.pix_fmt,
            bpc=raw.bpc,
            n_planes=raw.n_planes,
            w=tuple(raw.w),
            h=tuple(raw.h),
            stride=tuple(raw.stride),
        )


@dataclass(frozen=True)
class PooledScore:
    """A score pooled over a range of frames."""

    pool: int
    first: int
    last: int
    value: float
    feature: str | None

    @classmethod
    def from_c(cls, raw: VmafxPooledScore) -> PooledScore:
        return cls(
            pool=raw.pool,
            first=raw.first,
            last=raw.last,
            value=raw.value,
            feature=_text(raw.feature),
        )


@dataclass(frozen=True)
class ModelSetScore:
    """The bootstrap score of a model set at one frame or pooled over frames."""

    pool: int
    first: int
    last: int
    bagging: float
    stddev: float
    ci95_lo: float
    ci95_hi: float
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxModelSetScore) -> ModelSetScore:
        return cls(
            pool=raw.pool,
            first=raw.first,
            last=raw.last,
            bagging=raw.bagging,
            stddev=raw.stddev,
            ci95_lo=raw.ci95_lo,
            ci95_hi=raw.ci95_hi,
            name=_text(raw.name),
        )


class Context:
    """A VmafxContext; close it with close() or a with-block."""

    def __init__(self, lib: ctypes.CDLL, config: ContextConfig | None = None) -> None:
        self._lib = lib
        raw = config.to_c() if config is not None else None
        handle = ctypes.c_void_p()
        error = ctypes.c_void_p()
        pointer = ctypes.byref(raw) if raw is not None else None
        status = lib.vmafx_context_create(pointer, ctypes.byref(handle), ctypes.byref(error))
        _raise(lib, status, error, "vmafx_context_create")
        self._handle = handle

    def __enter__(self) -> Context:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    def close(self) -> None:
        """Destroy the context; on failure it stays open and close() may be retried."""
        if not self._handle:
            return
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_destroy(self._handle, ctypes.byref(error))
        _raise(self._lib, status, error, "vmafx_context_destroy")
        self._handle = ctypes.c_void_p()

    def libvmaf_handle(self) -> int:
        """The libvmaf VmafContext * bound to this context, for calls not yet migrated."""
        return self._lib.vmafx_context_libvmaf_handle(self._handle)

    def provenance(self) -> Provenance:
        """Fill the provenance record of a context."""
        out = VmafxProvenance()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_provenance(
            self._handle, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_provenance")
        return Provenance.from_c(out)

    def extractor_info(self, index: int) -> ExtractorInfo:
        """Describe registered extractor `index`; VMAFX_E_NOTFOUND past the last one."""
        out = VmafxExtractorInfo()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_extractor_info(
            self._handle, index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_extractor_info")
        return ExtractorInfo.from_c(out)

    def feature_score(self, feature: str, index: int) -> Score:
        """Score of `feature` at frame `index` with its producer; VMAFX_PENDING while the frame is not final."""
        out = VmafxScore()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_feature_score(
            self._handle, feature.encode(), index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_feature_score")
        return Score.from_c(out)

    def set_option(self, key: str, value: str) -> None:
        """Set a context option: `perceptual_weight` (`0` / `1`) or `perceptual_weight_strength` (a finite number >= 0). VMAFX_E_NOTFOUND names an unknown key, VMAFX_E_INVALID a value the key refuses."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_set_option(
            self._handle, key.encode(), value.encode(), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_set_option")

    def import_score(self, feature: str, index: int, value: float) -> None:
        """Record `value` as the score of `feature` at frame `index`, computed outside the library."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_import_score(
            self._handle, feature.encode(), index, value, ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_import_score")

    def flush(self) -> None:
        """Finish every submitted frame; scores of the last frames (motion) become final. A context is flushed once; a second flush or a submit after it is VMAFX_E_INVALID."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_flush(self._handle, ctypes.byref(error))
        _raise(self._lib, status, error, "vmafx_flush")

    def feature_score_pooled(self, feature: str, pool: int, first: int, last: int) -> PooledScore:
        """Scores of `feature` pooled as vmafx_score_pooled() does."""
        out = VmafxPooledScore()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_feature_score_pooled(
            self._handle,
            feature.encode(),
            pool,
            first,
            last,
            ctypes.byref(out),
            ctypes.byref(error),
        )
        _raise(self._lib, status, error, "vmafx_feature_score_pooled")
        return PooledScore.from_c(out)


class Library:
    """The loaded VMAFx library."""

    def __init__(self, path: str | None = None) -> None:
        self._lib = load(path)

    @property
    def raw(self) -> ctypes.CDLL:
        """The ctypes library, for calls the binding does not wrap."""
        return self._lib

    def context(self, config: ContextConfig | None = None) -> Context:
        """Create a context."""
        return Context(self._lib, config)

    def version_string(self) -> str | None:
        """Build version (git describe); valid for the process lifetime."""
        return _text(self._lib.vmafx_version_string())

    def abi_version(self) -> tuple[int, ...]:
        """ABI version of the loaded library. Each pointer may be NULL."""
        major = ctypes.c_uint32()
        minor = ctypes.c_uint32()
        patch = ctypes.c_uint32()
        self._lib.vmafx_abi_version(ctypes.byref(major), ctypes.byref(minor), ctypes.byref(patch))
        return (major.value, minor.value, patch.value)

    def status_name(self, status: int) -> str | None:
        """Name of a status code (`VMAFX_E_INVALID`), or `VMAFX_UNKNOWN_STATUS`."""
        return _text(self._lib.vmafx_status_name(status))

    def model_builtin_next(self, previous: str | None) -> str | None:
        """The built-in model version after `previous`, the first one for NULL, NULL after the last or for an unknown `previous`. Built-in model sets are listed too."""
        return _text(self._lib.vmafx_model_builtin_next(previous))

    def model_default_version(self) -> str | None:
        """Version of the default model (`vmaf_v1.0.16_3d0h`)."""
        return _text(self._lib.vmafx_model_default_version())


_check_layout()
