# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
#
# GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
# Do not edit: change the definition and run
# `python3 scripts/codegen/vmafx-api.py --write`.
"""ctypes binding of the VMAFx C API (generated)."""

from __future__ import annotations

import ctypes
import enum
import os
from dataclasses import dataclass

ABI_VERSION = (0, 1, 9)


class Status(enum.IntEnum):
    """VmafxStatus codes."""

    OK = 0
    PENDING = 1
    E_INVALID = -1
    E_NOMEM = -2
    E_NOTSUP = -3
    E_NOTFOUND = -4
    E_BUSY = -5
    E_DEVICE = -6
    E_IO = -7
    E_RANGE = -8
    E_INTERNAL = -9
    E_TIMEOUT = -10
    E_ABI = -11
    E_MISMATCH = -12


class LogLevel(enum.IntEnum):
    """VmafxLogLevel."""

    NONE = 0
    ERROR = 1
    WARNING = 2
    INFO = 3
    DEBUG = 4


class Backend(enum.IntEnum):
    """VmafxBackend."""

    CPU = 0
    CUDA = 1
    SYCL = 2
    METAL = 3
    HIP = 4


class PixelFormat(enum.IntEnum):
    """VmafxPixelFormat."""

    UNKNOWN = 0
    YUV420P = 1
    YUV422P = 2
    YUV444P = 3
    YUV400P = 4
    NV12 = 16
    P010 = 17
    P016 = 18
    NV16 = 19
    P210 = 20
    P216 = 21
    NV24 = 22
    P410 = 23
    P416 = 24
    Y210 = 25
    Y410 = 26
    YUYV422 = 27
    Y212 = 28
    VUYX = 29
    XV36 = 30
    YUV444P_MSB = 31


class Pool(enum.IntEnum):
    """VmafxPool."""

    NONE = 0
    MIN = 1
    MAX = 2
    MEAN = 3
    HARMONIC_MEAN = 4
    MEDIAN = 5
    PERC5 = 6
    PERC10 = 7
    PERC20 = 8


class SubjectKind(enum.IntEnum):
    """VmafxSubjectKind."""

    NONE = 0
    PARAMETER = 1
    CONTEXT = 2
    OPTION = 3
    FEATURE = 4
    EXTRACTOR = 5
    MODEL = 6
    FRAME = 7
    PLANE = 8
    DEVICE = 9
    BACKEND = 10
    PATH = 11
    FENCE = 12


class MemoryKind(enum.IntEnum):
    """VmafxMemoryKind."""

    NONE = 0
    HOST = 1
    DEVICE_POINTER = 2
    DEVICE_ARRAY = 3
    DMABUF = 4
    METAL_SURFACE = 5
    METAL_TEXTURE = 6
    WIN32_SHARED = 7
    GL_TEXTURE = 8


class FenceKind(enum.IntEnum):
    """VmafxFenceKind."""

    NONE = 0
    HOST = 1
    CUDA_EVENT = 2
    HIP_EVENT = 3
    SYCL_EVENT = 4
    SYNC_FILE = 5
    METAL_SHARED_EVENT = 6
    WIN32_SHARED = 7
    GL_SYNC = 8


class FeatureSource(enum.IntEnum):
    """VmafxFeatureSource."""

    UNKNOWN = 0
    EXTRACTOR = 1
    IMPORTED = 2
    MODEL = 3


class ReportFormat(enum.IntEnum):
    """VmafxReportFormat."""

    XML = 1
    JSON = 2
    CSV = 3
    SUB = 4


class WindowTarget(enum.IntEnum):
    """VmafxWindowTarget."""

    NONE = 0
    MODEL = 1
    MODEL_SET = 2
    FEATURE = 3


class ColorRange(enum.IntEnum):
    """VmafxColorRange."""

    UNKNOWN = 0
    LIMITED = 1
    FULL = 2


class ColorPrimaries(enum.IntEnum):
    """VmafxColorPrimaries."""

    UNKNOWN = 0
    BT709 = 1
    BT2020 = 2
    SMPTE432 = 3


class ColorTransfer(enum.IntEnum):
    """VmafxColorTransfer."""

    UNKNOWN = 0
    BT709 = 1
    SMPTE2084 = 2


class ColorMatrix(enum.IntEnum):
    """VmafxColorMatrix."""

    UNKNOWN = 0
    BT709 = 1
    BT2020_NCL = 2
    ICTCP = 3


class ResampleFilter(enum.IntEnum):
    """VmafxResampleFilter."""

    DEFAULT = 0
    BILINEAR = 1
    BICUBIC = 2
    LANCZOS = 3


class DnnDevice(enum.IntEnum):
    """VmafxDnnDevice."""

    AUTO = 0
    CPU = 1
    CUDA = 2
    OPENVINO = 3
    ROCM = 4
    COREML = 5
    COREML_ANE = 6
    COREML_GPU = 7
    COREML_CPU = 8
    OPENVINO_NPU = 9
    OPENVINO_CPU = 10
    OPENVINO_GPU = 11


class DnnResize(enum.IntEnum):
    """VmafxDnnResize."""

    DISABLED = 0
    BILINEAR = 1
    NEAREST = 2
    BICUBIC = 3


class McpTransport(enum.IntEnum):
    """VmafxMcpTransport."""

    SSE = 0
    UDS = 1
    STDIO = 2


class ModelFlags(enum.IntFlag):
    """VmafxModelFlags bits."""

    DISABLE_CLIP = 1
    ENABLE_TRANSFORM = 2
    DISABLE_TRANSFORM = 4


class ImportFlags(enum.IntFlag):
    """VmafxImportFlags bits."""

    ALLOW_COPY = 1


class DeviceFlags(enum.IntFlag):
    """VmafxDeviceFlags bits."""

    PROFILING = 1


class ReportFlags(enum.IntFlag):
    """VmafxReportFlags bits."""

    PROVENANCE_SIDECAR = 1


class ProvenanceJsonFlags(enum.IntFlag):
    """VmafxProvenanceJsonFlags bits."""

    CANONICAL = 1


class PoolMask(enum.IntFlag):
    """VmafxPoolMask bits."""

    _MIN = 2
    _MAX = 4
    _MEAN = 8
    _HARMONIC_MEAN = 16
    _MEDIAN = 32
    _PERC5 = 64
    _PERC10 = 128
    _PERC20 = 256


class WindowFlags(enum.IntFlag):
    """VmafxWindowFlags bits."""

    PARTIAL = 1


class DnnFlags(enum.IntFlag):
    """VmafxDnnFlags bits."""

    FP16_IO = 1


class VmafxContextConfig(ctypes.Structure):
    """C struct VmafxContextConfig."""


class VmafxProvenance(ctypes.Structure):
    """C struct VmafxProvenance."""


class VmafxModelProvenance(ctypes.Structure):
    """C struct VmafxModelProvenance."""


class VmafxFeatureProvenance(ctypes.Structure):
    """C struct VmafxFeatureProvenance."""


class VmafxAnnotation(ctypes.Structure):
    """C struct VmafxAnnotation."""


class VmafxExtractorInfo(ctypes.Structure):
    """C struct VmafxExtractorInfo."""


class VmafxScore(ctypes.Structure):
    """C struct VmafxScore."""


class VmafxFeatureResolution(ctypes.Structure):
    """C struct VmafxFeatureResolution."""


class VmafxDeviceDesc(ctypes.Structure):
    """C struct VmafxDeviceDesc."""


class VmafxDeviceInfo(ctypes.Structure):
    """C struct VmafxDeviceInfo."""


class VmafxFence(ctypes.Structure):
    """C struct VmafxFence."""


class VmafxImportPlane(ctypes.Structure):
    """C struct VmafxImportPlane."""


class VmafxFrameImport(ctypes.Structure):
    """C struct VmafxFrameImport."""


class VmafxModelConfig(ctypes.Structure):
    """C struct VmafxModelConfig."""


class VmafxFrameDesc(ctypes.Structure):
    """C struct VmafxFrameDesc."""


class VmafxHostPlanes(ctypes.Structure):
    """C struct VmafxHostPlanes."""


class VmafxFramePlanes(ctypes.Structure):
    """C struct VmafxFramePlanes."""


class VmafxPooledScore(ctypes.Structure):
    """C struct VmafxPooledScore."""


class VmafxModelSetScore(ctypes.Structure):
    """C struct VmafxModelSetScore."""


class VmafxWindowRequest(ctypes.Structure):
    """C struct VmafxWindowRequest."""


class VmafxWindowResult(ctypes.Structure):
    """C struct VmafxWindowResult."""


class VmafxWindowClockConfig(ctypes.Structure):
    """C struct VmafxWindowClockConfig."""


class VmafxWindowSpan(ctypes.Structure):
    """C struct VmafxWindowSpan."""


class VmafxColor(ctypes.Structure):
    """C struct VmafxColor."""


class VmafxConvertDesc(ctypes.Structure):
    """C struct VmafxConvertDesc."""


class VmafxDnnConfig(ctypes.Structure):
    """C struct VmafxDnnConfig."""


class VmafxDnnInput(ctypes.Structure):
    """C struct VmafxDnnInput."""


class VmafxDnnOutput(ctypes.Structure):
    """C struct VmafxDnnOutput."""


class VmafxMcpConfig(ctypes.Structure):
    """C struct VmafxMcpConfig."""


class VmafxMcpSseConfig(ctypes.Structure):
    """C struct VmafxMcpSseConfig."""


class VmafxMcpUdsConfig(ctypes.Structure):
    """C struct VmafxMcpUdsConfig."""


class VmafxMcpStdioConfig(ctypes.Structure):
    """C struct VmafxMcpStdioConfig."""


VmafxLogCallback = ctypes.CFUNCTYPE(None, ctypes.c_uint32, ctypes.c_char_p, ctypes.c_void_p)


VmafxFrameReleaseCallback = ctypes.CFUNCTYPE(None, ctypes.c_void_p)


VmafxWindowCallback = ctypes.CFUNCTYPE(
    None, ctypes.c_void_p, ctypes.POINTER(VmafxWindowResult), ctypes.c_void_p
)


VmafxContextConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("log_level", ctypes.c_uint32),
    ("n_threads", ctypes.c_uint32),
    ("n_subsample", ctypes.c_uint32),
    ("cpumask", ctypes.c_uint64),
    ("gpumask", ctypes.c_uint64),
    ("log_callback", VmafxLogCallback),
    ("log_user", ctypes.c_void_p),
    ("import_retry_wait_ns", ctypes.c_uint64),
)

VmafxProvenance._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("abi_major", ctypes.c_uint32),
    ("abi_minor", ctypes.c_uint32),
    ("abi_patch", ctypes.c_uint32),
    ("active_backend", ctypes.c_uint32),
    ("n_extractors", ctypes.c_uint32),
    ("version", ctypes.c_char_p),
    ("commit", ctypes.c_char_p),
    ("build_id", ctypes.c_char_p),
    ("compiler", ctypes.c_char_p),
    ("build_flags", ctypes.c_char_p),
    ("fp_policy", ctypes.c_char_p),
    ("backends", ctypes.c_char_p),
    ("rust_twins", ctypes.c_uint32),
    ("simd", ctypes.c_char_p),
    ("device_index", ctypes.c_int32),
    ("device_name", ctypes.c_char_p),
    ("device_runtime", ctypes.c_char_p),
    ("n_threads", ctypes.c_uint32),
    ("n_subsample", ctypes.c_uint32),
    ("cpumask", ctypes.c_uint64),
    ("gpumask", ctypes.c_uint64),
    ("frame_width", ctypes.c_uint32),
    ("frame_height", ctypes.c_uint32),
    ("pix_fmt", ctypes.c_uint32),
    ("bpc", ctypes.c_uint32),
    ("n_frames", ctypes.c_uint64),
    ("n_models", ctypes.c_uint32),
    ("n_features", ctypes.c_uint32),
    ("n_annotations", ctypes.c_uint32),
    ("encode_record", ctypes.c_char_p),
    ("scores_digest", ctypes.c_char_p),
    ("elapsed_ns", ctypes.c_uint64),
    ("digest", ctypes.c_char_p),
)

VmafxModelProvenance._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("name", ctypes.c_char_p),
    ("version", ctypes.c_char_p),
    ("sha256", ctypes.c_char_p),
    ("flags", ctypes.c_uint64),
    ("overrides", ctypes.c_char_p),
)

VmafxFeatureProvenance._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("feature", ctypes.c_char_p),
    ("extractor", ctypes.c_char_p),
    ("implementation", ctypes.c_char_p),
    ("backend", ctypes.c_uint32),
    ("device", ctypes.c_char_p),
    ("runtime", ctypes.c_char_p),
    ("options", ctypes.c_char_p),
    ("exactness", ctypes.c_char_p),
    ("source", ctypes.c_uint32),
)

VmafxAnnotation._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("key", ctypes.c_char_p),
    ("value", ctypes.c_char_p),
)

VmafxExtractorInfo._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("name", ctypes.c_char_p),
)

VmafxScore._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("index", ctypes.c_uint64),
    ("value", ctypes.c_double),
    ("feature", ctypes.c_char_p),
    ("extractor", ctypes.c_char_p),
)

VmafxFeatureResolution._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("extractor", ctypes.c_char_p),
    ("unsupported_option", ctypes.c_char_p),
)

VmafxDeviceDesc._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("index", ctypes.c_int32),
    ("flags", ctypes.c_uint32),
    ("external", ctypes.c_size_t * 2),
)

VmafxDeviceInfo._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("backend", ctypes.c_uint32),
    ("index", ctypes.c_int32),
    ("flags", ctypes.c_uint32),
    ("memory_kinds", ctypes.c_uint32),
    ("fence_kinds", ctypes.c_uint32),
    ("total_memory", ctypes.c_uint64),
    ("name", ctypes.c_char_p),
)

VmafxFence._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("kind", ctypes.c_uint32),
    ("handle", ctypes.c_size_t),
    ("value", ctypes.c_uint64),
    ("fd", ctypes.c_int32),
    ("reserved", ctypes.c_uint32),
)

VmafxImportPlane._fields_ = (
    ("handle", ctypes.c_size_t),
    ("fd", ctypes.c_int32),
    ("plane_index", ctypes.c_uint32),
    ("offset", ctypes.c_uint64),
    ("pitch", ctypes.c_uint64),
    ("modifier", ctypes.c_uint64),
    ("size", ctypes.c_uint64),
)

VmafxFrameImport._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("memory", ctypes.c_uint32),
    ("pix_fmt", ctypes.c_uint32),
    ("bpc", ctypes.c_uint32),
    ("w", ctypes.c_uint32),
    ("h", ctypes.c_uint32),
    ("n_planes", ctypes.c_uint32),
    ("plane", VmafxImportPlane * 3),
    ("acquire", VmafxFence),
    ("flags", ctypes.c_uint32),
    ("release", VmafxFrameReleaseCallback),
    ("user", ctypes.c_void_p),
)

VmafxModelConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("name", ctypes.c_char_p),
    ("flags", ctypes.c_uint64),
    ("log_level", ctypes.c_uint32),
    ("log_callback", VmafxLogCallback),
    ("log_user", ctypes.c_void_p),
)

VmafxFrameDesc._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pix_fmt", ctypes.c_uint32),
    ("bpc", ctypes.c_uint32),
    ("w", ctypes.c_uint32),
    ("h", ctypes.c_uint32),
)

VmafxHostPlanes._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("data", ctypes.c_void_p * 3),
    ("stride", ctypes.c_uint64 * 3),
    ("release", VmafxFrameReleaseCallback),
    ("user", ctypes.c_void_p),
)

VmafxFramePlanes._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pix_fmt", ctypes.c_uint32),
    ("bpc", ctypes.c_uint32),
    ("n_planes", ctypes.c_uint32),
    ("w", ctypes.c_uint32 * 3),
    ("h", ctypes.c_uint32 * 3),
    ("stride", ctypes.c_uint64 * 3),
    ("data", ctypes.c_void_p * 3),
)

VmafxPooledScore._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pool", ctypes.c_uint32),
    ("first", ctypes.c_uint64),
    ("last", ctypes.c_uint64),
    ("value", ctypes.c_double),
    ("feature", ctypes.c_char_p),
)

VmafxModelSetScore._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("pool", ctypes.c_uint32),
    ("first", ctypes.c_uint64),
    ("last", ctypes.c_uint64),
    ("bagging", ctypes.c_double),
    ("stddev", ctypes.c_double),
    ("ci95_lo", ctypes.c_double),
    ("ci95_hi", ctypes.c_double),
    ("name", ctypes.c_char_p),
)

VmafxWindowRequest._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("target", ctypes.c_uint32),
    ("pool_mask", ctypes.c_uint32),
    ("first", ctypes.c_uint64),
    ("last", ctypes.c_uint64),
    ("model", ctypes.c_void_p),
    ("model_set", ctypes.c_void_p),
    ("feature", ctypes.c_char_p),
    ("on_complete", VmafxWindowCallback),
    ("user", ctypes.c_void_p),
)

VmafxWindowResult._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("status", ctypes.c_int32),
    ("flags", ctypes.c_uint32),
    ("target", ctypes.c_uint32),
    ("pool_mask", ctypes.c_uint32),
    ("first", ctypes.c_uint64),
    ("last", ctypes.c_uint64),
    ("n_frames", ctypes.c_uint64),
    ("n_scored", ctypes.c_uint64),
    ("value", ctypes.c_double * 9),
    ("stddev", ctypes.c_double * 9),
    ("ci95_lo", ctypes.c_double * 9),
    ("ci95_hi", ctypes.c_double * 9),
    ("name", ctypes.c_char_p),
)

VmafxWindowClockConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("n_stats", ctypes.c_double),
    ("n_stats_frames", ctypes.c_uint64),
)

VmafxWindowSpan._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("flags", ctypes.c_uint32),
    ("window", ctypes.c_uint64),
    ("first", ctypes.c_uint64),
    ("last", ctypes.c_uint64),
    ("n_frames", ctypes.c_uint64),
    ("start_ns", ctypes.c_int64),
    ("end_ns", ctypes.c_int64),
)

VmafxColor._fields_ = (
    ("range", ctypes.c_uint32),
    ("primaries", ctypes.c_uint32),
    ("trc", ctypes.c_uint32),
    ("matrix", ctypes.c_uint32),
)

VmafxConvertDesc._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("src_pix_fmt", ctypes.c_uint32),
    ("src_bpc", ctypes.c_uint32),
    ("src_w", ctypes.c_uint32),
    ("src_h", ctypes.c_uint32),
    ("src_color", VmafxColor),
    ("dst_pix_fmt", ctypes.c_uint32),
    ("dst_bpc", ctypes.c_uint32),
    ("dst_w", ctypes.c_uint32),
    ("dst_h", ctypes.c_uint32),
    ("dst_color", VmafxColor),
    ("filter", ctypes.c_uint32),
)

VmafxDnnConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("device", ctypes.c_uint32),
    ("device_index", ctypes.c_int32),
    ("threads", ctypes.c_int32),
    ("flags", ctypes.c_uint32),
)

VmafxDnnInput._fields_ = (
    ("name", ctypes.c_char_p),
    ("data", ctypes.c_void_p),
    ("shape", ctypes.c_void_p),
    ("rank", ctypes.c_size_t),
)

VmafxDnnOutput._fields_ = (
    ("name", ctypes.c_char_p),
    ("data", ctypes.c_void_p),
    ("capacity", ctypes.c_size_t),
    ("written", ctypes.c_size_t),
)

VmafxMcpConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("queue_depth", ctypes.c_uint32),
    ("max_drain_per_frame", ctypes.c_uint32),
    ("user_agent", ctypes.c_char_p),
)

VmafxMcpSseConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("port", ctypes.c_uint32),
    ("path", ctypes.c_char_p),
)

VmafxMcpUdsConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("path", ctypes.c_char_p),
)

VmafxMcpStdioConfig._fields_ = (
    ("struct_size", ctypes.c_uint32),
    ("fd_in", ctypes.c_int32),
    ("fd_out", ctypes.c_int32),
)


LAYOUT = {
    VmafxContextConfig: (
        56,
        (
            ("struct_size", 0),
            ("log_level", 4),
            ("n_threads", 8),
            ("n_subsample", 12),
            ("cpumask", 16),
            ("gpumask", 24),
            ("log_callback", 32),
            ("log_user", 40),
            ("import_retry_wait_ns", 48),
        ),
    ),
    VmafxProvenance: (
        216,
        (
            ("struct_size", 0),
            ("abi_major", 4),
            ("abi_minor", 8),
            ("abi_patch", 12),
            ("active_backend", 16),
            ("n_extractors", 20),
            ("version", 24),
            ("commit", 32),
            ("build_id", 40),
            ("compiler", 48),
            ("build_flags", 56),
            ("fp_policy", 64),
            ("backends", 72),
            ("rust_twins", 80),
            ("simd", 88),
            ("device_index", 96),
            ("device_name", 104),
            ("device_runtime", 112),
            ("n_threads", 120),
            ("n_subsample", 124),
            ("cpumask", 128),
            ("gpumask", 136),
            ("frame_width", 144),
            ("frame_height", 148),
            ("pix_fmt", 152),
            ("bpc", 156),
            ("n_frames", 160),
            ("n_models", 168),
            ("n_features", 172),
            ("n_annotations", 176),
            ("encode_record", 184),
            ("scores_digest", 192),
            ("elapsed_ns", 200),
            ("digest", 208),
        ),
    ),
    VmafxModelProvenance: (
        48,
        (
            ("struct_size", 0),
            ("name", 8),
            ("version", 16),
            ("sha256", 24),
            ("flags", 32),
            ("overrides", 40),
        ),
    ),
    VmafxFeatureProvenance: (
        80,
        (
            ("struct_size", 0),
            ("feature", 8),
            ("extractor", 16),
            ("implementation", 24),
            ("backend", 32),
            ("device", 40),
            ("runtime", 48),
            ("options", 56),
            ("exactness", 64),
            ("source", 72),
        ),
    ),
    VmafxAnnotation: (
        24,
        (
            ("struct_size", 0),
            ("key", 8),
            ("value", 16),
        ),
    ),
    VmafxExtractorInfo: (
        16,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("name", 8),
        ),
    ),
    VmafxScore: (
        40,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("index", 8),
            ("value", 16),
            ("feature", 24),
            ("extractor", 32),
        ),
    ),
    VmafxFeatureResolution: (
        24,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("extractor", 8),
            ("unsupported_option", 16),
        ),
    ),
    VmafxDeviceDesc: (
        32,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("index", 8),
            ("flags", 12),
            ("external", 16),
        ),
    ),
    VmafxDeviceInfo: (
        40,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("index", 8),
            ("flags", 12),
            ("memory_kinds", 16),
            ("fence_kinds", 20),
            ("total_memory", 24),
            ("name", 32),
        ),
    ),
    VmafxFence: (
        32,
        (
            ("struct_size", 0),
            ("kind", 4),
            ("handle", 8),
            ("value", 16),
            ("fd", 24),
            ("reserved", 28),
        ),
    ),
    VmafxImportPlane: (
        48,
        (
            ("handle", 0),
            ("fd", 8),
            ("plane_index", 12),
            ("offset", 16),
            ("pitch", 24),
            ("modifier", 32),
            ("size", 40),
        ),
    ),
    VmafxFrameImport: (
        232,
        (
            ("struct_size", 0),
            ("memory", 4),
            ("pix_fmt", 8),
            ("bpc", 12),
            ("w", 16),
            ("h", 20),
            ("n_planes", 24),
            ("plane", 32),
            ("acquire", 176),
            ("flags", 208),
            ("release", 216),
            ("user", 224),
        ),
    ),
    VmafxModelConfig: (
        48,
        (
            ("struct_size", 0),
            ("name", 8),
            ("flags", 16),
            ("log_level", 24),
            ("log_callback", 32),
            ("log_user", 40),
        ),
    ),
    VmafxFrameDesc: (
        20,
        (
            ("struct_size", 0),
            ("pix_fmt", 4),
            ("bpc", 8),
            ("w", 12),
            ("h", 16),
        ),
    ),
    VmafxHostPlanes: (
        72,
        (
            ("struct_size", 0),
            ("data", 8),
            ("stride", 32),
            ("release", 56),
            ("user", 64),
        ),
    ),
    VmafxFramePlanes: (
        88,
        (
            ("struct_size", 0),
            ("pix_fmt", 4),
            ("bpc", 8),
            ("n_planes", 12),
            ("w", 16),
            ("h", 28),
            ("stride", 40),
            ("data", 64),
        ),
    ),
    VmafxPooledScore: (
        40,
        (
            ("struct_size", 0),
            ("pool", 4),
            ("first", 8),
            ("last", 16),
            ("value", 24),
            ("feature", 32),
        ),
    ),
    VmafxModelSetScore: (
        64,
        (
            ("struct_size", 0),
            ("pool", 4),
            ("first", 8),
            ("last", 16),
            ("bagging", 24),
            ("stddev", 32),
            ("ci95_lo", 40),
            ("ci95_hi", 48),
            ("name", 56),
        ),
    ),
    VmafxWindowRequest: (
        72,
        (
            ("struct_size", 0),
            ("target", 4),
            ("pool_mask", 8),
            ("first", 16),
            ("last", 24),
            ("model", 32),
            ("model_set", 40),
            ("feature", 48),
            ("on_complete", 56),
            ("user", 64),
        ),
    ),
    VmafxWindowResult: (
        352,
        (
            ("struct_size", 0),
            ("status", 4),
            ("flags", 8),
            ("target", 12),
            ("pool_mask", 16),
            ("first", 24),
            ("last", 32),
            ("n_frames", 40),
            ("n_scored", 48),
            ("value", 56),
            ("stddev", 128),
            ("ci95_lo", 200),
            ("ci95_hi", 272),
            ("name", 344),
        ),
    ),
    VmafxWindowClockConfig: (
        24,
        (
            ("struct_size", 0),
            ("n_stats", 8),
            ("n_stats_frames", 16),
        ),
    ),
    VmafxWindowSpan: (
        56,
        (
            ("struct_size", 0),
            ("flags", 4),
            ("window", 8),
            ("first", 16),
            ("last", 24),
            ("n_frames", 32),
            ("start_ns", 40),
            ("end_ns", 48),
        ),
    ),
    VmafxColor: (
        16,
        (
            ("range", 0),
            ("primaries", 4),
            ("trc", 8),
            ("matrix", 12),
        ),
    ),
    VmafxConvertDesc: (
        72,
        (
            ("struct_size", 0),
            ("src_pix_fmt", 4),
            ("src_bpc", 8),
            ("src_w", 12),
            ("src_h", 16),
            ("src_color", 20),
            ("dst_pix_fmt", 36),
            ("dst_bpc", 40),
            ("dst_w", 44),
            ("dst_h", 48),
            ("dst_color", 52),
            ("filter", 68),
        ),
    ),
    VmafxDnnConfig: (
        20,
        (
            ("struct_size", 0),
            ("device", 4),
            ("device_index", 8),
            ("threads", 12),
            ("flags", 16),
        ),
    ),
    VmafxDnnInput: (
        32,
        (
            ("name", 0),
            ("data", 8),
            ("shape", 16),
            ("rank", 24),
        ),
    ),
    VmafxDnnOutput: (
        32,
        (
            ("name", 0),
            ("data", 8),
            ("capacity", 16),
            ("written", 24),
        ),
    ),
    VmafxMcpConfig: (
        24,
        (
            ("struct_size", 0),
            ("queue_depth", 4),
            ("max_drain_per_frame", 8),
            ("user_agent", 16),
        ),
    ),
    VmafxMcpSseConfig: (
        16,
        (
            ("struct_size", 0),
            ("port", 4),
            ("path", 8),
        ),
    ),
    VmafxMcpUdsConfig: (
        16,
        (
            ("struct_size", 0),
            ("path", 8),
        ),
    ),
    VmafxMcpStdioConfig: (
        12,
        (
            ("struct_size", 0),
            ("fd_in", 4),
            ("fd_out", 8),
        ),
    ),
}


SIGNATURES = {
    "vmafx_version_string": (
        ctypes.c_char_p,
        (),
    ),
    "vmafx_abi_version": (
        None,
        (
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_uint32),
        ),
    ),
    "vmafx_status_name": (
        ctypes.c_char_p,
        (ctypes.c_int32,),
    ),
    "vmafx_error_status": (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_message": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_subject": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_errno": (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_free": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_create": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxContextConfig),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_destroy": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_provenance": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxProvenance),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_extractor_info": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxExtractorInfo),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_feature_score": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_error_subject_kind": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_function": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_options_set": (
        ctypes.c_int32,
        (
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_options_free": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_set_option": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_feature": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_model": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_model_set": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_import_score": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint64,
            ctypes.c_double,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_extractor_count": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_feature_resolve": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.POINTER(VmafxFeatureResolution),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_frame_retention": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_submit": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_flush": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_create": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxDeviceDesc),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_device_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_device_backend": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_device_count": (
        ctypes.c_int32,
        (
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_info": (
        ctypes.c_int32,
        (
            ctypes.c_uint32,
            ctypes.c_int32,
            ctypes.POINTER(VmafxDeviceInfo),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_describe": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxDeviceInfo),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_device_profile": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_char_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_use_device": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_create_host": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_wrap_host": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.POINTER(VmafxHostPlanes),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_planes": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFramePlanes),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_frame_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_frame_import": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameImport),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_release_fence": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_create": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_signal": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_wait": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxFence),
            ctypes.c_uint64,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_fence_destroy": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxFence),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_pool_create": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_pool_acquire": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_pool_destroy": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_admit": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_import_frame": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameImport),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_load": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_load_file": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_override_feature": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_name": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_feature_count": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_feature_name": (
        ctypes.c_char_p,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
        ),
    ),
    "vmafx_model_hash": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_builtin_next": (
        ctypes.c_char_p,
        (ctypes.c_char_p,),
    ),
    "vmafx_model_default_version": (
        ctypes.c_char_p,
        (),
    ),
    "vmafx_model_set_load": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_set_load_file": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxModelConfig),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_set_override_feature": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_set_ref": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_unref": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_lead": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_size": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_hash": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_score_frame": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_score_frame_model_set": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxModelSetScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_score_pooled": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.c_uint64,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxPooledScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_feature_score_pooled": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint32,
            ctypes.c_uint64,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxPooledScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_score_pooled_model_set": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.c_uint64,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxModelSetScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_model_provenance": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxModelProvenance),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_feature_provenance": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxFeatureProvenance),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_feature_provenance": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.POINTER(VmafxFeatureProvenance),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_annotate": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_annotation": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxAnnotation),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_set_encode_record": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_provenance_json": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_char_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_report_write": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint32,
            ctypes.c_uint32,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_report_open": (
        ctypes.c_int32,
        (
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_report_close": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_report_field": (
        ctypes.c_char_p,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
        ),
    ),
    "vmafx_report_verify": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_window_submit": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxWindowRequest),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_window_poll": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxWindowResult),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_window_wait": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxWindowResult),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_window_release": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_max_in_flight": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_window_clock_create": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxWindowClockConfig),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_window_clock_frame": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.c_int64,
            ctypes.POINTER(VmafxWindowSpan),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_window_clock_finish": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxWindowSpan),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_window_clock_destroy": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_from_libvmaf": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_libvmaf_handle": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_backend_name": (
        ctypes.c_char_p,
        (ctypes.c_uint32,),
    ),
    "vmafx_context_backend": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_preallocate": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxFrameDesc),
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_acquire_frame": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_attach_sidedata": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint64,
            ctypes.c_void_p,
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_converter_create": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxConvertDesc),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_convert": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_converter_destroy": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_dnn_available": (
        ctypes.c_uint32,
        (),
    ),
    "vmafx_context_use_tiny_model": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.POINTER(VmafxDnnConfig),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_set_codec_context": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.c_int32,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_is_codec_aware": (
        ctypes.c_uint32,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_set_tiny_resize": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_dnn_session_open": (
        ctypes.c_int32,
        (
            ctypes.c_char_p,
            ctypes.POINTER(VmafxDnnConfig),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_dnn_session_run_luma8": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_size_t,
            ctypes.c_uint32,
            ctypes.c_uint32,
            ctypes.c_void_p,
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_dnn_session_run_plane16": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_size_t,
            ctypes.c_uint32,
            ctypes.c_uint32,
            ctypes.c_uint32,
            ctypes.c_void_p,
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_dnn_session_run": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxDnnInput),
            ctypes.c_size_t,
            ctypes.POINTER(VmafxDnnOutput),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_dnn_session_close": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_dnn_session_runtime_device": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_dnn_verify_signature": (
        ctypes.c_int32,
        (
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_mcp_available": (
        ctypes.c_uint32,
        (),
    ),
    "vmafx_mcp_transport_available": (
        ctypes.c_uint32,
        (ctypes.c_uint32,),
    ),
    "vmafx_mcp_server_create": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxMcpConfig),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_mcp_start_sse": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxMcpSseConfig),
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_mcp_start_uds": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxMcpUdsConfig),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_mcp_start_stdio": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxMcpStdioConfig),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_mcp_stop": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_mcp_server_destroy": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_frame_from_picture": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_frame_to_picture": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_model_from_libvmaf": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_libvmaf_handle": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_from_libvmaf": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_model_set_libvmaf_handle": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
}


class VmafxError(Exception):
    """A failed VMAFx call: status, message, the named subject and the engine's errno."""

    def __init__(
        self, function: str, status: int, message: str, subject: str, errno_value: int
    ) -> None:
        self.function = function
        self.status = status
        self.message = message
        self.subject = subject
        self.errno = errno_value
        name = Status(status).name if status in Status.__members__.values() else str(status)
        detail = f" [{subject}]" if subject else ""
        super().__init__(f"{function}: {name}: {message}{detail}")


class VmafxPending(VmafxError):
    """The requested score is not final yet (VMAFX_PENDING)."""


def _text(raw: bytes | None) -> str | None:
    return raw.decode() if raw is not None else None


def _check_layout() -> None:
    """Refuse a binding whose structs disagree with the definition's layout."""
    for struct, (size, offsets) in LAYOUT.items():
        if ctypes.sizeof(struct) != size:
            raise ImportError(f"{struct.__name__}: size {ctypes.sizeof(struct)} != {size}")
        for name, offset in offsets:
            actual = getattr(struct, name).offset
            if actual != offset:
                raise ImportError(f"{struct.__name__}.{name}: offset {actual} != {offset}")


def load(path: str | None = None) -> ctypes.CDLL:
    """Load the library from `path` or $VMAFX_LIBRARY. There is no search fallback."""
    chosen = path or os.environ.get("VMAFX_LIBRARY")
    if not chosen:
        raise OSError("set VMAFX_LIBRARY or pass the path of the VMAFx shared library")
    lib = ctypes.CDLL(chosen)
    for name, (restype, argtypes) in SIGNATURES.items():
        function = getattr(lib, name)
        function.restype = restype
        function.argtypes = argtypes
    return lib


def _raise(lib: ctypes.CDLL, status: int, error: ctypes.c_void_p, function: str) -> None:
    if status == Status.OK:
        return
    message = _text(lib.vmafx_error_message(error)) or ""
    subject = _text(lib.vmafx_error_subject(error)) or ""
    errno_value = lib.vmafx_error_errno(error)
    lib.vmafx_error_free(error)
    kind = VmafxPending if status == Status.PENDING else VmafxError
    raise kind(function, status, message, subject, errno_value)


@dataclass(frozen=True)
class ContextConfig:
    """Context configuration. Initialise with VMAFX_CONTEXT_CONFIG_INIT."""

    log_level: int
    n_threads: int
    n_subsample: int
    cpumask: int
    gpumask: int
    import_retry_wait_ns: int

    @classmethod
    def from_c(cls, raw: VmafxContextConfig) -> ContextConfig:
        return cls(
            log_level=raw.log_level,
            n_threads=raw.n_threads,
            n_subsample=raw.n_subsample,
            cpumask=raw.cpumask,
            gpumask=raw.gpumask,
            import_retry_wait_ns=raw.import_retry_wait_ns,
        )

    def to_c(self) -> VmafxContextConfig:
        raw = VmafxContextConfig()
        raw.struct_size = ctypes.sizeof(raw)
        raw.log_level = self.log_level
        raw.n_threads = self.n_threads
        raw.n_subsample = self.n_subsample
        raw.cpumask = self.cpumask
        raw.gpumask = self.gpumask
        raw.import_retry_wait_ns = self.import_retry_wait_ns
        return raw


@dataclass(frozen=True)
class Provenance:
    """How the scores of a context are made (#2142). Strings live as long as the context."""

    abi_major: int
    abi_minor: int
    abi_patch: int
    active_backend: int
    n_extractors: int
    version: str | None
    commit: str | None
    build_id: str | None
    compiler: str | None
    build_flags: str | None
    fp_policy: str | None
    backends: str | None
    rust_twins: int
    simd: str | None
    device_index: int
    device_name: str | None
    device_runtime: str | None
    n_threads: int
    n_subsample: int
    cpumask: int
    gpumask: int
    frame_width: int
    frame_height: int
    pix_fmt: int
    bpc: int
    n_frames: int
    n_models: int
    n_features: int
    n_annotations: int
    encode_record: str | None
    scores_digest: str | None
    elapsed_ns: int
    digest: str | None

    @classmethod
    def from_c(cls, raw: VmafxProvenance) -> Provenance:
        return cls(
            abi_major=raw.abi_major,
            abi_minor=raw.abi_minor,
            abi_patch=raw.abi_patch,
            active_backend=raw.active_backend,
            n_extractors=raw.n_extractors,
            version=_text(raw.version),
            commit=_text(raw.commit),
            build_id=_text(raw.build_id),
            compiler=_text(raw.compiler),
            build_flags=_text(raw.build_flags),
            fp_policy=_text(raw.fp_policy),
            backends=_text(raw.backends),
            rust_twins=raw.rust_twins,
            simd=_text(raw.simd),
            device_index=raw.device_index,
            device_name=_text(raw.device_name),
            device_runtime=_text(raw.device_runtime),
            n_threads=raw.n_threads,
            n_subsample=raw.n_subsample,
            cpumask=raw.cpumask,
            gpumask=raw.gpumask,
            frame_width=raw.frame_width,
            frame_height=raw.frame_height,
            pix_fmt=raw.pix_fmt,
            bpc=raw.bpc,
            n_frames=raw.n_frames,
            n_models=raw.n_models,
            n_features=raw.n_features,
            n_annotations=raw.n_annotations,
            encode_record=_text(raw.encode_record),
            scores_digest=_text(raw.scores_digest),
            elapsed_ns=raw.elapsed_ns,
            digest=_text(raw.digest),
        )


@dataclass(frozen=True)
class ModelProvenance:
    """One mounted model (#2142). Strings live as long as the context. Added in ABI 0.1.5."""

    name: str | None
    version: str | None
    sha256: str | None
    flags: int
    overrides: str | None

    @classmethod
    def from_c(cls, raw: VmafxModelProvenance) -> ModelProvenance:
        return cls(
            name=_text(raw.name),
            version=_text(raw.version),
            sha256=_text(raw.sha256),
            flags=raw.flags,
            overrides=_text(raw.overrides),
        )


@dataclass(frozen=True)
class FeatureProvenance:
    """How the scores of one feature are made (#2142). Strings live as long as the context. Added in ABI 0.1.5."""

    feature: str | None
    extractor: str | None
    implementation: str | None
    backend: int
    device: str | None
    runtime: str | None
    options: str | None
    exactness: str | None
    source: int

    @classmethod
    def from_c(cls, raw: VmafxFeatureProvenance) -> FeatureProvenance:
        return cls(
            feature=_text(raw.feature),
            extractor=_text(raw.extractor),
            implementation=_text(raw.implementation),
            backend=raw.backend,
            device=_text(raw.device),
            runtime=_text(raw.runtime),
            options=_text(raw.options),
            exactness=_text(raw.exactness),
            source=raw.source,
        )


@dataclass(frozen=True)
class Annotation:
    """One caller annotation of the provenance record (vmafx_context_annotate()). Strings live as long as the context. Added in ABI 0.1.5."""

    key: str | None
    value: str | None

    @classmethod
    def from_c(cls, raw: VmafxAnnotation) -> Annotation:
        return cls(
            key=_text(raw.key),
            value=_text(raw.value),
        )


@dataclass(frozen=True)
class ExtractorInfo:
    """One registered feature extractor."""

    backend: int
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxExtractorInfo) -> ExtractorInfo:
        return cls(
            backend=raw.backend,
            name=_text(raw.name),
        )


@dataclass(frozen=True)
class Score:
    """One score and the extractor that produced it."""

    backend: int
    index: int
    value: float
    feature: str | None
    extractor: str | None

    @classmethod
    def from_c(cls, raw: VmafxScore) -> Score:
        return cls(
            backend=raw.backend,
            index=raw.index,
            value=raw.value,
            feature=_text(raw.feature),
            extractor=_text(raw.extractor),
        )


@dataclass(frozen=True)
class FeatureResolution:
    """Which extractor computes a feature on a context (ADR-1359). Strings live for the process lifetime."""

    backend: int
    extractor: str | None
    unsupported_option: str | None

    @classmethod
    def from_c(cls, raw: VmafxFeatureResolution) -> FeatureResolution:
        return cls(
            backend=raw.backend,
            extractor=_text(raw.extractor),
            unsupported_option=_text(raw.unsupported_option),
        )


@dataclass(frozen=True)
class DeviceDesc:
    """Which device to create. Initialise with VMAFX_DEVICE_DESC_INIT."""

    backend: int
    index: int
    flags: int
    external: tuple[int, ...]

    @classmethod
    def from_c(cls, raw: VmafxDeviceDesc) -> DeviceDesc:
        return cls(
            backend=raw.backend,
            index=raw.index,
            flags=raw.flags,
            external=tuple(raw.external),
        )


@dataclass(frozen=True)
class DeviceInfo:
    """What a device is and what it imports. Grows at the end: the format envelope of each device (largest frame, bit depths, chroma layouts; PR #2185) is appended by the generated capability tables of RC6 / RC7. Strings live for the process lifetime."""

    backend: int
    index: int
    flags: int
    memory_kinds: int
    fence_kinds: int
    total_memory: int
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxDeviceInfo) -> DeviceInfo:
        return cls(
            backend=raw.backend,
            index=raw.index,
            flags=raw.flags,
            memory_kinds=raw.memory_kinds,
            fence_kinds=raw.fence_kinds,
            total_memory=raw.total_memory,
            name=_text(raw.name),
        )


@dataclass(frozen=True)
class Fence:
    """A synchronisation point between the producer of a frame and the library. Passed by pointer; embedded by value in VmafxFrameImport, so it never grows. A fence the library returns (vmafx_fence_create(), vmafx_frame_release_fence()) belongs to the caller, who releases it once with vmafx_fence_destroy(). Initialise with VMAFX_FENCE_INIT."""

    kind: int
    handle: int
    value: int
    fd: int
    reserved: int

    @classmethod
    def from_c(cls, raw: VmafxFence) -> Fence:
        return cls(
            kind=raw.kind,
            handle=raw.handle,
            value=raw.value,
            fd=raw.fd,
            reserved=raw.reserved,
        )

    def to_c(self) -> VmafxFence:
        raw = VmafxFence()
        raw.struct_size = ctypes.sizeof(raw)
        raw.kind = self.kind
        raw.handle = self.handle
        raw.value = self.value
        raw.fd = self.fd
        raw.reserved = self.reserved
        return raw


@dataclass(frozen=True)
class ImportPlane:
    """Where one plane of an imported frame lives. Embedded by value in VmafxFrameImport: never grows. Fields a memory kind does not use are ignored."""

    handle: int
    fd: int
    plane_index: int
    offset: int
    pitch: int
    modifier: int
    size: int

    @classmethod
    def from_c(cls, raw: VmafxImportPlane) -> ImportPlane:
        return cls(
            handle=raw.handle,
            fd=raw.fd,
            plane_index=raw.plane_index,
            offset=raw.offset,
            pitch=raw.pitch,
            modifier=raw.modifier,
            size=raw.size,
        )

    def to_c(self) -> VmafxImportPlane:
        raw = VmafxImportPlane()
        raw.handle = self.handle
        raw.fd = self.fd
        raw.plane_index = self.plane_index
        raw.offset = self.offset
        raw.pitch = self.pitch
        raw.modifier = self.modifier
        raw.size = self.size
        return raw


@dataclass(frozen=True)
class FrameImport:
    """A frame the producer already holds in memory a device reads (design section 2.7). Initialise with VMAFX_FRAME_IMPORT_INIT."""

    memory: int
    pix_fmt: int
    bpc: int
    w: int
    h: int
    n_planes: int
    plane: tuple[ImportPlane, ...]
    acquire: Fence
    flags: int

    @classmethod
    def from_c(cls, raw: VmafxFrameImport) -> FrameImport:
        return cls(
            memory=raw.memory,
            pix_fmt=raw.pix_fmt,
            bpc=raw.bpc,
            w=raw.w,
            h=raw.h,
            n_planes=raw.n_planes,
            plane=tuple(ImportPlane.from_c(x) for x in raw.plane),
            acquire=Fence.from_c(raw.acquire),
            flags=raw.flags,
        )


@dataclass(frozen=True)
class ModelConfig:
    """How to load a model. Initialise with VMAFX_MODEL_CONFIG_INIT."""

    name: str | None
    flags: int
    log_level: int

    @classmethod
    def from_c(cls, raw: VmafxModelConfig) -> ModelConfig:
        return cls(
            name=_text(raw.name),
            flags=raw.flags,
            log_level=raw.log_level,
        )


@dataclass(frozen=True)
class FrameDesc:
    """Geometry of a frame. Initialise with VMAFX_FRAME_DESC_INIT."""

    pix_fmt: int
    bpc: int
    w: int
    h: int

    @classmethod
    def from_c(cls, raw: VmafxFrameDesc) -> FrameDesc:
        return cls(
            pix_fmt=raw.pix_fmt,
            bpc=raw.bpc,
            w=raw.w,
            h=raw.h,
        )

    def to_c(self) -> VmafxFrameDesc:
        raw = VmafxFrameDesc()
        raw.struct_size = ctypes.sizeof(raw)
        raw.pix_fmt = self.pix_fmt
        raw.bpc = self.bpc
        raw.w = self.w
        raw.h = self.h
        return raw


@dataclass(frozen=True)
class HostPlanes:
    """Caller-owned host planes a frame borrows. Initialise with VMAFX_HOST_PLANES_INIT."""

    stride: tuple[int, ...]

    @classmethod
    def from_c(cls, raw: VmafxHostPlanes) -> HostPlanes:
        return cls(
            stride=tuple(raw.stride),
        )


@dataclass(frozen=True)
class FramePlanes:
    """Where the samples of a frame are. The data pointers live as long as the frame."""

    pix_fmt: int
    bpc: int
    n_planes: int
    w: tuple[int, ...]
    h: tuple[int, ...]
    stride: tuple[int, ...]

    @classmethod
    def from_c(cls, raw: VmafxFramePlanes) -> FramePlanes:
        return cls(
            pix_fmt=raw.pix_fmt,
            bpc=raw.bpc,
            n_planes=raw.n_planes,
            w=tuple(raw.w),
            h=tuple(raw.h),
            stride=tuple(raw.stride),
        )


@dataclass(frozen=True)
class PooledScore:
    """A score pooled over a range of frames."""

    pool: int
    first: int
    last: int
    value: float
    feature: str | None

    @classmethod
    def from_c(cls, raw: VmafxPooledScore) -> PooledScore:
        return cls(
            pool=raw.pool,
            first=raw.first,
            last=raw.last,
            value=raw.value,
            feature=_text(raw.feature),
        )


@dataclass(frozen=True)
class ModelSetScore:
    """The bootstrap score of a model set at one frame or pooled over frames."""

    pool: int
    first: int
    last: int
    bagging: float
    stddev: float
    ci95_lo: float
    ci95_hi: float
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxModelSetScore) -> ModelSetScore:
        return cls(
            pool=raw.pool,
            first=raw.first,
            last=raw.last,
            bagging=raw.bagging,
            stddev=raw.stddev,
            ci95_lo=raw.ci95_lo,
            ci95_hi=raw.ci95_hi,
            name=_text(raw.name),
        )


@dataclass(frozen=True)
class WindowRequest:
    """A window to pool. Initialise with VMAFX_WINDOW_REQUEST_INIT. Added in ABI 0.1.8."""

    target: int
    pool_mask: int
    first: int
    last: int
    feature: str | None

    @classmethod
    def from_c(cls, raw: VmafxWindowRequest) -> WindowRequest:
        return cls(
            target=raw.target,
            pool_mask=raw.pool_mask,
            first=raw.first,
            last=raw.last,
            feature=_text(raw.feature),
        )


@dataclass(frozen=True)
class WindowResult:
    """The scores of a completed window. Each value is the synchronous call's (vmafx_score_pooled(), vmafx_feature_score_pooled(), vmafx_score_pooled_model_set()) over frames `first` to `first + n_frames - 1`, bit for bit: both run one pooling implementation. Initialise with VMAFX_WINDOW_RESULT_INIT. Added in ABI 0.1.8."""

    status: int
    flags: int
    target: int
    pool_mask: int
    first: int
    last: int
    n_frames: int
    n_scored: int
    value: tuple[float, ...]
    stddev: tuple[float, ...]
    ci95_lo: tuple[float, ...]
    ci95_hi: tuple[float, ...]
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxWindowResult) -> WindowResult:
        return cls(
            status=raw.status,
            flags=raw.flags,
            target=raw.target,
            pool_mask=raw.pool_mask,
            first=raw.first,
            last=raw.last,
            n_frames=raw.n_frames,
            n_scored=raw.n_scored,
            value=tuple(raw.value),
            stddev=tuple(raw.stddev),
            ci95_lo=tuple(raw.ci95_lo),
            ci95_hi=tuple(raw.ci95_hi),
            name=_text(raw.name),
        )


@dataclass(frozen=True)
class WindowClockConfig:
    """Window length of a VmafxWindowClock: exactly one of the two is set, as the `window` option group's `n_stats` and `n_stats_frames` (#2138). Initialise with VMAFX_WINDOW_CLOCK_CONFIG_INIT. Added in ABI 0.1.8."""

    n_stats: float
    n_stats_frames: int

    @classmethod
    def from_c(cls, raw: VmafxWindowClockConfig) -> WindowClockConfig:
        return cls(
            n_stats=raw.n_stats,
            n_stats_frames=raw.n_stats_frames,
        )

    def to_c(self) -> VmafxWindowClockConfig:
        raw = VmafxWindowClockConfig()
        raw.struct_size = ctypes.sizeof(raw)
        raw.n_stats = self.n_stats
        raw.n_stats_frames = self.n_stats_frames
        return raw


@dataclass(frozen=True)
class WindowSpan:
    """One window of a stream as a VmafxWindowClock cut it: submit `first` to `last` with vmafx_window_submit(). Initialise with VMAFX_WINDOW_SPAN_INIT. Added in ABI 0.1.8."""

    flags: int
    window: int
    first: int
    last: int
    n_frames: int
    start_ns: int
    end_ns: int

    @classmethod
    def from_c(cls, raw: VmafxWindowSpan) -> WindowSpan:
        return cls(
            flags=raw.flags,
            window=raw.window,
            first=raw.first,
            last=raw.last,
            n_frames=raw.n_frames,
            start_ns=raw.start_ns,
            end_ns=raw.end_ns,
        )

    def to_c(self) -> VmafxWindowSpan:
        raw = VmafxWindowSpan()
        raw.struct_size = ctypes.sizeof(raw)
        raw.flags = self.flags
        raw.window = self.window
        raw.first = self.first
        raw.last = self.last
        raw.n_frames = self.n_frames
        raw.start_ns = self.start_ns
        raw.end_ns = self.end_ns
        return raw


@dataclass(frozen=True)
class Color:
    """Colour description of a frame; embedded by value, so it never grows. Added in ABI 0.1.6."""

    range: int
    primaries: int
    trc: int
    matrix: int

    @classmethod
    def from_c(cls, raw: VmafxColor) -> Color:
        return cls(
            range=raw.range,
            primaries=raw.primaries,
            trc=raw.trc,
            matrix=raw.matrix,
        )

    def to_c(self) -> VmafxColor:
        raw = VmafxColor()
        raw.range = self.range
        raw.primaries = self.primaries
        raw.trc = self.trc
        raw.matrix = self.matrix
        return raw


@dataclass(frozen=True)
class ConvertDesc:
    """What a frame converter reads and writes. Initialise with VMAFX_CONVERT_DESC_INIT. Added in ABI 0.1.6."""

    src_pix_fmt: int
    src_bpc: int
    src_w: int
    src_h: int
    src_color: Color
    dst_pix_fmt: int
    dst_bpc: int
    dst_w: int
    dst_h: int
    dst_color: Color
    filter: int

    @classmethod
    def from_c(cls, raw: VmafxConvertDesc) -> ConvertDesc:
        return cls(
            src_pix_fmt=raw.src_pix_fmt,
            src_bpc=raw.src_bpc,
            src_w=raw.src_w,
            src_h=raw.src_h,
            src_color=Color.from_c(raw.src_color),
            dst_pix_fmt=raw.dst_pix_fmt,
            dst_bpc=raw.dst_bpc,
            dst_w=raw.dst_w,
            dst_h=raw.dst_h,
            dst_color=Color.from_c(raw.dst_color),
            filter=raw.filter,
        )


@dataclass(frozen=True)
class DnnConfig:
    """How to open a tiny-AI session. Initialise with VMAFX_DNN_CONFIG_INIT. Added in ABI 0.1.6."""

    device: int
    device_index: int
    threads: int
    flags: int

    @classmethod
    def from_c(cls, raw: VmafxDnnConfig) -> DnnConfig:
        return cls(
            device=raw.device,
            device_index=raw.device_index,
            threads=raw.threads,
            flags=raw.flags,
        )

    def to_c(self) -> VmafxDnnConfig:
        raw = VmafxDnnConfig()
        raw.struct_size = ctypes.sizeof(raw)
        raw.device = self.device
        raw.device_index = self.device_index
        raw.threads = self.threads
        raw.flags = self.flags
        return raw


@dataclass(frozen=True)
class DnnInput:
    """One named input tensor of vmafx_dnn_session_run(), float32 in row-major order; the layout of a libvmaf VmafDnnInput, never grows. Added in ABI 0.1.6."""

    name: str | None
    rank: int

    @classmethod
    def from_c(cls, raw: VmafxDnnInput) -> DnnInput:
        return cls(
            name=_text(raw.name),
            rank=raw.rank,
        )


@dataclass(frozen=True)
class DnnOutput:
    """One named output tensor of vmafx_dnn_session_run(); the layout of a libvmaf VmafDnnOutput, never grows. Added in ABI 0.1.6."""

    name: str | None
    capacity: int
    written: int

    @classmethod
    def from_c(cls, raw: VmafxDnnOutput) -> DnnOutput:
        return cls(
            name=_text(raw.name),
            capacity=raw.capacity,
            written=raw.written,
        )


@dataclass(frozen=True)
class McpConfig:
    """How to create an MCP server. Initialise with VMAFX_MCP_CONFIG_INIT. Added in ABI 0.1.6."""

    queue_depth: int
    max_drain_per_frame: int
    user_agent: str | None

    @classmethod
    def from_c(cls, raw: VmafxMcpConfig) -> McpConfig:
        return cls(
            queue_depth=raw.queue_depth,
            max_drain_per_frame=raw.max_drain_per_frame,
            user_agent=_text(raw.user_agent),
        )


@dataclass(frozen=True)
class McpSseConfig:
    """The SSE transport. Initialise with VMAFX_MCP_SSE_CONFIG_INIT. Added in ABI 0.1.6."""

    port: int
    path: str | None

    @classmethod
    def from_c(cls, raw: VmafxMcpSseConfig) -> McpSseConfig:
        return cls(
            port=raw.port,
            path=_text(raw.path),
        )


@dataclass(frozen=True)
class McpUdsConfig:
    """The Unix domain socket transport. Initialise with VMAFX_MCP_UDS_CONFIG_INIT. Added in ABI 0.1.6."""

    path: str | None

    @classmethod
    def from_c(cls, raw: VmafxMcpUdsConfig) -> McpUdsConfig:
        return cls(
            path=_text(raw.path),
        )


@dataclass(frozen=True)
class McpStdioConfig:
    """The file-descriptor transport. Initialise with VMAFX_MCP_STDIO_CONFIG_INIT. Added in ABI 0.1.6."""

    fd_in: int
    fd_out: int

    @classmethod
    def from_c(cls, raw: VmafxMcpStdioConfig) -> McpStdioConfig:
        return cls(
            fd_in=raw.fd_in,
            fd_out=raw.fd_out,
        )

    def to_c(self) -> VmafxMcpStdioConfig:
        raw = VmafxMcpStdioConfig()
        raw.struct_size = ctypes.sizeof(raw)
        raw.fd_in = self.fd_in
        raw.fd_out = self.fd_out
        return raw


class Context:
    """A VmafxContext; close it with close() or a with-block."""

    def __init__(self, lib: ctypes.CDLL, config: ContextConfig | None = None) -> None:
        self._lib = lib
        raw = config.to_c() if config is not None else None
        handle = ctypes.c_void_p()
        error = ctypes.c_void_p()
        pointer = ctypes.byref(raw) if raw is not None else None
        status = lib.vmafx_context_create(pointer, ctypes.byref(handle), ctypes.byref(error))
        _raise(lib, status, error, "vmafx_context_create")
        self._handle = handle

    def __enter__(self) -> Context:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    def close(self) -> None:
        """Destroy the context; on failure it stays open and close() may be retried."""
        if not self._handle:
            return
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_destroy(self._handle, ctypes.byref(error))
        _raise(self._lib, status, error, "vmafx_context_destroy")
        self._handle = ctypes.c_void_p()

    def libvmaf_handle(self) -> int:
        """The libvmaf VmafContext * bound to this context, for calls not yet migrated."""
        return self._lib.vmafx_context_libvmaf_handle(self._handle)

    def provenance(self) -> Provenance:
        """Fill the provenance record of a context."""
        out = VmafxProvenance()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_provenance(
            self._handle, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_provenance")
        return Provenance.from_c(out)

    def extractor_info(self, index: int) -> ExtractorInfo:
        """Describe registered extractor `index`; VMAFX_E_NOTFOUND past the last one."""
        out = VmafxExtractorInfo()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_extractor_info(
            self._handle, index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_extractor_info")
        return ExtractorInfo.from_c(out)

    def feature_score(self, feature: str, index: int) -> Score:
        """Score of `feature` at frame `index` with its producer; VMAFX_PENDING while the frame is not final."""
        out = VmafxScore()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_feature_score(
            self._handle, feature.encode(), index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_feature_score")
        return Score.from_c(out)

    def set_option(self, key: str, value: str) -> None:
        """Set a context option: `perceptual_weight` (`0` / `1`) or `perceptual_weight_strength` (a finite number >= 0). VMAFX_E_NOTFOUND names an unknown key, VMAFX_E_INVALID a value the key refuses."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_set_option(
            self._handle, key.encode(), value.encode(), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_set_option")
        return None

    def import_score(self, feature: str, index: int, value: float) -> None:
        """Record `value` as the score of `feature` at frame `index`, computed outside the library."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_import_score(
            self._handle, feature.encode(), index, value, ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_import_score")
        return None

    def flush(self) -> None:
        """Finish every submitted frame; scores of the last frames (motion) become final. A context is flushed once; a second flush or a submit after it is VMAFX_E_INVALID."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_flush(self._handle, ctypes.byref(error))
        _raise(self._lib, status, error, "vmafx_flush")
        return None

    def feature_score_pooled(self, feature: str, pool: int, first: int, last: int) -> PooledScore:
        """Scores of `feature` pooled as vmafx_score_pooled() does."""
        out = VmafxPooledScore()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_feature_score_pooled(
            self._handle,
            feature.encode(),
            pool,
            first,
            last,
            ctypes.byref(out),
            ctypes.byref(error),
        )
        _raise(self._lib, status, error, "vmafx_feature_score_pooled")
        return PooledScore.from_c(out)

    def model_provenance(self, index: int) -> ModelProvenance:
        """Describe mounted model `index` (models of vmafx_context_use_model() and vmafx_context_use_model_set(), and models mounted through the libvmaf API), in mount order; VMAFX_E_NOTFOUND past the last one. Added in ABI 0.1.5."""
        out = VmafxModelProvenance()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_model_provenance(
            self._handle, index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_model_provenance")
        return ModelProvenance.from_c(out)

    def feature_provenance(self, index: int) -> FeatureProvenance:
        """Describe feature `index` of the context, features in byte order of their names; VMAFX_E_NOTFOUND past the last one. Added in ABI 0.1.5."""
        out = VmafxFeatureProvenance()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_feature_provenance(
            self._handle, index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_feature_provenance")
        return FeatureProvenance.from_c(out)

    def feature_provenance(self, feature: str) -> FeatureProvenance:
        """Describe the feature named `feature` (as the scores carry it, option-decorated names included); VMAFX_E_NOTFOUND when the context has no score of it. Added in ABI 0.1.5."""
        out = VmafxFeatureProvenance()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_feature_provenance(
            self._handle, feature.encode(), ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_feature_provenance")
        return FeatureProvenance.from_c(out)

    def annotate(self, key: str, value: str) -> None:
        """Add `key` = `value` (both copied) to the context's provenance record, for what only the caller knows: the inputs, the command line. A key may repeat; annotations keep their order. VMAFX_E_INVALID names a key outside 1 to 64 characters of `a-z`, `0-9` and `_`, VMAFX_E_RANGE a value over 4096 bytes or the 257th annotation. Added in ABI 0.1.5."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_annotate(
            self._handle, key.encode(), value.encode(), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_annotate")
        return None

    def annotation(self, index: int) -> Annotation:
        """Annotation `index` of the context, in the order added; VMAFX_E_NOTFOUND past the last one. Added in ABI 0.1.5."""
        out = VmafxAnnotation()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_annotation(
            self._handle, index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_annotation")
        return Annotation.from_c(out)

    def set_encode_record(self, record: str) -> None:
        """Record the digest of the encode record of the distorted input (VMAFx/pelorus#81): `sha256:` and 64 lower-case hex digits, copied; NULL or empty clears it. VMAFX_E_INVALID names any other form. Added in ABI 0.1.5."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_set_encode_record(
            self._handle, record.encode(), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_set_encode_record")
        return None

    def report_write(self, path: str, format: int, flags: int, score_format: str) -> None:
        """Write the context's scores to `path` in `format` (VmafxReportFormat), numbers with `score_format` (a printf format of one double; NULL: `%.6f`). JSON and XML carry the provenance record; CSV and SUB keep their columns. `flags` (VmafxReportFlags) may also ask for a `<path>.provenance.json` sidecar. Added in ABI 0.1.5."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_report_write(
            self._handle, path.encode(), format, flags, score_format.encode(), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_report_write")
        return None

    def set_codec_context(self, codec: str, preset: str, crf: int) -> None:
        """The encoder `codec` (may be NULL), its `preset` (may be NULL) and `crf` that a codec-aware tiny model attached to the context reads. Added in ABI 0.1.6."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_set_codec_context(
            self._handle, codec.encode(), preset.encode(), crf, ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_set_codec_context")
        return None

    def set_tiny_resize(self, mode: int) -> None:
        """How frames are resized to the fixed input shape of the attached tiny model (VmafxDnnResize). Added in ABI 0.1.6."""
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_set_tiny_resize(self._handle, mode, ctypes.byref(error))
        _raise(self._lib, status, error, "vmafx_context_set_tiny_resize")
        return None


class Library:
    """The loaded VMAFx library."""

    def __init__(self, path: str | None = None) -> None:
        self._lib = load(path)

    @property
    def raw(self) -> ctypes.CDLL:
        """The ctypes library, for calls the binding does not wrap."""
        return self._lib

    def context(self, config: ContextConfig | None = None) -> Context:
        """Create a context."""
        return Context(self._lib, config)

    def version_string(self) -> str | None:
        """Build version (git describe); valid for the process lifetime."""
        return _text(self._lib.vmafx_version_string())

    def abi_version(self) -> tuple[int, ...]:
        """ABI version of the loaded library. Each pointer may be NULL."""
        major = ctypes.c_uint32()
        minor = ctypes.c_uint32()
        patch = ctypes.c_uint32()
        self._lib.vmafx_abi_version(ctypes.byref(major), ctypes.byref(minor), ctypes.byref(patch))
        return (major.value, minor.value, patch.value)

    def status_name(self, status: int) -> str | None:
        """Name of a status code (`VMAFX_E_INVALID`), or `VMAFX_UNKNOWN_STATUS`."""
        return _text(self._lib.vmafx_status_name(status))

    def model_builtin_next(self, previous: str | None) -> str | None:
        """The built-in model version after `previous`, the first one for NULL, NULL after the last or for an unknown `previous`. Built-in model sets are listed too."""
        return _text(self._lib.vmafx_model_builtin_next(previous))

    def model_default_version(self) -> str | None:
        """Version of the default model (`vmaf_v1.0.16_3d0h`)."""
        return _text(self._lib.vmafx_model_default_version())

    def backend_name(self, backend: int) -> str | None:
        """Lower-case name of a VmafxBackend (`cpu`, `cuda`, `sycl`, `metal`, `hip`), `unknown` for another value; a static string. Added in ABI 0.1.6."""
        return _text(self._lib.vmafx_backend_name(backend))


_check_layout()
