# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
#
# GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
# Do not edit: change the definition and run
# `python3 scripts/codegen/vmafx-api.py --write`.
"""ctypes binding of the VMAFx C API (generated)."""

from __future__ import annotations

import ctypes
import enum
import os
from dataclasses import dataclass

ABI_VERSION = (0, 1, 0)


class Status(enum.IntEnum):
    """VmafxStatus codes."""

    OK = 0
    PENDING = 1
    E_INVALID = -1
    E_NOMEM = -2
    E_NOTSUP = -3
    E_NOTFOUND = -4
    E_BUSY = -5
    E_DEVICE = -6
    E_IO = -7
    E_RANGE = -8
    E_INTERNAL = -9


class LogLevel(enum.IntEnum):
    """VmafxLogLevel."""

    NONE = 0
    ERROR = 1
    WARNING = 2
    INFO = 3
    DEBUG = 4


class Backend(enum.IntEnum):
    """VmafxBackend."""

    CPU = 0
    CUDA = 1
    SYCL = 2
    METAL = 3
    HIP = 4


class VmafxContextConfig(ctypes.Structure):
    _fields_ = (
        ("struct_size", ctypes.c_uint32),
        ("log_level", ctypes.c_uint32),
        ("n_threads", ctypes.c_uint32),
        ("n_subsample", ctypes.c_uint32),
        ("cpumask", ctypes.c_uint64),
        ("gpumask", ctypes.c_uint64),
    )


class VmafxProvenance(ctypes.Structure):
    _fields_ = (
        ("struct_size", ctypes.c_uint32),
        ("abi_major", ctypes.c_uint32),
        ("abi_minor", ctypes.c_uint32),
        ("abi_patch", ctypes.c_uint32),
        ("active_backend", ctypes.c_uint32),
        ("n_extractors", ctypes.c_uint32),
        ("version", ctypes.c_char_p),
    )


class VmafxExtractorInfo(ctypes.Structure):
    _fields_ = (
        ("struct_size", ctypes.c_uint32),
        ("backend", ctypes.c_uint32),
        ("name", ctypes.c_char_p),
    )


class VmafxScore(ctypes.Structure):
    _fields_ = (
        ("struct_size", ctypes.c_uint32),
        ("backend", ctypes.c_uint32),
        ("index", ctypes.c_uint64),
        ("value", ctypes.c_double),
        ("feature", ctypes.c_char_p),
        ("extractor", ctypes.c_char_p),
    )


LAYOUT = {
    VmafxContextConfig: (
        32,
        (
            ("struct_size", 0),
            ("log_level", 4),
            ("n_threads", 8),
            ("n_subsample", 12),
            ("cpumask", 16),
            ("gpumask", 24),
        ),
    ),
    VmafxProvenance: (
        32,
        (
            ("struct_size", 0),
            ("abi_major", 4),
            ("abi_minor", 8),
            ("abi_patch", 12),
            ("active_backend", 16),
            ("n_extractors", 20),
            ("version", 24),
        ),
    ),
    VmafxExtractorInfo: (
        16,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("name", 8),
        ),
    ),
    VmafxScore: (
        40,
        (
            ("struct_size", 0),
            ("backend", 4),
            ("index", 8),
            ("value", 16),
            ("feature", 24),
            ("extractor", 32),
        ),
    ),
}


SIGNATURES = {
    "vmafx_version_string": (
        ctypes.c_char_p,
        (),
    ),
    "vmafx_abi_version": (
        None,
        (
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_uint32),
            ctypes.POINTER(ctypes.c_uint32),
        ),
    ),
    "vmafx_status_name": (
        ctypes.c_char_p,
        (ctypes.c_int32,),
    ),
    "vmafx_error_status": (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_message": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_subject": (
        ctypes.c_char_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_errno": (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    "vmafx_error_free": (
        None,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_create": (
        ctypes.c_int32,
        (
            ctypes.POINTER(VmafxContextConfig),
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_destroy": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_provenance": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.POINTER(VmafxProvenance),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_extractor_info": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.POINTER(VmafxExtractorInfo),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_feature_score": (
        ctypes.c_int32,
        (
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.c_uint64,
            ctypes.POINTER(VmafxScore),
            ctypes.POINTER(ctypes.c_void_p),
        ),
    ),
    "vmafx_context_from_libvmaf": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    "vmafx_context_libvmaf_handle": (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
}


class VmafxError(Exception):
    """A failed VMAFx call: status, message, the named subject and the engine's errno."""

    def __init__(
        self, function: str, status: int, message: str, subject: str, errno_value: int
    ) -> None:
        self.function = function
        self.status = status
        self.message = message
        self.subject = subject
        self.errno = errno_value
        name = Status(status).name if status in Status.__members__.values() else str(status)
        detail = f" [{subject}]" if subject else ""
        super().__init__(f"{function}: {name}: {message}{detail}")


class VmafxPending(VmafxError):
    """The requested score is not final yet (VMAFX_PENDING)."""


def _text(raw: bytes | None) -> str | None:
    return raw.decode() if raw is not None else None


def _check_layout() -> None:
    """Refuse a binding whose structs disagree with the definition's layout."""
    for struct, (size, offsets) in LAYOUT.items():
        if ctypes.sizeof(struct) != size:
            raise ImportError(f"{struct.__name__}: size {ctypes.sizeof(struct)} != {size}")
        for name, offset in offsets:
            actual = getattr(struct, name).offset
            if actual != offset:
                raise ImportError(f"{struct.__name__}.{name}: offset {actual} != {offset}")


def load(path: str | None = None) -> ctypes.CDLL:
    """Load the library from `path` or $VMAFX_LIBRARY. There is no search fallback."""
    chosen = path or os.environ.get("VMAFX_LIBRARY")
    if not chosen:
        raise OSError("set VMAFX_LIBRARY or pass the path of the VMAFx shared library")
    lib = ctypes.CDLL(chosen)
    for name, (restype, argtypes) in SIGNATURES.items():
        function = getattr(lib, name)
        function.restype = restype
        function.argtypes = argtypes
    return lib


def _raise(lib: ctypes.CDLL, status: int, error: ctypes.c_void_p, function: str) -> None:
    if status == Status.OK:
        return
    message = _text(lib.vmafx_error_message(error)) or ""
    subject = _text(lib.vmafx_error_subject(error)) or ""
    errno_value = lib.vmafx_error_errno(error)
    lib.vmafx_error_free(error)
    kind = VmafxPending if status == Status.PENDING else VmafxError
    raise kind(function, status, message, subject, errno_value)


@dataclass(frozen=True)
class ContextConfig:
    """Context configuration. Initialise with VMAFX_CONTEXT_CONFIG_INIT."""

    log_level: int
    n_threads: int
    n_subsample: int
    cpumask: int
    gpumask: int

    @classmethod
    def from_c(cls, raw: VmafxContextConfig) -> ContextConfig:
        return cls(
            log_level=raw.log_level,
            n_threads=raw.n_threads,
            n_subsample=raw.n_subsample,
            cpumask=raw.cpumask,
            gpumask=raw.gpumask,
        )

    def to_c(self) -> VmafxContextConfig:
        raw = VmafxContextConfig()
        raw.struct_size = ctypes.sizeof(raw)
        raw.log_level = self.log_level
        raw.n_threads = self.n_threads
        raw.n_subsample = self.n_subsample
        raw.cpumask = self.cpumask
        raw.gpumask = self.gpumask
        return raw


@dataclass(frozen=True)
class Provenance:
    """How the scores of a context are made (#2142). Strings live as long as the context."""

    abi_major: int
    abi_minor: int
    abi_patch: int
    active_backend: int
    n_extractors: int
    version: str | None

    @classmethod
    def from_c(cls, raw: VmafxProvenance) -> Provenance:
        return cls(
            abi_major=raw.abi_major,
            abi_minor=raw.abi_minor,
            abi_patch=raw.abi_patch,
            active_backend=raw.active_backend,
            n_extractors=raw.n_extractors,
            version=_text(raw.version),
        )


@dataclass(frozen=True)
class ExtractorInfo:
    """One registered feature extractor."""

    backend: int
    name: str | None

    @classmethod
    def from_c(cls, raw: VmafxExtractorInfo) -> ExtractorInfo:
        return cls(
            backend=raw.backend,
            name=_text(raw.name),
        )


@dataclass(frozen=True)
class Score:
    """One score and the extractor that produced it."""

    backend: int
    index: int
    value: float
    feature: str | None
    extractor: str | None

    @classmethod
    def from_c(cls, raw: VmafxScore) -> Score:
        return cls(
            backend=raw.backend,
            index=raw.index,
            value=raw.value,
            feature=_text(raw.feature),
            extractor=_text(raw.extractor),
        )


class Context:
    """A VmafxContext; close it with close() or a with-block."""

    def __init__(self, lib: ctypes.CDLL, config: ContextConfig | None = None) -> None:
        self._lib = lib
        raw = config.to_c() if config is not None else None
        handle = ctypes.c_void_p()
        error = ctypes.c_void_p()
        pointer = ctypes.byref(raw) if raw is not None else None
        status = lib.vmafx_context_create(pointer, ctypes.byref(handle), ctypes.byref(error))
        _raise(lib, status, error, "vmafx_context_create")
        self._handle = handle

    def __enter__(self) -> Context:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    def close(self) -> None:
        """Destroy the context; on failure it stays open and close() may be retried."""
        if not self._handle:
            return
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_destroy(self._handle, ctypes.byref(error))
        _raise(self._lib, status, error, "vmafx_context_destroy")
        self._handle = ctypes.c_void_p()

    def libvmaf_handle(self) -> int:
        """The libvmaf VmafContext * bound to this context, for calls not yet migrated."""
        return self._lib.vmafx_context_libvmaf_handle(self._handle)

    def provenance(self) -> Provenance:
        """Fill the provenance record of a context."""
        out = VmafxProvenance()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_provenance(
            self._handle, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_provenance")
        return Provenance.from_c(out)

    def extractor_info(self, index: int) -> ExtractorInfo:
        """Describe registered extractor `index`; VMAFX_E_NOTFOUND past the last one."""
        out = VmafxExtractorInfo()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_context_extractor_info(
            self._handle, index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_context_extractor_info")
        return ExtractorInfo.from_c(out)

    def feature_score(self, feature: str, index: int) -> Score:
        """Score of `feature` at frame `index` with its producer; VMAFX_PENDING while the frame is not final."""
        out = VmafxScore()
        out.struct_size = ctypes.sizeof(out)
        error = ctypes.c_void_p()
        status = self._lib.vmafx_feature_score(
            self._handle, feature.encode(), index, ctypes.byref(out), ctypes.byref(error)
        )
        _raise(self._lib, status, error, "vmafx_feature_score")
        return Score.from_c(out)


class Library:
    """The loaded VMAFx library."""

    def __init__(self, path: str | None = None) -> None:
        self._lib = load(path)

    @property
    def raw(self) -> ctypes.CDLL:
        """The ctypes library, for calls the binding does not wrap."""
        return self._lib

    def context(self, config: ContextConfig | None = None) -> Context:
        """Create a context."""
        return Context(self._lib, config)

    def version_string(self) -> str | None:
        """Build version (git describe); valid for the process lifetime."""
        return _text(self._lib.vmafx_version_string())

    def abi_version(self) -> tuple[int, ...]:
        """ABI version of the loaded library. Each pointer may be NULL."""
        major = ctypes.c_uint32()
        minor = ctypes.c_uint32()
        patch = ctypes.c_uint32()
        self._lib.vmafx_abi_version(ctypes.byref(major), ctypes.byref(minor), ctypes.byref(patch))
        return (major.value, minor.value, patch.value)

    def status_name(self, status: int) -> str | None:
        """Name of a status code (`VMAFX_E_INVALID`), or `VMAFX_UNKNOWN_STATUS`."""
        return _text(self._lib.vmafx_status_name(status))


_check_layout()
