// Copyright 2026 Lusoris
// SPDX-License-Identifier: EUPL-1.2
//
// build.rs — generate the C header for the TAD extractor via cbindgen.
//
// The generated header is written to `$OUT_DIR/include/vmafx_tad.h`.
// The Meson custom_target (core/src/meson.build) copies this file into
// the build tree so the C-side wrapper (tad_rust.c) can #include it.

use std::env;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let crate_dir = env::var("CARGO_MANIFEST_DIR")?;
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);

    let include_dir = out_dir.join("include");
    std::fs::create_dir_all(&include_dir)?;

    let header_path = include_dir.join("vmafx_tad.h");

    let wrote_header = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("VMAFX_TAD_H")
        .with_header(concat!(
            "/**\n",
            " * vmafx_tad.h — generated by cbindgen (ADR-0707).\n",
            " * DO NOT EDIT — regenerate via `cargo build` inside the tad crate.\n",
            " *\n",
            " * Copyright 2026 Lusoris\n",
            // REUSE-IgnoreStart
            " * SPDX-License-Identifier: EUPL-1.2\n",
            // REUSE-IgnoreEnd
            " */",
        ))
        .generate()?
        .write_to_file(&header_path);
    if !wrote_header {
        return Err(std::io::Error::other("failed to write generated TAD header").into());
    }

    // Tell Cargo to rerun build.rs only when the library sources change.
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=build.rs");

    // Expose OUT_DIR/include to the crate itself (not strictly needed since
    // this is a pure Rust crate, but makes the path available for scripts).
    println!("cargo:include={}", include_dir.display());
    Ok(())
}
