// Copyright 2026 Lusoris
// SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
//
// pkg/pyjson/pyjson_test.go — CPython parity tests for the JSON encoder.
//
// The expected strings in TestFloatRepr were generated by running
// repr(float(x)) under CPython 3 for each input and pasting the result, so the
// table is evidence of parity rather than a restatement of the Go
// implementation. The hand-picked head covers every branch of the
// fixed-vs-exponential switch (decpt <= -4, decpt > 16), subnormals, negative
// zero, and 17-significant-digit round-trips; the tail is a deterministic
// sample of random IEEE-754 doubles.

package pyjson

import (
	"math"
	"strconv"
	"strings"
	"testing"
)

func TestFloatRepr(t *testing.T) {
	t.Parallel()

	tests := []struct {
		in   float64
		want string
	}{
		{in: 0.0, want: "0.0"},
		{in: math.Copysign(0, -1), want: "-0.0"},
		{in: 1.0, want: "1.0"},
		{in: 24.0, want: "24.0"},
		{in: 23.976, want: "23.976"},
		{in: 0.1, want: "0.1"},
		{in: 1e16, want: "1e+16"},
		{in: 1e15, want: "1000000000000000.0"},
		{in: 1e-5, want: "1e-05"},
		{in: 0.0001, want: "0.0001"},
		{in: 1.5e-7, want: "1.5e-07"},
		{in: 123456789012345.0, want: "123456789012345.0"},
		{in: 1234567890123456.0, want: "1234567890123456.0"},
		{in: 12345678901234567.0, want: "1.2345678901234568e+16"},
		{in: 3.141592653589793, want: "3.141592653589793"},
		{in: -2.5, want: "-2.5"},
		{in: 1e300, want: "1e+300"},
		{in: 5e-324, want: "5e-324"},
		{in: 2.2250738585072014e-308, want: "2.2250738585072014e-308"},
		{in: 100.0, want: "100.0"},
		{in: 0.5, want: "0.5"},
		{in: 1e17, want: "1e+17"},
		{in: 9.99999999999999e15, want: "9999999999999990.0"},
		{in: 1e-323, want: "1e-323"},
		{in: -1e-7, want: "-1e-07"},
		{in: 0.30000000000000004, want: "0.30000000000000004"},
		{in: 1234.5678, want: "1234.5678"},
		{in: 1e22, want: "1e+22"},
		{in: 1e-22, want: "1e-22"},
		{in: -1.029321421473029e+287, want: "-1.029321421473029e+287"},
		{in: -4.051599009329648e-256, want: "-4.051599009329648e-256"},
		{in: -3.638449391783954e-299, want: "-3.638449391783954e-299"},
		{in: -4.496274314197459e+72, want: "-4.496274314197459e+72"},
		{in: 3.88585941555665e-223, want: "3.88585941555665e-223"},
		{in: 1.7072069967245014e+300, want: "1.7072069967245014e+300"},
		{in: 3.3597038441834e-290, want: "3.3597038441834e-290"},
		{in: -8.585278454063701e+161, want: "-8.585278454063701e+161"},
		{in: -3.381660136101574e+49, want: "-3.381660136101574e+49"},
		{in: -1.1334275671346567e-165, want: "-1.1334275671346567e-165"},
		{in: 7.353703576331801e-308, want: "7.353703576331801e-308"},
		{in: -3.4444893728777614e-32, want: "-3.4444893728777614e-32"},
		{in: 1.5000202283672719e+57, want: "1.5000202283672719e+57"},
		{in: -4.52780643492962e-257, want: "-4.52780643492962e-257"},
		{in: 2.1775810416614333e-37, want: "2.1775810416614333e-37"},
		{in: math.NaN(), want: "nan"},
		{in: math.Inf(1), want: "inf"},
		{in: math.Inf(-1), want: "-inf"},
	}

	for _, tc := range tests {
		if got := FloatRepr(tc.in); got != tc.want {
			t.Errorf("FloatRepr(%v) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestFloatReprRoundTrips(t *testing.T) {
	t.Parallel()

	// Every finite repr must parse back to the identical double — that is
	// the property CPython's shortest-repr algorithm guarantees and the one
	// downstream trainers rely on when re-reading a corpus.
	values := []float64{
		0, 1, -1, 0.1, 1.0 / 3.0, 1e-300, 1e300, 6.02214076e23,
		math.MaxFloat64, math.SmallestNonzeroFloat64, 23.976023976023978,
	}
	for _, v := range values {
		s := FloatRepr(v)
		back, err := strconv.ParseFloat(s, 64)
		if err != nil {
			t.Fatalf("re-parse %q: %v", s, err)
		}
		if back != v {
			t.Errorf("FloatRepr(%v) = %q re-parsed to %v", v, s, back)
		}
	}
}

func TestMarshalSorted(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		row  map[string]any
		want string
	}{
		{
			name: "keys are sorted and floats use repr",
			row: map[string]any{
				"zebra":     1,
				"alpha":     "a",
				"framerate": 24.0,
			},
			want: `{"alpha": "a", "framerate": 24.0, "zebra": 1}`,
		},
		{
			name: "non-finite floats use the bare CPython tokens",
			row: map[string]any{
				"adm2_mean": math.NaN(),
				"pos":       math.Inf(1),
				"neg":       math.Inf(-1),
			},
			want: `{"adm2_mean": NaN, "neg": -Infinity, "pos": Infinity}`,
		},
		{
			name: "string lists and booleans",
			row: map[string]any{
				"extra_params": []string{"-vf", "scale=640:480"},
				"hdr_forced":   false,
			},
			want: `{"extra_params": ["-vf", "scale=640:480"], "hdr_forced": false}`,
		},
		{
			name: "empty list renders as []",
			row:  map[string]any{"extra_params": []string{}},
			want: `{"extra_params": []}`,
		},
		{
			name: "non-ascii is escaped like ensure_ascii=True",
			row:  map[string]any{"src": "clip-\u00e9.yuv"},
			want: `{"src": "clip-\u00e9.yuv"}`,
		},
		{
			name: "astral plane uses a surrogate pair",
			row:  map[string]any{"src": "clip-\U0001F3AC.yuv"},
			want: `{"src": "clip-\ud83c\udfac.yuv"}`,
		},
		{
			name: "control characters use the short escapes",
			row:  map[string]any{"stderr": "a\nb\tc\"d\\e"},
			want: `{"stderr": "a\nb\tc\"d\\e"}`,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, err := MarshalSorted(tc.row)
			if err != nil {
				t.Fatalf("MarshalRowSorted: %v", err)
			}
			if got != tc.want {
				t.Errorf("MarshalSorted() =\n  %s\nwant\n  %s", got, tc.want)
			}
		})
	}
}

func TestMarshalSortedRejectsUnsupportedTypes(t *testing.T) {
	t.Parallel()

	if _, err := MarshalSorted(map[string]any{"x": struct{}{}}); err == nil {
		t.Fatal("MarshalRowSorted accepted an unsupported value type")
	}
}

func TestSanitizeNonFinite(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		line string
		// wantSentinels counts how many bare tokens should have been
		// rewritten.
		wantSentinels int
	}{
		{name: "no tokens", line: `{"a": 1}`, wantSentinels: 0},
		{name: "one NaN", line: `{"a": NaN}`, wantSentinels: 1},
		{name: "all three", line: `{"a": NaN, "b": Infinity, "c": -Infinity}`, wantSentinels: 3},
		{
			name:          "token inside a string is untouched",
			line:          `{"a": "NaN was here", "b": NaN}`,
			wantSentinels: 1,
		},
		{
			name:          "escaped quote does not end the string early",
			line:          `{"a": "quote \" then NaN", "b": Infinity}`,
			wantSentinels: 1,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := SanitizeNonFinite(tc.line)
			n := strings.Count(got, "vmafx-")
			if n != tc.wantSentinels {
				t.Errorf("SanitizeNonFinite(%s) produced %d sentinels, want %d (got %s)",
					tc.line, n, tc.wantSentinels, got)
			}
		})
	}
}
