// Copyright 2026 Lusoris
// SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
//
// pkg/pyjson/pyjson_test.go — CPython parity tests for the float spelling and
// the non-finite token reader.
//
// The expected strings in the repr tables were generated by running
// repr(float(x)) under CPython 3 for each input and pasting the result, so
// the tables are evidence of parity rather than a restatement of the Go
// implementation. The hand-picked head covers every branch of the
// fixed-vs-exponential switch (decpt <= -4, decpt > 16), subnormals, negative
// zero, and 17-significant-digit round-trips; the tail is a deterministic
// sample of random IEEE-754 doubles.

package pyjson

import (
	"encoding/json"
	"math"
	"strconv"
	"strings"
	"testing"
)

func TestFloatRepr(t *testing.T) {
	t.Parallel()

	tests := []struct {
		in   float64
		want string
	}{
		{in: 0.0, want: "0.0"},
		{in: math.Copysign(0, -1), want: "-0.0"},
		{in: 1.0, want: "1.0"},
		{in: 24.0, want: "24.0"},
		{in: 23.976, want: "23.976"},
		{in: 0.1, want: "0.1"},
		{in: 1e16, want: "1e+16"},
		{in: 1e15, want: "1000000000000000.0"},
		{in: 1e-5, want: "1e-05"},
		{in: 0.0001, want: "0.0001"},
		{in: 1.5e-7, want: "1.5e-07"},
		{in: 123456789012345.0, want: "123456789012345.0"},
		{in: 1234567890123456.0, want: "1234567890123456.0"},
		{in: 12345678901234567.0, want: "1.2345678901234568e+16"},
		{in: 3.141592653589793, want: "3.141592653589793"},
		{in: -2.5, want: "-2.5"},
		{in: 1e300, want: "1e+300"},
		{in: 5e-324, want: "5e-324"},
		{in: 2.2250738585072014e-308, want: "2.2250738585072014e-308"},
		{in: 100.0, want: "100.0"},
		{in: 0.5, want: "0.5"},
		{in: 1e17, want: "1e+17"},
		{in: 9.99999999999999e15, want: "9999999999999990.0"},
		{in: 1e-323, want: "1e-323"},
		{in: -1e-7, want: "-1e-07"},
		{in: 0.30000000000000004, want: "0.30000000000000004"},
		{in: 1234.5678, want: "1234.5678"},
		{in: 1e22, want: "1e+22"},
		{in: 1e-22, want: "1e-22"},
		{in: -1.029321421473029e+287, want: "-1.029321421473029e+287"},
		{in: -4.051599009329648e-256, want: "-4.051599009329648e-256"},
		{in: -3.638449391783954e-299, want: "-3.638449391783954e-299"},
		{in: -4.496274314197459e+72, want: "-4.496274314197459e+72"},
		{in: 3.88585941555665e-223, want: "3.88585941555665e-223"},
		{in: 1.7072069967245014e+300, want: "1.7072069967245014e+300"},
		{in: 3.3597038441834e-290, want: "3.3597038441834e-290"},
		{in: -8.585278454063701e+161, want: "-8.585278454063701e+161"},
		{in: -3.381660136101574e+49, want: "-3.381660136101574e+49"},
		{in: -1.1334275671346567e-165, want: "-1.1334275671346567e-165"},
		{in: 7.353703576331801e-308, want: "7.353703576331801e-308"},
		{in: -3.4444893728777614e-32, want: "-3.4444893728777614e-32"},
		{in: 1.5000202283672719e+57, want: "1.5000202283672719e+57"},
		{in: -4.52780643492962e-257, want: "-4.52780643492962e-257"},
		{in: 2.1775810416614333e-37, want: "2.1775810416614333e-37"},
		// Boundaries the benchmark / encode-profile port pinned separately.
		{in: 92.0, want: "92.0"},
		{in: -3.0, want: "-3.0"},
		{in: 123.456, want: "123.456"},
		{in: -3.25, want: "-3.25"},
		{in: 1.0 / 3.0, want: "0.3333333333333333"},
		{in: 999999.0, want: "999999.0"},
		{in: 1e6, want: "1000000.0"},
		{in: 1234567.0, want: "1234567.0"},
		{in: 9999999999999998.0, want: "9999999999999998.0"},
		{in: 2.5e-10, want: "2.5e-10"},
		{in: 1e100, want: "1e+100"},
		{in: math.MaxFloat64, want: "1.7976931348623157e+308"},
		{in: 1828.686011867366, want: "1828.686011867366"},
		{in: 1828.6860118673662, want: "1828.6860118673662"},
		{in: math.NaN(), want: "nan"},
		{in: math.Inf(1), want: "inf"},
		{in: math.Inf(-1), want: "-inf"},
	}

	for _, tc := range tests {
		if got := FloatRepr(tc.in); got != tc.want {
			t.Errorf("FloatRepr(%v) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestFloatReprRoundTrips(t *testing.T) {
	t.Parallel()

	// Every finite repr must parse back to the identical double — that is
	// the property CPython's shortest-repr algorithm guarantees and the one
	// downstream trainers rely on when re-reading a corpus.
	values := []float64{
		0, 1, -1, 0.1, 1.0 / 3.0, 1e-300, 1e300, 6.02214076e23,
		math.MaxFloat64, math.SmallestNonzeroFloat64, 23.976023976023978,
		92.5, -1e-7, math.Pi, 1e16, 1e-5, 0.0001, 1234567.0, -0.30000000000000004,
	}
	for _, v := range values {
		s := FloatRepr(v)
		back, err := strconv.ParseFloat(s, 64)
		if err != nil {
			t.Fatalf("re-parse %q: %v", s, err)
		}
		if back != v {
			t.Errorf("FloatRepr(%v) = %q re-parsed to %v", v, s, back)
		}
		var viaJSON float64
		if err := json.Unmarshal([]byte(s), &viaJSON); err != nil {
			t.Fatalf("FloatRepr(%v) = %q is not valid JSON: %v", v, s, err)
		}
	}
}

// TestFormatFloatMatchesCPythonRepr pins the four ways CPython's repr()
// differs from Go's %g inside json.dumps: the mandatory ".0" on integral
// values, the fixed/exponential switch at decpt <= -4 || decpt > 16, the
// two-digit exponent, and the bare non-finite tokens.
func TestFormatFloatMatchesCPythonRepr(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   float64
		want string
	}{
		{"zero gains a .0", 0, "0.0"},
		{"negative zero keeps its sign", math.Copysign(0, -1), "-0.0"},
		{"integral value gains a .0", 1, "1.0"},
		{"integral negative", -42, "-42.0"},
		{"typical VMAF score", 93.5, "93.5"},
		{"shortest round-trip digits", 0.1, "0.1"},
		{"long mantissa", 1828.686011867366, "1828.686011867366"},
		{"seventeen-digit mantissa", 1828.6860118673662, "1828.6860118673662"},
		{"800", 800.0, "800.0"},
		{"1000000", 1000000.0, "1000000.0"},
		// The fixed/exponential switch. Go's %g flips at 1e15; CPython at 1e16.
		{"1e15 stays fixed", 1e15, "1000000000000000.0"},
		{"1e16 goes exponential", 1e16, "1e+16"},
		{"negative 1e16", -1e16, "-1e+16"},
		{"1.5e20", 1.5e20, "1.5e+20"},
		// The small end: exponential at decpt <= -4, i.e. from 1e-5 down.
		{"1e-4 stays fixed", 1e-4, "0.0001"},
		{"1e-5 goes exponential with two exponent digits", 1e-5, "1e-05"},
		{"9.9e-5", 9.9e-5, "9.9e-05"},
		{"1.25e-7", 1.25e-7, "1.25e-07"},
		{"three-digit exponent", 1e-300, "1e-300"},
		// Non-finite tokens: CPython's allow_nan=True default.
		{"NaN", math.NaN(), "NaN"},
		{"positive infinity", math.Inf(1), "Infinity"},
		{"negative infinity", math.Inf(-1), "-Infinity"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := FormatFloat(tc.in); got != tc.want {
				t.Errorf("FormatFloat(%v) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestSanitizeNonFinite(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		line string
		// wantSentinels counts how many bare tokens should have been
		// rewritten.
		wantSentinels int
	}{
		{name: "no tokens", line: `{"a": 1}`, wantSentinels: 0},
		{name: "one NaN", line: `{"a": NaN}`, wantSentinels: 1},
		{name: "all three", line: `{"a": NaN, "b": Infinity, "c": -Infinity}`, wantSentinels: 3},
		{
			name:          "token inside a string is untouched",
			line:          `{"a": "NaN was here", "b": NaN}`,
			wantSentinels: 1,
		},
		{
			name:          "escaped quote does not end the string early",
			line:          `{"a": "quote \" then NaN", "b": Infinity}`,
			wantSentinels: 1,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := SanitizeNonFinite(tc.line)
			n := strings.Count(got, "vmafx-")
			if n != tc.wantSentinels {
				t.Errorf("SanitizeNonFinite(%s) produced %d sentinels, want %d (got %s)",
					tc.line, n, tc.wantSentinels, got)
			}
		})
	}
}

// TestSanitizeAndResolveRoundTrip checks that a CPython-written line with
// every non-finite token parses through encoding/json and comes back as the
// float64 values it stood for.
func TestSanitizeAndResolveRoundTrip(t *testing.T) {
	t.Parallel()

	line := `{"nan": NaN, "pos": Infinity, "neg": -Infinity, "text": "NaN", "xs": [NaN, 1.0]}`
	var decoded any
	if err := json.Unmarshal([]byte(SanitizeNonFinite(line)), &decoded); err != nil {
		t.Fatalf("sanitised line does not parse: %v", err)
	}
	row, ok := ResolveSentinels(decoded).(map[string]any)
	if !ok {
		t.Fatalf("resolved value is %T, want map", decoded)
	}
	if v, _ := row["nan"].(float64); !math.IsNaN(v) {
		t.Errorf("nan = %v, want NaN", row["nan"])
	}
	if v, _ := row["pos"].(float64); !math.IsInf(v, 1) {
		t.Errorf("pos = %v, want +Inf", row["pos"])
	}
	if v, _ := row["neg"].(float64); !math.IsInf(v, -1) {
		t.Errorf("neg = %v, want -Inf", row["neg"])
	}
	if row["text"] != "NaN" {
		t.Errorf("text = %v, want the literal string NaN", row["text"])
	}
	xs, _ := row["xs"].([]any)
	if len(xs) != 2 || !math.IsNaN(xs[0].(float64)) || xs[1] != 1.0 {
		t.Errorf("xs = %v, want [NaN, 1.0]", row["xs"])
	}
}
