#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Oracle of the RGB to Y'CbCr conversion in exact rational arithmetic (ADR-2146).

Writes `core/test/vmafx_rgb_oracle.h`: for every matrix, input range, output
range and a set of bit depths, pixels (the edges of both ranges, the primaries
and a deterministic pseudo-random set) with the Y', Cb', Cr' code values the
conversion of H.273 gives, evaluated with `fractions.Fraction` and rounded half
up, clipped to the code range. A pixel whose exact value lies within 2^-11 of a
rounding tie is marked `slack`: the Q30 coefficients may land one step to either
side of it, and the C test accepts that and nothing else.

The model is checked against zimg (FFmpeg's zscale) for full-range input by
`scripts/codegen/tests/test_vmafx_rgb_oracle.py`; zimg treats RGB input as full
range, so the limited-range input cases rest on the H.273 equations alone.

    python3 scripts/dev/gen_rgb_oracle.py --write
    python3 scripts/dev/gen_rgb_oracle.py --check
"""

from __future__ import annotations

import argparse
import itertools
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "codegen"))

from vmafx_api import rgb_coefficients as rc  # noqa: E402

SPDX = "SPDX-" + "License-Identifier: EUPL-1.2"
OUTPUT = Path("core/test/vmafx_rgb_oracle.h")
MATRICES = {
    "VMAFX_COLOR_MATRIX_BT601": (Fraction("0.299"), Fraction("0.114")),
    "VMAFX_COLOR_MATRIX_BT709": (Fraction("0.2126"), Fraction("0.0722")),
    "VMAFX_COLOR_MATRIX_BT2020_NCL": (Fraction("0.2627"), Fraction("0.0593")),
}
RANGE_ENUM = {"limited": "VMAFX_COLOR_RANGE_LIMITED", "full": "VMAFX_COLOR_RANGE_FULL"}
DEPTHS = (8, 10, 12, 16)
RANDOM_PIXELS = 24
TIE_SLACK = Fraction(1, 2048)


def pixels(bpc: int) -> list[tuple[int, int, int]]:
    """Edges of both ranges, the primaries and pseudo-random pixels."""
    s, top = 1 << (bpc - 8), (1 << bpc) - 1
    black, white = 16 * s, 235 * s
    levels = (0, black, 128 * s, white, top)
    out = [(v, v, v) for v in levels]
    out += [(top, 0, 0), (0, top, 0), (0, 0, top), (top, top, 0), (0, top, top), (top, 0, top)]
    out += [(white, black, black), (black, white, black), (black, black, white)]
    out += [(black - 1, white + 1, 128 * s), (1, top - 1, top // 2)]
    state = 0x2545F4914F6CDD1D ^ bpc
    for _ in range(RANDOM_PIXELS):
        triple = []
        for _ in range(3):
            state ^= (state << 13) & 0xFFFFFFFFFFFFFFFF
            state ^= state >> 7
            state ^= (state << 17) & 0xFFFFFFFFFFFFFFFF
            triple.append((state >> 20) % (top + 1))
        out.append((triple[0], triple[1], triple[2]))
    return out


def expect(value: Fraction, top: int) -> tuple[int, bool]:
    rounded = (value + Fraction(1, 2)).__floor__()
    tie = abs((value - value.__floor__()) - Fraction(1, 2)) < TIE_SLACK
    return max(0, min(top, rounded)), tie


def header_lines() -> list[str]:
    return [
        "/**",
        " *",
        " *  Copyright 2026 Lusoris",
        " *",
        f" * {SPDX}",
        " */",
        "",
        "/*",
        " * GENERATED by scripts/dev/gen_rgb_oracle.py (ADR-2146). Do not edit.",
        " *",
        " * The RGB to Y'CbCr conversion in exact rational arithmetic: per configuration",
        " * (matrix, input range, output range, bits) the pixels and the Y', Cb', Cr' code",
        " * values rounded half up and clipped. `slack` is set when an exact value lies",
        " * within 2^-11 of a rounding tie, where the Q30 coefficients may differ by one.",
        " */",
        "",
        "#ifndef VMAFX_RGB_ORACLE_H",
        "#define VMAFX_RGB_ORACLE_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        '#include "vmafx/vmafx.h"',
        "",
        "/* clang-format off */",
        "typedef struct VroCase {",
        "    uint16_t r, g, b;",
        "    uint16_t y, cb, cr;",
        "    uint8_t slack; /* bit 0: Y', bit 1: Cb', bit 2: Cr' within 2^-11 of a tie */",
        "} VroCase;",
        "",
        "typedef struct VroConfig {",
        "    uint32_t matrix, in_range, out_range, bpc;",
        "    size_t n;",
        "    const VroCase *cases;",
        "} VroConfig;",
        "",
    ]


def case_rows(kr: Fraction, kb: Fraction, rng_in: str, rng_out: str, bpc: int) -> list[str]:
    """The C initialisers of one configuration's pixels."""
    top = (1 << bpc) - 1
    rows = []
    for px in pixels(bpc):
        values = [expect(v, top) for v in rc.exact(kr, kb, rng_in, rng_out, bpc, px)]
        slack = sum(int(tie) << i for i, (_, tie) in enumerate(values))
        rows.append(
            "    {"
            + ", ".join(str(c) for c in px)
            + ", "
            + ", ".join(str(v) for v, _ in values)
            + f", {slack}}},"
        )
    return rows


def render() -> str:
    out = header_lines()
    configs: list[tuple[str, str, str, int, int, str]] = []
    for matrix, (kr, kb) in MATRICES.items():
        for rng_in, rng_out, bpc in itertools.product(rc.RANGES, rc.RANGES, DEPTHS):
            name = f"vro_{len(configs)}"
            rows = case_rows(kr, kb, rng_in, rng_out, bpc)
            out += [f"static const VroCase {name}[] = {{", *rows, "};", ""]
            configs.append((matrix, rng_in, rng_out, bpc, len(rows), name))
    out.append("static const VroConfig vro_configs[] = {")
    for matrix, rng_in, rng_out, bpc, n, name in configs:
        out.append(
            f"    {{{matrix}, {RANGE_ENUM[rng_in]}, {RANGE_ENUM[rng_out]}, {bpc}u, {n}u, {name}}},"
        )
    out += [
        "};",
        "",
        "#define VRO_N_CONFIGS (sizeof(vro_configs) / sizeof(vro_configs[0]))",
        "/* clang-format on */",
        "",
        "#endif /* VMAFX_RGB_ORACLE_H */",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    text = render()
    target = args.root / OUTPUT
    if args.write:
        target.write_text(text, encoding="utf-8")
        print(f"wrote {OUTPUT}")
        return 0
    if not target.exists() or target.read_text(encoding="utf-8") != text:
        print(f"{OUTPUT} is not what the oracle produces; run with --write", file=sys.stderr)
        return 1
    print(f"{OUTPUT} is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
