/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx-api.py from core/api/vmafx.toml (ADR-1852).
 * Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`.
 */

#include <errno.h>
#include <stddef.h>

#include "compat_errno.h"
#include "vmafx/error.h"

/* status, name, negative errno for libvmaf, maps back from that errno */
static const struct {
    VmafxStatus status;
    const char *name;
    int negative_errno;
    int reverse;
} status_rows[] = {
    {VMAFX_OK, "VMAFX_OK", 0, 1},
    {VMAFX_PENDING, "VMAFX_PENDING", -EAGAIN, 1},
    {VMAFX_E_INVALID, "VMAFX_E_INVALID", -EINVAL, 1},
    {VMAFX_E_NOMEM, "VMAFX_E_NOMEM", -ENOMEM, 1},
    {VMAFX_E_NOTSUP, "VMAFX_E_NOTSUP", -ENOTSUP, 1},
    {VMAFX_E_NOTFOUND, "VMAFX_E_NOTFOUND", -ENOENT, 1},
    {VMAFX_E_BUSY, "VMAFX_E_BUSY", -EBUSY, 1},
    {VMAFX_E_DEVICE, "VMAFX_E_DEVICE", -EIO, 0},
    {VMAFX_E_IO, "VMAFX_E_IO", -EIO, 1},
    {VMAFX_E_RANGE, "VMAFX_E_RANGE", -ERANGE, 1},
    {VMAFX_E_INTERNAL, "VMAFX_E_INTERNAL", -EIO, 0},
    {VMAFX_E_TIMEOUT, "VMAFX_E_TIMEOUT", -ETIMEDOUT, 1},
    {VMAFX_E_ABI, "VMAFX_E_ABI", -EINVAL, 0},
    {VMAFX_E_MISMATCH, "VMAFX_E_MISMATCH", -EBADMSG, 1},
};

#define N_STATUS_ROWS (sizeof(status_rows) / sizeof(status_rows[0]))

int vmaf_compat_status_errno(VmafxStatus status)
{
    for (size_t i = 0; i < N_STATUS_ROWS; i++) {
        if (status_rows[i].status == status) {
            return status_rows[i].negative_errno;
        }
    }
    return -EIO;
}
