#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Write core/test/dnn/signer_fixtures.h, the Sigstore bundles of the signer tests (ADR-2985).

Usage: python3 core/test/dnn/gen_signer_fixtures.py RELEASE_BUNDLE

RELEASE_BUNDLE is a Sigstore bundle VMAFx's supply-chain workflow wrote for a
release, for example `vmaf.bundle` of v1.0.0-rc.3
(`gh release download v1.0.0-rc.3 -R VMAFx/vmafx -p vmaf.bundle`). Its Fulcio
certificate is the accepted case. The other certificates are self-signed with
openssl and differ from an accepted one in one field each: the signer code
reads names and extensions, cosign checks signatures, so a self-signed
certificate exercises exactly the code under test.
"""

from __future__ import annotations

import base64
import hashlib
import json
import pathlib
import subprocess
import sys
import tempfile

OWNER_OID = "1.3.6.1.4.1.57264.1.17"
OWNER_ID = "288567244"
WORKFLOW = "https://github.com/VMAFx/vmafx/.github/workflows/supply-chain.yml"
OUT = pathlib.Path(__file__).with_name("signer_fixtures.h")

# name -> (subject alternative name extension value, owner ID or None)
SYNTHETIC = {
    "master": (f"URI:{WORKFLOW}@refs/heads/master", OWNER_ID),
    "wrong_owner": (f"URI:{WORKFLOW}@refs/tags/v1.0.0", "999999999"),
    "no_owner": (f"URI:{WORKFLOW}@refs/tags/v1.0.0", None),
    "prefix": (f"URI:https://evil.example/{WORKFLOW}@refs/tags/v1.0.0", OWNER_ID),
    "suffix": (f"URI:{WORKFLOW}@refs/heads/master/evil", OWNER_ID),
    "dot": (
        "URI:https://githubXcom/VMAFx/vmafx/.github/workflows/supply-chain.yml" "@refs/tags/v1.0.0",
        OWNER_ID,
    ),
    "other_workflow": (
        "URI:https://github.com/VMAFx/vmafx/.github/workflows/evil.yml" "@refs/heads/master",
        OWNER_ID,
    ),
    "two_names": (f"URI:{WORKFLOW}@refs/heads/master,URI:https://evil.example/", OWNER_ID),
}


def synthetic_certificate(workdir: pathlib.Path, name: str, san: str, owner: str | None) -> bytes:
    key = workdir / f"{name}.key"
    der = workdir / f"{name}.der"
    cmd = [
        "openssl",
        "req",
        "-x509",
        "-newkey",
        "ec",
        "-pkeyopt",
        "ec_paramgen_curve:prime256v1",
        "-nodes",
        "-keyout",
        str(key),
        "-subj",
        "/CN=sigstore-test",
        "-days",
        "1",
        "-outform",
        "DER",
        "-out",
        str(der),
        "-addext",
        f"subjectAltName=critical,{san}",
    ]
    if owner is not None:
        cmd += ["-addext", f"{OWNER_OID}=ASN1:UTF8String:{owner}"]
    subprocess.run(cmd, check=True, capture_output=True)  # noqa: S603 -- fixed argv, no shell
    return der.read_bytes()


def bundle_json(der: bytes) -> str:
    return json.dumps(
        {
            "mediaType": "application/vnd.dev.sigstore.bundle.v0.3+json",
            "verificationMaterial": {"certificate": {"rawBytes": base64.b64encode(der).decode()}},
        },
        separators=(",", ":"),
    )


def c_literal(text: str, width: int = 90) -> str:
    parts = [text[i : i + width] for i in range(0, len(text), width)]
    return "\n".join('    "' + p.replace("\\", "\\\\").replace('"', '\\"') + '"' for p in parts)


def main() -> int:
    args = sys.argv[1:]
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    release_path = pathlib.Path(args[0])
    release = json.loads(release_path.read_text(encoding="utf-8"))
    release_der = base64.b64decode(release["verificationMaterial"]["certificate"]["rawBytes"])
    digest = hashlib.sha256(release_path.read_bytes()).hexdigest()

    bundles = {"release": bundle_json(release_der)}
    with tempfile.TemporaryDirectory() as tmp:
        for name, (san, owner) in SYNTHETIC.items():
            bundles[name] = bundle_json(synthetic_certificate(pathlib.Path(tmp), name, san, owner))

    lines = [
        "/**",
        " *  Copyright 2026 Lusoris",
        # Split so REUSE does not read this string as this script's licence line.
        " *  SPDX-" "License-Identifier: EUPL-1.2",
        " *",
        " *  Generated by core/test/dnn/gen_signer_fixtures.py; do not edit (ADR-2985).",
        f" *  `release` holds the Fulcio certificate of {release_path.name} (sha256 {digest[:16]}),",
        " *  the others self-signed certificates that differ from an accepted one in one field.",
        " */",
        "",
        "#ifndef VMAF_TEST_DNN_SIGNER_FIXTURES_H_",
        "#define VMAF_TEST_DNN_SIGNER_FIXTURES_H_",
        "",
    ]
    for name, text in bundles.items():
        lines.append(f"static const char k_bundle_{name}[] =")
        lines.append(c_literal(text) + ";")
        lines.append("")
    lines.append("#endif /* VMAF_TEST_DNN_SIGNER_FIXTURES_H_ */")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(bundles)} bundles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
