/**
 *  Copyright 2026 Lusoris
 *  SPDX-License-Identifier: EUPL-1.2
 *
 *  Generated by core/test/dnn/gen_signer_fixtures.py; do not edit (ADR-2985).
 *  `release` holds the Fulcio certificate of vmaf.bundle (sha256 f27075b9ffbd0c8a),
 *  the others self-signed certificates that differ from an accepted one in one field.
 */

#ifndef VMAF_TEST_DNN_SIGNER_FIXTURES_H_
#define VMAF_TEST_DNN_SIGNER_FIXTURES_H_

static const char k_bundle_release[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIIG+DCCBn6gAwIBAgIUN0Q425I5VXg2YpLMU48yIJ+iGc8wCgYIKoZIzj0EAwMwNzEV"
    "MBMGA1UEChMMc2lnc3RvcmUuZGV2MR4wHAYDVQQDExVzaWdzdG9yZS1pbnRlcm1lZGlhdGUwHhcNMjYxMDA3MDg1Mz"
    "U4WhcNMjYxMDA3MDkwMzU4WjAAMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzG4+WKOvDZEpnuYcoeW3F5Yp2iip"
    "uKh63UlXpubU3Np1hZaquliG2sALKOF8XcwCLVovICPtRIAz7dyig5XkM6OCBZ0wggWZMA4GA1UdDwEB/wQEAwIHgD"
    "ATBgNVHSUEDDAKBggrBgEFBQcDAzAfBgNVHSMEGDAWgBTf0+nPViQRlvmo2OkoVaLGLhhkPzBlBgNVHREBAf8EWzBZ"
    "hldodHRwczovL2dpdGh1Yi5jb20vVk1BRngvdm1hZngvLmdpdGh1Yi93b3JrZmxvd3Mvc3VwcGx5LWNoYWluLnltbE"
    "ByZWZzL3RhZ3MvdjEuMC4wLXJjLjMwOQYKKwYBBAGDvzABAQQraHR0cHM6Ly90b2tlbi5hY3Rpb25zLmdpdGh1YnVz"
    "ZXJjb250ZW50LmNvbTAVBgorBgEEAYO/MAECBAdyZWxlYXNlMDYGCisGAQQBg78wAQMEKDQwZTg3YjE1OWQzN2QzMT"
    "IwNjZmZWY4MzA0N2FlN2M2NGQ0YWMzYjQwGgYKKwYBBAGDvzABBAQMc3VwcGx5LWNoYWluMBkGCisGAQQBg78wAQUE"
    "C1ZNQUZ4L3ZtYWZ4MCMGCisGAQQBg78wAQYEFXJlZnMvdGFncy92MS4wLjAtcmMuMzA7BgorBgEEAYO/MAEIBC0MK2"
    "h0dHBzOi8vdG9rZW4uYWN0aW9ucy5naXRodWJ1c2VyY29udGVudC5jb20wZwYKKwYBBAGDvzABCQRZDFdodHRwczov"
    "L2dpdGh1Yi5jb20vVk1BRngvdm1hZngvLmdpdGh1Yi93b3JrZmxvd3Mvc3VwcGx5LWNoYWluLnltbEByZWZzL3RhZ3"
    "MvdjEuMC4wLXJjLjMwOAYKKwYBBAGDvzABCgQqDCg0MGU4N2IxNTlkMzdkMzEyMDY2ZmVmODMwNDdhZTdjNjRkNGFj"
    "M2I0MB0GCisGAQQBg78wAQsEDwwNZ2l0aHViLWhvc3RlZDAuBgorBgEEAYO/MAEMBCAMHmh0dHBzOi8vZ2l0aHViLm"
    "NvbS9WTUFGeC92bWFmeDA4BgorBgEEAYO/MAENBCoMKDQwZTg3YjE1OWQzN2QzMTIwNjZmZWY4MzA0N2FlN2M2NGQ0"
    "YWMzYjQwJQYKKwYBBAGDvzABDgQXDBVyZWZzL3RhZ3MvdjEuMC4wLXJjLjMwGgYKKwYBBAGDvzABDwQMDAoxMjUyMj"
    "M1MzM0MCgGCisGAQQBg78wARAEGgwYaHR0cHM6Ly9naXRodWIuY29tL1ZNQUZ4MBkGCisGAQQBg78wAREECwwJMjg4"
    "NTY3MjQ0MGcGCisGAQQBg78wARIEWQxXaHR0cHM6Ly9naXRodWIuY29tL1ZNQUZ4L3ZtYWZ4Ly5naXRodWIvd29ya2"
    "Zsb3dzL3N1cHBseS1jaGFpbi55bWxAcmVmcy90YWdzL3YxLjAuMC1yYy4zMDgGCisGAQQBg78wARMEKgwoNDBlODdi"
    "MTU5ZDM3ZDMxMjA2NmZlZjgzMDQ3YWU3YzY0ZDRhYzNiNDAXBgorBgEEAYO/MAEUBAkMB3JlbGVhc2UwUgYKKwYBBA"
    "GDvzABFQREDEJodHRwczovL2dpdGh1Yi5jb20vVk1BRngvdm1hZngvYWN0aW9ucy9ydW5zLzM3NTk0NTU4MTE4L2F0"
    "dGVtcHRzLzEwFgYKKwYBBAGDvzABFgQIDAZwdWJsaWMwHwYKKwYBBAGDvzABFwQRDA9yZWxlYXNlLXB1Ymxpc2gwPA"
    "YKKwYBBAGDvzABGAQuDCxyZXBvOlZNQUZ4L3ZtYWZ4OmVudmlyb25tZW50OnJlbGVhc2UtcHVibGlzaDCBiwYKKwYB"
    "BAHWeQIEAgR9BHsAeQB3AN09MGrGxxEyYxkeHJlnNwKiSl643jyt/4eKcoAvKe6OAAABoRWRyQgAAAQDAEgwRgIhAP"
    "a6m4MdiZpykQIVhJrR0JTYlblROnW1Nybp/dI0CRkUAiEAinKrv27AIL9MllIqiI3/b3nD25NEUp2rDY4kAlXYiSYw"
    "CgYIKoZIzj0EAwMDaAAwZQIxAMwGS8WsJ1p0XPorpuj9m54N3QQQJR7kup63qfDRp36EIdBdKlwiz4rWcNzZiA9ltw"
    "IwC/DejM1ceH7bIRZRtPfgX78oYGta0fa6EU0wgPEjevSqaeTDP6bjIHWYojH2s2sk\"}}}";

static const char k_bundle_master[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIICBTCCAaugAwIBAgIUCDfNFkU5mSXlQHuxLeRlzbD2+LswCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT2uKuRpbXRfQQ/38C/csUCSDOevmXEwPfsugIk"
    "ybfrHTKHfKWSvCwPfnRIwnFT8BWduKDAWhdjE+jb2fH3u2tZo4HSMIHPMB0GA1UdDgQWBBQKgdRqzbqtguVnIUfVla"
    "obvSegHzAfBgNVHSMEGDAWgBQKgdRqzbqtguVnIUfVlaobvSegHzAPBgNVHRMBAf8EBTADAQH/MGEGA1UdEQEB/wRX"
    "MFWGU2h0dHBzOi8vZ2l0aHViLmNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcmtmbG93cy9zdXBwbHktY2hhaW4ueW"
    "1sQHJlZnMvaGVhZHMvbWFzdGVyMBkGCisGAQQBg78wAREECwwJMjg4NTY3MjQ0MAoGCCqGSM49BAMCA0gAMEUCICn4"
    "1k6D6dX5paodNzE1RnlV6n1Poi3+ruKDWcyB3Qr7AiEA3GYSkFeohRf33OdV9RAlL3nXi2qzX57Wjr2siYp/7DY=\"}"
    "}}";

static const char k_bundle_wrong_owner[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIICBDCCAaqgAwIBAgIUPmrOPJPhnsowHgGiZ7bF/sKAAgAwCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQbc0XneHn3lsF3sOSllfR9Z5V2d77MhS9seMTY"
    "YxB8tKwGyRvjzeI1Amm5jdnu32xkFYpaQaz1NGXDaPa/4xcfo4HRMIHOMB0GA1UdDgQWBBSNKfLVpDdGHhYF4RFvqy"
    "vWAGBjaDAfBgNVHSMEGDAWgBSNKfLVpDdGHhYF4RFvqyvWAGBjaDAPBgNVHRMBAf8EBTADAQH/MGAGA1UdEQEB/wRW"
    "MFSGUmh0dHBzOi8vZ2l0aHViLmNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcmtmbG93cy9zdXBwbHktY2hhaW4ueW"
    "1sQHJlZnMvdGFncy92MS4wLjAwGQYKKwYBBAGDvzABEQQLDAk5OTk5OTk5OTkwCgYIKoZIzj0EAwIDSAAwRQIhAJwS"
    "Xa3cIi5I8vkzmPDDxUhV+as7ob7R6VVzEeErUof7AiBDrSfdNV+wL0PRVgpEFoo5EVV7ZUVsle2Zt/gj39HJkg==\"}"
    "}}";

static const char k_bundle_no_owner[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIIB6DCCAY+gAwIBAgIUZHVd7ZhWd+zX80/Q5he/L78OPGgwCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARK2lIxf2VP000LRihlSxoNRbFeiFlQwg5VDd5L"
    "J+qBQWHZ7ADJpPRtraE28BcFm965gr1FxE805qgsPspHniwco4G2MIGzMB0GA1UdDgQWBBRcfyrO+VZQyA9BxDU/2u"
    "lVW21hsjAfBgNVHSMEGDAWgBRcfyrO+VZQyA9BxDU/2ulVW21hsjAPBgNVHRMBAf8EBTADAQH/MGAGA1UdEQEB/wRW"
    "MFSGUmh0dHBzOi8vZ2l0aHViLmNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcmtmbG93cy9zdXBwbHktY2hhaW4ueW"
    "1sQHJlZnMvdGFncy92MS4wLjAwCgYIKoZIzj0EAwIDRwAwRAIgHiZwHsia7ANzBH8G5zgVRySuV5jUKghRSM2SD7JB"
    "QcYCICsl1l179oYN5YBi8sfxJRMeij4uxQyLTin9QOVlgtLU\"}}}";

static const char k_bundle_prefix[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIICGTCCAb+gAwIBAgIUCLbkSX7AU1H44GMBIM0XfU3VJTQwCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASZ4Y9YHfw3rhaUIWKLoozAH0V7fdYaGiCtpUdQ"
    "2orzO2/V4c3MAUNSfnvHrhJxI8cwbeX+/wfat45QCoy2mWRbo4HmMIHjMB0GA1UdDgQWBBQ6xV7fz+u0Da0d14RhiO"
    "wg0Q/JujAfBgNVHSMEGDAWgBQ6xV7fz+u0Da0d14RhiOwg0Q/JujAPBgNVHRMBAf8EBTADAQH/MHUGA1UdEQEB/wRr"
    "MGmGZ2h0dHBzOi8vZXZpbC5leGFtcGxlL2h0dHBzOi8vZ2l0aHViLmNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcm"
    "tmbG93cy9zdXBwbHktY2hhaW4ueW1sQHJlZnMvdGFncy92MS4wLjAwGQYKKwYBBAGDvzABEQQLDAkyODg1NjcyNDQw"
    "CgYIKoZIzj0EAwIDSAAwRQIgeelYmyxuxlVRmcjjfvlENB8UJ7i0vmHfQJbVRrv4Q7QCIQD7eLvALcYv7sCmqPFViB"
    "/h8HlQARx/QdLmce20+ZpH6g==\"}}}";

static const char k_bundle_suffix[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIICCjCCAbCgAwIBAgIUIBtY63BCSXfviDfChWs0oc6vnakwCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQa+JtHIXTfsq471FG7EcL4jDQTKX7DfDC0cZEc"
    "NYGy9Q5w1M/7WTFm4VAL2B5eeSgR6O+DiJw6vLOW6C2xcu5go4HXMIHUMB0GA1UdDgQWBBRAzyADFzP4g6Ye8gKduU"
    "Yqf6xMNTAfBgNVHSMEGDAWgBRAzyADFzP4g6Ye8gKduUYqf6xMNTAPBgNVHRMBAf8EBTADAQH/MGYGA1UdEQEB/wRc"
    "MFqGWGh0dHBzOi8vZ2l0aHViLmNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcmtmbG93cy9zdXBwbHktY2hhaW4ueW"
    "1sQHJlZnMvaGVhZHMvbWFzdGVyL2V2aWwwGQYKKwYBBAGDvzABEQQLDAkyODg1NjcyNDQwCgYIKoZIzj0EAwIDSAAw"
    "RQIhAOinetPhC7v6Q7jv2/6O/KkGYKQFDjhU4ahlcAnlVNQIAiBkl+txnidemup3pzJs8zdCTjqgz5cVUxkAdw5+/N"
    "umdg==\"}}}";

static const char k_bundle_dot[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIICBDCCAaqgAwIBAgIUGeaOVROY1rJGGQurPTQsXBbzCE0wCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATDAmmR7eAw051XDaGBfhTMcAs678v4d9JjnZIy"
    "vrJ1Eo3c4KshrocvgYZUrzbhC5x5vTxRYcUF4+6wwyWzv77ho4HRMIHOMB0GA1UdDgQWBBQGaHSpXkGZP3NBWwrKdL"
    "1b58cm5zAfBgNVHSMEGDAWgBQGaHSpXkGZP3NBWwrKdL1b58cm5zAPBgNVHRMBAf8EBTADAQH/MGAGA1UdEQEB/wRW"
    "MFSGUmh0dHBzOi8vZ2l0aHViWGNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcmtmbG93cy9zdXBwbHktY2hhaW4ueW"
    "1sQHJlZnMvdGFncy92MS4wLjAwGQYKKwYBBAGDvzABEQQLDAkyODg1NjcyNDQwCgYIKoZIzj0EAwIDSAAwRQIgJdnR"
    "Bpo3S4Ch33GEl12ot9b5qZTOJ3RhfwBF6cCJWCcCIQCMeOQwLYFv+Sv9Qkqk7A+DczaHZWRNzLinwjJF9db2ug==\"}"
    "}}";

static const char k_bundle_other_workflow[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIIB/jCCAaOgAwIBAgIUZhNhBTvHYXbjrXW6JAkCo7pTSMkwCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASg33fxIGPFBGJGb8tYQv9+JOUiNVkfbAm2lKDt"
    "a8zISk/1SoAecZV5dpeUfCimn3FSytrep0BDCP1W4D5r2Ptpo4HKMIHHMB0GA1UdDgQWBBQjoDbDd9o1jKvmfFYa7G"
    "MIN2q6WjAfBgNVHSMEGDAWgBQjoDbDd9o1jKvmfFYa7GMIN2q6WjAPBgNVHRMBAf8EBTADAQH/MFkGA1UdEQEB/wRP"
    "ME2GS2h0dHBzOi8vZ2l0aHViLmNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcmtmbG93cy9ldmlsLnltbEByZWZzL2"
    "hlYWRzL21hc3RlcjAZBgorBgEEAYO/MAERBAsMCTI4ODU2NzI0NDAKBggqhkjOPQQDAgNJADBGAiEA1hrviaGbpTUU"
    "xO7t0vRkmopJMiPRCftlZ6O474s4jhUCIQCz3kfeJSl0cAdf0Upl/fIXFV0dKK8l4mwbYlquIEm9RA==\"}}}";

static const char k_bundle_two_names[] =
    "{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"cert"
    "ificate\":{\"rawBytes\":\"MIICHDCCAcKgAwIBAgIUMd5kOmTMa64TXbPoIW4cyV1t0QswCgYIKoZIzj0EAwIwGDEW"
    "MBQGA1UEAwwNc2lnc3RvcmUtdGVzdDAeFw0yNjEwMDkxNTE0MTBaFw0yNjEwMTAxNTE0MTBaMBgxFjAUBgNVBAMMDX"
    "NpZ3N0b3JlLXRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASOZRrIQFEWeizPE7+guIFX18UYf91KTv2QTWjP"
    "bRP9Bjh2u8DTG0mz2OlKEB4RmbdEM0lwpmUDYt3vWc5Wub7Oo4HpMIHmMB0GA1UdDgQWBBSai56a+DFwsB1xzAA23b"
    "z92bCmEDAfBgNVHSMEGDAWgBSai56a+DFwsB1xzAA23bz92bCmEDAPBgNVHRMBAf8EBTADAQH/MHgGA1UdEQEB/wRu"
    "MGyGU2h0dHBzOi8vZ2l0aHViLmNvbS9WTUFGeC92bWFmeC8uZ2l0aHViL3dvcmtmbG93cy9zdXBwbHktY2hhaW4ueW"
    "1sQHJlZnMvaGVhZHMvbWFzdGVyhhVodHRwczovL2V2aWwuZXhhbXBsZS8wGQYKKwYBBAGDvzABEQQLDAkyODg1Njcy"
    "NDQwCgYIKoZIzj0EAwIDSAAwRQIhAOrDWic2g8WZF3o3zhLJjmdNFIND1prkBm5+0QICgPzcAiBouP21WAVMg31TQY"
    "u1JjIKDgtZ8qqbcfQ+bhsyOmM0Sw==\"}}}";

#endif /* VMAF_TEST_DNN_SIGNER_FIXTURES_H_ */
