#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Generate and check the deepcopy code, the CRDs and the RBAC role (ADR-2350 D13).

Usage::

    python3 scripts/codegen/crd_generate.py --write
    python3 scripts/codegen/crd_generate.py --check
    python3 scripts/codegen/crd_generate.py --check --compat-against-merge-base origin/master

scripts/codegen/vmafx-api.py writes the Go types of the custom resources
(api/vmafx/v1) from api/vmafx-platform.toml. This script runs controller-gen,
the version go.mod pins as a tool, on them and on the RBAC markers of
cmd/vmafx-operator, into a scratch tree, adds the SPDX header, and writes or
compares:

- api/vmafx/v1/zz_generated.deepcopy.go   (object)
- deploy/helm/vmafx/crds/*.yaml            (crd; the only CRD tree)
- config/rbac/role.yaml                    (rbac)

--compat-against REF / --compat-against-merge-base REF also compare every CRD
with the one REF (or the merge base of HEAD and REF) holds: within v1 a
resource only grows (vmafx_api/crd_compat.py). Without Go, or when the base
cannot be read, --check exits 77 and says why.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml  # type: ignore[import-untyped]

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tree_sync import collect, differences, write
from vmafx_api import crd_compat, gitref

REPO = Path(__file__).resolve().parents[2]
SKIP = 77
TOOL_TIMEOUT_S = 900
# Package patterns by import path, never as filesystem roots ("./x/..."):
# controller-tools (v0.22.0, LoadRootsWithConfig in pkg/loader/loader.go) makes
# a relative root absolute with filepath.Abs before it looks for the trailing
# "...". On Windows filepath.Abs (syscall.FullPath, GetFullPathNameW) drops
# trailing dots, so "x\..." became "x" and go/packages was asked for ".\." in
# that directory: only its own package loaded. The operator's role then lost
# every marker of cmd/vmafx-operator/internal/controller and
# test_crd_generated_current failed on the Windows ARM64 MSVC leg
# (T-CRD-GENERATE-WINDOWS-RELATIVE-PATTERN-2026-10-09; upstream
# kubernetes-sigs/controller-tools#1484, fix proposed in #1485).
TYPES_PACKAGES = "api/vmafx/v1/..."
OPERATOR_PACKAGES = "cmd/vmafx-operator/..."
DEEPCOPY = Path("api/vmafx/v1")
CRDS = Path("deploy/helm/vmafx/crds")
RBAC = Path("config/rbac")
ROLE = "vmafx-operator-role"
GO_HEADER = "// SPDX-License-Identifier: EUPL-1.2\n// Copyright 2026 Lusoris\n"
YAML_HEADER = """# SPDX-License-Identifier: EUPL-1.2
# Copyright 2026 Lusoris
#
# GENERATED by controller-gen (scripts/codegen/crd_generate.py, ADR-2350 D13)
# from {source}. Do not edit: change api/vmafx-platform.toml, then run
# scripts/codegen/vmafx-api.py --write and scripts/codegen/crd_generate.py --write.
"""


class Unavailable(Exception):
    """Go or controller-gen cannot run here; the check is skipped."""


MODULE_LINE = re.compile(r"^module\s+(\S+)\s*$", re.MULTILINE)


def package_pattern(root: Path, packages: str) -> str:
    """`packages` (a path under the module root, ending in /...) as an import
    path pattern of the module go.mod at root declares."""
    found = MODULE_LINE.search((root / "go.mod").read_text(encoding="utf-8"))
    if found is None:
        raise SystemExit(f"crd_generate: {root / 'go.mod'} declares no module")
    return f"{found.group(1)}/{packages}"


def controller_gen(root: Path, *args: str) -> None:
    """Run the controller-gen go.mod pins, bounded by TOOL_TIMEOUT_S."""
    go = shutil.which("go")
    if go is None:
        raise Unavailable("go is not on PATH")
    try:
        out = subprocess.run(  # noqa: S603 (resolved go, the pinned tool, fixed argv)
            [go, "tool", "controller-gen", *args],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=TOOL_TIMEOUT_S,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise SystemExit(
            f"crd_generate: controller-gen {args[0]} ran over {TOOL_TIMEOUT_S} s"
        ) from exc
    if out.returncode != 0:
        raise SystemExit(f"crd_generate: controller-gen {args[0]} failed:\n{out.stderr}")


def generate(root: Path, scratch: Path) -> dict[str, str]:
    """Run the three generators into scratch; return {repository path: text}."""
    header = scratch / "boilerplate.go.txt"
    header.write_text(GO_HEADER, encoding="utf-8")
    types = package_pattern(root, TYPES_PACKAGES)
    operator = package_pattern(root, OPERATOR_PACKAGES)
    controller_gen(
        root,
        f"object:headerFile={header}",
        f"paths={types}",
        f"output:object:dir={scratch / 'object'}",
    )
    controller_gen(
        root, "crd:allowDangerousTypes=true", f"paths={types}", f"output:crd:dir={scratch / 'crds'}"
    )
    controller_gen(
        root, f"rbac:roleName={ROLE}", f"paths={operator}", f"output:rbac:dir={scratch / 'rbac'}"
    )
    files = {
        (DEEPCOPY / Path(p).name).as_posix(): text
        for p, text in collect(scratch, scratch / "object", "*.go").items()
    }
    for p, text in collect(scratch, scratch / "crds", "*.yaml").items():
        files[(CRDS / Path(p).name).as_posix()] = (
            YAML_HEADER.format(source=DEEPCOPY.as_posix()) + text
        )
    for p, text in collect(scratch, scratch / "rbac", "*.yaml").items():
        source = "the +kubebuilder:rbac markers of cmd/vmafx-operator"
        files[(RBAC / Path(p).name).as_posix()] = YAML_HEADER.format(source=source) + text
    return files


def committed(root: Path) -> dict[str, str]:
    files: dict[str, str] = collect(root, root / DEEPCOPY, "zz_generated.deepcopy.go")
    files.update(collect(root, root / CRDS, "*.yaml"))
    files.update(collect(root, root / RBAC, "*.yaml"))
    return files


def crds_of(texts: list[str]) -> list[dict]:  # type: ignore[type-arg]
    return [doc for text in texts for doc in yaml.safe_load_all(text) if doc]


def compat(root: Path, ref: str, want: dict[str, str]) -> list[str]:
    """Incompatibilities of the generated CRDs with the CRDs at ref."""
    old = gitref.files_at(root, ref, CRDS.as_posix(), ".yaml")
    new = [text for path, text in want.items() if path.startswith(CRDS.as_posix() + "/")]
    return [
        f"compat with {ref}: {f}"
        for f in crd_compat.findings(crds_of(list(old.values())), crds_of(new))
    ]


def run(root: Path, mode: str, against: str | None) -> tuple[list[str], list[str]]:
    """(drift, incompatibilities): generated files that differ from the tree
    (check mode; write mode rewrites them), and CRD narrowings against `against`."""
    with tempfile.TemporaryDirectory(prefix="crd-") as tmp:
        want = generate(root, Path(tmp))
    have = committed(root)
    drift: list[str] = []
    if mode == "write":
        write(root, want, have)
    else:
        drift = differences(want, have)
    return drift, compat(root, against, want) if against else []


def report(drift: list[str], incompatible: list[str]) -> int:
    for line in drift + incompatible:
        print(f"crd_generate: {line}")
    if drift:
        print("crd_generate: run python3 scripts/codegen/vmafx-api.py --write, then")
        print("  python3 scripts/codegen/crd_generate.py --write (never edit generated files)")
    if incompatible:
        print("crd_generate: within v1 a resource only grows; add an optional field or")
        print("  widen validation instead, or introduce a new version (ADR-2350 D13)")
    return 1 if drift or incompatible else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate in place")
    group.add_argument("--check", action="store_true", help="fail on any difference")
    base = parser.add_mutually_exclusive_group()
    base.add_argument("--compat-against", metavar="REF", help="compare the CRDs with REF")
    base.add_argument(
        "--compat-against-merge-base", metavar="REF", help="... with merge-base(HEAD, REF)"
    )
    parser.add_argument("--root", type=Path, default=REPO, help="repository root")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    mode = "write" if args.write else "check"
    try:
        against = args.compat_against
        if args.compat_against_merge_base:
            against = gitref.merge_base(root, args.compat_against_merge_base)
        drift, incompatible = run(root, mode, against)
    except (Unavailable, gitref.Unavailable) as exc:
        if mode == "check":
            print(f"crd_generate: SKIP: {exc}")
            return SKIP
        raise SystemExit(f"crd_generate: {exc}") from exc
    return report(drift, incompatible)


if __name__ == "__main__":
    sys.exit(main())
