#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Generate core/src/vmafx/exactness_gen.c from the cross-backend parity gate data.

The table gives, for every device twin the gate knows, its exactness class:
``exact`` (a fragment in ``scripts/ci/exact_twins.d``), ``libm-bounded <bound>``
(``LIBM_TWINS``) or ``tolerance <bound>`` (``FEATURE_TOLERANCE``). The CPU is
the reference and has no row. The provenance record reads it through
``vmafx_exactness_class()``.

    python3 scripts/codegen/vmafx_exactness.py --write
    python3 scripts/codegen/vmafx_exactness.py --check
"""

from __future__ import annotations

import argparse
import difflib
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from scripts.ci.cross_backend_calibration import (  # noqa: E402 -- path set above
    EXACT_TWIN_FRAGMENTS,
    LIBM_TWINS,
)
from scripts.ci.cross_backend_parity_gate import (  # noqa: E402
    BACKEND_EXTRACTOR_ALIASES,
    BACKEND_SUFFIX,
    DEFAULT_FP32_TOLERANCE,
    FEATURE_ALIASES,
    FEATURE_TOLERANCE,
)

# The gate's tables are re-exported for the tests that render planted inputs.
__all__ = [
    "BACKEND_EXTRACTOR_ALIASES",
    "BACKEND_SUFFIX",
    "DEFAULT_FP32_TOLERANCE",
    "EXACT_TWIN_FRAGMENTS",
    "FEATURE_ALIASES",
    "FEATURE_TOLERANCE",
    "LIBM_TWINS",
    "OUTPUT",
    "check",
    "class_text",
    "main",
    "render",
    "render_live",
]

OUTPUT = ROOT / "core" / "src" / "vmafx" / "exactness_gen.c"
LIBM_ADR = "ADR-1426"
BACKEND_ENUM = {
    "cuda": "VMAFX_BACKEND_CUDA",
    "sycl": "VMAFX_BACKEND_SYCL",
    "metal": "VMAFX_BACKEND_METAL",
    "hip": "VMAFX_BACKEND_HIP",
}
KIND_ENUM = {
    "exact": "VMAFX_EXACTNESS_EXACT",
    "libm": "VMAFX_EXACTNESS_LIBM_BOUNDED",
    "tolerance": "VMAFX_EXACTNESS_TOLERANCE",
}
# The class text the provenance record carries (design section 2.9).
KIND_TEXT = {"exact": "exact", "libm": "libm-bounded", "tolerance": "tolerance"}


def class_text(kind: str, bound: str) -> str:
    """`exact`, `libm-bounded <bound>` or `tolerance <bound>`."""
    return KIND_TEXT[kind] if kind == "exact" else f"{KIND_TEXT[kind]} {bound}"


HEADER = """\
/**
 *
 *  Copyright 2026 Lusoris
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

/*
 * GENERATED by scripts/codegen/vmafx_exactness.py from scripts/ci/exact_twins.d,
 * LIBM_TWINS and FEATURE_TOLERANCE. Do not edit: run
 * python3 scripts/codegen/vmafx_exactness.py --write.
 */

#include <stdint.h>

#include "vmafx/exactness.h"
#include "vmafx/types.h"

/* Sorted by extractor, so a reader can bisect. */
/* clang-format off */
const VmafxExactnessRow vmafx_exactness_rows[] = {
"""


class ExactnessError(ValueError):
    """The gate data cannot be turned into a table."""


Row = tuple[str, str, str, str, str, str]  # twin, base, backend, kind, bound, adr


def fragment_map(fragments: Sequence[Any]) -> dict[tuple[str, str], str]:
    """(feature, backend) -> ADR ids of the fragment, joined by ", "."""
    return {(f.feature, f.backend): ", ".join(f.adrs) for f in fragments}


def backends_of(feature: str, fragments: Mapping[tuple[str, str], str]) -> frozenset[str]:
    return frozenset(b for (f, b) in fragments if f == feature)


def check_inputs(
    fragments: Mapping[tuple[str, str], str],
    libm_twins: Mapping[str, Mapping[str, float]],
    tolerance: Mapping[str, float],
    aliases: Mapping[str, tuple[str, str]],
) -> list[str]:
    """Validate the data; return the base feature names."""
    bases = sorted(set(tolerance) - set(aliases))
    known = set(bases) | set(aliases)
    for feature, backend in sorted(fragments):
        if feature not in known:
            raise ExactnessError(
                f"fragment {feature}.{backend}: feature is neither a base nor an alias"
            )
    for alias, (base, _options) in sorted(aliases.items()):
        exact_a, exact_b = backends_of(alias, fragments), backends_of(base, fragments)
        if exact_a != exact_b:
            raise ExactnessError(
                f"alias {alias}: exact backends {sorted(exact_a)} differ from "
                f"base {base}: {sorted(exact_b)}"
            )
        libm_a = frozenset(libm_twins.get(alias, {}))
        libm_b = frozenset(libm_twins.get(base, {}))
        if libm_a != libm_b:
            raise ExactnessError(
                f"alias {alias}: libm backends {sorted(libm_a)} differ from "
                f"base {base}: {sorted(libm_b)}"
            )
    return bases


def classify(
    base: str,
    backend: str,
    fragments: Mapping[tuple[str, str], str],
    libm_twins: Mapping[str, Mapping[str, float]],
    tolerance: Mapping[str, float],
    default_tolerance: float,
) -> tuple[str, str, str]:
    """Return (kind, bound text, ADR text) of one twin."""
    if (base, backend) in fragments:
        return "exact", format(0.0, "g"), fragments[(base, backend)]
    libm = libm_twins.get(base, {}).get(backend)
    if libm:
        return "libm", format(libm, "g"), LIBM_ADR
    return "tolerance", format(tolerance.get(base, default_tolerance), "g"), ""


def build_rows(
    fragments: Sequence[Any],
    libm_twins: Mapping[str, Mapping[str, float]],
    tolerance: Mapping[str, float],
    default_tolerance: float,
    aliases: Mapping[str, tuple[str, str]],
    suffix: Mapping[str, str],
    extractor_aliases: Mapping[tuple[str, str], str],
) -> list[Row]:
    frags = fragment_map(fragments)
    bases = check_inputs(frags, libm_twins, tolerance, aliases)
    backends = [b for b in suffix if b != "cpu"]
    rows: list[Row] = []
    for base in bases:
        for backend in backends:
            twin = extractor_aliases.get((base, backend), base + suffix[backend])
            kind, bound, adr = classify(
                base, backend, frags, libm_twins, tolerance, default_tolerance
            )
            rows.append((twin, base, backend, kind, bound, adr))
    return sorted(rows)


def render(
    fragments: Sequence[Any],
    libm_twins: Mapping[str, Mapping[str, float]],
    tolerance: Mapping[str, float],
    default_tolerance: float,
    aliases: Mapping[str, tuple[str, str]],
    suffix: Mapping[str, str],
    extractor_aliases: Mapping[tuple[str, str], str],
) -> str:
    """The C source text of the table."""
    rows = build_rows(
        fragments, libm_twins, tolerance, default_tolerance, aliases, suffix, extractor_aliases
    )

    out = [HEADER.rstrip("\n")]
    for twin, base, backend, kind, bound, adr in rows:
        out.append(
            f'    {{"{twin}", "{base}", {BACKEND_ENUM[backend]}, {KIND_ENUM[kind]}, '
            f'"{bound}", "{adr}", "{class_text(kind, bound)}"}},'
        )
    out.append("};")
    out.append("/* clang-format on */")
    out.append("")
    out.append("const uint32_t vmafx_exactness_row_count =")
    out.append("    (uint32_t)(sizeof(vmafx_exactness_rows) / sizeof(vmafx_exactness_rows[0]));")
    return "\n".join(out) + "\n"


def render_live() -> str:
    return render(
        EXACT_TWIN_FRAGMENTS,
        LIBM_TWINS,
        FEATURE_TOLERANCE,
        DEFAULT_FP32_TOLERANCE,
        FEATURE_ALIASES,
        BACKEND_SUFFIX,
        BACKEND_EXTRACTOR_ALIASES,
    )


def check(path: Path, text: str) -> int:
    """0 when *path* holds *text*, else 1 with a diff hint naming the file."""
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == text:
        return 0
    diff = difflib.unified_diff(
        current.splitlines(), text.splitlines(), str(path), "generated", lineterm="", n=1
    )
    shown = list(diff)[:40]
    print(f"{path} is out of date; run python3 scripts/codegen/vmafx_exactness.py --write")
    print("\n".join(shown))
    return 1


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite the generated file")
    mode.add_argument("--check", action="store_true", help="fail when the file differs")
    parser.add_argument("--path", type=Path, default=OUTPUT, help="file to write or check")
    args = parser.parse_args(argv)
    try:
        text = render_live()
    except ExactnessError as error:
        print(f"vmafx_exactness: {error}", file=sys.stderr)
        return 2
    if args.check:
        return check(args.path, text)
    args.path.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
